### ISSUE TITLE
5.6 Pruebas de psicotecnia

### ISSUE THREAD

**Issue by nmartinezmarin** [ISWPOLI/Pacto-de-Honor#11]

**Comment by CamilaG08** [comment]
**Descripción**

Investigación, definición e implementación de las pruebas psicotécnicas dentro del juego.

**TAREAS**

- [x] Reunirse con el departamento de Psicología.
- [x] Ideas sobre cómo implementar las pruebas en el juego.
- [x] Leer manual P-IPG y realizar un documento sobre este. @JuanSebastianRodriguezJ 
- [x] Leer manual 16 PF-5 y realizar un documento sobre este. @jrsosago

**Comment by jrsosago** [comment]
El 8 de marzo, fuimos con @JuanSebastianRodriguezJ a el departamento de Psicología donde hablamos con Fabio Martinez, quien es el Director del laboratorio de Psicología. Le expusimos la idea, características y metodología del juego, después de esto Fabio nos informó que no hay una prueba especifica para el juego y nos dio algunas sugerencias.
A las conclusiones que llegue fueron las siguientes:
- Realizar preguntas relacionadas con los 10 tipos de plagio y demás decisiones no correctas (colarse, llegar tarde, etc). enfocadas a situaciones de la vida diaria, estás preguntas se realizarían en tercera persona.
- Utilizar la escala de Likert, para las preguntas.
- Las preguntas se pueden ubicar:
      * Desbloqueo personajes: Antes de desbloquear un personaje una pregunta.
      * Recarga Poder: El poder necesita menor tiempo de recarga para ser usado si se contesta una         pregunta.
**Tiempo empleado: 40 minutos**

**Comment by ghost** [comment]
Se realiza una reunión con el departamento de psicología, en conjunto con (jeimy) @jrsosago para preguntar la manera en la que podemos implementar pruebas psicotecnicas y realizar la evaluación de los jugadores en nuestra aplicación. 
Según lo que dijo Fabio Martinez el director de laboratorio, indico que las pruebas que necesitamos al ser tan especificas no estaban disponibles, también dijo que las pruebas disponibles no se podían aplicar a nuestro proyecto y que era necesario que las preguntas las hiciéramos nosotros. 

También indico como debíamos realizar las preguntas y como "evaluarlas", y propuso que al tener los resultados de dichas preguntas nos remitiéramos nuevamente al departamento para que él junto con varios profesores de la facultad hicieran el análisis de dichos resultados.

**Tiempo empleado: 40 minutos.**

**Comment by jrsosago** [comment]
Documento de consolidación elaborado por @JuanSebastianRodriguezJ y @jrsosago.                                

**Tiempo empleado: 20 minutos** 
[PRUEBAS PSICOTÉCNICAS.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/829246/PRUEBAS.PSICOTECNICAS.docx)

**Comment by jrsosago** [comment]
Documento sobre la prueba 16PF-5. **Tiempo empleado: 1 hora**
[PRUEBA 16 PF.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/835474/PRUEBA.16.PF.docx)

**Comment by jrsosago** [comment]
Se crean dos Issues relacionadas a está característica, se asignan a @JuanSebastianRodriguezJ Issue  #186 y @jrsosago Issue #185

**Comment by ghost** [comment]
Documento sobre la prueba P-IPG. Tiempo empleado: 2 horas.
[Manual Perfil – Inventario de la Personalidad.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/846238/Manual.Perfil.Inventario.de.la.Personalidad.docx)

**Comment by CamilaG08** [comment]
Debido a que es una Característica y se realizaron cambios sobre esta, se mueve al Sprint 9 ya que falta la propuesta de implementación en el juego y realizar ese proceso de implementación.

**Comment by ghost** [comment]
Desde la reunión de retrospectiva del sprint 7, se solicito una manera de perfilar a los usuarios mediante las acciones en el juego, por lo que se realizo una propuesta en la que se sugiere hacer las evaluaciones dependiendo de: el personaje que selecciona al principio del juego, el numero de golpes que acierta en las batallas, si decide invitar amigo o no al juego y cuantos invita, si decide desbloquear personajes usando monedas y si tiene codigo que den los profesores por llegar temprano etc.
[Aplicaciones del perfilamiento de usuarios a Poli Fighters.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/939545/Aplicaciones.del.perfilamiento.de.usuarios.a.Poli.Fighters.docx)
 
Jeimy realiza una propuesta diferente en un issue aparte.
Tiempo empleado: 2 horas.

**Comment by jrsosago** [comment]
Se termina la documentación sobre las pruebas Psicotécnicas, dando paso a la implementación de las pruebas en la Épica Escenarios (número 1) y en la Característica Mundos y Escenarios (número 1), en la Issue #378 por tal motivo se cierra está característica.
