### ISSUE TITLE
Propuesta definida detalladamente

### ISSUE THREAD

**Issue by ingenieriadelsoftware** [ISWPOLI/Pacto-de-Honor#113]
**Propuesta definida detalladamente**
**Tareas**
- [x] Reunión con el equipo de trabajo
- [x] Revisar y detallar documento de la propuesta

**Comment by CamilaG08** [comment]
Chicos, adjunto el documento modificado por @jdma0440 y yo, y el de los personajes para revisión.

[Limitaciones-del-Juego-26-de-Febrero.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/802608/Limitaciones-del-Juego-26-de-Febrero.docx)

[2.Entrega.Subgrupo.-.Practica.Aplicada-1.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/802609/2.Entrega.Subgrupo.-.Practica.Aplicada-1.docx)

**Sólo quedan faltando los logros a desbloquear, que no son relevantes en esta entrega pero están en proceso**

**Comment by wpradere** [comment]
#### Gracias el documento ya fue compartido con el grupo 👍 👍  1 hora en este proceso

**Comment by CamilaG08** [comment]
El documento queda listo para revisión y aprobación o modificación por parte de @DiegOliveros y @jolarter

**Comment by CamilaG08** [comment]
Se sube el archivo de los logros y el de personajes corregido.

[2.Entrega.Subgrupo.-.Practica.Aplicada-1.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/812830/2.Entrega.Subgrupo.-.Practica.Aplicada-1.docx)

[Logros.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/812831/Logros.docx)

**Comment by JuanCheroslan** [comment]
documento de requerimientos version 1.0 

[Especificacion de Requerimientos V0.1.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/818362/Especificacion.de.Requerimientos.V0.1.docx)
