### ISSUE TITLE
Definir la plataforma de desarrollo

### ISSUE THREAD

**Issue by ingenieriadelsoftware** [ISWPOLI/Pacto-de-Honor#114]
**Diagrama de infraestructura**
**Tareas**
- [x] Reunión con el equipo de trabajo 
- [x] Diagrama de infraestructura
- [x] Adicionar las tareas faltantes en esta historia
- [x] explicar el diagrama de infraestructura

**Comment by nmartinezmarin** [comment]
MODELO DE INFRAESTRUCTURA
[Diagrama1.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/802690/Diagrama1.pdf)

Para el proyecto que estamos desarrollando vamos a implementar un modelo con tres servidores como se muestra a continuación.

Servidor Apache: Este servidor es el que se enfrenta directamente al usuario y en el vamos a almacenar dos cosas; la primera es el portal del proyecto (donde mostramos todos los archivos web de la página) y la segunda es el juego como tal. En el diagrama se puede observar que este servidor está conectado directamente al base de datos y también puede llegar a ella comunicándose con otro servidor  esto se debe a que para responder a todas las solicitudes que se generen en el juego (log-in de un usuario, mostrar personajes desbloqueados…etc.) vamos a utilizar un intermediario para acceder a la base de datos y así poder responder a estas solicitudes, por otro lado tenemos toda la información de las plantillas que utilizamos en nuestro portal y para tener acceso a esta información es que nos confrontamos directamente con la base de datos. Para todo esto vamos a utilizar un servidos Apache.


Se adjunta la primera parte de la descripción del modelo de infraestructura y el diagrama

Tiempo Registrado: 1 hora

**Comment by CristianGarzonBernal** [comment]
[MODELO DE INFRAESTRUCTURA.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/809777/MODELO.DE.INFRAESTRUCTURA.docx)
Tiempo registrado 1 hora

**Comment by manuk160** [comment]
Reunión equipo de trabajo:

1. Se realiza una reunión con el equipo de trabajo para definir el esquema de la arquitectura y los lineamientos para el documento en la cual participan el equipo de infraestructura. Tiempo Registrado: 2 horas

2. Posteriormente se realiza validación del documento MODELO DE INFRAESTRUCTURA.docx y Diagrama1.pdf y se definen nuevas tareas con el fin de adelantar la documentación para la primera entrega. Tiempo Registrado: 1 hora

- [x] Crear diagramas mas detallados de la arquitectura y agregarlos al documento base.

- [x] Agregar al documento las especificaciones técnicas de Glassfish 4.1.1 (build 1)

- [ ] Agregar al documento las especificaciones técnicas de Apache 2.X

- [x] Agregar al documento las especificaciones técnicas de Mysql 5.X

**Comment by manuk160** [comment]
De acuerdo a la validación interna del equipo de trabajo en cuento al desarrollo del EJB y JPA se tomo la decisión de cambiar el contenedor principal Tomcat a Glassfish puesto que tomcat no nos proporcionaba todas la funcionalidades requeridas para el desarrollo del proyecto.

Url acceso servicios: http://190.60.244.154:8080
Url Aceeso admin console: http://190.60.244.154:4848/login.jsf  
Usuario: admin
Contraseña: oAm584$%"193dfR

![image](https://cloud.githubusercontent.com/assets/25807878/23553369/7662307a-ffee-11e6-9462-065ce9005645.png)

**Comment by nmartinezmarin** [comment]
Tenienendo en cuenta las validaciones que se realizaron con el equipo de trabajo se realizan las modificaciones pertinentes al documento MODELO DE INFRAESTRUCTURA.docx
[MODELO.DE.INFRAESTRUCTURA-1.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/818474/MODELO.DE.INFRAESTRUCTURA-1.docx)

Tiempo Registrado : 2 Horas

**Comment by manuk160** [comment]
Diagrama de infraestructura actualizado.

[DiagramaServidores.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/821261/DiagramaServidores.pdf)

**Comment by manuk160** [comment]
Adjunto el documento de modelo de infraestructura modificado de acuerdo a la revisión del mismo y la definición presentada el día 4 de marzo de 2017.

[MODELO_DE_INFRAESTRUCTURA-PRESENTADO.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/821353/MODELO_DE_INFRAESTRUCTURA-PRESENTADO.docx)

**Comment by CristianGarzonBernal** [comment]
[Especificaciones  técnicas MySql.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/826319/Especificaciones.tecnicas.MySql.docx)
Especificaciones MySql y GLass Fish.
tiempo registrado 45 minutos.

**Comment by manuk160** [comment]
Actualización de documentos funcionales de acuerdo a especificaciones técnicas enviadas por @cirlord1 

[MODELO_DE_INFRAESTRUCTURA_V4.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/827892/MODELO_DE_INFRAESTRUCTURA_V4.docx)
