### ISSUE TITLE
Base de Datos

### ISSUE THREAD

**Issue by JuanCheroslan** [ISWPOLI/Pacto-de-Honor#115]
**Generacion de la base de datos**

- [x] Creacion del modelo entidad relación

- [x] Creacion de scripts de base de datos

- [x] Poblar la base de datos ( Personajes deben tener las definiciones según las descripciones entregadas)

**Adjuntar:**
- [x] Scripts de la base de datos 
- [ ] Scripts de población de la base 
- [x] Adicionar integrantes y las tareas faltantes en esta historia

**Comment by zergiozerna81** [comment]
Tiempo: 3 horas de clase

Alexander Saboya Sánchez
Juan Guillermo Celemín
Sergio Andres Serna Franco

Se trabajo en el desarrollo de un muevo modelo entidad relación dado que se identificaron falencia en el primer modelo propuesto, para esto se aclararon dudas que teníamos con el equipo de Camila.

Se género el borrador del mismo.

**Comment by zergiozerna81** [comment]
Tiempo: 2 horas

Se elabora el modelo entidad relación, el cual se adjunta en Visio y pdf.

[Modelo Entidad Relación Poli Fighters.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/802296/Modelo.Entidad.Relacion.Poli.Fighters.zip)

**Comment by jnrubiano** [comment]
Hola @zergiozerna81, ¿podrían indicar los cambios que realizaron e indicar si van a incluir el script de creación? Gracias.

**Comment by alexsabsan** [comment]
Tiempo 2 horas 
Scrip Creacion Base de datos Segun entidad Relacion cargado

[Pacto_Honor_BD_SQL.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/802440/Pacto_Honor_BD_SQL.zip)

**Comment by juancelemin** [comment]
- [x] se crea script para la bd (1 min)

- [x] se identifican errores en la bd y modelo (30 min)

- [x] se adjunta el script con excepción de la tabla poder_personaje y tablero por que considero importante corregir primero los errores de diseño (2 horas) (por que el la carga de datos fue por cada personaje y aun faltan personajes por cargar)


1. 

- el campo costo de la tabla personaje esta mal escrito esta costro 
- la base de datos no esta normalizada (existen campos repetidos en la tabla personaje)
- la base de datos no cubre todos los aspectos de los personajes
[poblacion.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/802628/poblacion.txt)

**Comment by JuanCheroslan** [comment]
Equipo, ya estan los scripts definitivos? recuerden que las demas tareas dependen 100% de que tengamos la base

**Comment by juancelemin** [comment]
Por el momento serian esos por que para hacer la correcion es neseario
comunicarse con el otro equipo para aclarar dudas

**Comment by jnrubiano** [comment]
Buenas noches. Por favor tener en cuenta, aparte del levantamiento de requerimientos por parte del grupo 1,  los reportes propuestos en el issue 142 "Reportes consolidados" ya que debemos exponer servicios para dichos consumos. He propuesto algunos servicios y comento los siguientes puntos para que por favor los debatamos mañana y de ser necesario realizar las modificaciones pertinentes:
- [x] ¿Cómo se sabe en qué nivel se encuentra un jugador?
- [x] Si existe una tabla cruzada entre personaje y poder, ¿es necesario tener dos atributos para dos poderes? 
- [x] ¿Qué es el campo rol en el personaje?
- [x] Debemos tener unas tablas para generar logs (tiempos, fechas, horas)
- [x] ¿Insignias?

También aprovecho para que empecemos a usar versiones de los issues, ya se tenía una V1 de este issue, ésta modificación debería ser la V1.1 o V2 y deberiamos nombrar los script con dichas terminaciones, esto no sólo evita la generación de muchos hilos para una tarea sino que también ayuda en el control de los cambios que se realizan.

**Comment by jnrubiano** [comment]
De acuerdo a la reunión sostenida el sábado 1 de Marzo con @juancelemin @JuanCheroslan @wpradere @zergiozerna81 @alexsabsan se acordaron lo siguientes cambios:

- Eliminar llave entre mundo y personaje.
- Cambiar el nombre de la tabla tablero a "nivel"
- Agregar llave foránea id_nivel_actual (jugador) y id_nivel (nivel)
- Eliminar los atributos id_poder1 y id_poder2 de la tabla personaje
- Crear tabla rol (id, nombre, descripcion) y hacer la relación rol(personaje)
- Crear tabla log (id_log [AI], id_jugador, tiempo [time], fecha_inicio, fecha_final)

Aclaración:
- No están especificadas las insignicas en el documento de las limitaciones.

@wpradere por favor su colaboración modificando el script.

**Comment by wpradere** [comment]
Buenas noches se sube scrip sql 

@zergiozerna81 @juancelemin @alexsabsan 


[Pacto_Honor_BD0.4.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/812599/Pacto_Honor_BD0.4.txt)

[Modelo Entidad Relación v0.4.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/812604/Modelo.Entidad.Relacion.v0.4.pdf)

**Comment by zergiozerna81** [comment]
Tiempo: 3 horas

Se trabajo en la revisión del modelo entidad relación de la BD, se realizaron los cambio propuestos, se sube el Modelo Entidad Relación v0.4 y los scripts de la BD

**Comment by manuk160** [comment]
Validación en cargue:

Durante el proceso de población de la base de datos se genera un error al cargar el jugador con respecto a una llave a la tabla log.

[SQL]INSERT INTO Jugador (nickname, monedas, puntosexpe, nivel_jugador, puntos_vida) VALUES ("redSoul",100,1500,2,200);
[Err] 1452 - Cannot add or update a child row: a foreign key constraint fails (`p_h01`.`jugador`, CONSTRAINT `fk_Jugador_Log1` FOREIGN KEY (`Log_idLog`) REFERENCES `log` (`idLog`) ON DELETE NO ACTION ON UPDATE NO ACTION)

**Comment by zergiozerna81** [comment]
Tiempo: 4 horas

Adjunto script base de datos y modelo entidad relación v0.7 habiendo cargado datos en la BD de forma correcta.

[bd pacto de honor v07.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/818439/bd.pacto.de.honor.v07.zip)

**Comment by manuk160** [comment]
Este fue la base de datos presentada en clase y el modelo. Se realiza cargue para la muestra para mostrar avances y de acuerdo a la reunión posterior a la presentación esta seria la actividad final a reportar para cerrar este ciclo.

![image](https://cloud.githubusercontent.com/assets/25807878/23611331/ad9ee80a-0244-11e7-9673-1680a96240e5.png)
