### ISSUE TITLE
Definir módulos a desarrollar

### ISSUE THREAD

**Issue by ingenieriadelsoftware** [ISWPOLI/Pacto-de-Honor#116]
**Definir módulos a desarrollar**
**Tareas**
- [x] Realizar documento de especificación de los módulos 
- [x] Adicionar las tareas faltantes en esta historia

**Comment by CamilaG08** [comment]
Se cierra ya que se replica la tarea en el Issue #169 y se asigna a Camila Gutiérrez y Juan Sebastián Rodríguez.
