### ISSUE TITLE
Crear historias tareas hasta la primera entrega

### ISSUE THREAD

**Issue by ingenieriadelsoftware** [ISWPOLI/Pacto-de-Honor#117]
**Crear historias tareas hasta la primera entrega**

**Tareas**
- [x] Documento con pantallazos de las historias creadas-
- [x] Adicionar las tareas faltantes en esta historia

**Comment by CamilaG08** [comment]
[Historias creadas desde el 1ro de marzo hasta el 5 de marzo.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/822689/Historias.creadas.desde.el.1ro.de.marzo.hasta.el.5.de.marzo.docx)
