### ISSUE TITLE
Definición de sprints y entregables 

### ISSUE THREAD

**Issue by ingenieriadelsoftware** [ISWPOLI/Pacto-de-Honor#118]
** Definición de sprints y entregables **

**Tareas**
- [x] Definición y Creación de milestons en git
- [x] Adicionar las tareas faltantes en esta historia

**Comment by jrsosago** [comment]
Cada semana nos reunimos con @CamilaG08 para organizar el sprint y los entregables, los cuales son informados a @jdbernalv. Por lo tanto se cierra está Issue.
