### ISSUE TITLE
Creación de historias

### ISSUE THREAD

**Issue by ingenieriadelsoftware** [ISWPOLI/Pacto-de-Honor#12]
** Historia relacionada **
Como grupo del proyecto es necesario definir historias para cada uno de los módulos del juego.

** Descripción de la tarea **
- [x] Combate
- [x] Soluciones personajes
- [x] Psicotécnica
- [x] Tipos de plagio.

**Comment by CamilaG08** [comment]
[Consolidación de personajes.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/822248/Consolidacion.de.personajes.docx)

[Ideas-10tiposdeplagio.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/822250/Ideas-10tiposdeplagio.pdf)

**Comment by CamilaG08** [comment]
Se cierra ya que la documentación relacionada a la psicotecnia queda en los Issues #185 y #186 .
