### ISSUE TITLE
Modulo Administración

### ISSUE THREAD

**Issue by JuanCheroslan** [ISWPOLI/Pacto-de-Honor#120]
el modulo de administración debe consumir la base de datos para hacer las siguientes actividades

- [ ] Crear mundos y niveles ( siempre  5 por mundo)

- [ ] Mostrar los mundos que no han sido desbloqueados

- [ ] Reportes de administracion

**Comment by Lakes1234** [comment]
Tiempo: 3 horas de clase
Compañeros de acuerdo a instrucciones debemos diseñar un proyecto web que nos permita desarrollar el modulo de administración a nivel funcional incluyendo su login.

Se realiza mockup del diseño del modulo.

Steven Lagos
Ricardo Zambrano

**Comment by JuanCheroslan** [comment]
Estimados,  como van con el avance de esta tarea

**Comment by Lakes1234** [comment]
Juan estamos trabajando en el diseño y entorno del modulo por otra parte estamos buscando herramientas para consumo de datos.

**Comment by EdnaEspejo** [comment]
Se realizara prototipo para modelar el esquema que nos permita ver desde HTML los datos del Jugadro en cuanto a Nivel, Experiencia y Logros obtenidos durante el juego. Para el tipo de Login por medio del juego se necesita realizar la conexión a la BD que contenga los datos del Jugador y generar el reporte de su estado en el juego.
Se esta validando como traer la información del jugador si el ingreso es por otro tipo de Login independiente al que tiene el juego ya que la consulta se realiza por otro medio

**Comment by EdnaEspejo** [comment]
Tiempo: 2 horas

Se realiza ventana de login para el administrador, este nos direccionará al modulo donde se puede administrar el juego, este  codigo es un prototipo funcional de la ventana de login con un usuario administracion fijo que se usará para realizar pruebas, a futuro esta validación debe realizarse directamente en la base de datos, tambien para validar que se ejecuta de manera correcta se muestra un mensaje de bienvenida luego este desaparece y en su reemplazo nos direccionará a la ventana del modulo en el que nos encontramos trabajando en este momento

[LoginAdmin.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/815867/LoginAdmin.zip)

**Comment by rzambrano112** [comment]
Adicionalmente se esta pensando en el prototipo para tomar los datos de la base de datos y presentar en la ventana del administrador todo la información concerniente al juego.

**Comment by EdnaEspejo** [comment]
[ModuloAdmin.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/818668/ModuloAdmin.zip)

Se adjunta el avance del proceso de desarrollo del modelo
Tiempo: 4 horas

**Comment by jnrubiano** [comment]
Hola buenas tardes:

¿Han visto algo de gestores de contenido? Les recomiendo ver Wordpress o Joomla, permiten la gestión del contenido de una forma amena y además les construye todo el GUI con la instalación de los mismos ésto les ahorrará tiempo en la maquetación y en funcionalidad de cada uno de los elementos de la pantalla.

https://es.wordpress.com/
https://www.joomla.org/

Saludos.
