### ISSUE TITLE
Persistencia-Netbeans

### ISSUE THREAD

**Issue by JuanCheroslan** [ISWPOLI/Pacto-de-Honor#121]
Modulo de Persistencia usando java beans consumiendo el servicio rest

- [ ] Configuracion del servicio REST

- [x] Creacion de los Beans respectivos

- [x] conexion con la base de datos

**Comment by wpradere** [comment]
Se crea la persistencia JPA y Sesión con la base de datos en Mysql  Horas empleadas 4
![image](https://cloud.githubusercontent.com/assets/22016129/23391118/8de64d86-fd40-11e6-9e7f-9185c5bee79c.png)

**Comment by jnrubiano** [comment]
Buenas noches. Por favor tener en cuenta también los reportes propuestos en el issue 142 "Reportes consolidados" ya que debemos exponer servicios para dichos consumos. He propuesto algunos servicios y comento los siguientes puntos para que por favor los debatamos mañana y de ser necesario realizar las modificaciones pertinentes:
- [ ] ¿Cómo se sabe en qué nivel se encuentra un jugador?
- [ ]Si existe una tabla cruzada entre personaje y poder, ¿para qué se ponen dos atributos para dos poderes?
- [ ] ¿Qué es el campo rol en el personaje?
- [ ] Debemos tener unas tablas para generar logs (tiempos, fechas, horas)
- [ ] ¿Insignias?
También aprovecho para que empecemos a usar versiones de los issues, ya se tenía una V1 de este issue, ésta modificación debería ser la V1.1 o V2, esto no sólo evita la generación de muchos hilos para una tarea sino que también ayuda en el control de los cambios que se realizan.

**Comment by wpradere** [comment]
### Se realizan modificaciones en la BD 
1. Se crea relación mundo personaje
2. Se se cambia atributo idTablero Id nivel 

Horas empleadas   1 

 @manuk160 @JuanCheroslan 
[Pacto_Honor_BD05.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/814017/Pacto_Honor_BD05.txt)
[Modelo Entidad Relación v0.5.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/814028/Modelo.Entidad.Relacion.v0.5.pdf)

**Comment by manuk160** [comment]
Validación de Script

- Se  realiza proceso de validación de acuerdo a los cambios sugeridos en el modelo entidad relación.

- Montaje de prueba de script en mysql.

![script_bd_montado](https://cloud.githubusercontent.com/assets/25807878/23516539/7ff1d734-ff3b-11e6-9dc2-98e2e2084e99.JPG)

![modelo_entidad_relacion](https://cloud.githubusercontent.com/assets/25807878/23516542/81f1065e-ff3b-11e6-9f6b-6926026dca8a.JPG)

**Comment by wpradere** [comment]
### Se actualiza persistencia 
1. JPA
2. EJB


Horas empleadas 2
![persistenciav2](https://cloud.githubusercontent.com/assets/22016129/23528055/63829b8a-ff66-11e6-875b-67163d010cec.png)

**Comment by manuk160** [comment]
De acuerdo al confirmación sobre le jpa y el ejb envió los datos de acceso servidor de prueba glassfish:

Url acceso servicios: http://190.60.244.154:8080
Url Aceeso admin console: http://190.60.244.154:4848/login.jsf
Usuario: admin
Contraseña: oAm584$%"193dfR

**Comment by wpradere** [comment]
[com.Persistenciav6.jar.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/818398/com.Persistenciav6.jar.txt)

## Se realiza modificación en la base de datos y actualiza la persistencia 

Horas empleadas 4
![base4](https://cloud.githubusercontent.com/assets/22016129/23576172/e2471ee0-006b-11e7-9b01-b3302d82a5f9.png)



@alexsabsan @manuk160 @DanteVDrako @nicardenasp 
[Pacto_Honor_BD06 .txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/818400/Pacto_Honor_BD06.txt)

**Comment by zergiozerna81** [comment]
William tener en cuenta que la categoría va relacionada al personaje y no al jugador, la información que contiene es el rol y el tipo de personaje.

Sip ya se hizo la actualización :thumbsup:
