### ISSUE TITLE
1.1.3 Mockups mapa primer y segundo mundo.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#122]
**Descripción:**
Mockups mapa, niveles y la batalla final del primer y segundo mundo.

**Tareas a realizar:**
- [x] Mockup mapa del primer y segundo mundo (niveles y batalla final).
- [x] Mockup de cada nivel (8 en total).
- [x] Mockup batalla final (escenario y personaje correspondiente a el mundo 1 y 2)

**Comment by ghost** [comment]
## REGISTRO TOTAL DE TIEMPO: 4 horas y 30 Minutos

## Mockups Selección Primer y segundo mundo (Registro de Tiempo: 30 minutos)

![mockup5](https://cloud.githubusercontent.com/assets/22629833/23343253/46ee2ab2-fc36-11e6-9ed9-34dab48336b0.png)
![mockup6](https://cloud.githubusercontent.com/assets/22629833/23343252/46eb826c-fc36-11e6-89f6-62621286c586.png)


## Mockups Niveles 1 hasta el 10 (Registro de Tiempo: 4 Horas)

![mockupnivel1a](https://cloud.githubusercontent.com/assets/22629833/23346276/d856f6b6-fc66-11e6-8167-4e5847171180.png)
![mockupnivel1b](https://cloud.githubusercontent.com/assets/22629833/23346271/d853f754-fc66-11e6-9123-457eb85e81cf.png)
![mockupnivel2a](https://cloud.githubusercontent.com/assets/22629833/23346272/d8542986-fc66-11e6-92b2-31caf13bf0fb.png)
![mockupnivel2b](https://cloud.githubusercontent.com/assets/22629833/23346273/d854b7f2-fc66-11e6-8968-8c86ec2622fb.png)
![mockupnivel3a](https://cloud.githubusercontent.com/assets/22629833/23346274/d855afae-fc66-11e6-8c68-fe3aed7e99f7.png)
![mockupnivel3b](https://cloud.githubusercontent.com/assets/22629833/23346275/d8566ef8-fc66-11e6-81c9-fc69971dfad8.png)
![mockupnivel4a](https://cloud.githubusercontent.com/assets/22629833/23346278/d864e3de-fc66-11e6-80cb-99823e0388c8.png)
![mockupnivel4b](https://cloud.githubusercontent.com/assets/22629833/23346277/d8643bd2-fc66-11e6-910d-f9185dc91b8f.png)
![mockupnivel5a](https://cloud.githubusercontent.com/assets/22629833/23346279/d864ebd6-fc66-11e6-8936-497a6d04960d.png)
![mockupnivel5b](https://cloud.githubusercontent.com/assets/22629833/23346280/d86596a8-fc66-11e6-90f1-a716f195b88d.png)
![mockupnivel5c](https://cloud.githubusercontent.com/assets/22629833/23346281/d867c554-fc66-11e6-88a3-f5963e0a3c01.png)
![mockupnivel6a](https://cloud.githubusercontent.com/assets/22629833/23346282/d867cc3e-fc66-11e6-8cc0-b9b5294ffa91.png)
![mockupnivel6b](https://cloud.githubusercontent.com/assets/22629833/23346288/d87b2d7e-fc66-11e6-8354-4d535af7a049.png)
![mockupnivel7a](https://cloud.githubusercontent.com/assets/22629833/23346283/d875ad0e-fc66-11e6-9376-c5a18f621311.png)
![mockupnivel7b](https://cloud.githubusercontent.com/assets/22629833/23346284/d875f5ca-fc66-11e6-84e0-5b04e48c7801.png)
![mockupnivel8a](https://cloud.githubusercontent.com/assets/22629833/23346285/d876570e-fc66-11e6-807d-7850bf426875.png)
![mockupnivel8b](https://cloud.githubusercontent.com/assets/22629833/23346286/d8797344-fc66-11e6-955e-ae69fb9e15f5.png)
![mockupnivel9a](https://cloud.githubusercontent.com/assets/22629833/23346287/d8799464-fc66-11e6-80d1-df7aef134cd0.png)
![mockupnivel9b](https://cloud.githubusercontent.com/assets/22629833/23346289/d88722c8-fc66-11e6-8a71-b21be0c46849.png)
![mockupnivel10a](https://cloud.githubusercontent.com/assets/22629833/23346290/d8874eec-fc66-11e6-8f7b-d56e5ffbcd01.png)
![mockupnivel10b](https://cloud.githubusercontent.com/assets/22629833/23346291/d8876616-fc66-11e6-829b-2f1aac983c05.png)
![mockupnivel10c](https://cloud.githubusercontent.com/assets/22629833/23346292/d88b343a-fc66-11e6-8e8a-ed81467fad66.png)
