### ISSUE TITLE
Evaluar la propuesta de reportes

### ISSUE THREAD

**Issue by ingenieriadelsoftware** [ISWPOLI/Pacto-de-Honor#123]
**Evaluar la propuesta de reportes**
**Tareas**
- [x] Documento de Diseño de los reportes del juego 
- [x] Adicionar las tareas faltantes en esta historia

**Comment by ghost** [comment]
# **Propuesta Evaluación de Reportes**

Gabriel Álvarez. Código 1310011422
Iván Barrantes. Código 1410012431
Camilo D’Achiardi Código 1520010428
Sebastián Rodríguez Código: 1010017141



[Evaluacion.de.propuesta.de.reportes.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/809700/Evaluacion.de.propuesta.de.reportes.docx)


Registro de tiempo: 3 horas.
