### ISSUE TITLE
1.4.2 Mockups de combates en computador y celular

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#125]
**Descripción:**

Mockup final del combate web y en el celular (con Joystick y botones).

**Comment by KmiArthur** [comment]
# Mockup web y juego móvil: 
Tiempo trabajo: 3.5h

![mockups web logos poderes 001](https://cloud.githubusercontent.com/assets/17441569/23477353/bff36b14-fe8b-11e6-999a-51e4ad6ca7ac.jpeg)
![mockups web logos poderes 002](https://cloud.githubusercontent.com/assets/17441569/23477356/c010d12c-fe8b-11e6-9997-e40d8e77c741.jpeg)
![mockups web logos poderes 003](https://cloud.githubusercontent.com/assets/17441569/23477358/c0127dd8-fe8b-11e6-8e52-f2ebe425c86f.jpeg)
![mockups web logos poderes 004](https://cloud.githubusercontent.com/assets/17441569/23477354/c00cebac-fe8b-11e6-9276-0868ff8c3f9b.jpeg)
![mockups web logos poderes 005](https://cloud.githubusercontent.com/assets/17441569/23477359/c012efca-fe8b-11e6-9091-1296f76ff739.jpeg)
![mockups web logos poderes 006](https://cloud.githubusercontent.com/assets/17441569/23477357/c011e56c-fe8b-11e6-86d1-e3e354e3ed4b.jpeg)
![mockups web logos poderes 007](https://cloud.githubusercontent.com/assets/17441569/23477355/c00f90be-fe8b-11e6-8c91-3769756eb1be.jpeg)
![mockups web logos poderes 008](https://cloud.githubusercontent.com/assets/17441569/23477360/c021f7ea-fe8b-11e6-973e-e11a10f747dd.jpeg)
![mockups web logos poderes 009](https://cloud.githubusercontent.com/assets/17441569/23477362/c03334ba-fe8b-11e6-9357-d528900a2291.jpeg)
![mockups web logos poderes 010](https://cloud.githubusercontent.com/assets/17441569/23477361/c02a6a1a-fe8b-11e6-8a31-664c02555731.jpeg)

**Comment by KmiArthur** [comment]
Adjunto imágenes del _joystick_ para su descarga en HD: 
[Joystick movil.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/811828/Joystick.movil.zip)
