### ISSUE TITLE
1.3.1 Mockups finales de mapa de navegación

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#126]
**Descripción**
De acuerdo a las especificaciones de la letra contenidos en el Issue #86 realizar cambios a la estética de las navegaciones, teniendo en cuenta los nuevos escenarios y la distribución de estos.

**Comment by ivandav** [comment]
**MOCKUPS FINALES DE NAVEGACION**
Falta añadir a un mockup la imagen de la facultad de ingeniería,se actualizara cuando se suba esta imagen.
REGISTRO DE TIEMPO 30 MINUTOS
![mockup1](https://cloud.githubusercontent.com/assets/22629584/23346134/91c0b954-fc65-11e6-827e-51b6d8f4097f.png)
![mockup2](https://cloud.githubusercontent.com/assets/22629584/23346135/91c906c2-fc65-11e6-99bc-e7481e1044ea.png)
![mockup3](https://cloud.githubusercontent.com/assets/22629584/23346137/91c9cd96-fc65-11e6-8824-013f3a5dcd3b.png)
![mockup4](https://cloud.githubusercontent.com/assets/22629584/23346136/91c9526c-fc65-11e6-9bd9-abbe2007a900.png)
![mockup5](https://cloud.githubusercontent.com/assets/22629584/23346139/91caa428-fc65-11e6-835e-c4d56a2a4a90.png)
![mockup6](https://cloud.githubusercontent.com/assets/22629584/23346138/91ca7b10-fc65-11e6-9924-84844d8ed5d8.png)
![new mockup 1](https://cloud.githubusercontent.com/assets/22629584/23538217/88e9633e-ff9f-11e6-9dd0-b642596e60d3.png)

![mockup8](https://cloud.githubusercontent.com/assets/22629584/23346141/91e9a2ec-fc65-11e6-9e5b-cb214b73e16f.png)
![mockup9](https://cloud.githubusercontent.com/assets/22629584/23346145/91f26b3e-fc65-11e6-9c5b-810460888985.png)
![mockup10](https://cloud.githubusercontent.com/assets/22629584/23346142/91ee9658-fc65-11e6-91f1-d0f5ffd23a57.png)
![mockup11](https://cloud.githubusercontent.com/assets/22629584/23346143/91f0d44a-fc65-11e6-8064-39a81282e012.png)
![mockup12](https://cloud.githubusercontent.com/assets/22629584/23346144/91f15ae6-fc65-11e6-9aa9-e1460dbde59d.png)
![mockup13](https://cloud.githubusercontent.com/assets/22629584/23346146/9203548a-fc65-11e6-8c39-440a926404c1.png)
