### ISSUE TITLE
Comunicación entre equipos 

### ISSUE THREAD

**Issue by ingenieriadelsoftware** [ISWPOLI/Pacto-de-Honor#127]
**Comunicación entre equipos **

**tareas**
- [x] Consolidar reglas, manual de comunicación del equipo. @dayepesb

- [x] Adicionar las tareas faltantes en esta historia

- [x] Organigrama del equipo de trabajo
- [x] Identificación de roles.
- [x] Identificación de funciones (por lo menos 2 semanas)

**Comment by dayepesb** [comment]
[Comunicación y re-organización entre equipos.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/805486/Comunicacion.y.re-organizacion.entre.equipos.docx)

Solución a la falta de comunicación entre equipos de trabajo

Tiempo : 1 hora

**Comment by Richardcas7ro** [comment]
[Organigrama.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/809582/Organigrama.docx)

**Comment by dayepesb** [comment]
Organigrama 
30 min

[Organigrama.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/812597/Organigrama.docx)

**Comment by dayepesb** [comment]
La asignación de tareas, e indentificación de funciones corresponde a:
@CamilaG08  
@jrsosago 
@jdma0440 
@JuanSebastianRodriguezJ
