### ISSUE TITLE
1.1.4 Algoritmo de batalla

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#128]
- [x] Codificar el tiempo (1:30) del reloj del campo de  batalla @jrsosago 
- [x] Determinar Ganagor en una partida en los diferentes casos propuestos, y el caso de un empate
- [ ] Algoritmo para que el villano juegue de la mejor manera contra un heroe

**Comment by jrsosago** [comment]
[Práctica Aplicada.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/812317/Practica.Aplicada.pdf)

**Comment by dayepesb** [comment]
[algoritmo de batalla.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/818491/algoritmo.de.batalla.txt)

**Comment by CamilaG08** [comment]
**TAREAS**

- [x] Tener los componentes del campo de batalla
- [x] Realizar el campo de batalla para realizar pruebas (o utilizar el realizado por @gsalvarez )
- [ ] Algoritmo de combate del malo teniendo en cuenta: Tiempo, ganar o perder y empate
- [x] Interacción de los componentes (Barras, tiempo, poderes)
- [ ] Pantalla de resultado de la batalla
- [ ] Previo al combate, poner diálogos de los personajes ( @jrsosago  )
- [x] Menú de pausa funcional
- [x] Organizar las imágenes  en las direcciones estándar.

**Comment by dayepesb** [comment]
[juego.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/829525/juego.zip)

aqui se adeanto el trabajo del reloj y que se detenga y lo arroje a una nueva pantalla que determine cual es el ganador, tambien se realizo los movimientos de cada personaje.

se realizo el trabajo con @nicolas96 y @ivandav

**Comment by nmartinezmarin** [comment]
[juego.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/852134/juego.zip)

Aquí se adelanto la opción de pausa con @ivandav  y se gestiono el movimiento automático de el villano  ademas de gestionar las colisiones de los personajes en la batalla para que no queden acorralados y surge una nueva tarea
Tiempo de trabajo : 5 horas.
- [ ] modificar los sprites para que los personajes se puedan tocar

**Comment by CamilaG08** [comment]
Se corre a 1 sprint más, siendo el 24 de marzo la fecha límite de entrega ya que será uno de los entregables a mostrar en la reunión de cierre del Sprint 6.

**Comment by CamilaG08** [comment]
**NUEVA TAREA**

- [ ] Modificar el tamaño de los sprites anteriormente realizados para que las colisiones se vean mejor.

**Comment by ingenieriadelsoftware** [comment]
Es importante que si bien las historias pueden no están asignadas a una sola persona (deber ser), por lo menos las tareas si tengan una persona asignada.

- [ ] Asignar una sola persona a cada una de las tareas restantes @CamilaG08 

- [ ] Definir quienes estarán encargados de la creación de los sprites o específicamente de qué personaje @CamilaG08.

**Comment by ivandav** [comment]
Se anexan pantallas de juego con menu de pausa y pantalla de ganador
![juego terminado](https://cloud.githubusercontent.com/assets/22629584/24319385/468c418c-10e8-11e7-8aee-6a4df6aa380e.png)
![menu pausa](https://cloud.githubusercontent.com/assets/22629584/24319384/468b24c8-10e8-11e7-9ff1-66fedee162bb.png)
![pantalla ganador](https://cloud.githubusercontent.com/assets/22629584/24319383/4688c61a-10e8-11e7-8c80-ebc8891c6670.png)

**Comment by nmartinezmarin** [comment]
Se hace commit a la rama Nicolas Martinez con los siguientes items 

- [x] se implentean los poderes del villano

- [x] se mejora el movimiento del villano

- [x] se activa el daño cada vez que se impacte con una ataque por medio de una funcion

Tiempo registrado : 5 horas

**Comment by jrsosago** [comment]
Se cierra este Issue a pesar de que falta una tarea por realizar, para asignarla individualmente con modificaciones de lo revisado por @CamilaG08 y yo, para el Sprint 7 y 8.
