### ISSUE TITLE
1.2.6 Algoritmo de navegación del juego.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#129]
**Descripción**

Algoritmo (y su implementación) que integre el login con la historieta introductoria, que siga a la selección de avatar y luego al mapa de navegación.

**Tareas a realizar**

- [x] 1. Integración del login con la historia introductoria.
- [x] 2. Selección personaje.
- [x] 2. Mapa de los 12 mundos con todos sus niveles.
- [x] 3. Integración ítem 1, 2 y 3.

**Comment by ghost** [comment]
- [x] 1.2.5.1 Algoritmo de navegación del juego Integración login con historieta Introducción.
- [ ] 1.2.5.2 Algoritmo de navegación del juego Selección Avatar.
- [x] 1.2.5.3 Algoritmo de navegación del juego Mapa Navegación.

**Comment by ghost** [comment]
Se divide la tarea en 3 para los integrantes del grupo o las personas que están asignadas, en mi tarea  1.2.5.1 Algoritmo de navegación del juego Integración login con historieta Introducción, se realiza el algoritmo pensado en modo desarrollado.

**Comment by ghost** [comment]
La issues 1.2.5.1 Algoritmo de navegación del juego Integración login con historieta Introducción, se realiza el algoritmo pensado en modo desarrollado, se hace la documentación correspondiente y se genera la incrustación del login con la historieta.

**Comment by jrsosago** [comment]
Se cambia la asignación de este Issue. Se asigna @KmiArthur @gsalvarez  y @CristianGarzonBernal

**Comment by gabogabbs** [comment]
Se realiza la conexión entre los javascript de selección de avatar, selección de personaje, mapa de mundos, campo de batalla. Falta conectar login e historieta.
[Pacto de Honor.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/835476/Pacto.de.Honor.zip)

REGISTRO DE TIEMPO: 3 HORAS.

**Comment by CamilaG08** [comment]
Queda pendiente la terminación de los mundos por @CristianGarzonBernal perteneciente a la Issue #190 y el login con la historieta por parte de @gsalvarez ; por lo tanto se extiende hasta el martes 14 de marzo.

**Comment by CristianGarzonBernal** [comment]
![captura](https://cloud.githubusercontent.com/assets/22016808/23843349/3d89e48a-0789-11e7-87ae-5be7f4136051.PNG)
![captura1](https://cloud.githubusercontent.com/assets/22016808/23843362/4b9f50d2-0789-11e7-9951-9c3dec3f4dfe.PNG)
![captura3](https://cloud.githubusercontent.com/assets/22016808/23843374/5f77bbda-0789-11e7-93d0-3ff47df0caa0.PNG)
![captura4](https://cloud.githubusercontent.com/assets/22016808/23843376/6141c370-0789-11e7-9ad8-91bfd8c9d79d.PNG)
![captura5](https://cloud.githubusercontent.com/assets/22016808/23843379/63db2914-0789-11e7-9a5f-6fefa42ee5ba.PNG)

El codigo de la seleccion de mapas se ha enviado a @gsalvarez para unificación con el resto del codigo.
Tiempo registrado 6 hrs.

**Comment by gabogabbs** [comment]
Se descargan los archivos html de login para su integración.

Ventanas integradas:
- Login.
- Selección de avatar.
- Navegación por mundos.
- Selección de personaje.

Por lo anterior, se da como terminado el issue.

[Pacto de Honor.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/843179/Pacto.de.Honor.zip)

REGISTRO DE TIEMPO: 1 HORA Y 30 MINUTOS.

**Comment by jrsosago** [comment]
Falta subir todo el código según la distribución de carpetas que se encuentra en la Issue #169 , se le asigna está tarea a @CristianGarzonBernal y después de esto @CristianGarzonBernal debe cerrar esta Issue.

**Comment by CamilaG08** [comment]
Se cierra debido a que el día de hoy se explica el uso de las ramas y cómo subir código en el repositorio.
