### ISSUE TITLE
Creación de historias

### ISSUE THREAD

**Issue by DiegOliveros** [ISWPOLI/Pacto-de-Honor#13]
** Historia relacionada **
Como grupo del proyecto es necesario definir historias para cada uno de los módulos del juego.

** Descripción de la tarea **
- [x] Combate
- [x] Selección personajes
- [x] Psicitécnica
- [x] tipos de plagio.
![whatsapp image 2017-02-14 at 16 56 48](https://cloud.githubusercontent.com/assets/2998313/22985880/d1c83730-f377-11e6-8bac-99c14e035d6c.jpeg)

**Comment by jnrubiano** [comment]
@DiegOliveros profe, ¿acá toca definir la historia de usuario para "combate"?

**Comment by zergiozerna81** [comment]
@DiegOliveros profesor colocó este issue en grupo 2 y corresponde al grupo 1

**Comment by CamilaG08** [comment]
Las historias de usuario, se encuentran recopiladas en un documento que actualmente se está pasando al formato IEEE 830
