### ISSUE TITLE
1.3.2 Arreglar Mockups de las 4 facultades.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#130]
**Descripción**

Caricaturizar correctamente los 4 escenarios correspondientes a las 4 facultades.

**Comment by CristianGarzonBernal** [comment]
![amarillo](https://cloud.githubusercontent.com/assets/22016808/23537619/49d1b420-ff9b-11e6-97f0-e85a4a11cf01.gif)
![azukjpg](https://cloud.githubusercontent.com/assets/22016808/23537620/4b4e4192-ff9b-11e6-9916-5cc7475df719.gif)
![roja](https://cloud.githubusercontent.com/assets/22016808/23537621/4cdfe77c-ff9b-11e6-9c2c-6decf9cd8583.gif)
![verde](https://cloud.githubusercontent.com/assets/22016808/23537624/4f21670e-ff9b-11e6-9597-111871c58892.gif)

**Comment by CamilaG08** [comment]
Se cierra dado que se re asigna la tarea en el Issue #150 con otras tareas similares.
