### ISSUE TITLE
4.2.2 Modificar sprites.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#131]
**Descripción**

Modificar sprites realizados por Camilo y Juan Sebastián. Con ayuda de @ivandav terminar los sprites de los mini personajes y realizar los sprites con los poderes.

**TAREAS**

- [x] Modificar los sprites de Camilo
- [x] Modificar los sprites de Sebastián
- [x] Realizar los sprites de los mini peronajes
- [x] Integrar los poderes a los sprites

**Imágenes poderes 2 primeros mundos**

- Falta el poder de personalidad de Felipe Oso, que consta de tirar 2 libros juntos, uno de color más oscuro que otro.

Felipe Oso :  

- Plagio

![16833462_1333170060076046_679412913_o](https://cloud.githubusercontent.com/assets/22283896/23343556/7586b8a8-fc3b-11e6-81aa-30bdbfa4202a.png)

Andrés Zorro : 

- Personalidad

![16910611_1333159420077110_616200376_o](https://cloud.githubusercontent.com/assets/22283896/23343560/88595594-fc3b-11e6-819f-97249b2ad46c.png)

- Plagio

![16923973_1333195680073484_148212663_n](https://cloud.githubusercontent.com/assets/22283896/23343571/a77df178-fc3b-11e6-8147-c012144070c5.png)

**Comment by gabogabbs** [comment]
Se adjuntan los sprites de los personajes modificados y los sprites de los mini personjaes realizados por @ivandav .
Falta:

- Hacer animación de segundo poder para los personajes malos.
- Integrar los poderes a los sprites

[SpritesDePersonajes.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/809443/SpritesDePersonajes.zip)

REGISTRO DE TIEMPO: 7 HORAS Y 30 MINUTOS.

**Comment by gabogabbs** [comment]
Se realizaron los sprites de los poderes de plagio de los personajes malos (Falta Reutilización ya que la imagen no existía al momento de trabajar en este issue).
Faltan: los poderes de personalidad de todos los personajes.
Este issue queda en espera debido a la prioridad del código fuente. Ver el issue #129 
[poderesPlagio.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/835480/poderesPlagio.zip)

REGISTRO DE TIEMPO: 6 HORAS.

**Comment by gabogabbs** [comment]
Se realizan y modifican los siguientes sprites:
- Poderes personalidad personajes buenos.
- Poderes personalidad personajes malos.
- Poderes plagio personajes malos.

[PoderesPersonajes.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/843032/PoderesPersonajes.zip)

REGISTRO DE TIEMPO: 1 HORA Y 30 MINUTOS.

**Comment by gabogabbs** [comment]
La realización de los sprites de los mini personajes ha sido movida al issue #168. Por esto, se da por terminado este issue.

**Comment by jrsosago** [comment]
Se cierra este Issue, debido a que ya está terminada la tarea.
