### ISSUE TITLE
1.6.2 Revisar, definir, mockups e implementación logros.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#132]
**Descripción**

Revisar y complementar lo presentado por @rzambrano112 y realizar el pseudo-código para el desbloqueo de dichos logros.

**TAREAS**

- [x] Revisar los documentos presentados
- [x] Complementar los logros
- [x] Complementar las imágenes
- [x] Realizar el pseudo-código a implementar 
- [x] Implementar el tablero de logros

**Documentos**

[Creacion.y.definicion.de.logros.Ricardo.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/802307/Creacion.y.definicion.de.logros.Ricardo.pdf)

[MOCKUP.DEL.TABLERO.DE.LOGROS.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/802308/MOCKUP.DEL.TABLERO.DE.LOGROS.pdf)

**Comment by rzambrano112** [comment]
En relación a los logros obtenidos alrededor del juego teniendo en cuenta cada uno de los escenarios en donde hay 12 mundos y 60 niveles de pelea. Se realiza una propuesta de logros por cada uno de los niveles de cada mundo con la finalidad de generar mayor jugabilidad e impacto del mismo. Dicha propuesta se hace sobre el proyecto original y unificado del juego.
[MOCKUP DEL TABLERO DE LOGROS ACTUALIZADA.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/811993/MOCKUP.DEL.TABLERO.DE.LOGROS.ACTUALIZADA.docx)

**Comment by CamilaG08** [comment]
Este es el documento parcial de logros, queda pendiente fusionar los 2 presentados.


Tiempo utilizado: 2 horas y 30 minutos
[Logros.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/812405/Logros.docx)

**Comment by CamilaG08** [comment]
Documento completo de los logros.

Tiempo empleado: 30 minutos

[Logros.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/812827/Logros.docx)

**Comment by CamilaG08** [comment]
**Mockups Tablero de Logros**

![mockuplocked](https://cloud.githubusercontent.com/assets/22283896/23833780/927a0f40-0718-11e7-88c6-4f058648fa4a.jpg)


![mockupunlocked](https://cloud.githubusercontent.com/assets/22283896/23833779/9279911e-0718-11e7-8cd0-dd3a438d5cff.jpg)


Tiempo empleado: 30 minutos

**Comment by CamilaG08** [comment]
Se cierra el Issue ya que se asigna la implementación de los logros a Juan Carlos.
