### ISSUE TITLE
1.1 Mundos y escenarios

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#133]
**Descripción**

Todos los componentes necesarios para la consolidación de los mundos y escenarios

**TAREAS**

- [x] Mockups mapas y mundo 1 y 2
- [x] Algoritmo de batalla

**Comment by jrsosago** [comment]
Issues pertenecientes a está característica
- [x] 1.1.1 Mockups mapa primer y segundo mundo #122
- [x] 1.1.2 Algoritmo de batalla #128
