### ISSUE TITLE
2.1.2 Bosquejos de todos los poderes y sus logos

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#134]
**Descripción**

Creación de los logos y las imágenes de todos los poderes (personalidad y plagio en el caso de los malos), menos Andrés Zorro y Felipe Oso.

**TAREAS**

- [x] Logo e imagen para los poderes de Camilo Perezoso
- [x] Logo e imagen para los poderes de Carlos Buitre
- [x] Logo e imagen para los poderes de Nicolás Lagarto
- [x] Logo e imagen para los poderes de Víctor Hiena
- [x] Logo e imagen para los poderes de Julián Burro
- [x] Logo e imagen para los poderes de Juan Rata
- [x] Logo e imagen para los poderes de Ana Abeja
- [x] Logo e imagen para los poderes de Sara Abeja
- [x] Logo e imagen para los poderes de Juan Camaleón
- [x] Logo e imagen para los poderes de Luis Víbora (Sólo personalidad)
- [x] Logo e imagen para los poderes de Fabián Babuino (Sólo personalidad)
- [x] Logo e imagen para los poderes de Iván Ruiseñor
- [x] Logo e imagen para los poderes de Tati Hormiga
- [x] Logo e imagen para los poderes de Andrés Gallo
- [x] Logo e imagen para los poderes de Fabián Canario
- [x] Logo e imagen para los poderes de Cata Cierva
- [x] Logo e imagen para los poderes de Ana Pantera
- [x] Logo e imagen para los poderes de Daniela Jirafa
- [x] Logo e imagen para los poderes de Daniel León
- [x] Logo e imagen para los poderes de Pedro Ratón

**Imágenes de ejemplo**

Logo:

![16810555_1333170023409383_1695692339_o](https://cloud.githubusercontent.com/assets/22283896/23343794/fce30362-fc3e-11e6-87ec-6e7ab8b4c88c.jpg)

![16910811_1333159240077128_847830883_o](https://cloud.githubusercontent.com/assets/22283896/23343795/0301062c-fc3f-11e6-9a63-b264dc722e16.jpg)

Poder:

![16833462_1333170060076046_679412913_o](https://cloud.githubusercontent.com/assets/22283896/23343797/0c340ba4-fc3f-11e6-936c-f152a4031f2c.png)

![16910611_1333159420077110_616200376_o](https://cloud.githubusercontent.com/assets/22283896/23343799/12d8b39c-fc3f-11e6-9814-3af045ff8e32.png)

**Comment by CamilaG08** [comment]
**Documento de los personajes**

[2.Entrega.Subgrupo.-.Practica.Aplicada-1.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/802459/2.Entrega.Subgrupo.-.Practica.Aplicada-1.docx)

**Comment by KmiArthur** [comment]
# Logos de poderes según personaje: 
Diseño de logos caricaturizados acorde al diseño de los personajes del Pacto
(trabajo 8H)

![logos 001](https://cloud.githubusercontent.com/assets/17441569/23474737/d14e081e-fe82-11e6-8d7f-a3ee21966160.jpeg)
![logos 002](https://cloud.githubusercontent.com/assets/17441569/23474738/d16a9d44-fe82-11e6-8eb5-3b31bd3258f1.jpeg)
![logos 003](https://cloud.githubusercontent.com/assets/17441569/23474739/d16c6d2c-fe82-11e6-9073-b30cc43f54c4.jpeg)
![logos 004](https://cloud.githubusercontent.com/assets/17441569/23474740/d16d8518-fe82-11e6-897a-bbe404af088e.jpeg)

**Comment by KmiArthur** [comment]
**Adjunto el original de cada uno de los logos para su descarga en tamaño completo HD [aquí](https://drive.google.com/drive/folders/0B0eNk39asXpSYjFCeFdULW5lNDA?usp=sharing).**

**Comment by CamilaG08** [comment]
**TAREAS PENDIENTES**

- [x] Realizar las imágenes de los poderes para el campo de batalla 
- [x] Pasar las imágenes a @gsalvarez

**Comment by KmiArthur** [comment]
Entrega de imanes para poderes de personajes 
(Trabajo: 4.5h)

[Imágenes poderes (incompleto).zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/818453/Imagenes.poderes.incompleto.zip)

**Comment by KmiArthur** [comment]
# Entrega de imágenes para poderes de personajes terminados:
(Trabajo: 1h15m)

[Imagenes Poderes COMPLETO.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/818691/Imagenes.Poderes.COMPLETO.zip)

**Comment by CamilaG08** [comment]
Se cierra después de revisión y aprobación de los poderes, se descargan los archivos para dárselos a Gabriel.
