### ISSUE TITLE
1.2.5.1 Algoritmo de navegación del juego Integración login con historieta Introducción

### ISSUE THREAD

**Issue by ghost** [ISWPOLI/Pacto-de-Honor#135]
- [x] Descripción algoritmo login con historieta introducción 
- [x] Implementación algoritmo login historieta introducción

**Comment by JuanSebastianRodriguezJ** [comment]
Descripción Algoritmo Login.

- Creación formulario PHP.
- Captura de datos desde formulario.
- Creación base de datos Mysql PhpMyAdmin.
- Conexión base de datos.
- Almacenamiento de datos capturados en base de datos.
- Verificación de datos formulario- base.
- Enviar correo de autenticación cuenta. * Opcional.
- Acceso a Historia de juego.

**Comment by ghost** [comment]
Descripción Algoritmo Login.

- Creación formulario PHP.
- Captura de datos desde formulario.
- Creación base de datos.
- Conexión base de datos.
- Almacenamiento de datos capturados en base de datos.
- Verificación de datos formulario- base.
- Acceso a Historia de juego.

**Comment by ghost** [comment]
Implementación Algoritmo.
- Creación formulario.
 Nota: la implementación del formulario de login es tomada del repositorio.

https://raw.githubusercontent.com/ISWPOLI/Pacto-de-Honor/e899db3ed4a61456b055098b5ef1e5ce77f6f74b/Formulario_login

**Comment by ghost** [comment]
Se genera el acceso a la historieta integrado desde el login de usuario, se crea con href para poder pasar desde  el formulario login ya que el proceso de login no esta bien definido hasta ahora.

**Comment by ghost** [comment]
Incrustar la historieta en el login que se planteo inicialmente, podría ser de este modo, recordar que solo es una propuesta esta sujeto a cambios.

![incrustacionhistorieta-login](https://cloud.githubusercontent.com/assets/25758763/23719976/515948e2-040b-11e7-854d-4d2a17abba92.JPG)

**Comment by ghost** [comment]
Lo que se realizo es que con el href  se referencia la historieta en un Label (historieta) ya que por ahora la historieta solo es una unión de imágenes que no tiene eventos por eso no se plantea como un AccionEvent cuando se acciona el evento en el botón (Iniciar Sección).

**Comment by ghost** [comment]
La Historieta que se tiene actual es:

https://cloud.githubusercontent.com/assets/22629833/23109525/eb057f32-f6e7-11e6-9466-15fdd6442dee.jpg

**Comment by ghost** [comment]
Los pasos del algoritmo no se siguen ya que según el feedback no se debe proseguir por que la tarea es incrustar la historieta al login y no hacer el logueo de la aplicación.

**Comment by ghost** [comment]
El desarrollo de la historieta fue echo por: https://github.com/ISWPOLI/Pacto-de-Honor/issues/36

**Comment by ghost** [comment]
El html que se modifico para la realización de la incrustación se sube a continuación, solo se sube HTML ya que el formulario creado estaba realizado en php de este modo.

[LoginRegistroHistorieta.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/828773/LoginRegistroHistorieta.zip)

**Comment by ghost** [comment]
Se Integra el login con la historieta, se cargan toda la documentación y código asociado, por este motivo  se le da cierre al Issues.
