### ISSUE TITLE
1.2.5.2 Algoritmo de navegación del juego Selección Avatar. 

### ISSUE THREAD

**Issue by ghost** [ISWPOLI/Pacto-de-Honor#136]
- [x] Descripción algoritmo selección Avatar.

- [x] Implementación algoritmo selección Avatar.

**Comment by ghost** [comment]
Descripción algoritmo selección de personajes. 

- Creación de formulario selección avatar (PHP).
- Capturar datos o eventos del personaje seleccionado.
- Implementar mockups y assets de personajes jugables.
- Cargar datos sobre los personajes de la base de datos.
- Generar algún aviso sobre la selección.
- Pasar a la sección de navegación de los mundos.

**Comment by jrsosago** [comment]
Le pregunte @JuanSebastianRodriguezJ, ¿Con qué objetivo se abrió esta Issue?, y me dijo que se creo para realizar la codificación del login, mapa de navegación y selección de personaje. Tareas que después fueron reasignadas. Por tal motivo se cierra esta Issue
