### ISSUE TITLE
1.2.5.3 Algoritmo de navegación del juego Mapa Navegación.

### ISSUE THREAD

**Issue by ghost** [ISWPOLI/Pacto-de-Honor#137]
- [x] Descripción algoritmo navegación Mapa.

- [x] Implementación algoritmo navegación Mapa.

**Comment by juankrlos08** [comment]
Descripción algoritmos navegación del juego mapa.

1. Creación de formulario selección Inicio,(PHP).
2. Capturar datos o eventos del mapa del juego.
3. Implementar mockups y assets de iconos del mapa.
4. Cargar datos sobre cada uno de los iconos del mapa en una base de datos.
5. Generar algún aviso sobre la selección.
6. Pasar a la sección de navegación de los mundos, configuración, inicio, personajes.

**Comment by juankrlos08** [comment]
[prueba.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/812358/prueba.zip)

adjunta prueba de navegacion menu con el mapa
hora empleadas : 4horas

**Comment by jrsosago** [comment]
Le pregunte @JuanSebastianRodriguezJ, ¿Con qué objetivo se abrió esta Issue?, y me dijo que se creo para realizar la codificación del login, mapa de navegación y selección de personaje. Tareas que después fueron reasignadas. Por tal motivo se cierra esta Issue
