### ISSUE TITLE
5.1.2 Creación de Historias

### ISSUE THREAD

**Issue by DiegOliveros** [ISWPOLI/Pacto-de-Honor#14]
** Historia relacionada **
Como grupo del proyecto es necesario definir historias para cada uno de los módulos del juego.

** Descripción de la tarea **
- [x] Combate
- [x] Soliciones personajes
- [x] Psicitécnica
- [x] tipos de plagio.

**Comment by wpradere** [comment]
Se crean las historias de usuario Adjunto 
[Historias de usuario.xlsx](https://github.com/ISWPOLI/Pacto-de-Honor/files/784693/Historias.de.usuario.xlsx)

**Comment by CamilaG08** [comment]
https://docs.google.com/document/d/1AC5tztp0d4KDGZ37oyFyKgTktMqPDulrWFsLUTPCgFI/edit?usp=sharing

**Comment by CamilaG08** [comment]
Solución de personajes:

[2.Entrega.Subgrupo.-.Practica.Aplicada.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/792030/2.Entrega.Subgrupo.-.Practica.Aplicada.pdf)
