### ISSUE TITLE
Generacion de reportes

### ISSUE THREAD

**Issue by Lakes1234** [ISWPOLI/Pacto-de-Honor#143]
Se requiere establecer una lista de reportes que permita a la administración del juego determinar planes de acción o simplemente monitoriar la actividad diaria.

**Comment by Lakes1234** [comment]
Se adjuntan reportes propuestos inicialmente.
[RequerimientosInformes.xlsx](https://github.com/ISWPOLI/Pacto-de-Honor/files/809710/RequerimientosInformes.xlsx)

**Comment by jolarter** [comment]
Se cierra este issue. Steven debe trabajar en otras asignaciones.
