### ISSUE TITLE
5.1.4 Pasar las historias de usuario a requerimientos (Formato IEEE 830)

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#144]
**Descripción**

Consolidar las historias de usuario en el formato de requerimientos IEEE 830

**TAREAS**

- [x] Recopilar historias de usuario
- [x] Entender el formato IEEE 830
- [x] Pasar los requerimientos al formato IEEE 830

**Comment by CamilaG08** [comment]
Se realiza el cambio de asignaciones, se espera un documento base con el cual trabajar.

**Comment by jdbernalv** [comment]
Se realiza la entrega del documento IEEE830 con los requerido por el Issue 144, para la supervisión, rectificación y aprobación de @CamilaG08.

Observaciones: Se debe validar algunos temas faltantes del documento con el grupo de Back End.
[Formato IEEE830 - Jaime Bernal.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/819103/Formato.IEEE830.-.Jaime.Bernal.pdf)

**Comment by CamilaG08** [comment]
Se cierra debido a que se finaliza el documento.

[Formato de requerimientos IEEE830.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/852154/Formato.de.requerimientos.IEEE830.docx)

[Requerimientos.backend.V1.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/852155/Requerimientos.backend.V1.pdf)
