### ISSUE TITLE
5.2.1 Crear un repositorio de los mockups finales

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#145]
**Descripción**

Crear un repositorio fijo de todos los mockups previamente presentados y aprobados.

**TAREAS**

- [x] Recopilar mockups de escenarios
- [x] Recopilar mockups/sprites de personajes
- [x] Recopilar mockups de escudos y poderes
- [x] Recopilar mockup de campo de batalla
- [x] Recopilar mockups de login
- [x] Recopilar mockup de mapa de navegación
- [x] Recopilar mockup de selección de personaje
- [x] Recopilar mockup de perfil del jugador
- [x] Recopilar historieta
- [x] Recopilar mockups de navegación web
- [x] Recopilar mockups de navegación móvil

**Comment by rzambrano112** [comment]
Envió la tarea correspondiente a la creación de los Mockups Finales.

**Comment by rzambrano112** [comment]
Sin embargo hay algunos temas que aún se están desarrollando.

**Comment by rzambrano112** [comment]
Anexo el documento.
[Repositorio.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/818467/Repositorio.pdf)

**Comment by rzambrano112** [comment]
Horas de trabajo en la creaciòn del repositorio.
4 horas 30 minutos.

**Comment by CamilaG08** [comment]
Se realiza el cambio de roles, en este caso se asigna a @jrsosago y a mí para consolidar este documento.

**Comment by jrsosago** [comment]
**Descripción**
Se realiza cambio de rol, en este caso se asigna @jrsosago.
**Tareas a realizar**
- [x] Recopilar mockups de escenarios
- [x] Recopilar mockups/sprites de personajes
- [x] Recopilar mockups de escudos y poderes
- [x] Recopilar mockup de campo de batalla
- [x] Recopilar mockups de login
- [x] Recopilar mockup de mapa de navegación
- [x] Recopilar mockup de selección de personaje
- [x] Recopilar mockup recompensas
- [x] Recopilar historieta
- [x] Recopilar mockups de navegación web
- [x] Recopilar mockups de navegación móvil
-  [x] Recopilar ranking
 - [x] Recopilar perfil usuario
 - [x] Diálogos Pre-batalla

**Comment by jrsosago** [comment]
No se puede adjuntar el repositorio de los Mockups con documento principal y anexos, debido a que supera el tamaño aceptado por GitHub. Se envia copia por google drive a el profesor Diego Oliveros, profesor Julian Olarte, @CamilaG08  y @jdma0440

**Tiempo empleado: 2 horas y 20 minutos**

**Comment by jrsosago** [comment]
No se puede adjuntar continuación del repositorio con documento principal y anexos, debido a que supera el tamaño aceptado por GitHub. Se envia copia por google drive a el profesor Diego Oliveros, profesor Julian Olarte, @CamilaG08 y @jdma0440 

Tiempo empleado: 2 horas y 30 minutos
