### ISSUE TITLE
Cargar base de datos

### ISSUE THREAD

**Issue by manuk160** [ISWPOLI/Pacto-de-Honor#146]
Cargar base de datos

Con el objetivo de realizar el proceso de prueba de los diferentes servicios se poblara la base de datos creada en mysql partiendo de una archivo de excel base de cada una de las tablas para posteriormente crear el sql a ejecutar.

- [x] Cargar 5 registros por cada tabla.

- [ ] validar la integridad de la data.

[bd_practica.xlsx](https://github.com/ISWPOLI/Pacto-de-Honor/files/814472/bd_practica.xlsx)

![modelo_entidad_relacion](https://cloud.githubusercontent.com/assets/25807878/23517248/c9012d10-ff3d-11e6-80d0-89b35754a5eb.JPG)

**Comment by juancelemin** [comment]
- [x] Se adjunta el script de poblacion pediente por COMPILAR (2H):

[poblacion.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/814524/poblacion.txt)

**Comment by DanteVDrako** [comment]
Se genera Script para llenado de Bases de Datos.

[bd_practica.xlsx](https://github.com/ISWPOLI/Pacto-de-Honor/files/817266/bd_practica.xlsx)

[ScriptBD.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/817267/ScriptBD.txt)

**Comment by manuk160** [comment]
Este fue la base de datos presentada en clase y el modelo. Se realiza cargue para la muestra para mostrar avances y de acuerdo a la reunión posterior a la presentación esta seria la actividad final a reportar para cerrar este ciclo.

![image](https://cloud.githubusercontent.com/assets/25807878/23610944/c5f9d11e-0242-11e7-8cdd-472e95f64fcc.png)

Script de creacion de bases de datos:

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for categoria
-- ----------------------------
DROP TABLE IF EXISTS `categoria`;
CREATE TABLE `categoria` (
  `idCategoria` int(11) NOT NULL AUTO_INCREMENT,
  `Nombre` varchar(20) NOT NULL,
  `Tipo` int(11) NOT NULL,
  PRIMARY KEY (`idCategoria`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of categoria
-- ----------------------------
INSERT INTO `categoria` VALUES ('1', 'Heroe', '1');
INSERT INTO `categoria` VALUES ('2', 'Heroe', '2');
INSERT INTO `categoria` VALUES ('3', 'Jefe', '1');
INSERT INTO `categoria` VALUES ('4', 'Jefe', '2');
INSERT INTO `categoria` VALUES ('5', 'Enemigo', '1');
INSERT INTO `categoria` VALUES ('6', 'Enemigo', '2');

-- ----------------------------
-- Table structure for jugador
-- ----------------------------
DROP TABLE IF EXISTS `jugador`;
CREATE TABLE `jugador` (
  `idJugador` int(11) NOT NULL AUTO_INCREMENT,
  `nickname` varchar(45) NOT NULL,
  `monedas` int(11) NOT NULL,
  `puntosexpe` int(11) NOT NULL,
  `nivel_jugador` int(11) NOT NULL,
  `puntos_vida` int(11) NOT NULL,
  `Nivel_idnivel` int(11) NOT NULL,
  PRIMARY KEY (`idJugador`,`Nivel_idnivel`),
  KEY `fk_Jugador_Nivel1_idx` (`Nivel_idnivel`),
  CONSTRAINT `fk_Jugador_Nivel1` FOREIGN KEY (`Nivel_idnivel`) REFERENCES `nivel` (`idnivel`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of jugador
-- ----------------------------
INSERT INTO `jugador` VALUES ('1', 'Zergio', '10', '0', '1', '20', '1');
INSERT INTO `jugador` VALUES ('2', 'manuk', '10', '0', '1', '20', '1');

-- ----------------------------
-- Table structure for jugador_has_personaje
-- ----------------------------
DROP TABLE IF EXISTS `jugador_has_personaje`;
CREATE TABLE `jugador_has_personaje` (
  `Jugador_idJugador` int(11) NOT NULL,
  `Personaje_idPersonaje` int(11) NOT NULL,
  PRIMARY KEY (`Jugador_idJugador`,`Personaje_idPersonaje`),
  KEY `fk_Jugador_has_Personaje_Personaje1_idx` (`Personaje_idPersonaje`),
  KEY `fk_Jugador_has_Personaje_Jugador_idx` (`Jugador_idJugador`),
  CONSTRAINT `fk_Jugador_has_Personaje_Jugador` FOREIGN KEY (`Jugador_idJugador`) REFERENCES `jugador` (`idJugador`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jugador_has_Personaje_Personaje1` FOREIGN KEY (`Personaje_idPersonaje`) REFERENCES `personaje` (`idPersonaje`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of jugador_has_personaje
-- ----------------------------

-- ----------------------------
-- Table structure for log
-- ----------------------------
DROP TABLE IF EXISTS `log`;
CREATE TABLE `log` (
  `idLog` int(11) NOT NULL AUTO_INCREMENT,
  `idjugador` int(11) NOT NULL,
  `Tiempo` time(4) NOT NULL,
  `fechainicio` datetime(6) NOT NULL,
  `fechafinal` datetime(6) NOT NULL,
  `jugador_idJugador` int(11) NOT NULL,
  PRIMARY KEY (`idLog`,`jugador_idJugador`),
  KEY `fk_log_jugador1_idx` (`jugador_idJugador`),
  CONSTRAINT `fk_log_jugador1` FOREIGN KEY (`jugador_idJugador`) REFERENCES `jugador` (`idJugador`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of log
-- ----------------------------

-- ----------------------------
-- Table structure for mundo
-- ----------------------------
DROP TABLE IF EXISTS `mundo`;
CREATE TABLE `mundo` (
  `idMundo` int(11) NOT NULL AUTO_INCREMENT,
  `Nombre_mundo` varchar(20) NOT NULL,
  PRIMARY KEY (`idMundo`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of mundo
-- ----------------------------
INSERT INTO `mundo` VALUES ('1', 'Cafeteria');
INSERT INTO `mundo` VALUES ('2', 'Biblioteca');

-- ----------------------------
-- Table structure for mundo_has_personaje
-- ----------------------------
DROP TABLE IF EXISTS `mundo_has_personaje`;
CREATE TABLE `mundo_has_personaje` (
  `mundo_idMundo` int(11) NOT NULL,
  `personaje_idPersonaje` int(11) NOT NULL,
  PRIMARY KEY (`mundo_idMundo`,`personaje_idPersonaje`),
  KEY `fk_mundo_has_jugador_mundo1_idx` (`mundo_idMundo`),
  KEY `fk_mundo_has_personaje_personaje1_idx` (`personaje_idPersonaje`),
  CONSTRAINT `fk_mundo_has_jugador_mundo1` FOREIGN KEY (`mundo_idMundo`) REFERENCES `mundo` (`idMundo`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_mundo_has_personaje_personaje1` FOREIGN KEY (`personaje_idPersonaje`) REFERENCES `personaje` (`idPersonaje`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of mundo_has_personaje
-- ----------------------------
INSERT INTO `mundo_has_personaje` VALUES ('1', '3');

-- ----------------------------
-- Table structure for nivel
-- ----------------------------
DROP TABLE IF EXISTS `nivel`;
CREATE TABLE `nivel` (
  `idnivel` int(11) NOT NULL AUTO_INCREMENT,
  `nombre_nivel` varchar(20) NOT NULL,
  `id_personaje_enemigo` int(11) NOT NULL,
  `mundo_idMundo` int(11) NOT NULL,
  PRIMARY KEY (`idnivel`,`mundo_idMundo`),
  KEY `fk_nivel_mundo1_idx` (`mundo_idMundo`),
  CONSTRAINT `fk_nivel_mundo1` FOREIGN KEY (`mundo_idMundo`) REFERENCES `mundo` (`idMundo`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of nivel
-- ----------------------------
INSERT INTO `nivel` VALUES ('1', 'Cafeteria1', '2', '1');
INSERT INTO `nivel` VALUES ('2', 'Cafeteria2', '4', '1');
INSERT INTO `nivel` VALUES ('3', 'Cafeteria3', '4', '1');
INSERT INTO `nivel` VALUES ('4', 'Cafeteria4', '2', '1');
INSERT INTO `nivel` VALUES ('5', 'Cafeteria Final', '3', '1');

-- ----------------------------
-- Table structure for personaje
-- ----------------------------
DROP TABLE IF EXISTS `personaje`;
CREATE TABLE `personaje` (
  `idPersonaje` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(20) NOT NULL,
  `Descripcion_p` varchar(255) NOT NULL,
  `costo` int(11) NOT NULL,
  `Puntos_ataques_fisicos` int(11) NOT NULL,
  `Categoria_idCategoria` int(11) NOT NULL,
  PRIMARY KEY (`idPersonaje`,`Categoria_idCategoria`),
  KEY `fk_Personaje_Categoria1_idx` (`Categoria_idCategoria`),
  CONSTRAINT `fk_Personaje_Categoria1` FOREIGN KEY (`Categoria_idCategoria`) REFERENCES `categoria` (`idCategoria`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=big5 COMMENT='	';

-- ----------------------------
-- Records of personaje
-- ----------------------------
INSERT INTO `personaje` VALUES ('1', 'Leon', 'valiente', '20', '5', '1');
INSERT INTO `personaje` VALUES ('2', 'Aveja', 'Rapido y Volador', '25', '4', '6');
INSERT INTO `personaje` VALUES ('3', 'Andres Zorro', 'Listo', '35', '4', '3');
INSERT INTO `personaje` VALUES ('4', 'Mini Zorro', 'Listo', '15', '3', '5');

-- ----------------------------
-- Table structure for personaje_has_poder
-- ----------------------------
DROP TABLE IF EXISTS `personaje_has_poder`;
CREATE TABLE `personaje_has_poder` (
  `Personaje_idPersonaje` int(11) NOT NULL,
  `poder_idpoder` int(11) NOT NULL,
  PRIMARY KEY (`Personaje_idPersonaje`,`poder_idpoder`),
  KEY `fk_Personaje_has_poder_poder1_idx` (`poder_idpoder`),
  KEY `fk_Personaje_has_poder_Personaje1_idx` (`Personaje_idPersonaje`),
  CONSTRAINT `fk_Personaje_has_poder_Personaje1` FOREIGN KEY (`Personaje_idPersonaje`) REFERENCES `personaje` (`idPersonaje`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personaje_has_poder_poder1` FOREIGN KEY (`poder_idpoder`) REFERENCES `poder` (`idpoder`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=big5;

-- ----------------------------
-- Records of personaje_has_poder
-- ----------------------------
INSERT INTO `personaje_has_poder` VALUES ('1', '1');
INSERT INTO `personaje_has_poder` VALUES ('2', '1');
INSERT INTO `personaje_has_poder` VALUES ('3', '1');
INSERT INTO `personaje_has_poder` VALUES ('4', '1');
INSERT INTO `personaje_has_poder` VALUES ('2', '2');
INSERT INTO `personaje_has_poder` VALUES ('3', '2');
INSERT INTO `personaje_has_poder` VALUES ('4', '2');
INSERT INTO `personaje_has_poder` VALUES ('1', '3');

-- ----------------------------
-- Table structure for poder
-- ----------------------------
DROP TABLE IF EXISTS `poder`;
CREATE TABLE `poder` (
  `idpoder` int(11) NOT NULL AUTO_INCREMENT,
  `nombre_poder` varchar(20) NOT NULL,
  `descripcion_poder` varchar(255) NOT NULL,
  `tipo_poder` varchar(7) NOT NULL,
  `forma_poder` varchar(7) NOT NULL,
  `potencia` int(11) NOT NULL,
  PRIMARY KEY (`idpoder`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of poder
-- ----------------------------
INSERT INTO `poder` VALUES ('1', 'Lanzar', 'Lanza rocas', '1', '1', '7');
INSERT INTO `poder` VALUES ('2', 'Tirar', 'Tira copias de examenes del cielo', '1', '2', '6');
INSERT INTO `poder` VALUES ('3', 'Escudo Superior', 'Se proteje de ataques aereos', '2', '2', '12');
INSERT INTO `poder` VALUES ('4', 'Escudo Frontal', 'Se proteje de ataques frontales', '2', '1', '12');
