### ISSUE TITLE
1.4.4 Realizar personaje y Modulo de batalla

### ISSUE THREAD

**Issue by wpradere** [ISWPOLI/Pacto-de-Honor#15]
**Descripción**  

**Tareas asociadas** 
- [x] Maquetación personaje 
- [ ] Codificación

**Comment by jrsosago** [comment]
**Poderes personajes y combates.**

**1. TatiHormiga:** Su cualidad es ser muy organizada y distribuir su trabajo. Su poder es arrojar partes de trabajo.
![finalhormiga](https://cloud.githubusercontent.com/assets/22827594/23002147/29b1d552-f3b7-11e6-8576-eda8452949d0.gif)
**2. VíctorHiena:** Su defecto es hablar mal de los demás. Por eso su poder es arrojar globos de historietas.
![finalhiena](https://cloud.githubusercontent.com/assets/22827594/23002177/5a373550-f3b7-11e6-8c5d-cedff79ada59.gif)
**Batalla**
![finalbatalla](https://cloud.githubusercontent.com/assets/22827594/23002227/99c4748a-f3b7-11e6-8a6e-d4263a5cf9b2.gif)

**Comment by DiegOliveros** [comment]
Esta tarea no está codificada

**Comment by wpradere** [comment]
Se realizó el proceso de maquetación de 2 personajes  los cuales se  plantea un poder 

Se realiza la codificación en Javascrip Framework Phaser  

[Archivo comprimido.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/778823/Archivo.comprimido.zip)

**Comment by gabogabbs** [comment]
Tareas realizadas: Prototipos de dos personajes voladores (Ruiseñor y Buitre).
Estos prototipos se realizaron por medio de Javascript y HTML5 con el editor de texto Sublime Text 3; y las imágenes modificadas con Photoshop.
[PrototipoGabriel.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/778870/PrototipoGabriel.zip)

REGISTRO DE TIEMPO: 5 HORAS, 30 MINUTOS

**Comment by dayepesb** [comment]
tareas realizadas: prototipo de los personajes felipe el oso, juan el gallo.
se realizaron con javascript y html5, con el editor de texto aptana, y las 3 imagenes editadas co photoshop

[Prototipo-1-David-Yepes.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/778904/Prototipo-1-David-Yepes.zip)
