### ISSUE TITLE
1.1.11 Caricaturizar los escenarios

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#150]
**Descripción**

Caricaturizar los escenarios previamente animados.

**TAREAS**

- [ ] Caricaturizar escenario de Poli Medellín
- [ ] Caricaturizar escenario de Sede Postgrados
- [x] Caricaturizar escenarios de las 4 facultades
- [ ] Caricaturizar escenarios restantes

**Comment by CristianGarzonBernal** [comment]
![roja](https://cloud.githubusercontent.com/assets/22016808/23686611/a832645c-0378-11e7-99b8-10878d95cd7e.gif)
![Uploading amarillo.gif…]()
![Uploading verde.gif…]()
![Uploading azukjpg.gif…]()

**Comment by CristianGarzonBernal** [comment]
tiempo registrado 2 horas y media

**Comment by CristianGarzonBernal** [comment]
![verde](https://cloud.githubusercontent.com/assets/22016808/23885638/893ab1de-0842-11e7-8f1d-61279cc8ccd4.gif)
![azul](https://cloud.githubusercontent.com/assets/22016808/23885641/8edea2a8-0842-11e7-936e-f1c7c3d0d7c4.gif)
![amarillo](https://cloud.githubusercontent.com/assets/22016808/23885648/97b2166c-0842-11e7-947c-5be425a027b9.gif)

**Comment by CamilaG08** [comment]
Se cierra a pesar de no terminar las tareas, ya que se re-asigna esta animación de escenarios en otro Issue perteneciente al Sprint 7.
