### ISSUE TITLE
2.1.2 Efectos/Impactos de los ataques

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#151]
**Descripción**

Describir y plantear los efectos o impactos que tienen los ataques en los escenarios y en los contrincantes.

**TAREAS**

- [x] Descripción de los efectos de los ataques de personalidad de los personajes buenos
- [x] Descripción de los efectos de los ataques de personalidad de los personajes malos
- [x] Descripción de los efectos de los ataques de plagio de los personajes malos
- [x] Imágenes de los efectos de los ataques de personalidad de los personajes buenos
- [x] Imágenes de los efectos de los ataques de personalidad de los personajes malos
- [x] Imágenes de los efectos de los ataques de plagio de los personajes malos
- [x] Cargar el documento con las descripciones e imágenes
- [x] Dar las imágenes a Gabriel Álvarez ( @gsalvarez  )

**Documento de apoyo**

[2.Entrega.Subgrupo.-.Practica.Aplicada-1.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/818950/2.Entrega.Subgrupo.-.Practica.Aplicada-1.docx)

**Comment by CristianGarzonBernal** [comment]
[Descripcion y Sprites.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/826279/Descripcion.y.Sprites.docx)
Tiempo registrado 6 horas.

**Comment by jolarter** [comment]
Este documento debería ir en el repositorio general.
