### ISSUE TITLE
1.1.12 Ventana Administrador

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#152]
**Descripción**

Crear el entorno para el administrador donde pueda ver los reportes, estadísticas y resultados de las pruebas psicotécnicas (cuando se integren).

**TAREAS**

- [x] Mockups de la interfaz del administrador (Ventana de reportes, ventana de estadísticas y ventana de resultados de pruebas)
- [ ] Definir los reportes a recibir
- [ ] Definir las estadísticas a crear
- [x] Definir la vista delos resultados de las pruebas
- [ ] Integrar los estilos del mapa de diseño ( a cargo de @KmiArthur ) a la interfaz del administrador #167 
- [ ] Implementar módulo

**Comment by ghost** [comment]
En este avance del modulo hay varias propuestas sobre la visualización de:
- Login del usuario en mockup y una version en HTML.
- Grafica de barras y barra en mockup y html. 

Todo esta por separado e independiente a la base de datos.

**Comment by ghost** [comment]
Avances de los Mockups.

[Mockups.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/835841/Mockups.zip)

**Comment by ghost** [comment]
Avance de la vista del modulo Administrador en HTML.

[Modulo Admin.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/835842/Modulo.Admin.zip)

**Comment by ghost** [comment]
Debido a una charla con los profesores esta tarea será rechazada debido a que la misma tarea se esta realizando en el grupo de back-end.

**Comment by CamilaG08** [comment]
Se cierra debido a que se encuentra replicada en una asignación en el grupo de backend.
