### ISSUE TITLE
Normalizar-BD

### ISSUE THREAD

**Issue by wpradere** [ISWPOLI/Pacto-de-Honor#153]
# Normalizar la base de datos 

-  [x] Todos los atributos son atómicos
-  [x] La tabla contiene una clave primaria única
-  [x] La clave primaria no contiene atributos nulos
-  [x] No debe existir variación en el número de columnas
-  [x] Los Campos no clave deben identificarse por la clave (Dependencia Funcional)

@juancelemin

**Comment by juancelemin** [comment]
se adjuntan la base y el modelo de la BD pendiente por aprobar

[poli_fighter.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/819797/poli_fighter.txt)
![diagrama](https://cloud.githubusercontent.com/assets/17105514/23591921/ae05dd2c-01c6-11e7-848a-627a640ac01a.png)
@manuk160

**Comment by manuk160** [comment]
Bueno después de validar el script tengo esta serie de cambios y preguntas:

Tabla Jugador:

* Como se hace la trazabilidad con el registro a nivel de la aplicación y cuales campos se deben integrar?
* Donde se guarda la contraseña.
* correo electrónico.
* Los datos básicos de cada estudiante si queremos saber cómo entro al pacto de honor y demás.
* nivel_id_nivel: cambiar el nombre del campo "id_nivel".
* numero_monedas_jugador: cambiar el nombre "monedas_jugador"
* Falta el campo de imagen del jugador.
* Que define la vida de un jugador en esta tabla "es un campo a almacenar o como se maneja"

Tabla nivel:

* mundo_id_mundo: cambiar el nombre del campo "id_mundo".

Tabla Mundo:

*Falta el campo de la imagen del mundo, se tiene que tener en cuenta que mediante el desarrollo con phaser un mundo o tablero puede estar armado por más de una imagen

Tabla Personaje: 

* Cuantos personajes puede tener un jugador?
* Si tiene más de un personaje como se calcula el nivel?
* Como veo el avance por personaje o es el mismo al desbloquear alguno nuevo.
* dano_fisico_personaje: cambiar nombre por "nivel_dano"

Tabla nivel_tiene_personaje:

* El personaje tiene un nivel o es el jugador con un personaje que tiene un nivel.
* Si el personaje está asociado a un mundo debería replantearse ese orden.

Tabla jugador_tiene_personaje

* jugador_id_jugador: cambiar el nombre "id_jugador"
* personaje_id_personaje: cambiar el nombre "id_personaje"

Tabla personaje_tiene_poder

* personaje_id_personaje: cambiar el nombre "id_personaje"
* poder_id_poder: cambiar el nombre "id_poder"
* los poderes tienen imágenes? - faltaría el campo

Tabla personaje_tiene_frase

* personaje_id_personaje: cambiar el nombre "id_personaje"
* frase_id_frase: cambiar el nombre "id_frase"

**Comment by juancelemin** [comment]
[poli_fighter.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/826632/poli_fighter.txt)

**Comment by juancelemin** [comment]
[poli_fighter.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/827675/poli_fighter.txt)
![diagrama](https://cloud.githubusercontent.com/assets/17105514/23705445/dc206098-03d7-11e7-937b-4a5fd0ed9ebf.png)



se corrigen a esepcion de algunos aspectos de tabla jugador por q no entiendo como se maneja el tema del logeo

- Como se hace la trazabilidad con el registro a nivel de la aplicación y cuales campos se deben integrar?
- Donde se guarda la contraseña.
- Los datos básicos de cada estudiante si queremos saber cómo entro al pacto de honor y demás.

**Comment by manuk160** [comment]
Hola @juancelemin en cuanto al nuevo modelo estas son las sugerencias:

1. Creo que la tabla imagen aplica para el tema de los mundos, poderes y los personajes "tenemos que validar hoy si es posible con el otro equipo como piensan desarrollar ese tema".

2. Quitaría la tabla imagen de jugador y lo dejaría como un campo tipo varchar puesto que si no se tiene la imagen no se puede cargar el jugador.

3. Nos toca validar las llaves en cuanto a las acciones pero eso lo podemos validar adelante.

4. En cuanto al tema de acceso de usuarios existen dos opciones:

- Opción 1: Colocar una tabla usuario, para poder gestionar los usuarios registrados a la aplicacion con la opción de tener roles que nos permita diferencias un administrador de un jugador y posibles roles adicionales que encontremos en desarrollo de la aplicacion "en esta opción podemos llegar un poco mas a fondo agregando mas campos  y validar el registro de los estudiantes a nivel de facultad entre otros". Si se crea esta tabla también incluiríamos el correo y lo retiraríamos de jugador.
 
![image](https://cloud.githubusercontent.com/assets/25807878/23707334/f9b63ec2-03df-11e7-8a41-1da964c08a98.png)

![image](https://cloud.githubusercontent.com/assets/25807878/23707399/2f178ad0-03e0-11e7-9c7c-c9c92024c217.png)

- Opción 2: Colocar los campos directamente en la tabla de jugador.

5. Aun no tenemos respuesta de esto por lo cual deberíamos validarlo hoy con el otro grupo

Tabla Personaje:
Cuantos personajes puede tener un jugador?
Si tiene más de un personaje como se calcula el nivel?
Como veo el avance por personaje o es el mismo al desbloquear alguno nuevo.

**Comment by manuk160** [comment]
@juankrlos08 me envió un script de tabla de usuarios que requieren para la parte de los módulos de acceso a la aplicacion. Se valido y se realizaron cambios para que coincida con lo que se esta manejando, esto afectaría la tabla jugador de acuerdo a la anterior retroalimentacion.

Por otra parte se debe incluir una tabla país y una tabla ciudad. @juancelemin 

CREATE TABLE `usuarios` (
  `id_usuario` int(10) NOT NULL,
  `Nombre` varchar(100)  NOT NULL,
  `Apellido` varchar(100)  NOT NULL,
  `email` varchar(150)  NOT NULL,
  `pais` varchar(50)  NOT NULL,
  `ciudad` varchar(50)  NOT NULL,
  `usuario` varchar(50)  NOT NULL,
  `password` varchar(20) NOT NULL,
  `id_role` int(10) NOT NULL,
  `fecha_registro` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

**Comment by juancelemin** [comment]
[poli_fighter.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/829801/poli_fighter.txt)
![diagrama](https://cloud.githubusercontent.com/assets/17105514/23736244/109bdede-0459-11e7-85df-85a32aa06796.png)

**Comment by juancelemin** [comment]
CORRECION DE LA BD PENDIENTE POR APROBAR @manuk160 
[poli_fighter.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/829804/poli_fighter.txt)
![diagrama](https://cloud.githubusercontent.com/assets/17105514/23736296/728b9fd0-0459-11e7-9d5c-b8f3a7454a51.png)

**Comment by jnrubiano** [comment]
Hola @juancelemin:

¿Con lo que hiciste hace unos dias pordemos cerrar este issue?

Por favor todos los modelos ER que generes, agregarlos en el issue correspondiente para no tener todos los modelos regados. ISSUE -> Diseño ER #57

**Comment by wpradere** [comment]
Buenas tardes @juancelemin verifiquemos por favor si este scrip es el de la base final para dejarla visionada y cerrar este issue.

**Comment by zergiozerna81** [comment]
Estoy pendiente de la confirmación de que está es la BD con la cual puedo iniciar a trabajar en el issue #156.

**Comment by juancelemin** [comment]
[poli_fighter.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/835481/poli_fighter.txt)
![diagrama](https://cloud.githubusercontent.com/assets/17105514/23820232/716734ea-05e2-11e7-8a94-9484332ad69f.png)
se corrigen los errores que no dejaban importar la bd y el campo repetido de la tabla usurario  para que pueda ser poblada @zergiozerna81

**Comment by manuk160** [comment]
script con carga base:

/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50710
Source Host           : localhost:3306
Source Database       : p_h01

Target Server Type    : MYSQL
Target Server Version : 50710
File Encoding         : 65001

Date: 2017-03-12 16:56:26
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for categoria
-- ----------------------------
DROP TABLE IF EXISTS `categoria`;
CREATE TABLE `categoria` (
  `id_categoria` int(11) NOT NULL AUTO_INCREMENT,
  `rol` int(11) NOT NULL,
  `tipo` int(11) NOT NULL,
  PRIMARY KEY (`id_categoria`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of categoria
-- ----------------------------
INSERT INTO `categoria` VALUES ('1', '1', '1');
INSERT INTO `categoria` VALUES ('2', '2', '2');

-- ----------------------------
-- Table structure for ciudad
-- ----------------------------
DROP TABLE IF EXISTS `ciudad`;
CREATE TABLE `ciudad` (
  `id_ciudad` int(11) NOT NULL AUTO_INCREMENT,
  `nombre_ciudad` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id_ciudad`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of ciudad
-- ----------------------------
INSERT INTO `ciudad` VALUES ('1', 'Bogota');
INSERT INTO `ciudad` VALUES ('2', 'Medellin');
INSERT INTO `ciudad` VALUES ('3', 'Cali');

-- ----------------------------
-- Table structure for frase
-- ----------------------------
DROP TABLE IF EXISTS `frase`;
CREATE TABLE `frase` (
  `id_frase` int(11) NOT NULL AUTO_INCREMENT,
  `descripcion` varchar(255) NOT NULL,
  PRIMARY KEY (`id_frase`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of frase
-- ----------------------------
INSERT INTO `frase` VALUES ('1', 'Frase asociada a personaje 01');
INSERT INTO `frase` VALUES ('2', 'Frase asociada a personaje 02');

-- ----------------------------
-- Table structure for imagen
-- ----------------------------
DROP TABLE IF EXISTS `imagen`;
CREATE TABLE `imagen` (
  `id_imagen` int(11) NOT NULL AUTO_INCREMENT,
  `foto` varchar(255) NOT NULL,
  PRIMARY KEY (`id_imagen`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of imagen
-- ----------------------------
INSERT INTO `imagen` VALUES ('1', '/personaje1/foto1');
INSERT INTO `imagen` VALUES ('2', '/personaje2/foto1');
INSERT INTO `imagen` VALUES ('3', '/personaje2/foto2');
INSERT INTO `imagen` VALUES ('4', '/personaje1/foto2');
INSERT INTO `imagen` VALUES ('5', '/mundos/mundo1');
INSERT INTO `imagen` VALUES ('6', '/mundos/mundo2');
INSERT INTO `imagen` VALUES ('7', '/poderes/poder1');
INSERT INTO `imagen` VALUES ('8', '/poderes/poder2');

-- ----------------------------
-- Table structure for jugador
-- ----------------------------
DROP TABLE IF EXISTS `jugador`;
CREATE TABLE `jugador` (
  `id_jugador` int(11) NOT NULL AUTO_INCREMENT,
  `id_nivel` int(11) NOT NULL,
  `nickname` varchar(50) NOT NULL,
  `moneda_jugador` int(11) NOT NULL,
  `experiencia_jugador` int(11) NOT NULL,
  `nivel_jugador` int(11) NOT NULL,
  PRIMARY KEY (`id_jugador`,`id_nivel`),
  KEY `fk_jugador_nivel1_idx` (`id_nivel`),
  KEY `id_jugador` (`id_jugador`),
  CONSTRAINT `fk_jugador_nivel1` FOREIGN KEY (`id_nivel`) REFERENCES `nivel` (`id_nivel`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_jugador_usuario1` FOREIGN KEY (`id_jugador`) REFERENCES `usuario` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of jugador
-- ----------------------------
INSERT INTO `jugador` VALUES ('1', '1', 'nick01', '100', '10', '1');

-- ----------------------------
-- Table structure for jugador_tiene_personaje
-- ----------------------------
DROP TABLE IF EXISTS `jugador_tiene_personaje`;
CREATE TABLE `jugador_tiene_personaje` (
  `id_jugador` int(11) NOT NULL,
  `id_personaje` int(11) NOT NULL,
  PRIMARY KEY (`id_jugador`,`id_personaje`),
  KEY `fk_Jugador_has_Personaje_Personaje1_idx` (`id_personaje`),
  KEY `fk_Jugador_has_Personaje_Jugador_idx` (`id_jugador`),
  CONSTRAINT `fk_Jugador_has_Personaje_Jugador` FOREIGN KEY (`id_jugador`) REFERENCES `jugador` (`id_jugador`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jugador_has_Personaje_Personaje1` FOREIGN KEY (`id_personaje`) REFERENCES `personaje` (`id_personaje`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of jugador_tiene_personaje
-- ----------------------------

-- ----------------------------
-- Table structure for log
-- ----------------------------
DROP TABLE IF EXISTS `log`;
CREATE TABLE `log` (
  `id_log` int(11) NOT NULL AUTO_INCREMENT,
  `id_jugador` int(11) NOT NULL,
  `tiempo_log` time NOT NULL,
  `fecha_inicio` datetime NOT NULL,
  `fecha_final` datetime NOT NULL,
  PRIMARY KEY (`id_log`,`id_jugador`),
  KEY `fk_log_jugador1_idx` (`id_jugador`),
  CONSTRAINT `fk_log_jugador1` FOREIGN KEY (`id_jugador`) REFERENCES `jugador` (`id_jugador`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of log
-- ----------------------------
INSERT INTO `log` VALUES ('1', '1', '16:14:23', '2017-03-02 16:14:25', '2017-03-04 16:14:31');
INSERT INTO `log` VALUES ('2', '1', '16:14:42', '2017-03-03 16:14:45', '2017-03-04 16:14:51');

-- ----------------------------
-- Table structure for mundo
-- ----------------------------
DROP TABLE IF EXISTS `mundo`;
CREATE TABLE `mundo` (
  `id_mundo` int(11) NOT NULL AUTO_INCREMENT,
  `nombre_mundo` varchar(20) NOT NULL,
  PRIMARY KEY (`id_mundo`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of mundo
-- ----------------------------
INSERT INTO `mundo` VALUES ('1', 'Cafeteria');
INSERT INTO `mundo` VALUES ('2', 'Bloque K');
INSERT INTO `mundo` VALUES ('3', 'Plazoleta Principal');

-- ----------------------------
-- Table structure for mundo_tiene_imagen
-- ----------------------------
DROP TABLE IF EXISTS `mundo_tiene_imagen`;
CREATE TABLE `mundo_tiene_imagen` (
  `id_mundo` int(11) NOT NULL,
  `id_imagen` int(11) NOT NULL,
  PRIMARY KEY (`id_mundo`,`id_imagen`),
  KEY `fk_mundo_tiene_imagen_imagen1_idx` (`id_imagen`),
  CONSTRAINT `fk_mundo_tiene_imagen_imagen1` FOREIGN KEY (`id_imagen`) REFERENCES `imagen` (`id_imagen`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_mundo_tiene_imagen_mundo1` FOREIGN KEY (`id_mundo`) REFERENCES `mundo` (`id_mundo`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of mundo_tiene_imagen
-- ----------------------------
INSERT INTO `mundo_tiene_imagen` VALUES ('1', '5');
INSERT INTO `mundo_tiene_imagen` VALUES ('2', '6');

-- ----------------------------
-- Table structure for nivel
-- ----------------------------
DROP TABLE IF EXISTS `nivel`;
CREATE TABLE `nivel` (
  `id_nivel` int(11) NOT NULL AUTO_INCREMENT,
  `id_mundo` int(11) NOT NULL,
  `nombre_nivel` varchar(20) NOT NULL,
  PRIMARY KEY (`id_nivel`,`id_mundo`),
  KEY `fk_nivel_mundo1_idx` (`id_mundo`),
  CONSTRAINT `Fk_nivel_mundo1` FOREIGN KEY (`id_mundo`) REFERENCES `mundo` (`id_mundo`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of nivel
-- ----------------------------
INSERT INTO `nivel` VALUES ('1', '1', 'Nivel 1');
INSERT INTO `nivel` VALUES ('2', '1', 'nivel 2');
INSERT INTO `nivel` VALUES ('3', '1', 'nivel 3');
INSERT INTO `nivel` VALUES ('4', '1', 'nivel 4');
INSERT INTO `nivel` VALUES ('5', '1', 'Nivel 5 - Final');
INSERT INTO `nivel` VALUES ('6', '2', 'Nivel 1');
INSERT INTO `nivel` VALUES ('7', '2', 'Nivel 2');
INSERT INTO `nivel` VALUES ('8', '2', 'Nivel 3');
INSERT INTO `nivel` VALUES ('9', '2', 'Nivel 4');
INSERT INTO `nivel` VALUES ('10', '2', 'Nivel 5 - Final');

-- ----------------------------
-- Table structure for pais
-- ----------------------------
DROP TABLE IF EXISTS `pais`;
CREATE TABLE `pais` (
  `id_pais` int(11) NOT NULL AUTO_INCREMENT,
  `nombre_pais` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id_pais`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of pais
-- ----------------------------
INSERT INTO `pais` VALUES ('1', 'Colombia');

-- ----------------------------
-- Table structure for personaje
-- ----------------------------
DROP TABLE IF EXISTS `personaje`;
CREATE TABLE `personaje` (
  `id_personaje` int(11) NOT NULL AUTO_INCREMENT,
  `id_categoria` int(11) NOT NULL,
  `id_imagen` int(11) NOT NULL,
  `nombre_personaje` varchar(20) NOT NULL,
  `descripcion_personaje` varchar(255) NOT NULL,
  `costo` int(11) NOT NULL,
  `nivel_dano` int(11) NOT NULL,
  PRIMARY KEY (`id_personaje`,`id_categoria`,`id_imagen`),
  KEY `fk_personaje_rol_tipo1_idx` (`id_categoria`),
  KEY `fk_personaje_imagen1_idx` (`id_imagen`),
  CONSTRAINT `fk_personaje_imagen1` FOREIGN KEY (`id_imagen`) REFERENCES `imagen` (`id_imagen`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_personaje_rol_tipo1` FOREIGN KEY (`id_categoria`) REFERENCES `categoria` (`id_categoria`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of personaje
-- ----------------------------
INSERT INTO `personaje` VALUES ('1', '1', '1', 'juan rata', 'personaje 01 cargue ejemplo', '500', '50');
INSERT INTO `personaje` VALUES ('2', '2', '2', 'pepe grillo', 'personaje 02 cargue ejemplo', '1000', '100');

-- ----------------------------
-- Table structure for personaje_tiene_frase
-- ----------------------------
DROP TABLE IF EXISTS `personaje_tiene_frase`;
CREATE TABLE `personaje_tiene_frase` (
  `id_personaje` int(11) NOT NULL,
  `id_frase` int(11) NOT NULL,
  PRIMARY KEY (`id_personaje`,`id_frase`),
  KEY `fk_personaje_tiene_frase_personaje1_idx` (`id_personaje`),
  KEY `fk_personaje_tiene_frase_frase1_idx` (`id_frase`),
  CONSTRAINT `fk_personaje_tiene_frase_frase1` FOREIGN KEY (`id_frase`) REFERENCES `frase` (`id_frase`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_personaje_tiene_frase_personaje1` FOREIGN KEY (`id_personaje`) REFERENCES `personaje` (`id_personaje`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of personaje_tiene_frase
-- ----------------------------
INSERT INTO `personaje_tiene_frase` VALUES ('1', '1');
INSERT INTO `personaje_tiene_frase` VALUES ('2', '2');

-- ----------------------------
-- Table structure for personaje_tiene_poder
-- ----------------------------
DROP TABLE IF EXISTS `personaje_tiene_poder`;
CREATE TABLE `personaje_tiene_poder` (
  `id_personaje` int(11) NOT NULL,
  `id_poder` int(11) NOT NULL,
  PRIMARY KEY (`id_personaje`,`id_poder`),
  KEY `fk_Personaje_has_poder_poder1_idx` (`id_poder`),
  KEY `fk_Personaje_has_poder_Personaje1_idx` (`id_personaje`),
  CONSTRAINT `fk_Personaje_has_poder_Personaje1` FOREIGN KEY (`id_personaje`) REFERENCES `personaje` (`id_personaje`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personaje_has_poder_poder1` FOREIGN KEY (`id_poder`) REFERENCES `poder` (`id_poder`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of personaje_tiene_poder
-- ----------------------------
INSERT INTO `personaje_tiene_poder` VALUES ('1', '1');
INSERT INTO `personaje_tiene_poder` VALUES ('2', '2');

-- ----------------------------
-- Table structure for poder
-- ----------------------------
DROP TABLE IF EXISTS `poder`;
CREATE TABLE `poder` (
  `id_poder` int(11) NOT NULL AUTO_INCREMENT,
  `id_imagen` int(11) NOT NULL,
  `nombre_poder` varchar(20) NOT NULL,
  `descripcion_poder` varchar(255) NOT NULL,
  `tipo_poder` int(11) NOT NULL,
  `forma_poder` int(11) NOT NULL,
  `potencia_poder` int(11) NOT NULL,
  PRIMARY KEY (`id_poder`,`id_imagen`),
  KEY `fk_poder_imagen1_idx` (`id_imagen`),
  CONSTRAINT `fk_poder_imagen1` FOREIGN KEY (`id_imagen`) REFERENCES `imagen` (`id_imagen`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of poder
-- ----------------------------
INSERT INTO `poder` VALUES ('1', '7', 'golpe frontal', 'Poder efectuado desde el frente', '1', '1', '10');
INSERT INTO `poder` VALUES ('2', '8', 'golpe superior', 'Poder efectuado desde la parte superior', '2', '2', '15');

-- ----------------------------
-- Table structure for pregunta_prueba_psicotecnica
-- ----------------------------
DROP TABLE IF EXISTS `pregunta_prueba_psicotecnica`;
CREATE TABLE `pregunta_prueba_psicotecnica` (
  `id_pregunta_psicotecnica` int(11) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `id_prueba_psicotecnica` int(11) NOT NULL,
  `pregunta` varchar(255) NOT NULL,
  `id_tipo_pregunta_psicotecnica` int(11) NOT NULL,
  PRIMARY KEY (`id_prueba_psicotecnica`,`id_pregunta_psicotecnica`,`id_tipo_pregunta_psicotecnica`),
  KEY `fk_pregunta_psicotecnica_respuesta_psicotecnica1_idx` (`pregunta`),
  KEY `fk_pregunta_psicotecnica_tipo_pregunta_psicotecnica1_idx` (`id_tipo_pregunta_psicotecnica`),
  KEY `id_pregunta_psicotecnica` (`id_pregunta_psicotecnica`),
  CONSTRAINT `fk_prueba_psicotecnica1_idx` FOREIGN KEY (`id_prueba_psicotecnica`) REFERENCES `prueba_psicotecnica` (`id_prueba_psicotecnica`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_pregunta_psicotecnica1_idx` FOREIGN KEY (`id_tipo_pregunta_psicotecnica`) REFERENCES `tipo_pregunta_psicotecnica` (`id_tipo_pregunta_psicotecnica`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of pregunta_prueba_psicotecnica
-- ----------------------------

-- ----------------------------
-- Table structure for prueba_psicotecnica
-- ----------------------------
DROP TABLE IF EXISTS `prueba_psicotecnica`;
CREATE TABLE `prueba_psicotecnica` (
  `id_prueba_psicotecnica` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(100) NOT NULL,
  `fecha_creacion` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  `id_tipo_prueba` int(11) NOT NULL,
  PRIMARY KEY (`id_prueba_psicotecnica`,`id_tipo_prueba`),
  KEY `fk_tipo_prueba1_idx` (`id_tipo_prueba`),
  KEY `id_prueba_psicotecnica` (`id_prueba_psicotecnica`),
  CONSTRAINT `fk_tipo_prueba1_idx` FOREIGN KEY (`id_tipo_prueba`) REFERENCES `tipo_prueba` (`id_tipo_prueba`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of prueba_psicotecnica
-- ----------------------------

-- ----------------------------
-- Table structure for respuesta_preguntas_psicotecnicas
-- ----------------------------
DROP TABLE IF EXISTS `respuesta_preguntas_psicotecnicas`;
CREATE TABLE `respuesta_preguntas_psicotecnicas` (
  `id_pregunta_prueba_psicotecnica` int(11) NOT NULL,
  `id_respuesta_psicotecnica` int(11) NOT NULL AUTO_INCREMENT,
  `descripcion_prueba_psicotecnica` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id_respuesta_psicotecnica`,`id_pregunta_prueba_psicotecnica`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of respuesta_preguntas_psicotecnicas
-- ----------------------------

-- ----------------------------
-- Table structure for rol_usuario
-- ----------------------------
DROP TABLE IF EXISTS `rol_usuario`;
CREATE TABLE `rol_usuario` (
  `id_rol_usuario` int(11) NOT NULL AUTO_INCREMENT,
  `tipo_usuario` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id_rol_usuario`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of rol_usuario
-- ----------------------------
INSERT INTO `rol_usuario` VALUES ('1', 'Estudiante');
INSERT INTO `rol_usuario` VALUES ('2', 'Administrador');
INSERT INTO `rol_usuario` VALUES ('3', 'Reportes');
INSERT INTO `rol_usuario` VALUES ('4', 'Psicologia');

-- ----------------------------
-- Table structure for tipo_pregunta_psicotecnica
-- ----------------------------
DROP TABLE IF EXISTS `tipo_pregunta_psicotecnica`;
CREATE TABLE `tipo_pregunta_psicotecnica` (
  `id_tipo_pregunta_psicotecnica` int(11) NOT NULL AUTO_INCREMENT,
  `clase_pregunta` int(11) DEFAULT NULL,
  PRIMARY KEY (`id_tipo_pregunta_psicotecnica`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of tipo_pregunta_psicotecnica
-- ----------------------------

-- ----------------------------
-- Table structure for tipo_prueba
-- ----------------------------
DROP TABLE IF EXISTS `tipo_prueba`;
CREATE TABLE `tipo_prueba` (
  `id_tipo_prueba` int(11) NOT NULL AUTO_INCREMENT,
  `tipo_prueba` varchar(100) NOT NULL,
  `descripcion_tipo_prueba` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id_tipo_prueba`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of tipo_prueba
-- ----------------------------

-- ----------------------------
-- Table structure for usuario
-- ----------------------------
DROP TABLE IF EXISTS `usuario`;
CREATE TABLE `usuario` (
  `id_usuario` int(11) NOT NULL AUTO_INCREMENT,
  `id_pais` int(11) NOT NULL,
  `id_ciudad` int(11) NOT NULL,
  `id_rol_usuario` int(11) NOT NULL,
  `nombre_usuario` varchar(100) DEFAULT NULL,
  `apellido_usuario` varchar(100) DEFAULT NULL,
  `email_usuario` varchar(150) DEFAULT NULL,
  `contrasena_usuario` varchar(20) DEFAULT NULL,
  `fecha_registro` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`,`id_pais`,`id_ciudad`,`id_rol_usuario`),
  KEY `fk_usuario_jugador1_idx` (`id_usuario`),
  KEY `fk_usuario_pais1_idx` (`id_pais`),
  KEY `fk_usuario_ciudad1_idx` (`id_ciudad`),
  KEY `fk_usuario_rol_usuario1_idx` (`id_rol_usuario`),
  CONSTRAINT `fk_usuario_ciudad1` FOREIGN KEY (`id_ciudad`) REFERENCES `ciudad` (`id_ciudad`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_pais1` FOREIGN KEY (`id_pais`) REFERENCES `pais` (`id_pais`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_rol_usuario1` FOREIGN KEY (`id_rol_usuario`) REFERENCES `rol_usuario` (`id_rol_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of usuario
-- ----------------------------
INSERT INTO `usuario` VALUES ('1', '1', '1', '1', 'Estudiante', 'Demo', 'usuario@poligran.edu.co', 'demo123', '2017-03-04 10:20:16');

**Comment by jnrubiano** [comment]
Por favor usemos un solo nombre para la base de datos. Añadir las primeras dos lineas al script antes de ejecutar:
create database pactohonor;
use pactohonor;

**Comment by jolarter** [comment]
Poner el nombre de quien debe hacer el cambio en el script de la base de datos señores.

**Comment by jnrubiano** [comment]
Se adjunta el script enviado por Manuel con las líneas mencionadas anteriormente.





[PactoHonor_v1.0.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/847872/PactoHonor_v1.0.txt)

**Comment by jnrubiano** [comment]
Buenas noches:

Se actualiza la base de datos. Se sube script en la ruta Pacto-de-Honor/BACKEND/Polifight/DB/ del branch "Consolidacion" commit 93eb06a3d6802351584755206b10837e67094e27
