### ISSUE TITLE
1.3.3 Creación de la sección de créditos

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#155]
**Descripción**

Creación de los textos correspondientes a la sección de créditos. Se toma en cuenta la información sobre la campaña Pacto de Honor, sus personajes y los 10 tipos de plagio.

**TAREAS**

- [x] Textos descriptivos sobre la campaña Pacto de Honor
- [x] Textos descriptivos de los 10 tipos de plagio
- [x] Textos descriptivos de los personajes

**Documento de apoyo**

[2.Entrega.Subgrupo.-.Practica.Aplicada-1.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/818960/2.Entrega.Subgrupo.-.Practica.Aplicada-1.docx)

**Comment by jrsosago** [comment]
Se cambia a @Jdbernalv94 a este issue, debido a que se va asignar a @KmiArthur a otro Issue.

**Comment by jdbernalv** [comment]
Se realiza la entrega del documento con los textos correspondientes a la campaña Pacto de Honor, sus personajes y los 10 tipos de plagio. Anexo entrega
[Creación de Textos (Creditos) - Jaime David Bernal Villarraga.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/840336/Creacion.de.Textos.Creditos.-.Jaime.David.Bernal.Villarraga.docx)

**Comment by CamilaG08** [comment]
Se cierra el Issue  debido a la correcta entrega de la asignación.
