### ISSUE TITLE
Control de Calidad BD

### ISSUE THREAD

**Issue by wpradere** [ISWPOLI/Pacto-de-Honor#157]
# Realizar control de calidad a la Bd 
- [ ] Realizar retroalimentación y o aspectos a mejorar 

@manuk160

**Comment by manuk160** [comment]
De acuerdo a los avances presentados por el equipo se realizaran procesos de validación del modelo entidad relación y la estructura de datos a cargar.

**Comment by manuk160** [comment]
Tabla Jugador:

* Como se hace la trazabilidad con el registro a nivel de la aplicación y cuales campos se deben integrar?
* Donde se guarda la contraseña.
* correo electrónico.
* Los datos básicos de cada estudiante si queremos saber cómo entro al pacto de honor y demás.
* nivel_id_nivel: cambiar el nombre del campo "id_nivel".
* numero_monedas_jugador: cambiar el nombre "monedas_jugador"
* Falta el campo de imagen del jugador.
* Que define la vida de un jugador en esta tabla "es un campo a almacenar o como se maneja"

Tabla nivel:

* mundo_id_mundo: cambiar el nombre del campo "id_mundo".

Tabla Mundo:

*Falta el campo de la imagen del mundo, se tiene que tener en cuenta que mediante el desarrollo con phaser un mundo o tablero puede estar armado por más de una imagen

Tabla Personaje: 

* Cuantos personajes puede tener un jugador?
* Si tiene más de un personaje como se calcula el nivel?
* Como veo el avance por personaje o es el mismo al desbloquear alguno nuevo.
* dano_fisico_personaje: cambiar nombre por "nivel_dano"

Tabla nivel_tiene_personaje:

* El personaje tiene un nivel o es el jugador con un personaje que tiene un nivel.
* Si el personaje está asociado a un mundo debería replantearse ese orden.

Tabla jugador_tiene_personaje

* jugador_id_jugador: cambiar el nombre "id_jugador"
* personaje_id_personaje: cambiar el nombre "id_personaje"

Tabla personaje_tiene_poder

* personaje_id_personaje: cambiar el nombre "id_personaje"
* poder_id_poder: cambiar el nombre "id_poder"
* los poderes tienen imágenes? - faltaría el campo

Tabla personaje_tiene_frase

* personaje_id_personaje: cambiar el nombre "id_personaje"
* frase_id_frase: cambiar el nombre "id_frase"

**Comment by manuk160** [comment]
se tomo como referencia le ultimo modelo cargado

![image](https://cloud.githubusercontent.com/assets/25807878/23663658/4583fbb0-0321-11e7-9e82-f0bb4da60ee8.png)

**Comment by manuk160** [comment]
Se realiza una nueva validación al modelo propuesto y estos son los puntos a tener en cuenta:

En cuanto al nuevo modelo estas son las sugerencias:

1. Creo que la tabla imagen aplica para el tema de los mundos, poderes y los personajes "tenemos que validar hoy si es posible con el otro equipo como piensan desarrollar ese tema".

2. Quitaría la tabla imagen de jugador y lo dejaría como un campo tipo varchar puesto que si no se tiene la imagen no se puede cargar el jugador.

3. Nos toca validar las llaves en cuanto a las acciones pero eso lo podemos validar adelante.

4. En cuanto al tema de acceso de usuarios existen dos opciones:

- Opción 1: Colocar una tabla usuario, para poder gestionar los usuarios registrados a la aplicacion con la opción de tener roles que nos permita diferencias un administrador de un jugador y posibles roles adicionales que encontremos en desarrollo de la aplicacion "en esta opción podemos llegar un poco mas a fondo agregando mas campos  y validar el registro de los estudiantes a nivel de facultad entre otros". Si se crea esta tabla también incluiríamos el correo y lo retiraríamos de jugador.
 
![image](https://cloud.githubusercontent.com/assets/25807878/23707334/f9b63ec2-03df-11e7-8a41-1da964c08a98.png)

![image](https://cloud.githubusercontent.com/assets/25807878/23707399/2f178ad0-03e0-11e7-9c7c-c9c92024c217.png)

- Opción 2: Colocar los campos directamente en la tabla de jugador.

5. Aun no tenemos respuesta de esto por lo cual deberíamos validarlo hoy con el otro grupo

Tabla Personaje:
Cuantos personajes puede tener un jugador?
Si tiene más de un personaje como se calcula el nivel?
Como veo el avance por personaje o es el mismo al desbloquear alguno nuevo.

**Comment by manuk160** [comment]
Se valida con el grupo que esta haciendo el modulo de acceso a la aplicacion y se confirma la tabla de usuario 

Script de tabla de usuarios que requieren para la parte de los módulos de acceso a la aplicacion. Se valido y se realizaron cambios para que coincida con lo que se esta manejando, esto afectaría la tabla jugador de acuerdo a la anterior retroalimentacion.

Por otra parte se debe incluir una tabla país y una tabla ciudad. 

CREATE TABLE usuarios (
id_usuario int(10) NOT NULL,
Nombre varchar(100) NOT NULL,
Apellido varchar(100) NOT NULL,
email varchar(150) NOT NULL,
pais varchar(50) NOT NULL,
ciudad varchar(50) NOT NULL,
usuario varchar(50) NOT NULL,
password varchar(20) NOT NULL,
id_role int(10) NOT NULL,
fecha_registro timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

**Comment by manuk160** [comment]
Se realiza control de calidad nuevamente al modelo de base de datos y se tiene una versión inicial para el juego. Se tiene que re evaluar los requerimientos en cuanto a las pruebas psicotecnicas por lo cual se adelanta en el diseño.

![image](https://cloud.githubusercontent.com/assets/25807878/23836131/6b5dc00e-0741-11e7-9833-9e46c7d230ea.png)
