### ISSUE TITLE
Definición de template de documentación 

### ISSUE THREAD

**Issue by wpradere** [ISWPOLI/Pacto-de-Honor#158]
- [x] Template para la documentación del grupo respecto al los procesos de versioning software

@jnrubiano

**Comment by jnrubiano** [comment]
Se adjunta documento con la propuesta de nomenclatura que deben serguir todos los archivos y documentos que se generen.
[Nomenclatura.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/835210/Nomenclatura.docx)
