### ISSUE TITLE
2.1 Creacion servicios REST JUGADOR

### ISSUE THREAD

**Issue by wpradere** [ISWPOLI/Pacto-de-Honor#159]
## Creación servicio REST Jugador 

- [ ] Jugador

@jnrubiano

**Comment by jnrubiano** [comment]
Buenas tardes:

Se adjunta la documentación del servicio, esto incluye la estructura de entrada, la estructura de salida cuando es satisfactorio o no y la dependencia sobre otros servicios.

Saludos.
[ServicioJugador_v0.1.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/863081/ServicioJugador_v0.1.pdf)

**Comment by jnrubiano** [comment]
Se culmina el desarrollo, se espera el despliegue en el servidor para la realización de las pruebas de consumo.
