### ISSUE TITLE
Selección de Personaje

### ISSUE THREAD

**Issue by CristianGarzonBernal** [ISWPOLI/Pacto-de-Honor#16]
**Descripción de la historia**
Como el grupo asignado a la selección de personajes vamos a realizar los mockups para dar mostrar como va ser la navegación de los usuarios por el juego, luego se realizara la codificación  y sus respectivas pruebas.
El grupo también se encargara de animar los escenarios correspondientes a diferentes instalaciones del Politécnico Grancolombiano.
Por ultimo se crearan las historias de usuario. 
**Caracteristicas**

- [x] Mockups
- [ ] Codificación
- [ ] Pruebas
- [x] Escenarios
- [x] Historias de usuario

**Comment by cirlord1** [comment]
![mockup1](https://cloud.githubusercontent.com/assets/22016808/23002115/cd59cdd2-f39d-11e6-98ce-28e30536953b.png)
![mockup2](https://cloud.githubusercontent.com/assets/22016808/23002122/d483095c-f39d-11e6-845b-7cc927e1ca43.png)

**Comment by ghost** [comment]
**ESCENARIOS**

![bienestar lluvia](https://cloud.githubusercontent.com/assets/22629833/23098309/ac9c32ce-f618-11e6-8a1f-43e6aba4262e.gif)
![bienestar nieve](https://cloud.githubusercontent.com/assets/22629833/23098307/ac9a9c7a-f618-11e6-9bdb-b3223a175f50.gif)
![bienestar sol](https://cloud.githubusercontent.com/assets/22629833/23098308/ac9b2244-f618-11e6-9ca8-b3029a06fe57.gif)
![bloque c lluvia](https://cloud.githubusercontent.com/assets/22629833/23098306/ac9a2f92-f618-11e6-8f89-be93e8466d8e.gif)
![bloque c nieve](https://cloud.githubusercontent.com/assets/22629833/23098310/ac9e2fe8-f618-11e6-9085-41f0d553b183.gif)
![bloque c sol](https://cloud.githubusercontent.com/assets/22629833/23098311/aca10d12-f618-11e6-929c-dc4cb993d064.gif)
![bloque g lluvia](https://cloud.githubusercontent.com/assets/22629833/23098312/acadc3ae-f618-11e6-834c-57c756b278cd.gif)
![bloque g nieve](https://cloud.githubusercontent.com/assets/22629833/23098314/acaf5c0a-f618-11e6-906d-75bbcbe17935.gif)
![bloque g sol](https://cloud.githubusercontent.com/assets/22629833/23098313/acae6ce6-f618-11e6-91e8-1a99c5f57795.gif)
![bloque i lluvia](https://cloud.githubusercontent.com/assets/22629833/23098315/acb22c64-f618-11e6-88df-ce6b688e1ba8.gif)
![bloque i nieve](https://cloud.githubusercontent.com/assets/22629833/23098317/acb56e06-f618-11e6-8af1-45f632eae486.gif)
![bloque i sol](https://cloud.githubusercontent.com/assets/22629833/23098316/acb2336c-f618-11e6-9504-01c7f6e80386.gif)
![bloque j lluvia](https://cloud.githubusercontent.com/assets/22629833/23098322/acc57ddc-f618-11e6-98f6-2804d9f44a8c.gif)
![bloque j nieve](https://cloud.githubusercontent.com/assets/22629833/23098320/acc305e8-f618-11e6-8a90-d6ffcbdd5091.gif)
![bloque j sol](https://cloud.githubusercontent.com/assets/22629833/23098318/acc1d092-f618-11e6-9878-1fa3ed4eae4b.gif)
![bloque k lluvia](https://cloud.githubusercontent.com/assets/22629833/23098319/acc2323a-f618-11e6-828f-671ec5f6049e.gif)
![bloque k nieve](https://cloud.githubusercontent.com/assets/22629833/23098321/acc36d08-f618-11e6-964f-365a056d3986.gif)
![bloque k sol](https://cloud.githubusercontent.com/assets/22629833/23098323/acc60734-f618-11e6-88b4-81f9205d4cab.gif)
![cancha lluvia](https://cloud.githubusercontent.com/assets/22629833/23098324/acd2b9de-f618-11e6-8341-4a9770b2f8fe.gif)
![cancha nieve](https://cloud.githubusercontent.com/assets/22629833/23098327/acd3efb6-f618-11e6-99cf-9f05841b42ef.gif)
![cancha sol](https://cloud.githubusercontent.com/assets/22629833/23098326/acd4092e-f618-11e6-882f-a5f2614ef593.gif)
![paradero lluvia](https://cloud.githubusercontent.com/assets/22629833/23098325/acd3fad8-f618-11e6-9e9e-7601b9c07856.gif)
![paradero nieve](https://cloud.githubusercontent.com/assets/22629833/23098328/acd6aeb8-f618-11e6-9033-486c0f994228.gif)
![paradero sol](https://cloud.githubusercontent.com/assets/22629833/23098329/acd994ca-f618-11e6-972e-ea1f3c39a7b0.gif)
![plazoleta lluvia](https://cloud.githubusercontent.com/assets/22629833/23098330/ace3bc48-f618-11e6-992b-dbaa315de7d0.gif)
![plazoleta nieve](https://cloud.githubusercontent.com/assets/22629833/23098332/ace46c88-f618-11e6-8bc2-4e2eacad2871.gif)
![plazoleta sol](https://cloud.githubusercontent.com/assets/22629833/23098331/ace42cfa-f618-11e6-99e5-7328b092b96e.gif)
![poli medellin lluvia](https://cloud.githubusercontent.com/assets/22629833/23098333/ace80ae6-f618-11e6-9f8a-b4b9cd800740.gif)
![poli medellin nieve](https://cloud.githubusercontent.com/assets/22629833/23098335/aceee24e-f618-11e6-9b62-f49213e13a62.gif)
![poli medellin sol](https://cloud.githubusercontent.com/assets/22629833/23098334/acebf5c0-f618-11e6-968e-a345163847b6.gif)
![sede excelencia lluvia](https://cloud.githubusercontent.com/assets/22629833/23098336/acf43faa-f618-11e6-91dc-ca3a8cd1b8c7.gif)
![sede excelencia nieve](https://cloud.githubusercontent.com/assets/22629833/23098337/acf49d74-f618-11e6-9ee2-27534935cbef.gif)
![sede excelencia sol](https://cloud.githubusercontent.com/assets/22629833/23098338/acf4b32c-f618-11e6-940d-d2b7a22ae6f3.gif)
![sede postgrados lluvia](https://cloud.githubusercontent.com/assets/22629833/23098339/acfaa1d8-f618-11e6-9dd8-89cb7fde70dd.gif)
![sede postgrados nieve](https://cloud.githubusercontent.com/assets/22629833/23098340/acff68bc-f618-11e6-885e-0b0bf968a411.gif)
![sede postgrados sol](https://cloud.githubusercontent.com/assets/22629833/23098341/ad06661c-f618-11e6-8844-2849c51d5047.gif)

**Comment by ivandav** [comment]
**HISTORIAS DE USUARIO (PERSONAJES BUENOS Y MALOS, ESTETICA, NAVEGACION Y ESCENARIOS ANIMADOS)**

[Historias-de-usuario.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/778803/Historias-de-usuario.docx)

**Comment by DiegOliveros** [comment]
Esto no está codificado

**Comment by jnrubiano** [comment]
Hola @jdma0440:

¿Nos indicas por favor si requieres el apoyo del equipo 2 para alguna tarea de este issue? Veo que esta tarea corresponde al equipo 1 y en este momento nos encontramos cerrando todos los issues que se terminaron o que tengan relación con otros.

Quedamos atentos a tus comentarios.

**Comment by ghost** [comment]
@jnrubiano, esta Issue esta duplicada, la que se tuvo en cuenta fue la siguiente:

- https://github.com/ISWPOLI/Pacto-de-Honor/issues/44
