### ISSUE TITLE
1.2.7 Selección del personaje (Mockups e implementación)

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#160]
**Descripción**

Crear la sección en donde se permite seleccionar el avatar del jugador y la sección donde se escoge el personaje para la batalla.

**TAREAS**

- [x] Definir mockup para la selección de avatar
- [x] Definir mockup para la selección de personajes antes de la batalla
- [x] Describir el funcionamiento de estas secciones
- [x] Realizar el componente gráfico de la selección de avatar
- [x] Realizar el componente gráfico de la selección de personajes antes de la batalla
- [x] Implementar dicho funcionamiento a código fuente
- [x] Realizar sprites de botones a utilizar

**Comment by ghost** [comment]
### Selección de Avatar (Registro de Tiempo: 4 horas y 30 minutos)

https://drive.google.com/open?id=0B8ttTD0H6QRCTnpKaVZXVXotSzQ

**Comment by ghost** [comment]
### Selección de personajes (Registro de Tiempo: 4 horas)

https://drive.google.com/open?id=0B8ttTD0H6QRCY3B3RnV0WGZWY0U

**Comment by ghost** [comment]
### Sprites de botones (Registro de Tiempo: 1 hora)

![anapanterabutton](https://cloud.githubusercontent.com/assets/22629833/23820788/60c43e56-05ee-11e7-9f2a-c82b5d037c7d.png)
![andresgallobutton](https://cloud.githubusercontent.com/assets/22629833/23820791/60ca116e-05ee-11e7-93ae-7e5c6374178b.png)
![cataciervabutton](https://cloud.githubusercontent.com/assets/22629833/23820790/60ca0714-05ee-11e7-8a95-78e911ee324d.png)
![danielagirafabutton](https://cloud.githubusercontent.com/assets/22629833/23820789/60c9e9fa-05ee-11e7-9c32-9d368cdd0c1f.png)
![danielleonbutton](https://cloud.githubusercontent.com/assets/22629833/23820793/60cdec6c-05ee-11e7-86dd-0b0568022a52.png)
![fabiancanariobutton](https://cloud.githubusercontent.com/assets/22629833/23820792/60cd1968-05ee-11e7-8c8b-ec174552df56.png)
![ivanruisenorbutton](https://cloud.githubusercontent.com/assets/22629833/23820794/60d53c2e-05ee-11e7-96c8-5bd72b30a46c.png)
![pedroratonbutton](https://cloud.githubusercontent.com/assets/22629833/23820796/60db0d48-05ee-11e7-9359-6bf4afedd95a.png)
![tatihormigabutton](https://cloud.githubusercontent.com/assets/22629833/23820795/60da741e-05ee-11e7-830f-b03a13fdd722.png)

**Comment by ghost** [comment]
### Informe

[Informe3.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/835521/Informe3.docx)
