### ISSUE TITLE
Creación Servicios REST NIVEL

### ISSUE THREAD

**Issue by wpradere** [ISWPOLI/Pacto-de-Honor#161]
## Creación servicio REST nivel 

- [x] Nivel 

@EdnaEspejo

**Comment by EdnaEspejo** [comment]
Hasta el momento he logrado generar la persistencia, pero estoy presentando inconvenientes para visualizar la base de datos que carge desde el glassfish

**Comment by EdnaEspejo** [comment]
Se genera servicio REST y se agrega al proyecto Backend
