### ISSUE TITLE
2.3 Creación servicios REST PODER

### ISSUE THREAD

**Issue by wpradere** [ISWPOLI/Pacto-de-Honor#163]
## Creación servicios REST PODER
- [x] Instalación Net Beans y JDK
- [x] Instalación Glassfish 4.1.1
- [x] Implementación de servicio Rest: Poder

@DanteVDrako

**Comment by DanteVDrako** [comment]
Se realiza la configuración de Netbeans 7.4 y conexión a base de datos de prueba y servidor Glassfish 4.0.

- [x] Se importa a un cliente XAMMP la base de datos p_h01 creada para el proyecto.

![image](https://cloud.githubusercontent.com/assets/25806785/23964827/d817eb36-0983-11e7-9a53-a7b238e9e2ef.png)

- [x] Se realiza instalación de Glassfish 4.0

![image](https://cloud.githubusercontent.com/assets/25806785/23964864/ff3bea28-0983-11e7-9d03-9280be278a80.png)

- [x] Se integra Netbeans 7.4 con Glassfish y la base de datos.

![image](https://cloud.githubusercontent.com/assets/25806785/23964906/27054d92-0984-11e7-8879-d3b665b2f610.png)

**Comment by DanteVDrako** [comment]
Configuración de servicio Rest.

- [x] Se crea proyecto Java Web.

![image](https://cloud.githubusercontent.com/assets/25806785/23964960/635ca100-0984-11e7-8ac9-93cd440d4ce9.png)

- [x] Se crea sobre el proyecto la persistencia que permitirá obtener conexión a la base de datos.

![image](https://cloud.githubusercontent.com/assets/25806785/23965005/8dcac4d0-0984-11e7-8278-0c97fae19656.png)

- [x] Se crean las entidades Rest para la tabla de Poder y su dependencia la tabla de Imagen.

![image](https://cloud.githubusercontent.com/assets/25806785/23965076/d39138fa-0984-11e7-92da-26f5fdbeaa67.png)

- [x] Crear cada una de los Java Script para cada entidad rest creada en el punto anterior.

![image](https://cloud.githubusercontent.com/assets/25806785/23965225/51fabd9c-0985-11e7-9cc6-5cbcb903e66c.png)

- [x] Hacer Deploy del proyecto para crear archivo war.

![image](https://cloud.githubusercontent.com/assets/25806785/23965322/9adbee8c-0985-11e7-9939-f562d2b69f6b.png)

- [x] Hacer Test local del proyecto.

![image](https://cloud.githubusercontent.com/assets/25806785/23965355/addfae24-0985-11e7-9b37-26ab8de8c424.png)

![image](https://cloud.githubusercontent.com/assets/25806785/23965392/d20671de-0985-11e7-9a18-55c7854c23e4.png)

- [x] Hacer Test del proyecto en paquete war.

![whatsapp image 2017-03-15 at 10 12 12](https://cloud.githubusercontent.com/assets/25806785/23971362/a966c1f0-099b-11e7-860f-bf011f4b03e3.jpeg)

**Comment by jnrubiano** [comment]
Hola @DanteVDrako:

¿Creaste EJB o creaste entidades a partir de una conexión a la DB Local? El propósito de los EJB es brindar una persistencia para no tener una conexión directa a una DB si lo haces así sería innecesario tener unos EJB.

**Comment by DanteVDrako** [comment]
@jnrubiano Sí, las apliqué directamente a una BD mapeada a localhost, Según entiendo luego de crear el war se puede desplegar en glassfish con normalidad.

**Comment by DanteVDrako** [comment]
Se sube código fuente al repositorio del proyecto.

![image](https://cloud.githubusercontent.com/assets/25806785/23979211/21e44916-09c6-11e7-8488-1e4fce009795.png)
