### ISSUE TITLE
4.2.3 Descripción de los mini-personajes de los 10 mundos restantes

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#165]
**Descripción**

Crear la descripción de los mini-personajes, basarse en el Issue #37 .

**TAREAS**

- [x] Crear 4 mini-personajes por mundo relacionados con el jefe final
- [x] Descripción detallada de personalidad de dichos mini-personajes
- [x] Descripción detallada de poder de cada uno de esos mini-personajes

**Comment by jdbernalv** [comment]
Se realiza la creación del comportamiento de los 48 Mini-Personajes (Nombre, Descripción, Personalidad, Poder y tipo). Anexo Documento Final. @gsalvarez 
[Comportamiento 48 Mini-Personajes - Jaime David Bernal.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/835965/Comportamiento.48.Mini-Personajes.-.Jaime.David.Bernal.docx)

**Comment by CamilaG08** [comment]
Se presenta el documento a Gabriel y se cierra el Issue.
