### ISSUE TITLE
1.1.13 Creación del manual de diseño

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#167]
**Descripción**

Crear el manual de diseño que hará de guía para la estandarización del diseño de la aplicación.

**TAREAS**

- [x] Revisar el material proporcionado en el Issue #86 
- [x] Establecer los parámetros del diseño
- [x] Realizar el manual de diseño

**Comment by KmiArthur** [comment]
# Libro de guías de diseño para la GUI: 
(Trabajo: 3h)

[Design Booklet.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/828298/Design.Booklet.pdf)
