### ISSUE TITLE
4.2.4 Creación de los sprites de los mini personajes

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#168]
**Descripción**

Crear las imágenes y los sprites de los mini-personajes pertenecientes al mundo 3 en adelante.

**TAREAS**

- [x] Revisar las descripciones detalladas sobre los mini - personajes
- [x] Realizar modificaciones (en caso de ser necesario)
- [x] Realizar los sprites de cada mini - personaje

**Comment by gabogabbs** [comment]
Este issue queda pendiente de realizar debido a la prioridad del código fuente. La tarea asignada el miércoles 8 de marzo se encuentra en el issue #129

**Comment by CamilaG08** [comment]
Se retoma este Issue para la terminación de componentes gráficos.

**Comment by gabogabbs** [comment]
Se realizan 36 Sprites de mini personajes.
Faltan 12 Sprites.
[Mini personajes.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/869481/Mini.personajes.zip)

REGISTRO DE TIEMPO: 7 HORAS.
TIEMPO ESTIMADO PARA FINALIZAR TAREA: 2 HORAS.

**Comment by CamilaG08** [comment]
Queda pendiente para cierre con plazo máximo el martes 28 de marzo.

**Comment by gabogabbs** [comment]
Se realizan los 12 Sprites de los mini personajes faltantes, por lo tanto el issue se da por terminado. 

[Mini personajes.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/871413/Mini.personajes.zip)

REGISTRO DE TIEMPO: 2 HORAS Y 30 MINUTOS.

**Comment by CamilaG08** [comment]
Se cierra el Issue dado que la entrega fue de acuerdo con lo estipulaado.
