### ISSUE TITLE
1.7 Creación de módulos y organización de carpetas

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#169]
**Descripción**

Este Issue tiene como propósito la creación de plantillas, módulos y carpetas que permitan la organización y el entendimiento del proyecto en su desarrollo.

**TAREAS**

- [x] Establecer los módulos de trabajo
- [x] Verificar y aprobar dichos módulos
- [x] Realizar las plantillas de los módulos establecidos
- [x] Revisar que los módulos cubran lo requerido para la integración
- [x] Crear un diagrama de organización de carpetas
- [x] Implementar las plantillas basándose en la organización de carpetas establecida
- [x] Subir a GitHub dichas plantillas
- [x] Socializar con el grupo de Front-end lo realizado para estandarizar el proceso de desarrollo

**Comment by ghost** [comment]
Se realiza reunión con el docente @DiegOliveros y @CamilaG08 para establecer las carpetas y módulos por crear, para la organización y estructuración del proyecto. 

Tiempo empleado: 45 min.

**Comment by DiegOliveros** [comment]
Fueron como 5 -.-

**Comment by ghost** [comment]
Carpetas 
[Poli Fighters.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/829401/Poli.Fighters.zip)

**Comment by CamilaG08** [comment]
Quedan pendientes las plantillas, que se encuentran en proceso.

**Comment by CamilaG08** [comment]
Se cierra a pesar de no terminar las tareas, ya que las tareas faltantes que es la creación de las plantillas y el portal se asignarán en otro Issue #205
