### ISSUE TITLE
1.3.4 Investigación sobre interacción social y códigos alfanuméricos

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#170]
**Descripción**

Investigar sobre la interacción social en un juego WEB y su implementación con Phaser y Javascript. Investigar sobre información codificada en códigos alfanuméricos.

**TAREAS**

- [x] Investigar sobre la interacción social en un juego WEB
- [x] Listar las interacciones entre jugadores que requiere el juego
- [x] Investigar cómo implementar dichas interacciones en Phaser y con Javascript
- [x] Investigar sobre códigos alfanuméricos y su almacenamiento de información
- [x] Describir el manejo de estos códigos a través del juego para el desbloqueo de personajes y/o logros

**Comment by rzambrano112** [comment]
Se realizan las actividades de :
Investigar sobre la interacción social en un juego WEB
Listar las interacciones entre jugadores que requiere el juego
 Investigar cómo implementar dichas interacciones en Phaser y con Javascript

[Uploading Investigar sobre la interacción social en un juego WEB.docx…]()

**Comment by rzambrano112** [comment]
Se anexa el documento realizado
[Investigar sobre la interacción social en un juego WEB.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/829326/Investigar.sobre.la.interaccion.social.en.un.juego.WEB.docx)

**Comment by rzambrano112** [comment]
3.Investigar cómo implementar dichas interacciones en Phaser y con Javascript.
Se anexa documento sobre dicho punto.
[Implementacion de Phaser con JavaScript.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/835484/Implementacion.de.Phaser.con.JavaScript.docx)

**Comment by rzambrano112** [comment]
4.Investigar sobre códigos alfanuméricos y su almacenamiento de información
	
Todo lo relacionado con el almacenamiento y códigos alfanuméricos se encuentran depositados en el siguiente repositorio de GitHub.
http://phaser.io/docs/2.6.2/index

**Comment by jrsosago** [comment]
El listado de tareas a realizar está completo, se cierra esta Issue.
