### ISSUE TITLE
5.5 Reunión de revisión con Juanita Ríos

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#171]
**Descripción**

Presentación de avances, tomar nota de modificaciones y detallar el producto final.

**TAREAS**

- [x] Organizar la reunión con Juanita
- [x] Preparar lo que se va a exponer (Documentación y mockups)
- [x] Realizar la reunión
- [x] Exponer el producto
- [x] Tomar nota de las modificaciones
- [x] Detallar el producto
- [x] Generar un acta de reunión

**Comment by CamilaG08** [comment]
Quedamos atentos a la disponibilidad de Juanita a través de @DiegOliveros y @jolarter

**Comment by DiegOliveros** [comment]
@CamilaG08  Juanita se encuentra en el bloque b, en la oficina exterior bajo el gimnasio, en horario de oficina, ya se le informó que tendría visita esta semana.

**Comment by CamilaG08** [comment]
Se realiza la reunión satisfactoriamente con Juanita, queda pendiente cargar el acta @jdma0440 

Tiempo empleado: 30 minutos

**Comment by ghost** [comment]
## Acta de reunión de revisión de producto con Juana Ríos (Registro de tiempo: 30 minutos)

[Acta de Reunion de Revisión de Producto.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/835514/Acta.de.Reunion.de.Revision.de.Producto.docx)
