### ISSUE TITLE
Revisiòn de historias

### ISSUE THREAD

**Issue by ingenieriadelsoftware** [ISWPOLI/Pacto-de-Honor#173]
**Revisión de historias**
Esta historia está creada para que mediante el reporte se logre poner orden a las historias actuales.
**Tareas**
- [x] Reporte de personas que han creado historias en Git: No de historias creadas(bien creadas-con asignación, con milestone, con lista de tareas), nombre.
- [x] Enviar correos para que corrijan las historias mal elaboradas.
- [x] Crear hoja de calculo en linea con el reporte y compartir con los líderes y directores de proyecto.

**Comment by CamilaG08** [comment]
Se cierra al realizar la socialización con el grupo.

**Comment by jdbernalv** [comment]
Se enviara informe del Product Backlog a los lideres y directores del proyecto antes de cada clase "Actualizado". @ingenieriadelsoftware
