### ISSUE TITLE
5.3.3 Análisis de riesgos

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#179]
**Descripción**

Realizar el análisis de riesgos del proyecto.

**TAREAS**

- [x] Listar los riesgos
- [x] Realizar el documento de análisis de riesgos
- [x]  Realizar gráfica de análisis de riesgos
- [x] Realizar plan de contingencia para cada riesgo

**Comment by jrsosago** [comment]
Se adjunta documento de análisis de riesgos. **Tiempo empleado:2 horas**
[análisis de riesgos.xlsx](https://github.com/ISWPOLI/Pacto-de-Honor/files/852114/analisis.de.riesgos.xlsx)
