### ISSUE TITLE
6.3.1. Documentación Sprint 4

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#181]
- [x] Acta reunión Juanita Rios.
- [x] Archivos presentados a Juana Ríos.
- [x] Acta reunión Psicología
- [x] Documento de consolidación de reportes de Scrum- Master

**Comment by ghost** [comment]
## Archivos presentados en la reunión con Juana Ríos

https://drive.google.com/open?id=0B8ttTD0H6QRCQV9nMnZfMngzbUk

**Comment by ghost** [comment]
## Reportes SCRUM MASTER

[Reportes SCRUM MASTER.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/849805/Reportes.SCRUM.MASTER.docx)

**Comment by CamilaG08** [comment]
Se cierra dado que la documentación de psicología queda para el Sprint 5 y se subirá en los Issues #185 y #186 .

**Comment by jrsosago** [comment]
Adjunto se envía acta reunión con departamento de Psicología.
[PRUEBAS.PSICOTECNICAS.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/852507/PRUEBAS.PSICOTECNICAS.docx)
