### ISSUE TITLE
5.7.1 Reunión con el Decano Rafael García

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#183]
**Descripción:**
Reunirse con el decano para mostrar todos los documentos relacionados con el proyecto
**Tareas a realizar:**
- [x] Consolidar documentación a mostrar.
- [x] Consolidar código a mostrar.
- [x] Preparar exposición.
- [x] Mostrar exposición al profesor Diego o al profesor Julián.
- [x] Reunirnos con el decano. 
Reunión se aplaza para el 9no sprint, ya que queremos presentarle un juego funcional

**Comment by CamilaG08** [comment]
Se mueve al sprint 10, ya que para realizarse se debe tener el prototipo funcional.

**Comment by CamilaG08** [comment]
Se establece la reunión para el día jueves 20 de Abril a la 1:30 pm

**Comment by jrsosago** [comment]
Se realiza reunión con los profesores para definir presentación para el día de mañana.

**Comment by CamilaG08** [comment]
Se realiza la exposición al decano y a Juanita Ríos.

Presentación: https://docs.google.com/presentation/d/13ELoI3eV4257AEPZaT4VqmNIE1YxD6e-giVo4wdxErY/edit?usp=sharing 

Quedan como conclusiones:

- Rafael García se encargará de generar el apoyo por parte del departamento de Psicología o Humanidades y con los requerimientos de Infraestructura.
- Queda una reunión para @DiegOliveros y @jolarter con Juanita para hablar con varios departamentos como TROMPO.
- El equipo de desarrollo debe tener un demo del juego en el siguiente Sprint.
- Queda pendiente realizar la presentación del producto al Vice - Rector.

**Comment by jrsosago** [comment]
Se realiza la exposición al decano y a Juanita Ríos, el día Jueves 30 de Abril. **Tiempo reunión: 1 hora** y quedan las conclusiones expuestas por @CamilaG08
