### ISSUE TITLE
5.7.2 Reunión Vicerrector Politécnico Grancolombiano.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#184]
Reunión con Vicerrector para mostrar los documentos, relacionados con el proyecto

**Comment by JuanCheroslan** [comment]
@CamilaG08 @jrsosago @manuk160  estoy preparando una presentacion inicial para el vicerrector donde le "vendamos" el juego, en un par de horas la subo a este issue.

**Comment by JuanCheroslan** [comment]
adjunto el primer draft de la presentacion al vicerrector

@jrsosago  @CamilaG08 @manuk160  agradezco sus comentarios
[Poli Fighters.pptx](https://github.com/ISWPOLI/Pacto-de-Honor/files/846017/Poli.Fighters.pptx)

**Comment by ingenieriadelsoftware** [comment]
@jrsosago @CamilaG08 @manuk160 @jolarter  Esta reunión se aplaza hasta tanto no exista un prototipo completo funcional y debe ser después de la reunión con Rafael.

**Comment by ingenieriadelsoftware** [comment]
Si una Historia no tiene entregables asociados no debe crearse.
