### ISSUE TITLE
5.6.1 Investigación pruebas psicotécnicas

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#185]
**Descripción**
Leer y realizar documento sobre los manuales de dos pruebas psicotecnias, en el transcurso de está semana.
**Tareas a realizar**
- [x] Leer manual prueba MMPI-A
- [x] Realizar documento prueba MMPI-A
- [x] Leer manual prueba CPS (Cuestionario personalidad situacional).
- [x] Realizar documento prueba CPS (Cuestionario personalidad situacional).

**Comment by jrsosago** [comment]
Se adjunta documento resumen de la prueba MMPI-A **Tiempo empleado:1 hora y 22 minutos**
[MMPI-A.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/846178/MMPI-A.pdf)

**Comment by jrsosago** [comment]
Visita al departamento de Psicología para revisar cuales pruebas son referentes a la personalidad y nos pueden servir en el proyecto; las pruebas que nos pueden servir son las siguientes:
-  16-PF5
-  P-IPG
- MMPI-A
- CPC
- IPV
- SIV
Se saca prestado el manual de la prueba MMPI-A. **Tiempo empleado:15 minutos**

**Comment by jrsosago** [comment]
Fui al departamento de Psicología el 15 de Marzo y no pude sacar prestada la prueba CPS, debido aq que no hay copias, por está razón se escoge NEO PI-R, que es otra prueba de personalidad.

**Comment by jrsosago** [comment]
Se adjunta documento resumen de la prueba NEO PI-R. **Tiempo empleado:1 hora y 3 minutos**
[PRUEBA NEO PI.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/850025/PRUEBA.NEO.PI.docx)

**Comment by jrsosago** [comment]
Me dirigí al departamento de psicología, para pedir el cuadernillo de preguntas de la prueba NEO-FFI, pero este cuadernillo no lo tienen, pregunte el manual de la prueba CPS (Cuestionario de personalidad Situacional) del cual se encuentra el cuadernillo de preguntas pero no tienen el manual. Fui donde el Profesor Diego Oliveros para sacarle copia al cuadernillo, ya que como es el original no lo prestan, y imprimimos otra prueba llamada BFI (Big Five Inventory).
**Tiempo empleado:40 minutos**

**Comment by jrsosago** [comment]
Se adjunta documento resumen de la prueba CPS. **Tiempo empleado:1 hora y 4 minutos.**
[PRUEBA CPS.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/852113/PRUEBA.CPS.docx)
