### ISSUE TITLE
5.6.2 Investigación pruebas psicotécnicas

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#186]
**Descripción**
Leer y realizar documento sobre los manuales de dos pruebas psicotecnias, en el transcurso de está semana.
**Tareas a realizar**
- [x] Leer manual prueba IPV (Inventario de personalidad).
- [x] Realizar documento prueba IPV (Inventario de personalidad).
- [x] Leer manual prueba SIV (Valores interpersonales).
- [x] Realizar documento prueba SIV (Valores interpersonales).

**Comment by ghost** [comment]
Avance de la tarea asignada. Tiempo 2 horas 40 min.
[SIV Cuestionario de valores interpersonales.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/846525/SIV.Cuestionario.de.valores.interpersonales.docx)

**Comment by ghost** [comment]
Reporte Final para la tarea.

- Documento relacionado con el SIV o cuestionario de valores interpersonales.
[SIV Cuestionario de valores interpersonales.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/852167/SIV.Cuestionario.de.valores.interpersonales.docx)
Tiempo: 2 horas 40 minutos.

- Documento relacionado con el PIV o Inventario de personalidad para vendedores.
[Inventario de personalidad para vendedores.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/852168/Inventario.de.personalidad.para.vendedores.docx)
Tiempo: 3 horas 13 minutos.

**Comment by CamilaG08** [comment]
Se cierra ya que se pasa a la siguiente fase de crear las preguntas y la propuesta de implementación al juego.
