### ISSUE TITLE
5.7.3 Reunión con TROMPO

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#187]
Reunión con TROMPO, para mostrar documentación del proyecto

**Comment by ivandav** [comment]
La reunion no es muy importante por ahora, se cerrara y se abrirá cuando se vaya a realizar

**Comment by CamilaG08** [comment]
**TAREAS**

- [ ] Exponer el proyecto
- [ ] Mostrar los mockups de personajes y poderes
- [ ] Mostrar los mockups de escenarios y navegación
- [ ] Pedir la creación de sprites
- [ ] Pedir la creación de escenarios (Recuerden que al ser animados, deben ser en forma de sprites)
- [ ] Pedir la creación de los logos de los logros

Al ser los encargados de pedir los sprites y escenarios, son los encargados de aprobarlos o rechazarlos según la estructura de juego que estamos manejando.

**Personas encargadas en TROMPO**

- Ana Milena Cortés
- Harry

**Comment by ghost** [comment]
## Reunion con TROMPO

Se habla con Diego Oliveros, y el nos dice que por ahora se usen los escenarios y sprites existentes, ya que la realización de estos por parte de trompo tomará mucho tiempo.

Despues de tener los escenarios y sprites por parte de trompo, se realizara esta reunion.

**Comment by jrsosago** [comment]
Según lo que dice mi compañero Dario, se reasigna está actividad para el Sprint 10.

**Comment by CamilaG08** [comment]
Se cierra esta tarea dado que de la reunión con Rafael y Juanita se llegó a la conclusión que estos requerimientos quedan pendientes y a cargo de los líderes de proyecto.
