### ISSUE TITLE
5.4.1 Consolidar la documentación del código

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#188]
**Descripción**

Realizar una primera versión de la documentación del código.

**Tareas a realizar**
- [x] Documentación Login.
- [x] Documentación Navegación.
- [x] Documentación Combates.
- [x] Selección de Nivel
- [x] Documentación Selección de personajes.
- [x] Documentación creditos
- [x] Documentación fin
- [x] Documentación batalla
- [x] Documentación navegación
- [x] Documentación historieta
- [x] Documentación

**Comment by ghost** [comment]
## Primera Version de documetnación de codigo del Login, Navegación, Selección de niveles y Batalla

[Documentación del Codigo Fuente.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/853023/Documentacion.del.Codigo.Fuente.docx)

**Comment by jrsosago** [comment]
Se sugiere averiguar como se documenta en java script.

**Comment by CamilaG08** [comment]
Se pone como fecha límite el Sprint 10 teniendo en cuenta que aún falta en la construcción del código.

**Comment by ghost** [comment]
## Documentación Código Frontend Hasta 30 de marzo (Registro de Tiempo: 5 horas)

[DocumentacionCodigoFront_30-03.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/884739/DocumentacionCodigoFront_30-03.docx)
