### ISSUE TITLE
1.1.14 Mundos funcionales

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#190]
**Descripción**
Realizar la implementación de todos los mundos.
**Tareas a realizar**
- [x] Implementar mundo 3
- [x] Implementar mundo 4
- [x] Implementar mundo 5
- [x] Implementar mundo 6
- [x] Implementar mundo 7
- [x] Implementar mundo 8
- [x] Implementar mundo 9
- [x] Implementar mundo 10
- [x] Implementar mundo 11
- [x] Implementar mundo 12

**Comment by CristianGarzonBernal** [comment]
El codigo de seleccion de mundos  esta en el issue #129
