### ISSUE TITLE
1.2.8 Diseño del login respecto al manual de diseño

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#191]
**Descripción**

- [x]  Cambiar diseño del login, basándose en el manual de diseño que se encuentra en Issue #167

**Comment by CamilaG08** [comment]
Se cierra ya que se reasigna la tarea en el Issue #220

**Comment by ghost** [comment]
Se aplica ajustes según manual de Diseño y se sube al repositorio.

https://github.com/ISWPOLI/Pacto-de-Honor/blob/master/FRONTEND/css/versionWeb/main2.css
