### ISSUE TITLE
1.2.9 Perfil de jugador

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#192]
**Descripción**

Realizar el módulo de perfil del jugador funcional.

**TAREAS**

- [x] Revisar mockups del perfil del jugador
- [x] Realizar el prototipo
- [x] Pedir sección de logros a Camila
- [x] Integrar los logros al perfil del jugador
- [x] Implementar el módulo con Phaser

**Comment by CamilaG08** [comment]
Revisar los mockups del perfil de jugador en el Issue #37 

**Mockups tablero de logros**

![mockuplocked](https://cloud.githubusercontent.com/assets/22283896/23833810/fbe7a8f2-0718-11e7-9c45-13675852f141.jpg)


![mockupunlocked](https://cloud.githubusercontent.com/assets/22283896/23833811/fbea2280-0718-11e7-87a9-338ac5513cf5.jpg)

En caso de necesitarlo este es el archivo de logros, por ahora no se toman los de retos diarios:

[Logros.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/836643/Logros.docx)

**Comment by juankrlos08** [comment]
Recibidos los logros que se van a implementar, con descripción de cada uno de ellos para implementar y sea funcional

**Comment by juankrlos08** [comment]
Se muestra un adelanto de esta semana, 4 horas de trabajo empleadas.
[Juan Carlos Quintana Parra 15 Marzo 2017.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/846438/Juan.Carlos.Quintana.Parra.15.Marzo.2017.docx)

**Comment by CamilaG08** [comment]
Se entregan las imágenes de los logros: 


[Logros.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/846691/Logros.zip)

**Comment by juankrlos08** [comment]
Imágenes recibidas para la implementacion.

**Comment by juankrlos08** [comment]
Se entrega la implementacion  de los logros del perfil del jugador

[Viernes17.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/852135/Viernes17.pdf)

**Comment by juankrlos08** [comment]
https://drive.google.com/drive/folders/0B7wkwzWIslrpVlMzd0xaRkVWRUE?usp=sharing

Se adjuntan los códigos utilizados para la elaboración de los logros del perfil del jugador. Se reciben cualquier tipo de sugerencias con respecto al cambio del formato, mejora de imágenes.

**Comment by CamilaG08** [comment]
Después de revisión se detectan las siguientes modificaciones:

- Separar un poco más las imágenes.
- Disminuir un poco el tamaño de la letra
- Cambiar el botón de seleccionar por una label que indique si el logro está bloqueado o desbloqueado
- Tomar las imágenes como png o si es necesario realizar un bosquejo de imágenes por logro para pedir la creación de estas a TROMPO

**Se cambia esta Issue al Sprint 6 con fecha límite del miércoles 22 de Marzo y se crea las nuevas tareas en el Issue #219**

**Comment by CamilaG08** [comment]
Al igual que el Issue #219 , se alarga al Sprint 7 con fecha límite el viernes 31 de marzo.

**Comment by CamilaG08** [comment]
Se cierra debido a que se asignan las tareas en el Issue #219
