### ISSUE TITLE
4.1.4 consolidación archivos originales personajes buenos

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#193]
**Descripción**
Consolidar archivos originales realizados por TROMPO de los personajes buenos, para ponerlos en el juego.

**Comment by ivandav** [comment]
PERSONAJES BUENO EN CUADROS PARA EL JUEGO
Tiempo estimado: 1 hora y 30 minutos 
![cierva](https://cloud.githubusercontent.com/assets/22629584/23883990/1e9a5da2-0838-11e7-87b5-178fdc02f9ea.png)
![gallo](https://cloud.githubusercontent.com/assets/22629584/23883992/1e9d4b16-0838-11e7-82db-d177cfaffeae.png)
![gorrion](https://cloud.githubusercontent.com/assets/22629584/23883989/1e9a550a-0838-11e7-8a50-f901df58fd28.png)
![hormiga](https://cloud.githubusercontent.com/assets/22629584/23883988/1e99fb82-0838-11e7-945c-d87bc3804cdb.png)
![jirafa](https://cloud.githubusercontent.com/assets/22629584/23883993/1e9fb658-0838-11e7-852c-a3f0bc202054.png)
![leon](https://cloud.githubusercontent.com/assets/22629584/23883991/1e9c92fc-0838-11e7-8c1e-3bf310279e09.png)
![pajaro](https://cloud.githubusercontent.com/assets/22629584/23883994/1ebf691c-0838-11e7-8daa-e8b00679c9fb.png)
![pantera](https://cloud.githubusercontent.com/assets/22629584/23883995/1ec44dd8-0838-11e7-953f-f22215ce1b75.png)
