### ISSUE TITLE
4.2.5 consolidación archivos originales personajes malos

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#194]
**Descripción**
Consolidar archivos originales realizados por TROMPO de los personajes malos, para ponerlos en el juego.

**Comment by ivandav** [comment]
PERSONAJES EN CUADRO PARA UTILIZAR EN JUEGO
Tiempo estimado: 1 hora y 30 minutos
![abejas](https://cloud.githubusercontent.com/assets/22629584/23885759/63fb3ac8-0843-11e7-9434-cea202d35e8d.png)
![babuino](https://cloud.githubusercontent.com/assets/22629584/23885757/63f7f05c-0843-11e7-89f7-56383c00230e.png)
![buitre](https://cloud.githubusercontent.com/assets/22629584/23885756/63f7a606-0843-11e7-8933-8b46b3b67a31.png)
![burro](https://cloud.githubusercontent.com/assets/22629584/23885758/63f83dbe-0843-11e7-9b16-29d725c287f4.png)
![camaleon](https://cloud.githubusercontent.com/assets/22629584/23885755/63f77afa-0843-11e7-8645-a04b4231d60d.png)
![culebra](https://cloud.githubusercontent.com/assets/22629584/23885760/63fd6ea6-0843-11e7-87ce-bef72e552c76.png)
![hiena](https://cloud.githubusercontent.com/assets/22629584/23885761/6412bf68-0843-11e7-87ed-866a325bf057.png)
![lobo](https://cloud.githubusercontent.com/assets/22629584/23885762/641af962-0843-11e7-90d2-f25377b43f67.png)
![peresozo](https://cloud.githubusercontent.com/assets/22629584/23885763/6420d9c2-0843-11e7-809b-43d0e1f18523.png)
![rata](https://cloud.githubusercontent.com/assets/22629584/23885764/642e2dc0-0843-11e7-839c-5983627b5987.png)
![serpiente](https://cloud.githubusercontent.com/assets/22629584/23885765/6431cf84-0843-11e7-9f65-e49670ab5dab.png)

**Comment by CamilaG08** [comment]
Se reabre dado que falta Felipe Oso.

**Comment by CamilaG08** [comment]
Se requiere la imagen de Felipe Oso para el cierre del Issue y el Sprint 5. ( @ivandav  )

**Comment by ivandav** [comment]
![oso](https://cloud.githubusercontent.com/assets/22629584/24129161/9fdc2384-0dae-11e7-8f2c-262742d3d2ba.png)

**Comment by CamilaG08** [comment]
Se cierra ya que se termina la tarea correctamente.
