### ISSUE TITLE
1.1.15 Pedir y crear los escenarios de los CSU

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#196]
**Descripción**

Pedir las fotos de los CSU e integrarlos como escenarios.

**TAREAS**

- [x] Camila: Pedir fotos a Juanita o la gerente de los CSU
- [x] Dario: Integrar los escenarios caricaturizados a los ya existentes
- [x] Dario: Escoger escenarios CSU y animarlos.
- [x] Dario: Convertie escenarios a Sprites

**Comment by CamilaG08** [comment]
Se piden las fotografías a Juanita, Ismael y la gerente de los CSU, se espera el envío de dichas fotografías.

**Comment by CamilaG08** [comment]
Se adjuntan fotos de algunos CSU, pendientes para caricaturizar en el Sprint 6 por @jdma0440 .

[RE%3a_Fotos_CSU.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/851756/RE.3a_Fotos_CSU.zip)

**Comment by ghost** [comment]
## Animar escenarios CSU (Registro de tiempo: 40 minutos)

![csu1 lluvia](https://cloud.githubusercontent.com/assets/22629833/24133104/6a0c1e0c-0dc8-11e7-8199-eda5d7032e97.gif)
![csu1 nieve](https://cloud.githubusercontent.com/assets/22629833/24133108/6a342be0-0dc8-11e7-9a5d-ab384b77950f.gif)
![csu1 sol](https://cloud.githubusercontent.com/assets/22629833/24133106/6a32cb24-0dc8-11e7-8b5a-8187a24f3a3f.gif)
![csu2-lluvia](https://cloud.githubusercontent.com/assets/22629833/24133107/6a33b9da-0dc8-11e7-890d-0e9fc80fea38.gif)
![csu2-nieve](https://cloud.githubusercontent.com/assets/22629833/24133110/6a358666-0dc8-11e7-810a-be277516aee0.gif)
![csu2-sol](https://cloud.githubusercontent.com/assets/22629833/24133105/6a31eb3c-0dc8-11e7-85ac-1f7a7381eaeb.gif)
![csu3](https://cloud.githubusercontent.com/assets/22629833/24133109/6a350f92-0dc8-11e7-888c-bf386faaa6ee.gif)
![csu4-lluvia](https://cloud.githubusercontent.com/assets/22629833/24133111/6a53bd20-0dc8-11e7-913d-f4b317b5ba4d.gif)
![csu4-nieve](https://cloud.githubusercontent.com/assets/22629833/24133113/6a545c44-0dc8-11e7-9904-7446cb59fa29.gif)
![csu4-sol](https://cloud.githubusercontent.com/assets/22629833/24133112/6a541a40-0dc8-11e7-808e-9b0f4e565e80.gif)

**Comment by ghost** [comment]
## Escenarios CSU en Sprites (Registro de tiempo : 1 hora)

![csu1 nieve](https://cloud.githubusercontent.com/assets/22629833/24308424/e54dfff2-1095-11e7-9ab5-c6cba9308018.png)
![csu1lluvia](https://cloud.githubusercontent.com/assets/22629833/24308426/e5526e16-1095-11e7-92ed-3ea161525b2f.png)
![csu1sol](https://cloud.githubusercontent.com/assets/22629833/24308425/e54ff578-1095-11e7-8652-7786f8be871d.png)
![csu2 lluvia](https://cloud.githubusercontent.com/assets/22629833/24308427/e552ea26-1095-11e7-8c10-21ab7acad69b.png)
![csu2 nieve](https://cloud.githubusercontent.com/assets/22629833/24308429/e55fef0a-1095-11e7-98c2-6903b4576343.png)
![csu2 sol](https://cloud.githubusercontent.com/assets/22629833/24308428/e556b250-1095-11e7-8c91-eccdd3025d58.png)
![csu3](https://cloud.githubusercontent.com/assets/22629833/24308430/e5639ff6-1095-11e7-9927-84efe4971221.png)
![csu4lluvia](https://cloud.githubusercontent.com/assets/22629833/24308432/e569e1ea-1095-11e7-9d2d-cad078602cb3.png)
![csu4nieve](https://cloud.githubusercontent.com/assets/22629833/24308431/e568553c-1095-11e7-8026-5a32af89aa5f.png)
![csu4sol](https://cloud.githubusercontent.com/assets/22629833/24308434/e56d88cc-1095-11e7-8d45-9ef1b21c71b9.png)

**Comment by CamilaG08** [comment]
Se cierra debido a que las nuevas modificaciones y sprites de escenarios se asignarán en un nuevo issue.
