### ISSUE TITLE
1.8.2 Realizar propuesta final interacciones sociales

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#197]
**Descripción**
Realizar documento  de propuesta final sobre las interacciones sociales.

**Comment by CristianGarzonBernal** [comment]
[Interacciones sociales con Facebook.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/856875/Interacciones.sociales.con.Facebook.docx)

Tiempo registrado 5 hrs.

**Comment by CristianGarzonBernal** [comment]
Propuesta de interacción con códigos alfanuméricos.
[Códigos Alfanuméricos.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/863497/Codigos.Alfanumericos.docx)

**Comment by ingenieriadelsoftware** [comment]
- [x] Coordinar con Cristian las tareas planeadas para la ejecución de la historia. @jrsosago 

- [x] Documentar las tareas asociadas a esta historia @CristianGarzonBernal

**Comment by jrsosago** [comment]
Se deja abierto este Issue, hasta que se complete de manera correcta la tarea códigos, ya que solo está la descripción pero no como se implementa.
**Tarea a realizar**
- [x] Documentar ¿Cómo implementar los códigos alfanuméricos en el Juego Web y móvil? @CristianGarzonBernal 
**No se asignan tareas hasta que se termine está.**

**Comment by CristianGarzonBernal** [comment]
[Implementación Códigos Alfanuméricos.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/871580/Implementacion.Codigos.Alfanumericos.docx)
Tiempo Registrado 3 hrs.

**Comment by CristianGarzonBernal** [comment]
[Interacciones sociales documento final.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/871586/Interacciones.sociales.documento.final.docx)

**Comment by jrsosago** [comment]
Se cierra está Issue debido a que se completaron las actividades y el documento final es Interacciones sociales documento final. Se asigna a @gsalvarez Interacción Social con Facebook y @CristianGarzonBernal  Implementación códigos Alfanuméricos.
