### ISSUE TITLE
Ambiente de desarrollo Modulo Administración

### ISSUE THREAD

**Issue by Lakes1234** [ISWPOLI/Pacto-de-Honor#199]
**Ambiente de desarrollo Modulo Administración**

**Tareas**

- [x] Instación wordpres
- [x] Instación xammp
- [x] Instación mysql
- [x] Conexion wordpre, xammp y mysql

**Comment by rzambrano112** [comment]
Se realiza la instalación del ambiente de desarrollo para la realización de las distintas actividades del modulo de administración.

**Comment by rzambrano112** [comment]
Se realiza la instalación completa para el ambiente de desarrollo del modulo de administración.

**Comment by rzambrano112** [comment]
Se realiza una investigación sobre gestores de contenido tales como https://es.wordpress.com/
https://www.joomla.org/. Gestores que según compañeros del grupo permiten desarrollar  el modulo de administración de forma mas agradable y amena.

**Comment by rzambrano112** [comment]
Se anexa documento.
[AMBIENTE DE DESARROLLO MODULO ADMINISTRACION.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/846125/AMBIENTE.DE.DESARROLLO.MODULO.ADMINISTRACION.docx)

Tiempo empleado : 3 horas

**Comment by rzambrano112** [comment]
Se realiza primeros aportes para el diseño de los requisitos necesarios para el modulo de administración.
Requisitos que requieren primeramente una consolidación de la interfaz del modulo antes de comenzar a construirlo en joomla como gestor de archivos. En razón, a que hay que determinar exactamente que es lo que se quiere visualizar en el modulo de administración.

**Comment by rzambrano112** [comment]
Se anexa d
[MOCKUP DEL MODULO DE ADMINISTRACION.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/852357/MOCKUP.DEL.MODULO.DE.ADMINISTRACION.docx)
ocumento de implementación.

**Comment by rzambrano112** [comment]
El issue se cierra dado la implementacion de los ambientes de desarrollo en los equipos respectivos.
