### ISSUE TITLE
4.1.3 Definir perfil psicológico personajes

### ISSUE THREAD

**Issue by ghost** [ISWPOLI/Pacto-de-Honor#20]
**Descripción de personajes**
Definir comportamientos asociados a cada personaje del juego, incluyendo perfil psicológico.

**Tareas**
- [x] especificar gritos de victoria, derrota
- [x] especificar descripción del comportamiento de un personaje según su animal asignado  
- [x] Definir una personalidad a cada personaje del juego
- [x] Jaime Crear el perfil de Camilo Perezoso
- [x] Jaime Crear el perfil de Felipe Oso
- [x] Jaime Crear el perfil de Carlos Buitre
- [x] Jaime Crear el perfil de Luis Víbora
- [x] Jaime Crear el perfil de Andrés Zorro
- [x] Sebastián Crear el perfil de Nicolás Lagarto
- [x] Sebastián Crear el perfil de Víctor Hiena
- [x] Sebastián Crear el perfil de Fabián Babuino
- [x] Ricardo Crear el perfil de Juan Camaleón
- [x] Ricardo Crear el perfil de Juan Rata
- [x] Ricardo Crear el perfil de Julián Burro

- [x] Jaime Modificar el perfil de Camilo Perezoso
- [x] Jaime Modificar el perfil de Felipe Oso
- [x] Jaime Modificar el perfil de Carlos Buitre
- [x] Jaime Modificar el perfil de Luis Víbora
- [x] Jaime Modificar el perfil de Andrés Zorro
- [x] Sebastián Modificar el perfil de Nicolás Lagarto
- [x] Sebastián Modificar el perfil de Víctor Hiena
- [x] Sebastián Modificar el perfil de Fabián Babuino
- [x] Ricardo Modificar el perfil de Juan Camaleón
- [x] Ricardo Modificar el perfil de Juan Rata
- [x] Ricardo Modificar el perfil de Julián Burro

- [x] Jaime Crear el perfil de Iván Ruiseñor
- [x] Jaime Crear el perfil de Tati Hormiga
- [x] Jaime Crear el perfil de Andrés Gallo
- [x] Sebastián Crear el perfil de Fabián Canario
- [x] Sebastián Crear el perfil de Cata Cierva
- [x] Sebastián Crear el perfil de Ana Pantera
- [x] Ricardo Crear el perfil de Diana Jirafa
- [x] Ricardo Crear el perfil de Daniel León
- [x] Ricardo Crear el perfil de Pedro Ratón

- [x] Grupo: Definir la creación y crear el perfil de Ana y Sara Abeja

**Comment by ghost** [comment]
[Personajes PactoHonor.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/784598/Personajes.PactoHonor.docx)

Mis personajes fueron creados y los que ya estaban también fueron modificados

**Comment by rzambrano112** [comment]
Los personajes asignados para el desarrollo de las descripciones de las características, tipo de control  y poder ya fueron desarrollados. Entre ellos por ejemplo Diana Jirafa, Daniel Leon y Pedro Ratón entre otros.

**Comment by rzambrano112** [comment]
[Pràctica Aplicada. Personalidad de personajes.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/801448/Practica.Aplicada.Personalidad.de.personajes.docx)
Adicionalmente los personajes  Julian Burro, Juan Rata, Juan Camaleón fueron complementados en lo referente al tipo de control, poder y en algunas características de personalidad.

**Comment by CamilaG08** [comment]
Chicos, las modificaciones y los nuevos personajes, por favor subirlas por este medio

**Comment by jdbernalv** [comment]
Se crean los siguientes personajes
- Camilo Perezoso, Felipe Oso, Carlos Buitre, Luis Vibora, Andres Zorro, Ivan Ruiseñor, Tati Hormiga y Andres Gallo
Tambien se encuentran todas las modificaciones exigidas por el grupo puntualmente sobre mis personajes.
[Entrega Jaime Bernal - Practica Aplicada.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/785056/Entrega.Jaime.Bernal.-.Practica.Aplicada.pdf)
.

**Comment by jdbernalv** [comment]
Se unifica la información de los personajes para realizar la entrega final. Se anexa entrega final.
Juan Sebastian Rodriguez, Ricardo Zambrano y Jaime Bernal.
[2. Entrega Subgrupo - Practica Aplicada.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/785057/2.Entrega.Subgrupo.-.Practica.Aplicada.docx)

**Comment by jdbernalv** [comment]
(Actualización) Se anexa documento final de Comportamientos de Personajes.
 - Se realiza la creación del personaje Ana y Sara Abeja
 - Se realiza la modificación de todos los poderes de cada personaje.
 - Se realiza la revisión del documento completo y se ajustan contenidos y distribución de información    en el archivo. 2 Horas
[2. Entrega Subgrupo - Practica Aplicada.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/786608/2.Entrega.Subgrupo.-.Practica.Aplicada.pdf)
