### ISSUE TITLE
Diccionario de Datos para la BD

### ISSUE THREAD

**Issue by juancelemin** [ISWPOLI/Pacto-de-Honor#200]
- [ ] se requiere definir un diccionario para los campos de la BD

- [x] se requiere que para cada campo se especifique su  tipor de dato, descripcion

**Comment by juancelemin** [comment]
Primera parte del diccionario 
[Formato_Dicionario_Datos y Servicios.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/846352/Formato_Dicionario_Datos.y.Servicios.docx)

**Comment by alexsabsan** [comment]
[Formato_Dicionario_Datos.y.Servicios.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/874113/Formato_Dicionario_Datos.y.Servicios.docx)
Cargue de la versión 0.2 de Diccionario de datos

**Comment by alexsabsan** [comment]
Quedo a al espera de comentarios y/o Correciones pertinentes

**Comment by wpradere** [comment]
Issue cerrado por redefinicion del tablero
