### ISSUE TITLE
sonidos de Ambientacion

### ISSUE THREAD

**Issue by juancelemin** [ISWPOLI/Pacto-de-Honor#201]
Descripción

Proponer los sonidos correspondientes para  los jefes y sonidos de abientacion

**Comment by jolarter** [comment]
Debes mostrarnos como reproducir sonidos y cuales serían los sonidos candidatos para diversas acciones en el juego. cc @DiegOliveros 
- [x] Presentación como reproducir sonidos
- [x] Propuesta de sonidos

**Comment by juancelemin** [comment]
[sonidos con phaser.pptx](https://github.com/ISWPOLI/Pacto-de-Honor/files/852086/sonidos.con.phaser.pptx)
Los sonidos y presentacion se adjunta en: Trabajo 7 (6h) Reporte 5 Viernes 17 de marzo ( moodlep)
por motivos de que no soporta las extenciones
