### ISSUE TITLE
1.3.6 Implementación de la sección de créditos

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#203]
**Descripción**

Implementar la sección de créditos.

**TAREAS**

- [x] Recibir los textos e información sobre Pacto de Honor de @Jdbernalv94 
- [x] Complementar con información que tenga @KmiArthur 
- [x] Implementar la sección de créditos
- [x] Unir la sección de créditos funcional al mapa de navegación

**Comment by gabogabbs** [comment]
Textos e información del Pacto de Honor descargados desde el issue #155 a cargo de @Jdbernalv94

**Comment by gabogabbs** [comment]
Se realizan las tareas asignadas en el issue.
Falta corregir el despliegue de los Tipos de Plagio. (Tiempo estimado de corrección: 30 minutos)
[Pacto de Honor.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/852130/Pacto.de.Honor.zip)

REGISTRO DE TIEMPO DE LA SECCION DE CREDITOS: 6 HORAS Y 30 MINUTOS.

**Comment by CamilaG08** [comment]
Se requieren las modificaciones para cerrar el Issue. ( @gsalvarez  )

**Comment by gabogabbs** [comment]
Se corrige el despliegue de información de los tipos de plagio en la sección de créditos del juego. Por lo tanto, se da como finalizado el issue. [CorreccionSeccionCreditos.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/853880/CorreccionSeccionCreditos.zip)

REGISTRO DE TIEMPO: 1 HORA.

**Comment by CamilaG08** [comment]
Se cierra debido a que se entrega la tarea correctamente.
