### ISSUE TITLE
4.2.6 Investigar sobre animaciones en Phaser

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#204]
**Descripción**

Investigar y plantear implementaciones de cierta animación de Phaser para los jefes finales.

**TAREAS**

- [x] Pedir página de la animación "Creature Dragon" de Phaser a @gsalvarez 
- [x] Investigar sobre dicha animación
- [x] Documento con propuestas para la implementación de dicha animación

**Comment by gabogabbs** [comment]
En la página de ejemplos de Phaser se encuentran varios tipos de animaciones.
https://phaser.io/examples/v2/category/animation

**Comment by CamilaG08** [comment]
Se requiere el documento para dar cierre al Issue y al Sprint 5. ( @dayepesb  )

**Comment by dayepesb** [comment]
[Reporte animaciones phaser.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/863269/Reporte.animaciones.phaser.docx)

Se hace el análisis y recomendaciones sobre el trabajo en animaciones de phaser
