### ISSUE TITLE
2.3 Propuesta para jugar con los malos

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#206]
**Descripción**

Realizar un documento detallado en el cual se muestre una propuesta sólida para jugar con los personajes malos.

- [x] Revisar la dinámica del juego
- [x] Detallar todos los componentes que se pueden afectar
- [x] Realizar un análisis de riesgos completo
- [x] Reglas y límites del juego (aumento de poderes y niveles)
- [x] Presentar la propuesta al grupo

**Comment by CamilaG08** [comment]
Se requiere el documento ya que es necesario cerrar la tarea y el Sprint 5. ( @Jdbernalv94  )

**Comment by jdbernalv** [comment]
Se realiza la entrega del documento expuesto el día Sábado 18 de Mayo para el cierre de la tarea y finalización del Sprint 5.
Mil disculpas por la demora pero por descuido olvide subirlo ese mismo día.
[2.3 Propuesta para jugar con los malos. #206.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/856540/2.3.Propuesta.para.jugar.con.los.malos.206.pdf)

**Comment by CamilaG08** [comment]
Se cierra el Issue pero queda la propuesta para ser considerada a partir del Sprint 9.
