### ISSUE TITLE
1.2 Poblar Base de Datos

### ISSUE THREAD

**Issue by zergiozerna81** [ISWPOLI/Pacto-de-Honor#208]
Realizar ingreso de datos en la BD de forma masiva de acuerdoa modelo BD definido y validado en el issue #157 y #153

- [x] Detallar información a cargar en la BD

- [x] Poblar BD

- [x] Subir Script de cargue de datos

- [x] Probar que el script cargue la información de forma correcta

**Comment by zergiozerna81** [comment]
Se define información preliminar a cargar en la BD
[bd_practica.xlsx](https://github.com/ISWPOLI/Pacto-de-Honor/files/846500/bd_practica.xlsx)

**Comment by zergiozerna81** [comment]
Tiempo empleado: 3 horas

Se ingresan datos a la BD en las siguientes tablas con información de personajes, poderes, frases, las categorías de personajes entre otros.

Se sube Script de BD con esta información y se prueba que cargue corrrectamente y sin errores.

[PactoHonor_v1.0.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/860290/PactoHonor_v1.0.txt

**Comment by zergiozerna81** [comment]
Se llenó la tabla de frases de todos los personajes principales (héroes y jefes) y se generó el script de esta tabla, incluyéndolo en el script de la DB.

En reunión con Camila se aclaró la siguiente información:
•	En el issue #38 se encuentra la información de los escudos.
•	Se aclara duda sobre el poder de plagio de Felipe el Oso.
•	La información de puntos de daño de los poderes se encuentra en el issue #113.
•	Se solicita las imágenes consolidadas que deben ir referenciadas en la BD, me indica que se encuentra en proceso.
•	Se solicita la información de las preguntas y respuestas de las pruebas psicotécnicas, me informa que se encuentra en proceso.
•	Me informa que en el mundo correspondiente a Ana y Sara Abeja serán 6 niveles, para un total de 61 niveles en el juego.
•	Los personajes Daniel León y Pedro ratón van a estar separados, utilizando los mismos poderes y frases.

Se adjunta Script con el llenado de la tabla frase.

[PactoHonor_v1.0.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/863493/PactoHonor_v1.0.txt)

**Comment by ingenieriadelsoftware** [comment]
- [ ] Subir archivos al repositorio mediante commit y haciendo referencia a la historia (no como comentario) @zergiozerna81

**Comment by zergiozerna81** [comment]
Tiempo empleado: 3 horas.

- Se instala Github para escritorio de windows.
- Se descarga de la página web del DANE la lista de las ciudades y municipios de Colombia en Excel y se genera el script de cargue de la tabla ciudad y se agrega un registro genérico para el caso de usuarios que vivan en el exterior del país.
- Se recopila en un archivo de Excel la información de los mundos y se genera el script de cargue de la tabla mundo.
- Se recopila en un archivo de Excel la información de los niveles y se genera el script de cargue de la tabla nivel.

[Tablas BD.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/869692/Tablas.BD.zip)

[PactoHonor_v1.0.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/869686/PactoHonor_v1.0.txt)
