### ISSUE TITLE
4.1.5 Implementación compra de personajes

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#209]
**Descripción**
Implementar compra de personajes en el juego, con monedas ganadas por el jugador durante el transcurso del mismo.

**Comment by CamilaG08** [comment]
Se sube un documento de adelanto, el cual queda pendiente ya que para obtener las monedas necesarias, habría que modificar las recompensas de los logros.

[Lineamientos para la compra de personajes.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/860071/Lineamientos.para.la.compra.de.personajes.docx)

Tiempo empleado: 20 minutos

**Comment by CamilaG08** [comment]
Se modifica el archivo de logros:

[Logros.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/869714/Logros.docx)

**Comment by CamilaG08** [comment]
Se reponen las 2 horas faltantes con:

1. Modificación del archivo de logros (Por segunda vez)
2. Modificación del archivo de recompensas
3. Creación de la sección de compra de personajes

[LogrosV3.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/877953/LogrosV3.docx)

[Lineamientos para la compra de personajes.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/877955/Lineamientos.para.la.compra.de.personajes.docx)

[Compra personajes.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/877962/Compra.personajes.zip)

**TAREAS PENDIENTES**

- [x] Habilitar las monedas en el juego (Algoritmo)
- [x] Crear sprite de la imagen de monedas
- [x] Integrar el sprite de monedas al mapa de navegación
- [x] Crear el sprite del label de "Comprado"
- [x] Agregar al algoritmo que identifique cuando un personaje ya fue comprado
- [x] Integrar al algoritmo que aumente las recompensas correspondientes (datos que se envían a la base de datos)

**Debido a la cantidad de tareas faltantes, se mueve al Sprint 8**

**En la reunión de cierre del Sprint 7 se propone mejorar la propuesta de compra de personajes y el uso de las monedas, y se da prioridad a la construcción de dicho documento**

**Comment by CamilaG08** [comment]
Imagen de monedas: 

![monedas](https://cloud.githubusercontent.com/assets/22283896/24687586/0f1df128-1980-11e7-9835-88fb9d2b76dd.jpg)


La implementación en el mapa de navegación que a cargo de @gsalvarez

**Comment by CamilaG08** [comment]
Sprite label de comprado:

![spritebuttonb](https://cloud.githubusercontent.com/assets/22283896/24689332/5fed684e-198b-11e7-91bc-ddc7b54bd1db.png)

**Comment by CamilaG08** [comment]
Se tiene una nueva versión de la compra de personajes, siendo faltante cambiar el botón de comprar por comprado en caso de ser necesario y la comunicación con el servicio para actualizar datos.

No se sube al repositorio aún debido a lo faltante.

**TIEMPO EMPLEADO: 2 horas y 30 minutos**

[Compra personajes.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/895316/Compra.personajes.zip)

**Comment by CamilaG08** [comment]
Con ayuda de @jdma0440 se realizan los cambios del módulo y queda restante realizar la verificación del funcionamiento.

**Tiempo empleado: 30 minutos**

[Compra personajes 2.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/901293/Compra.personajes.2.zip)

**Comment by CamilaG08** [comment]
Se realizan nuevas modificaciones, pero aún falta el manejo del botón y el label.

[Compra personajes.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/907286/Compra.personajes.zip)

**Tiempo empleado: 1 hora y 30 minutos**

**Comment by CamilaG08** [comment]
**Queda como fecha final el día lunes 10 de Abril**

**Comment by CamilaG08** [comment]
Se finaliza el módulo, se le hace entrega a @gsalvarez para integración con el juego (Issue #363) y por lo tanto se cierra la tarea.

**TIEMPO EMPLEADO: 2 horas**

[Compra personajes.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/921362/Compra.personajes.zip)
