### ISSUE TITLE
1.3.7 Implementación para móviles.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#210]
**Descripción**
Implementar juego para móviles con joystick. Revisar documento que se encuentra en la Issue #195 

- [ ] Se tiene que realizar la adaptación para moviles adaptando imagenes y todas las componentes del juego.
- [ ] Se tiene que realizar la investigación de como implementar y como funciona un joystic en phaser.
- [ ] Se debe realizar la implementación de un joystic para juegos en mobiles

**Comment by dayepesb** [comment]
[ ]

**Comment by dayepesb** [comment]
Se cierra el issue dado a que se reasigna en un nuevo issue en la semana de trabajo individual @CamilaG08
