### ISSUE TITLE
5.6.3 Crear preguntas psicotécnicas.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#211]
**Descripción**
Crear prototipo de preguntas de los manuales leidos.
**Tarea a realizar** 
- [x] Escoger una de las pruebas leidas.
- [x] Lectura cuadernillo de preguntas.
- [x] Realizar prototipo preguntas.

**Comment by ghost** [comment]
Fui al laboratorio de psicología, para separar un turno de las pruebas Psicotécnicas P-IPG. El encargado del laboratorio en esa hora me dice que: Las preguntas de las pruebas que seleccione no se aplican al ejercicio de practica que estamos haciendo e insiste que nosotros somos los que debemos realizar nuestras propias preguntas y que ellos en el laboratorio harían el análisis de esas preguntas y nos darían los resultados del cuestionario que nosotros hiciéramos. Cuando le pregunte que tendríamos que tener en cuenta para que nosotros mismos hiciéramos dicho cuestionario me dice que es bueno usar la “ESCALA LIKERT”, adicional a eso que él me daría un artículo el día jueves 23 de marzo con un resumen de lo que podríamos tener en cuenta para ello.  Así que el día jueves me estarían entregando dicho artículo.

Tiempo empleado: 20 minutos.

**Comment by ghost** [comment]
Se realiza documento de la escala Likert para tener en cuenta a la hora de seleccionar las primeras preguntas para el  juego PoliFighters. 
[ESCALA LIKERT.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/863312/ESCALA.LIKERT.docx)
Tiempo empleado: 1 hora, 30 minutos.

**Comment by ghost** [comment]
- Teniendo en cuenta las características de la escala Likert, se seleccionaron 8 preguntas del (IPV)  con un ámbito general que nos dé la posibilidad de modificar para adaptarlo al juego.

- Se realizo un avance en la modificación de las preguntas para adaptarlas al juego
[Propuestas para las preguntas Psicotécnicas.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/863489/Propuestas.para.las.preguntas.Psicotecnicas.docx) 
Tiempo empleado: 1 hora.

**Comment by ingenieriadelsoftware** [comment]
- [ ] Crear la base de datos en excel de las preguntas, las posibles respuestas y las actividades desarrolladas en el juego @JuanSebastianRodriguezJ

**Comment by ingenieriadelsoftware** [comment]
- [ ] Realizar commit de la documentación sobre el repositorio

**Comment by ghost** [comment]
Documentos Finales para este issue, Preguntas Pscicotecnicas, Presentación del manual, Documento word con las preguntas seleccionadas.

[Propuestas para las preguntas Psicotécnicas.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/870090/Propuestas.para.las.preguntas.Psicotecnicas.docx)
[Preguntas Psicotecnicas.xlsx](https://github.com/ISWPOLI/Pacto-de-Honor/files/870091/Preguntas.Psicotecnicas.xlsx)
[PIPG.pptx](https://github.com/ISWPOLI/Pacto-de-Honor/files/870092/PIPG.pptx)
Tiempo empleado: 3 horas 40 minutos

**Comment by jrsosago** [comment]
Se cierra este Issue, ya que se completaron todas las tareas.
