### ISSUE TITLE
4.2.8 Creación de los poderes de los mini-personajes

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#214]
**TAREAS**

- [x] Crear logos de los poderes de los mini-personajes
- [x] Crear las imágenes de los poderes de los mini-personajes

Documento de apoyo en el Issue #165

**Comment by CamilaG08** [comment]
Queda pendiente para el cierre a más tardar el día 28 de marzo.

**Comment by KmiArthur** [comment]
## Logos e Imágenes de 48 mini personajes:
(Trabajo: 9.5h)

Debido al peso, adjunto el [link de G Drive](https://drive.google.com/drive/folders/0B0eNk39asXpSam1xejV5bEZwZ3M?usp=sharing)
