### ISSUE TITLE
1.1.9 Implementar animaciones de Phaser

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#216]
- [x] Implementar los 12 personajes malos en phaser.
- [x] Modificar sprites de visualización de poderes para que desaparezcan al ser usados.

**Comment by ghost** [comment]
## Implementación de 6 personajes malos en phaser (Registro de tiempo: 4 horas)
### Se implementaron: las dos avispas, babuino, camaleon, rata y burro

https://drive.google.com/open?id=0B8ttTD0H6QRCLVhlUXBWZExiVVE

**Comment by ghost** [comment]
## Sprites modificados con frames transparentes (Registro de Tiempo: 1 hora)

![cloning](https://cloud.githubusercontent.com/assets/22629833/24233939/59eeb2ea-0f63-11e7-98a4-45e2d7c842ac.png)
![cope](https://cloud.githubusercontent.com/assets/22629833/24233941/59f50d0c-0f63-11e7-9bcb-a5ef8828a648.png)
![error404](https://cloud.githubusercontent.com/assets/22629833/24233942/59f530a2-0f63-11e7-8f2f-78e2bb095184.png)
![hybrid](https://cloud.githubusercontent.com/assets/22629833/24233940/59f41e88-0f63-11e7-9395-2bfb1a0c9a61.png)
![mosaic](https://cloud.githubusercontent.com/assets/22629833/24233943/59f5c5b2-0f63-11e7-8715-3e23b4c8c564.png)
![powerlion](https://cloud.githubusercontent.com/assets/22629833/24233944/59f70aa8-0f63-11e7-9c84-b55251659f94.png)
![recycling](https://cloud.githubusercontent.com/assets/22629833/24233945/59fe5ae2-0f63-11e7-9076-bc6c809d1f80.png)
![remix](https://cloud.githubusercontent.com/assets/22629833/24233946/5a04dd72-0f63-11e7-8c82-6d041c849c95.png)
![rss](https://cloud.githubusercontent.com/assets/22629833/24233948/5a06d6c2-0f63-11e7-8ad0-57de283f4d58.png)
![search](https://cloud.githubusercontent.com/assets/22629833/24233947/5a05be0e-0f63-11e7-8152-c20edbae27ec.png)

**Comment by ghost** [comment]
Se habla con el profesor Diego Oliveros y se decide que no se usara animaciones en phaser, ya que esto toma mucho tiempo, por lo tanto se decide que se seguira manejando en forma de sprites. Por lo tanto, esta Issue queda asi, y se cierra.

Se me reasigna una nueva tarea la cual consiste en crear ids para los botones de la selección de personajes, y pasarlos entre script.

Quedo pendiente de que @CamilaG08 cree la nueva Issue.
