### ISSUE TITLE
1.10 Modificación del portal

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#217]
**Descripción**

- [x] Modificar el portal web según las correcciones de clase.

**Comment by KmiArthur** [comment]
### Actualización de página con correcciones de objetivo y actualización de fotos (Trabajo 1H):
[pactodehonor.co.nf](http://pactodehonor.co.nf)

### Propuesta **nuevo logo** (Trabajo 2H):
![logo juego - nombre](https://cloud.githubusercontent.com/assets/17441569/24206994/d344030a-0eed-11e7-8cf5-af21b6e6de6f.png)
![logo juego](https://cloud.githubusercontent.com/assets/17441569/24206997/d5712efa-0eed-11e7-9510-fa56e8ff07df.png)

**Comment by KmiArthur** [comment]
Se cierra porque se cumplió con las tareas asignadas 👍
