### ISSUE TITLE
1.4.6 Documentación sobre los costos de publicación

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#218]
**TAREAS**

- [x] Revisar costos y procedimientos para publicar el juego en Play Store 
- [x] Revisar costos y procedimientos para publicar el juego en IOS
- [x] Realizar un documento consolidando esa información

**Comment by jdbernalv** [comment]
Se realiza la entrega de manera satisfactoria con el documento completo del procedimiento y costo para publicar publicaciones en APP STORE y PLAY STORE (Se realiza una explicación detallada para cumplir adecuadamente con lo solicitado).
[1.4.6 Documentación sobre los costos de publicación #218.docx.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/869687/1.4.6.Documentacion.sobre.los.costos.de.publicacion.218.docx.pdf)

**Comment by CamilaG08** [comment]
Se cierra el Issue debido a que se entrega la tarea correctamente y se tienen en cuenta los costos presentados para ser expuestos en la reunión con el Vicerrector.
