### ISSUE TITLE
1.2.10 Perfil del jugador funcional

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#219]
**Descripción**

Terminar el perfil del jugador totalmente funcional.

**TAREAS**

- [x] Realizar sección para nickname del jugador con la foto de sus personaje inicial y nivel del jugador
- [x] Realizar sección con los personajes desbloqueados
- [x] Realizar sección con poderes del personaje inicial
- [x] Realizar sección con los jefes derrotados
- [x] Integrar con la sección de logros modificada

Issue de referencia: #37

**Comment by juankrlos08** [comment]
Se generan algunas imágenes para el uso de unos scrolls que son necesarios en el perfil del usuario,  se usa código fuente de scrolls realizados para implementar en el perfil del jugador donde se mostraran los poderes, personajes, jefes y a su vez se conectara con el perfil del jugador en cuanto logros se refiere.

**Comment by CamilaG08** [comment]
Se alarga al Sprint 7 y se pone como fecha límite el viernes 31 de marzo.

**TAREAS**
- [x] Botón de logros
- [x] Botón de códigos
- [ ] Cambiar "nivel" por "escenario"

**Comment by juankrlos08** [comment]
Se socializa para generar los cambios y se dispone a realizar los cambios indicados

**Comment by juankrlos08** [comment]
[miercoles 29.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/880897/miercoles.29.pdf)

**Comment by juankrlos08** [comment]
falta implementar los botones funcionales para el paso a logros.

**Comment by juankrlos08** [comment]
https://drive.google.com/file/d/0B7wkwzWIslrpLS11MnBBTG5IMFE/view?usp=sharing

**Comment by juankrlos08** [comment]
se adjunta enlance del desarrollo del perfil con scroll de imagenes nickname imagenes de personajes

**Comment by CamilaG08** [comment]
La tarea se cierra ya que se pasa a etapa de revisión  en caso de haber modificaciones, se asignarán en un nuevo  Issue.
