### ISSUE TITLE
7.1 Login funcional modificado

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#220]
**Descripción**

Modificar el login según las características planteadas por el grupo de backend:

- Uso de JPA @Basespoli
- Uso de Java Enterprise Edition @Basespoli
- Servidor: Glassfish @Basespoli
- Uso de JSP @ivandav 

**TAREAS**

- [x] Identificar campos del formulario de login @Basespoli
- [x] Realizar el login con JPA @Basespoli
- [x] Modificar la vista con bases al manual de diseño. Ref: #167  @Basespoli

**Comment by ghost** [comment]
Se aplica ajustes según manual de Diseño y se sube al repositorio.

https://github.com/ISWPOLI/Pacto-de-Honor/blob/master/FRONTEND/css/versionWeb/main2.css

**Comment by ghost** [comment]
Se hace la conexión de base de datos con JPA con servidor Glassfish en Java Enterprise Edition con NetBeans.

https://github.com/ISWPOLI/Pacto-de-Honor/tree/master/FRONTEND/src/java/Contolador

**Comment by ghost** [comment]
Se realizo investigación adicional de 2 hora ya que no se tenían conocimientos en:
Uso de JPA 
Uso de Java Enterprise Edition 
Servidor: Glassfish 
Uso de JSP 

Desde el día domingo hasta el día miércoles 22 para poder afianzar los conocimientos en estas herramientas por parte de mi compañero Iván y mía.

**Comment by ghost** [comment]
Se realiza una charla con los product Owner Yeimy y juan camilo donde se definieron algunos de los campos del formulario, para poder definir algunos de los servicios que se van a persistir en la base.

**Comment by CamilaG08** [comment]
Se corre al Sprint 7, siendo el 31 de marzo la fecha límite de entrega, en caso de que salgan modificaciones después de esa fecha, se mantiene abierto el Issue pero ya no se mueve de Sprint por lo tanto no se asignará nueva tarea hasta que esta finalice.

**Cada tarea individual que se asigne debe estar creada en esta Issue con el responsable mencionado para registro en el burndownchart**

**Comment by CamilaG08** [comment]
Debido a que se asigna una persona más a esta tarea, se pone como fecha de entrega el viernes 7 de abril, por lo cual pertenece al Sprint 8. Y queda @Basespoli como el responsable de la creación y asignación de responsable de las tareas en este Issue.

Tener en cuenta el Issue #229 y el #278 que dependen del login, por lo tanto dependen de este Issue para completarse.

**Comment by ghost** [comment]
Como se realzo la asignación de el nuevo integrante Camilla, se hace una sub-división de tareas donde:

- [ ] Implementar código de facebook en el proyecto actual con el marco de trabajo @ivandav 

- [ ] Realizar pruebas funcionales sobre versión de código para poder detectar que excepciones se deben controlar en la persistencia de datos y su control @CamilaG08 

- [x] Realizar pruebas ambiente de desarrollo sobre el servidor con la versión actual de código para poder determinar las excepciones y como controlarlas. @CamilaG08 

- [x]  Identificar campos del formulario de login @Basespoli

- [x]  Realizar el conexión login con JPA @Basespoli

- [x] Conexión con servidor GlassFish @Basespoli

- [x] Crear los JSP @ivandav @CamilaG08 @Basespoli

- [x] Creación de JavaBeans  @Basespoli

- [x] Creación de Servlet JSP login @Basespoli 

- [x] Creación de Servlet JSP Registro @Basespoli  

- [x] Creación de Servlet JSP olvido clave @ivandav 

- [x] Verificar la persistencia @Basespoli

- [ ] Realizar el modelo de relación de clases @CamilaG08 

- [x]  Modificar la vista con bases al manual de diseño. Ref: #167 @Basespoli

**Comment by CamilaG08** [comment]
Las pruebas de despliegue no se realizan aún, ya que no se posee un despliegue automatizado o un prototipo funcional, esta acción es tomada como resultado de una reunión con @DiegOliveros

**Comment by CamilaG08** [comment]
Se sube el Servlet del formulario de registro, se modifica también el archivo RegistroLogin.java.

**Se envía el archivo a @Basespoli para revisión con el proyecto**

**TIEMPO EMPLEADO: 1 hora**

[Documents.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/907233/Documents.zip)

**Comment by ghost** [comment]
Se verifica todo el funcionamiento de la autenticación en la  parte registro donde el usuario ya se registra con éxito, se determina que no pueden  estar campos vacios, o informacion faltante se le notifica al usuario mediante pop up en forma de mobil para que no se tenga problema si la aplicación se presenta en android o otra plataforma, se realizan las prueba de funcionamiento correspondiente se sube la nueva versión al repositorio.

**Comment by ivandav** [comment]
# Creación del servlet de olvido de clave

[forgotServlet.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/924066/forgotServlet.txt)
[sendMail.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/924065/sendMail.txt)

   - Se modifica el servlet que ya se había entregado.
   - Se crea una nueva clase en la cual se hacen los envíos de correo con su respectivo asunto y mensaje.
   - Se crea un correo de Gmail para los envíos de estos correos.
   - Correo: polifighters@gmail.com 
   - Contraseña: juego123poli

**Comment by DiegOliveros** [comment]
Esta issue no registra actividad el día miércoles 26 de abril por parte de @Basespoli

**Comment by ghost** [comment]
El dia miercoles 26 de abril se asiste a la charla de Acreditación y en el reporte del dia se especifica el tiempo empleado, fue utilizado para terminar la parte funcional de la autentificación en el registro, mas en especifico como se inyecta un EJB para poder terminar el Login Funcional.

**Comment by ghost** [comment]
`@PersistenceContext(unitName = "PruebasPU")
    private EntityManager em;

    protected EntityManager getEntityManager() {
        return em;
    }  Registrologin rl = (Registrologin) em.createNamedQuery("Registrologin.findByEmail").setParameter("email", email).getSingleResult();`

**Comment by ghost** [comment]
Se indica que aunque se continúa con la realización de esta tarea en la parte de redes sociales, esta Issues debe ser cerrada ya que se terminó todo el trabajo puntual ya que fue entregado el registro de login funcional y probado su funcionamiento al docente de la materia.
