### ISSUE TITLE
1.5.2 Frases retadoras, de victoria y de derrota (Mundo 1 - 6)

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#221]
**Descripción**

Realizar las imágenes de frases retadoras que son al inicio de cada mundo y las frases de victoria o derrota que aparecerían según el resultado de la batalla final.

**TAREAS**

- [x] Revisar el documento que contiene las frases

- [x] Crear la imagen de la frase retadora de Andrés Zorro
- [x] Crear la imagen de la frase de victoria de Andrés Zorro
- [x] Crear la imagen de la frase de derrota de Andrés Zorro

- [x] Crear la imagen de la frase retadora de Felipe Oso
- [x] Crear la imagen de la frase de victoria de Felipe Oso
- [x] Crear la imagen de la frase retadora de Felipe Oso

- [x] Crear la imagen de la frase retadora de Camilo Perezoso
- [x] Crear la imagen de la frase de victoria de Camilo Perezoso
- [x] Crear la imagen de la frase retadora de Camilo Perezoso

- [x] Crear la imagen de la frase retadora de Julián Burro
- [x] Crear la imagen de la frase de victoria de Julián Burro
- [x] Crear la imagen de la frase retadora de Julián Burro

- [x] Crear la imagen de la frase retadora de Juan Camaleón
- [x] Crear la imagen de la frase de victoria de Juan Camaleón
- [x] Crear la imagen de la frase retadora de Juan Camaleón

- [x] Crear la imagen de la frase retadora de Ana y Sara Abeja
- [x] Crear la imagen de la frase de victoria de Ana y Sara Abeja
- [x] Crear la imagen de la frase retadora de Ana y Sara Abeja

**Documento de referencia**

[Consolidación de personajes.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/853001/Consolidacion.de.personajes.docx)

**Comment by juancelemin** [comment]
![abeja_ ganadora](https://cloud.githubusercontent.com/assets/17105514/24318596/3bd98e5a-10d6-11e7-9e57-c112720a0277.png)
![abejas_perdedoras](https://cloud.githubusercontent.com/assets/17105514/24318602/3bfcebac-10d6-11e7-93f3-dc9bb26a651b.png)
![abejas_retadoras](https://cloud.githubusercontent.com/assets/17105514/24318599/3bfa34f2-10d6-11e7-882a-7cbf7e8ce822.png)
![burro_ganador](https://cloud.githubusercontent.com/assets/17105514/24318601/3bfb8316-10d6-11e7-97fa-decac7d6f256.png)
![burro_perdedor](https://cloud.githubusercontent.com/assets/17105514/24318598/3bf9de6c-10d6-11e7-8455-16b144e1c2e5.png)
![burro_retador](https://cloud.githubusercontent.com/assets/17105514/24318600/3bfae456-10d6-11e7-96fd-680025527f7f.png)
![camaleon_derrotado](https://cloud.githubusercontent.com/assets/17105514/24318597/3beb72c8-10d6-11e7-9c4d-6af60c1fe9e3.png)
![camaleon_ganador](https://cloud.githubusercontent.com/assets/17105514/24318603/3bfd45de-10d6-11e7-8019-4940d70ada8a.png)
![camaleon_retador](https://cloud.githubusercontent.com/assets/17105514/24318604/3c0ec598-10d6-11e7-95b8-3adb87ffdab9.png)
![oso_ganador](https://cloud.githubusercontent.com/assets/17105514/24318609/3c0dffc8-10d6-11e7-9d86-cf5954f4c5b1.png)
![oso_perdedor](https://cloud.githubusercontent.com/assets/17105514/24318607/3c0f623c-10d6-11e7-8238-c91d9f6dba0c.png)
![perezoso_ganador](https://cloud.githubusercontent.com/assets/17105514/24318608/3c0f5ff8-10d6-11e7-8523-d04b833e8315.png)
![perezoso_perdedor](https://cloud.githubusercontent.com/assets/17105514/24318606/3c0f37e4-10d6-11e7-9e7c-5232c9251bfa.png)
![perezoso_retador](https://cloud.githubusercontent.com/assets/17105514/24318605/3c0f0f3a-10d6-11e7-9970-5fd9d14ccb77.png)
![zorro_ganador](https://cloud.githubusercontent.com/assets/17105514/24318611/3c21aeba-10d6-11e7-9f37-600a3babe655.png)
![zorro_perdedor](https://cloud.githubusercontent.com/assets/17105514/24318612/3c21a79e-10d6-11e7-848e-8107846e4010.png)
![zorro_retador](https://cloud.githubusercontent.com/assets/17105514/24318610/3c211c70-10d6-11e7-9a68-bcdfbe18c216.png)

**Comment by juancelemin** [comment]
![burro_retador](https://cloud.githubusercontent.com/assets/17105514/24318621/6ff42b32-10d6-11e7-8e94-6b3323c89bb1.png)
![camaleon_derrotado](https://cloud.githubusercontent.com/assets/17105514/24318622/6ff591b6-10d6-11e7-89ac-0e5ac0e5c861.png)
![camaleon_ganador](https://cloud.githubusercontent.com/assets/17105514/24318620/6ff3cb88-10d6-11e7-86e4-e418f14592dc.png)
![camaleon_retador](https://cloud.githubusercontent.com/assets/17105514/24318626/70109f74-10d6-11e7-99e4-123084bdac66.png)
![oso_ganador](https://cloud.githubusercontent.com/assets/17105514/24318628/70138aae-10d6-11e7-9a51-df26052c60f2.png)
![oso_perdedor](https://cloud.githubusercontent.com/assets/17105514/24318627/701385ae-10d6-11e7-8726-ab90ecfa6b34.png)
![perezoso_ganador](https://cloud.githubusercontent.com/assets/17105514/24318623/700603b6-10d6-11e7-8d52-7923ea7131e0.png)
![perezoso_perdedor](https://cloud.githubusercontent.com/assets/17105514/24318625/7009af8e-10d6-11e7-8dfd-07697d6627db.png)
![perezoso_retador](https://cloud.githubusercontent.com/assets/17105514/24318624/700870b0-10d6-11e7-924c-08681aae1cb1.png)
![zorro_ganador](https://cloud.githubusercontent.com/assets/17105514/24318629/7017ab52-10d6-11e7-9234-35b8325133b2.png)
![zorro_perdedor](https://cloud.githubusercontent.com/assets/17105514/24318630/70198152-10d6-11e7-9a61-1207b3adca0e.png)
![zorro_retador](https://cloud.githubusercontent.com/assets/17105514/24318631/701a0186-10d6-11e7-92b3-7959999e00bc.png)
![oso_retador](https://cloud.githubusercontent.com/assets/17105514/24318632/70222da2-10d6-11e7-9fe6-bf323ea1dd87.png)
![abeja_ ganadora](https://cloud.githubusercontent.com/assets/17105514/24318633/70239ade-10d6-11e7-8335-0f0d75a845d4.png)
![abejas_perdedoras](https://cloud.githubusercontent.com/assets/17105514/24318634/70247bf2-10d6-11e7-9762-ace25ffb0a6d.png)
![abejas_retadoras](https://cloud.githubusercontent.com/assets/17105514/24318635/7028390e-10d6-11e7-884a-62f33a659921.png)
![burro_ganador](https://cloud.githubusercontent.com/assets/17105514/24318637/702c5138-10d6-11e7-832a-1c0958c0eb60.png)
![burro_perdedor](https://cloud.githubusercontent.com/assets/17105514/24318636/702aa18a-10d6-11e7-99bd-6f07e0dd2173.png)

**Comment by CamilaG08** [comment]
Se cierra la tarea ya que se cumple a cabalidad y queda pendiente la asignación de un nuevo Issue.
