### ISSUE TITLE
8.1 Instalación Servidor - Sede principal POLI

### ISSUE THREAD

**Issue by manuk160** [ISWPOLI/Pacto-de-Honor#224]
Se instalara centos 7 de acuerdo la reunión sostenida con el profesor Alexis Rojas y se realizara todo el proceso de instalación, configuracion, pruebas y puesta en marcha.

- [x] Descargar la versión de Centos 7 a instalar

- [x] Realizar el proceso de pruebas en maquina virtual

- [x] Agendar proceso de instalación con el profesor Alexis Rojas

- [x] Realizar el proceso de instalación de Sistema Operativo servidor Politecnico

- [x] Realizar el proceso de instalación de Glassfish aplicaciones 1

- [x] Realizar el proceso de instalación de Apache servidor aplicaciones 2

- [x] Realizar el proceso de instalación de Mysql servidor Base Datos

- [x] Realizar el proceso de instalación de Apache Cordoba servidor Politecnico

 - [x] Realizar  el proceso de instalación de Glassfish para procesos de prueba "deploy" de war para servicios rest.

- [x] Instalación de base de datos para pruebas de servicios rest.

- [x] Validar conectividad a nivel interno y externo a servidor glassfish a base de datos.

- [x] Realizar las pruebas de funcionalidad de un servicio rest ( CRUD ).

- [x] Validar conectividad a nivel interno y externo.

**Comment by manuk160** [comment]
1.  Fue descargada la versión CentOS-7-x86_64-DVD-1611 y quemados los medios de instalación. 

2. Se realizara la prueba de instalación en maquina virtual el día 22 de marzo de 2017 con el objetivo de tener la documentación y paquetes requeridos para el día sábado 25 de marzo.

**Comment by manuk160** [comment]
Fue agendado el proceso de instalación de sistema operativo para el día sábado 25 de marzo de 2017 a partir de las 8:00 am

**Comment by manuk160** [comment]
Se realiza proceso de instalación de servidor de pruebas en maquina virtual sobre vmware 12 para escritorio.

Se realizara las siguientes actividades de instalación de acuerdo a la programacion. 

![img6](https://cloud.githubusercontent.com/assets/25807878/24228525/d152890e-0f42-11e7-8aad-e3f6d96ae34d.PNG)

**Comment by ingenieriadelsoftware** [comment]
- [x] Definir quién realiza cada una de las actividades listadas, en principio estas actividades están cargadas a manuel @manuk160 

- [x] Revisar qué actividades de esta historia le pertenecen. Separar las historias de manera que solo tengan un responsable o esten claramente definido quién hace qué @DanteVDrako

**Comment by DanteVDrako** [comment]
Se eligen tareas para ser realizadas por mi.

 - [x] Realizar  el proceso de instalación de Glassfish para procesos de prueba "deploy" de war para servicios rest.

- [x] Instalación de base de datos para pruebas de servicios rest.

- [x] Validar conectividad a nivel interno y externo a servidor glassfish a base de datos.

- [x] Realizar las pruebas de funcionalidad de un servicio rest ( CRUD ).

- [x] Validar conectividad a nivel interno y externo.

Modulo de pruebas en Issue 8.1.1

**Comment by manuk160** [comment]
Tareas seleccionadas para @manuk160

 - [x] Descargar la versión de Centos 7 a instalar

- [x]  Realizar el proceso de pruebas en maquina virtual

- [x] Agendar  proceso de instalación con el profesor Alexis Rojas

- [x]  Realizar el proceso de instalación de Sistema Operativo servidor Politecnico

- [x]  Realizar el proceso de instalación de Glassfish aplicaciones 1

 - [x] Realizar el proceso de instalación de Apache servidor aplicaciones 2

 - [x] Realizar el proceso de instalación de Mysql servidor Base Datos

- [x] Realizar  el proceso de instalación de Apache Cordoba servidor Politecnico

**Comment by manuk160** [comment]
Se realiza el proceso de instalación de servidores en el centro de datos de la universidad.

![img_20170421_113101](https://cloud.githubusercontent.com/assets/25807878/25297699/25acb158-26b5-11e7-9d81-670a11765c41.jpg)
![img_20170421_113106](https://cloud.githubusercontent.com/assets/25807878/25297700/25ad2a66-26b5-11e7-9cac-ca852b8d104c.jpg)
![img_20170421_122538](https://cloud.githubusercontent.com/assets/25807878/25297701/25ad25f2-26b5-11e7-81ad-072dd39ed763.jpg)
![img_20170421_122552](https://cloud.githubusercontent.com/assets/25807878/25297702/25ad924e-26b5-11e7-89e5-eb14e384853c.jpg)
![img_20170421_123620](https://cloud.githubusercontent.com/assets/25807878/25297703/25ad976c-26b5-11e7-87ac-720067170528.jpg)
![img_20170421_123710](https://cloud.githubusercontent.com/assets/25807878/25297704/25af97e2-26b5-11e7-8029-4de76c8798e5.jpg)
![img_20170421_123717](https://cloud.githubusercontent.com/assets/25807878/25297705/25bd6426-26b5-11e7-82c4-894fcd53687f.jpg)

**Comment by manuk160** [comment]
Se terminaron la tareas planteada y se procederá a realizar los despliegues semanales.
