### ISSUE TITLE
Documentación servicio REST Nivel

### ISSUE THREAD

**Issue by EdnaEspejo** [ISWPOLI/Pacto-de-Honor#226]
- [x] Elaboración del documento
- [x] Revisión del documento
- [x] Realizar correcciones recomendadas
- [x] Entrega para integración

**Comment by EdnaEspejo** [comment]
Se agrega primera versión para validación
[Servicio REST Nivel.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/863264/Servicio.REST.Nivel.docx)

**Comment by ingenieriadelsoftware** [comment]
@JuanCheroslan  quién realiza revisión de este documento para que esta historia se pueda cerrar?
No hay control del tiempo de ejecución sobre esta historia.

**Comment by EdnaEspejo** [comment]
Se da cierre a la tarea ya que esta se adiciona a ISWPOLI/Pacto-de-Honor#227 5.8 Documentacion Servicios REST para su unificación con lo realizado por los demas integrantes del grupo de trabajo,  de acuerdo a lo definido en la sesion del 22 de marzo.
