### ISSUE TITLE
1.3.8  Modificar el mapa de navegación-Invitar Amigos

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#229]
**TAREAS**

- [x] Crear el botón de invitar amigos
- [x] Agregar el botón de invitar amigos al mapa de navegación

**Comment by gabogabbs** [comment]
Se presenta un incoveniente, pues para hacer esta tarea, se necesita estar logueado a través de Facebook, lo cual aún no está implementado. Y además, se necesita un código que da Facebook cuando la app está montada en el servidor, que tampoco está implementada. Por lo tanto se congela el issue hasta que el Login y el servidor estén en funcionamiento.

**Comment by DiegOliveros** [comment]
@CamilaG08  favor asignar en cola esta tarea a quién tiene asignado el login

**Comment by CamilaG08** [comment]
Se cierra debido a que esta tarea depende del login, y queda asignado a las personas a cargo de dicho módulo.
