### ISSUE TITLE
Control de calidad Base de datos

### ISSUE THREAD

**Issue by manuk160** [ISWPOLI/Pacto-de-Honor#232]
Enviar los requerimientos para base de datos de acuerdo a la reunión realizada con el equipo de FRONTEND el dia 22 de marzo y el cargue de información realizado.

- [x] Enviar requerimientos FRONTEND reunion dia 22 de marzo. @jnrubiano 

- [x] Enviar requerimientos de acuerdo a cargue de base de datos. @zergiozerna81 

- [x] Realizar modificaciones requeridas en base de datos.

- [x] Generar nuevamente modelo entidad relación.

**Comment by JuanCheroslan** [comment]
tarea complementaria a la historia #231

**Comment by jnrubiano** [comment]
Hola @manuk160 

A continuación envio los cambios que se deben realizar sobre la DB de acuerdo a la reunión de Integración.

- [x] - Crear la tabla cruzada entre imagenes y personajes. Cada personaje tiene sprites, poderes, avatares.
- [x] - Ingresar los boolean para inactivar/activar los registros (POr definir las tablas que deban tener dicho elemento)

JUGADOR_TIENE_PERSONAJE

- [x] - Agregar nivel al personaje
- [x] - Agregar nivel de daño

FRASE

- [x] - Crear una relación con la imagen

Quedo atento a tus comentarios o inquietudes.

Saludos.

**Comment by zergiozerna81** [comment]
Tiempo 1 hora

De acuerdo al proceso de cargue de información en la base de datos, se requiere realizar las siguientes modificaciones a la Base de Datos:

- [ ] Incluir el atributo "tipo_frase" en la tabla "frase", corresponden a "Victoria", "Derrota" y "Reto".

- [ ] Incluir una tabla cruz entre las tablas "ciudad" y "pais".

- [ ] La tabla "poder" el atributo "tipo_poder" está definido como entero así:
       
   1 Ataque
   2 Escudo
   3 Recuperación
       
   Se debe definir si se cambia este atributo a varchar o de dejarlo como int, crear la tabla de referencia.

- [ ] El mismo caso anterior para el atributo "forma_poder" en la tabla "poder":

   1 Frontal
   2 Aéreo
   3 Tierra 

   Se debe definir si se cambia este atributo a varchar o de dejarlo como int, crear la tabla de referencia.

- [ ] El mismo caso anterior para el atributo "rol" en la tabla "categoria":

   1 Héroe
   2 Jefe
   3 Mini personaje

   Se debe definir si se cambia este atributo a varchar o de dejarlo como int, crear la tabla de referencia.

- [ ] El mismo caso anterior para el atributo "tipo" en la tabla "categoria":

   1 Terrestre
   2 Volador

   Se debe definir si se cambia este atributo a varchar o de dejarlo como int, crear la tabla de referencia.

**Comment by manuk160** [comment]
Me encuentro adelantando los cambios y validaciones adicionales por lo cual esta actividad continua su desarrollo.

**Comment by DiegOliveros** [comment]
- [ ] @manuk160 @zergiozerna81 @jnrubiano  Todas las tareas deben tener responsable.
![image](https://cloud.githubusercontent.com/assets/2998313/24570912/c77e2152-1633-11e7-97b5-a065c5ab6f78.png)

**Comment by jnrubiano** [comment]
@manuk160 @zergiozerna81 @JuanCheroslan por favor me ayudan verificando quién o quiénes son los encargados se las dos actividades faltantes para poder cerrar este issue? Gracias...

**Comment by jnrubiano** [comment]
Ésta tarea ya se realizó y asocia el issu #446  donde ya se realiza el despliegue en ambiente de pruebas
