### ISSUE TITLE
1.1.16 Propuestas del escudo final

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#235]
**Descripción**
Propuestas prototipo escudo final.
**Tareas a realizar**
- [x] Mockups escudo del juego

**Comment by KmiArthur** [comment]
## Propuesta nuevo escudo
(tiempo de trabajo: 1h)

![captura de pantalla 2017-03-24 a las 6 30 38 p m](https://cloud.githubusercontent.com/assets/17441569/24316907/08bcbf9e-10c0-11e7-820a-b3e9afd3adba.png)

**Comment by KmiArthur** [comment]
Finalización de tareas. `Diseño no aprobado.` 
Logo original oficial en el Issue #86
