### ISSUE TITLE
Arquitectura Servicio REST Mundo e Imagen 

### ISSUE THREAD

**Issue by wpradere** [ISWPOLI/Pacto-de-Honor#245]
- [x] Instancia entidad hijo en entidad padre 

- [x] Probar servicio

**Comment by DiegOliveros** [comment]
Estimado @wpradere por favor incluir descripción de la historia.

**Comment by wpradere** [comment]
Se crea el servicio Imagen y se realiza el commit del código  #21

**Comment by jnrubiano** [comment]
Se realiza el desarrollo, la documentación y las pruebas de la entidad Imagen y queda en el issue #361
