### ISSUE TITLE
Arquitectura Servicio REST Nivel

### ISSUE THREAD

**Issue by EdnaEspejo** [ISWPOLI/Pacto-de-Honor#247]
- [x] Ajustes del servicio
- [ ] Probar el servicio

**Comment by EdnaEspejo** [comment]
Se realizaron los cambios necesarios para la comunicacion con la base de datos, se hacen pruebas de conectividad desde glassfish respondiendo correctamente, se realiza deploy del codigo para identificar posibles error con resultados satisfactorios.
Sin embargo nuevamente me ha generado el error 1046 al momento de realizar el Test del servicio, se han intentado las siguientes alternativas de solucion:
+ Vaciado de la cache de las aplicaciones usadas para la implementacion
+ Creacion de nuevas conexiones 
+ Generacion desde cero de los servicios
+ Nuevo cargue de la base de datos
+ Reinstalacion de las aplicaciones

**Comment by wpradere** [comment]
Issue cerrado por redifinicion del tablero
