### ISSUE TITLE
4.1.6 Mockups Modulo Administrador

### ISSUE THREAD

**Issue by rzambrano112** [ISWPOLI/Pacto-de-Honor#250]
Mockups de las funciones que debe contemplar el modulo administrador.

- [x] Modulo administrador
- [x] Agregar mundo
- [x] Agregar nivel
- [x] Agregar personaje
- [x] Agregar poder
- [x] Agregar categoría
- [x] Generar reportes

**Comment by rzambrano112** [comment]
Se adjunta mockup modulo administrador.

<img width="652" alt="captura de pantalla 2017-03-25 a las 10 04 06 a m" src="https://cloud.githubusercontent.com/assets/20976993/24323369/73d0958a-1142-11e7-822b-4deea5299a84.png">

Realizado por:

Ricardo Zambrano
Steven Lagos

**Comment by Lakes1234** [comment]
Se adjunta versión en javascrip:


 <!DOCTYPE html>
  <html>
    <head>
      
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      
      <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>

      
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>

    <body>

<hr>
     <div class="card-panel teal lighten-2">
         <span class="white-text text-darken-2">MODULO ADMINISTRACION</span>
    </div>
    <hr>
        
    <div class="container">

    <div class="row"> 
    <div class="col s1 m3">Administrador</div>
    <img class = "responsive-img"src="https://cloud.githubusercontent.com/assets/17441569/24206994/d344030a-0eed-11e7-8cf5-af21b6e6de6f.png">
    <div>

     <div class="row">
    <div class="col s1 m3">Agregar_Mundo</div>
     </div>
        
        <div class="row">
        <div class="col s2">Agregar_Nivel</div>
        </div>

     <div class="row">
     <div class="col s3">Agregar_Personaje</div>
            </div>

    <div class="row">
    <div class="col s4">Agregar_Poder</div>
            </div>

    <div class="row">
    <div class="col s5">Agregar_Categoria</div>
            </div>

    <div class="row">
    <div class="col s6">Agregar_Jugador</div>
    </div>

    <div class="row">
     <div class="col s7">Generar_Reportes</div>
            </div>

             <div class="row">
            <div class="col s2">...</div>
            </div>
          	

        
     
 




    	 
      
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script type="text/javascript" src="js/materialize.min.js"></script>
    </body>
  </html>

**Comment by Lakes1234** [comment]
Mockup modulo mundo.


![mundof](https://cloud.githubusercontent.com/assets/25758873/24324288/abcdd7f4-1151-11e7-9ae2-8cb7c3f35d56.jpg)

Realizado por:
Ricardo Zambrano
Steven Lagos

**Comment by Lakes1234** [comment]
Mockup modulo nivel.

![nivel](https://cloud.githubusercontent.com/assets/25758873/24326642/c24e8f44-1180-11e7-920b-88c6dc1b5049.jpg)


Realizado por:
Ricardo Zambrano
Steven Lagos

**Comment by Lakes1234** [comment]
Mockup modulo personaje.

![personaje](https://cloud.githubusercontent.com/assets/25758873/24327270/515a93a2-1192-11e7-8fd0-6f50ffe21db0.jpg)


Realizado por:
Ricardo Zambrano
Steven Lagos

**Comment by Lakes1234** [comment]
Mockup modulo poderes.

![poder](https://cloud.githubusercontent.com/assets/25758873/24328371/7f0eb4e8-11ad-11e7-9525-0b7e8dc0be91.jpg)


Realizado por:
Ricardo Zambrano
Steven Lagos

**Comment by Lakes1234** [comment]
Mockup modulo categoría.

![categoria](https://cloud.githubusercontent.com/assets/25758873/24328491/e1925e6e-11b0-11e7-95d8-b1be54a92206.jpg)


Realizado por:

Ricardo Zambrano
Steven Lagos

**Comment by Lakes1234** [comment]
Mockup modulo reportes.

![reportes](https://cloud.githubusercontent.com/assets/25758873/24328567/9923ef4c-11b2-11e7-9315-7f8df2f5f6cb.jpg)


Realizado por:

Ricardo Zambrano
Steven Lagos

**Comment by rzambrano112** [comment]
Se anexa actualización del modulo de administración.
![imagenmodificadamoduloadministracion](https://cloud.githubusercontent.com/assets/20976993/24570182/cb4b9890-162f-11e7-9e59-43ec92282dd0.png)
