### ISSUE TITLE
1.1.17 Algoritmo navegación del juego y batalla

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#252]
**Descripción**

Terminar un prototipo pre - eliminar del juego consolidado teniendo en cuenta sus 2 grandes módulos: Navegación y Batallas.

**TAREAS**

- [x] Implementar escenario extra en el mundo correspondiente a Ana y Sara abeja para que luchen aparte 
- [x] Cambiar colores, tipo de letra y ortografía de la versión actual #167 
- [x] Cambiar el código según los cambios en el Issue #260 
- [x] Integrar botones de poderes
- [x] Hacer que las barras correspondan a los puntos de vida y poder @nicolas96

**Favor agregar una persona por tarea a través de una mención. En caso de faltar o aparecer nuevas tareas pertenecientes a este Issue, añadirlas con su respectivo responsable**

**Comment by nmartinezmarin** [comment]
- [ ] Asegurarse que el juego se vea bien en diferentes pantallas @nicolas96 @dayepesb
- [x] Conectar el menú de pausa con el resto del Mapa @gsalvarez
- [ ] Mejorar el Movimiento del villano @nicolas96 
- [x] Agregar componentes faltantes a la pantalla que determina el ganador en una batalla. @dayepesb
- [x] Agregar la pantalla de seleccion de personaje de batalla @dayepesb

**Comment by gabogabbs** [comment]
Se conectan los tres botones del menú de pausa con su respectiva función. 

![image](https://cloud.githubusercontent.com/assets/21046810/24781848/196fb452-1b08-11e7-8513-54360a1b85be.png)

REGISTRO DE TIEMPO: 3 HORAS.

**Comment by dayepesb** [comment]
Según lo hablado con @CamilaG08 , la implementación del escenario extra (ana y sara) , quedará a cargo de @CristianGarzonBernal en la semana de trabajo individual.

**Comment by CamilaG08** [comment]
Se cierra ya que las tareas faltantes se asignan en una nueva tarea.
