### ISSUE TITLE
1.5.3 Frases retadoras, de victoria y de derrota (Mundo 7 - 12)

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#256]
**Descripción**

Realizar las imágenes de frases retadoras que son al inicio de cada mundo y las frases de victoria o derrota que aparecerían según el resultado de la batalla final.

**TAREAS**

- [x] Revisar el documento que contiene las frases

- [x] Crear la imagen de la frase retadora de Juan Rata
- [x] Crear la imagen de la frase de victoria de Juan Rata
- [x] Crear la imagen de la frase de derrota de Juan Rata

- [x] Crear la imagen de la frase retadora de Carlos Buitre
- [x] Crear la imagen de la frase de victoria de Carlos Buitre
- [x] Crear la imagen de la frase retadora de Carlos Buitre

- [x] Crear la imagen de la frase retadora de Víctor Hiena
- [x] Crear la imagen de la frase de victoria de Víctor Hiena
- [x] Crear la imagen de la frase retadora de Víctor Hiena

- [x] Crear la imagen de la frase retadora de Nicolás Lagarto
- [x] Crear la imagen de la frase de victoria de Nicolás Lagarto
- [x] Crear la imagen de la frase retadora de Nicolás Lagarto

- [x] Crear la imagen de la frase retadora de Luis Víbora
- [x] Crear la imagen de la frase de victoria de Luis Víbora
- [x] Crear la imagen de la frase retadora de Luis Víbora

- [x] Crear la imagen de la frase retadora de Fabián Babuino
- [x] Crear la imagen de la frase de victoria de Fabián Babuino
- [x] Crear la imagen de la frase retadora de Fabián Babuino

**Comment by juancelemin** [comment]
**Descripción**

Realizar las imágenes de frases retadoras que son al inicio de cada mundo y las frases de victoria o derrota que aparecerían según el resultado de la batalla final.

**TAREAS**


- [x] Crear la imagen de la frase retadora de Carlos Buitre
- [x] Crear la imagen de la frase de victoria de Carlos Buitre
- [x] Crear la imagen de la frase de derrota de Carlos Buitre

- [x] Crear la imagen de la frase retadora de Luis Vibora
- [x] Crear la imagen de la frase de victoria de Luis Vibora
- [x] Crear la imagen de la frase retadora de Luis Vibora

- [x] Crear la imagen de la frase retadora de Nicolás Lagarto
- [x] Crear la imagen de la frase de victoria de Nicolás Lagarto
- [x] Crear la imagen de la frase retadora de Nicolás Lagarto

- [x] Crear la imagen de la frase retadora de Víctor Hiena
- [x] Crear la imagen de la frase de victoria de Víctor Hiena
- [x] Crear la imagen de la frase retadora de Víctor Hiena

- [x] Crear la imagen de la frase retadora de Fabián Babuino.
- [x] Crear la imagen de la frase de victoria de Fabián Babuino.
- [x] Crear la imagen de la frase retadora de Fabián Babuino.

- [x] Crear la imagen de la frase retadora de Juan Rata.
- [x] Crear la imagen de la frase de victoria de Juan Rata.
- [x] Crear la imagen de la frase retadora de Juan Rata.

**Comment by juancelemin** [comment]
Se corrigen las frases

![buitre_ganador](https://cloud.githubusercontent.com/assets/17105514/24580081/b7c3084c-16c7-11e7-9084-8e817e48a74d.png)
![buitre_perdedor](https://cloud.githubusercontent.com/assets/17105514/24580082/ba717bb4-16c7-11e7-9232-4a135deb1941.png)
![buitre_retador](https://cloud.githubusercontent.com/assets/17105514/24580083/bf9898ac-16c7-11e7-9590-91bba4e52bf5.png)
![hiena_ganador copia](https://cloud.githubusercontent.com/assets/17105514/24580084/c3e05814-16c7-11e7-8afd-136103c76ce8.png)
![hiena_perdedor copia](https://cloud.githubusercontent.com/assets/17105514/24580086/c6d12210-16c7-11e7-8be9-4104ed088fd6.png)
![hiena_retador](https://cloud.githubusercontent.com/assets/17105514/24580089/ca6d8288-16c7-11e7-8948-db165a07abd6.png)
![lagarto_ganador](https://cloud.githubusercontent.com/assets/17105514/24580092/cddcb808-16c7-11e7-95ea-9d211d274807.png)
![lagarto_perdedor copia](https://cloud.githubusercontent.com/assets/17105514/24580094/d0c0d8ce-16c7-11e7-8e52-71c83c24cf26.png)
![lagarto_retador](https://cloud.githubusercontent.com/assets/17105514/24580098/ee451f18-16c7-11e7-9c82-5e03f9b24380.png)
![mico_ganador](https://cloud.githubusercontent.com/assets/17105514/24580101/014bcc1a-16c8-11e7-852b-4c1d57bbeff9.png)
![mico_perdedor1](https://cloud.githubusercontent.com/assets/17105514/24580114/2c9e2e1c-16c8-11e7-920d-148d61f9e8f4.png)
![mico_retador](https://cloud.githubusercontent.com/assets/17105514/24580116/342db9b8-16c8-11e7-905b-0aed8992c317.png)
![rata_ganadora copia](https://cloud.githubusercontent.com/assets/17105514/24580117/3c886fae-16c8-11e7-88a9-cc4b0b840f42.png)
![rata_perdedora](https://cloud.githubusercontent.com/assets/17105514/24580120/4a99d2ea-16c8-11e7-9da1-37d6b2854c6c.png)
![rata_retadora copia](https://cloud.githubusercontent.com/assets/17105514/24580121/53c763aa-16c8-11e7-8822-d648946e56ea.png)
![serpiente_ganador](https://cloud.githubusercontent.com/assets/17105514/24580124/5999c9f8-16c8-11e7-903a-8e00a1e8985c.png)
![serpiente_perdedor](https://cloud.githubusercontent.com/assets/17105514/24580125/5ca73d60-16c8-11e7-8beb-95c68559cb2d.png)
![serpiente_retador copia](https://cloud.githubusercontent.com/assets/17105514/24580127/61239f8c-16c8-11e7-9c82-8743f46e2178.png)

**Comment by CamilaG08** [comment]
Por favor revisar ortografía en los textos de las imágenes.

**Comment by CamilaG08** [comment]
Se cierra debido a que se plantea otra forma de realizar estas imágenes y queda @KmiArthur a cargo de modificar/mejorar las imágenes correspondientes a Andrés Zorro y Felipe Oso
