### ISSUE TITLE
1.11 Diseño de portal en Wordpress

### ISSUE THREAD

**Issue by KmiArthur** [ISWPOLI/Pacto-de-Honor#257]
- [x] Diseño de portal en Wordpress

**Comment by KmiArthur** [comment]
Traslado completo de la página a WordPress con sus respectivas actualizaciones y correcciones:
(Trabajo: 7h)

![captura de pantalla 2017-03-31 a la s 11 01 14 p m](https://cloud.githubusercontent.com/assets/17441569/24575247/ff85e92c-1665-11e7-9fe3-2d7e496c4e4a.png)

**Comment by CamilaG08** [comment]
Se cierra ya que se realiza su tarea a cabalidad, sin embargo queda pendiente la revisión y si son necesarias modificaciones.
