### ISSUE TITLE
4.1 Documentacion Modulo de Administracion

### ISSUE THREAD

**Issue by JuanCheroslan** [ISWPOLI/Pacto-de-Honor#259]
Es necesario que se documente como se va a realizar el modulo de administrador.

el documento debe tener

- [x] Descripcion de la tecnologia a usar en el modulo administrador

- [x] Mokups documentados 

- [x] Modelo de Arquitectura empleado en el diseño

este documenot debe quedar listo para el dia 29 de marzo antes de la clase (6:40)

**Comment by JuanCheroslan** [comment]
Señores @rzambrano112 @zergiozerna81 @Lakes1234 @alexsabsan  no veo primer draft de documento de diseño del modulo de administrador, podrian indicarme donde se encuentra para hacer la revision?, cuando cree el issue les pedi que el documento fuera completado antes de la clase y hasta el momento no hay nada, lo unico que hay es la carpeta que creo steven el dia de ayer

**Comment by rzambrano112** [comment]
Se anexa mockups del modulo administrador. 
[MOCKUPS MODULO ADMNISTRADOR.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/887234/MOCKUPS.MODULO.ADMNISTRADOR.docx)

**Comment by rzambrano112** [comment]
Quedo atento a cualquier comentario.
Debido a que estoy trabajando en el tema del modulo de reportes.

**Comment by zergiozerna81** [comment]
Se sube el documento.

[DISEÑO MÓDULO ADMINISTRACIÓN.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/887314/DISENO.MODULO.ADMINISTRACION.docx)

**Comment by JuanCheroslan** [comment]
Estimados

@zergiozerna81 @rzambrano112 @Lakes1234 @alexsabsan 
el documento contiene unos mokups que no difrencian nada, la unica cosa que hacen es remarcar un boton y el logo del juego, porfavor corregir

![image](https://cloud.githubusercontent.com/assets/25808683/24765654/35d39f5e-1abe-11e7-93e7-a30ebc7e6424.png)

**Comment by rzambrano112** [comment]
Se anexan la unificación de los mockups del modulo de administración.

[UNIFICACION DE MOCKUPS MODULO ADMNISTRADOR.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/915377/UNIFICACION.DE.MOCKUPS.MODULO.ADMNISTRADOR.pdf)

Además la navegabilidad de los mismos y su implementación se encuentran en el issue #307

**Comment by rzambrano112** [comment]
Se cierra el issue
