### ISSUE TITLE
2.1.1 Estandarización de los poderes según el tipo de plagio

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#26]
**Descripción**

Cada integrante va a tomar algunos tipos de plagio, para los cuales asignará personaje y poder específico.

**TAREAS**

- [x] Nicolás Toma el primer grupo de tipos de plagio (Clonación, Copiado y pegado, Búsqueda y reemplazo) para definir el personaje y su poder
- [x] Camilo Toma el segundo grupo de tipos de plagio (Remix, Reciclado, Híbrido) para definir el personaje y su poder
- [x] Camila Toma el tercer grupo de tipos de plagio (Mosaico y Error 404) para definir el personaje y su poder
- [x] Ricardo Toma el cuarto grupo de tipos de plagio (Fuente RSS y Reutilización) para definir el personaje y su poder

**Comment by KmiArthur** [comment]
**REMIX**
**_Ana y Sara Abeja:_** Éstas dos fieles compañeras, llaman a su enjambre para obtener ayuda para ir sobre todos sus amigos y enemigos, aprovechando lo pequeñas que pueden reducir su tamaño y abducir al enemigo por 2 segundos y lo debilita un 5% menos de vida, ya que sin importar lo que necesiten, usan sus ojos especiales para obtener información de todo lo que puedan y así unir todo para cumplir sus objetivos finales.

**RECICLADO**
**_Juan Rata:_** Juan tiene le poder de multiplicar sus exámenes anteriores infinitamente que salen de sus manos, y así poder tomar retazos de cada uno de ellos para unirlos como un solo trabajo final, muy ingenioso para que nadie lo notase y se lo envía al oponente con un golpe bastsante fuerte que lo debilita y deja inconsciente.

**HÍBRIDO**
**_Juan Camaleón:_** Usando sus ojos, que tienen la capacidad de ver a todos lados, se monta en los hombros de sus enemigos para obtener la información que necesite, a diferencia que el ojo derecho siempre se acuerda de quién toma la información para tenerlo en cuenta, y el ojo izquierdo nunca sabe de dónde saca la información para al final hacer una mezcla terrible en el momento de hacer un trabajo, puesto que no siempre recuerda de dónde sacó toda la información. Sus ojos usan un laser verde que nubla toda la pantalla del oponente, dejándolo vulnerable a cualquier ataque por 2 segundos.

**Comment by CamilaG08** [comment]
**Tipo de plagio**

Mosaico

**Nombre del personaje**

Carlos Buitre

**Poder**

Logra copiar los poderes de sus enemigos (los cuales obtiene después de golpear a su enemigo 3 veces) y una vez en su poder, logran mezclarlos y crear una bola de luz de colores, lista para ser lanzada y confundir a sus enemigos por 5 segundos.

**Tipo de plagio**

Error 404

**Nombre del personaje**

Felipe Oso

**Poder**

Al quedarse sin vida, puede tomarla de una fuente inexistente y misteriosa (en este caso un huracán de libros de colores) que restaura su vida en un 50%..

**Comment by Richardcas7ro** [comment]
Tipo de plagio
Fuente RSS
Nombre del Personaje
Víctor Hiena
Poder
Logra agregar poderes de sus aliados, los cuales se activan al llenar su barra de poder  (la cual se llena encadenando 4 golpes seguidos sin fallar), al activar su poder escoge cualquier habilidad agregada y la usa, al momento de utilizar su poder se vacía su barra de poder y esta queda en cero

Tipo de plagio 
Reutilización 
Nombre del personaje
Camilo Perezoso 
Poder 
Lanza un liquido venenoso el cual si toca a su enemigo reduce en un 10% su barra de poder y su vida, además de que reutiliza ese 10% y lo agrega a su barra de poder, al lanzar su poder este gasta un 20% de su barra de energía.

**Comment by nmartinezmarin** [comment]
### Tipo de plagio

Clonación

### Nombre del personaje

Julián Burro

### Poder

Juan el burro copia trabajos y los presenta como propios como no creen que sean de el, les lanza toda la coleccion de trabajos copiados causando mucho daño



### Tipo de plagio

Copia y pegado

### Nombre del personaje

Nicolas Lagarto

### Poder

Nicolas el lagarto copia todo lo que ve, por eso cada vez que ve la habilidad especial de un coontrincante este se la devuelve

### Tipo de plagio

Búsqueda y reemplazo

### Nombre del personaje

Andrés Zorro

### Poder

Este personaje es muy astuto por eso cuando ve tres habilidades especiales de su contrincante este las logra combinar para que luzcan diferente tiene la capacidad de lanzar un rayo en forma de espiral y con la palabra "copia" inscrito en el  que causa mucho daño a lo que encuentre en el camino.
