### ISSUE TITLE
1.8.3 Entrega de requerimientos a Backend

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#260]

**Comment by nmartinezmarin** [comment]
- [x] Especificar la información de los niveles de los personajes para poder realizar las modificaciones en la base de datos - Tiempo : 1 hora y 30 minutos

**Comment by nmartinezmarin** [comment]
Hola @jnrubiano 

Adjunto el documento del juego modificado de acuerdo a la reunión de integración.
[Limitaciones-del-Juego-29-de-Marzo.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/878064/Limitaciones-del-Juego-29-de-Marzo.docx)

Quedo atento a cualquier cosa.

**Comment by CamilaG08** [comment]
Se cierra ya que se entrega el documento con los requerimientos estipulados.
