### ISSUE TITLE
1.4.7 Modificar Escenarios.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#261]
**Descripción**
Modificar Escenarios.
**Tareas a realizar**
- [x] Cambiar tamaño a todos los escenarios.
- [x] Agregar escenarios de las sedes del Poli de Virtual.

**Comment by ghost** [comment]
## Realización de 38 escenarios en sprites (Registro de tiempo: 3 horas y 30 minutos)

https://drive.google.com/open?id=0B8ttTD0H6QRCRWFPZmpXTDRYQnM
