### ISSUE TITLE
5.6.6 Leer libro prueba NEO PI-R

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#264]
**Descripción**
Leer libro prueba NEO PI-R. **Hasta el miércoles 29 de Marzo**
**Tareas a realizar**
- [x] Ir el lunes donde el profesor Julián por una copia del libro.
- [x] Leer libro.
- [x] Realizar un documento que soporte el ítem anterior.

**Comment by ghost** [comment]
El dia lunes 27 de marzo, me reuní con el profesor julian por una copia del libro NOE PI-R

Tiempo: 20 minutos.

**Comment by ghost** [comment]
Se realiza lectura del manual NEO PI-R, se realiza la extracción de algunas de las preguntas que se puedan implementar en el juego. 

La idea inicial para las pruebas psicotécnicas era que las preguntas se hicieran de manera general para que no hubiese la oportunidad por parte del usuario de sentirse evaluado y que llegara a mentir en las pruebas, pero debido a que las preguntas no pueden ser un centenar de ellas lo que propongo es que en medio de algunas preguntas se cuestione directamente lo que queremos saber de cada usuario.
El modo en el que debemos hacer las preguntas es el modo directo, que cuando el jugador necesite ayuda para recargar su poder especial o necesite ayuda para vencer al personaje contra el que pelea haga uso de una AYUDA para ello.
Al usar la ayuda le saldrá una descripción de lo que tiene que hacer y marcar de esa manera las preguntas del cuestionario.

[NeoPirDocumento.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/880864/NeoPirDocumento.zip)

Tiempo: 3horas 10 minutos.

**Comment by jrsosago** [comment]
Se cierra este Issue, ya que se finalizó la tarea
