### ISSUE TITLE
6.2.1 Reporte SCRUM Master (Miércoles 29 de Marzo)

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#266]
**Descripción**
Reporte SCRUM Master.
**Tareas a realizar**
- [x] Reporte Miércoles 29 de Marzo

**Comment by ghost** [comment]
# Reporte 29 de marzo

## Issue #214 - Creación de los poderes de los mini personajes [Camilo D'achiardi]
- Se terminaron de crear los 48 logos de los poderes.
- Se terminaron de crear las 48 visualizaciones de los poderes

## Issue #257 - Diseño de portal en wordpress [Camilo D'achiardi]
- Se creó portal en wordpress pero aun no esta terminado.
- Se esta incluyendo los textos que se tenian anteriormente.

## Issue #168 - Creación de los sprites de los mini personaJes [Gabriel Álvarez]
- Se terminó la realización de todos los sprites de los mini personajes (48 en total)

## Issue #229 - Modificar el mapa de navegación-invitar Amigos [Gabriel Álvarez]
- Se creo un nuevo estado que representara la sección de invitar-amigos.
- Se implementó un botón para abrir la sección de invitar-amigos.
- Aun no esta funcional ya que se necesita que este terminado el login, y que el juego este en un servidor

## Issue #219 - Perfil del jugador funcional (Perfil) [Juan Carlos Quintana]
- Se elimino la imagen que representaba el botón, en vez de esto se añadió un texto el cual es "personajes".
- Aun no esta terminado, ya que falta agregar los botones.
- Se implementó un scroll que representara los personajes del jugador pero aun no se ha probado.

## Issue #192 - Perfil del jugador (Logros) [JUan Carlos Quintana]
- Aun no se han realizado las imagenes de los logros que estaran dentro del scroll.
- Se tiene pensado agregar gif (en sprites) al scroll.

## Issue #256 - Frases retadoras, de victoria y de derrota [Juan Guillermo Celemin]
- Se han realizado las 3 frases de Victor Hiena.
- Se han realizado las 3 frases de Nicolás Lagarto.
- Se realizo una frase de Fabián Babuino (la retadora).
- Aun falta realizar 11 frases.

## Issue #220 - Login Funcional [Ivan Barrantes - Julio Ernesto Rodriguez]
- ya esta realizado el servlet de inicio de sesion
- esta el controlador de identidades.
- Se conectó el jsp con el servlet.
- Se conectó el servlet con EntityManagerFactory (Manejador de entidades).
- Se conecta EntityManagerFactory con el controlador de entidades.

## Issue #280 - Recopilar los documentos para la carpeta de documentación del proyecto [Camila Gutierrez]
- Se han recopilado 10 documentos.
- Se modificó el documento de consolidacion de personajes, arreglando su redacción.
- Aun no se esta recopilado el documento del manual de diseño, pero ya esta hecho, solo hace falta subirlo.
- Aun no se esta recopilado el repositorio de mockups actualizado, ya que esta en proceso.

## Issue #209 - Implementacion compra de personajes [Camila Gutierrez]
- Se volvio a modificar el documento de logros, modificandole las recompensas al obtener un logro.
- Se modifico el documento de comprar los personajes, separando las abejas, el león y el raton.
- Se miro el codigo de seleccion de avatar realizado por Dario Muñoz como referencia.
- Se implementó un scroll añadiendole como imagenes las realizadas por Ivan Barrantes en la Issue #194.
- Se implementaron los textos de la recompensa que se obtiene al comprar cada uno de los personajes.
- Aun no se ha hablado con el grupo de Backend para comentarles que se va a 
- Aun no esta implementado para que las monedas esten habilitadas en el juego.
- Aun falta crear el sprite de la imagen de monedas e integrarlo al mapa de navegación.
- Aun falta crear el sprite que representara el label "comprando".
- Aun falta implementar el algoritmo que indique cuando un personaje este comprado o no.
- Aun falta integrar el algoritmo que aumente las recompensas correspondiente

## Issue #183 - Reunión con el decano Rafael García [Camila Gutierrez, Jeimy Sosa, Nicolás Martinez y Juan Camilo Lancheros (o Manuel Sanchez)]
- Se tiene pensado realizar la reunion el dia viernes 31 de marzo.

## Issue #261 - Modificar escenarios [Dario Muñoz]
- Ya se convirtieron todos los escenarios .gif a sprites con el tamaño indicado.

## Issue #188 - Consolidar la documentación del codigo [Dario Muñoz]
- Ya se explicó y documentó el archivo selecciondepersonaje.js
- Ya se explicó y documentó el archivo selecciondeavatar.js
- Ya se explicó y documentó el archivo historieta.js
- Ya se explicó y documentó el archivo game.js
- Ya se explicó y documentó el archivo indexGame.html
- Ya se explicó y documentó el archivo navegacion.js
- Ya se explicó y documentó ela rchivo creditos.js
- Aun no se ha terminado la documentación del codigo, faltan alguno archivos.

## Issue #266 - Reporte SCRUM Master (miercoles 29 de marzo) [Dario Muñoz]
- Se revisaron avances en las tareas de 8 integrantes del grupo de frontend.

## Issue #264 - Leer libro prueba NEO PI-R [Sebastian Rodriguez]
- Hubo reunion con Julian Olarte para la entrega del manual.
- Se leyo el manual y se realizo un documento explicando sus caracteristicas.
- No se ha terminado con la realización del documento, aun falta el significado de la escala que se usa.
- Se realizo una presentación en Power Point, donde se propone como se presentaran las preguntas al jugador.
- Se realizo un documento explicando como implementar las preguntas segun el manual.
