### ISSUE TITLE
6.2.2 Reporte SCRUM Master (Miércoles 29 de Marzo)

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#267]
**Descripción**
Reporte SCRUM Master.
**Tareas a realizar**
- [x] Documento o soporte del reporte Miércoles 29 de Marzo

**Comment by ivandav** [comment]
# Reporte miercoles 29 de marzo

 Se hace la revisión de las actividades asignadas para el nuevo sprint, se revisan los avances hasta el momento con cada uno de los integrantes.
## Issue #263 Realizar documento de interacción social con Gmail y Microsoft [Jaime Bernal]:
   - No se encuentra información referente a la tarea.
   - Se hará una reunión con personas que  trabajan en desarrollo web y se recibirá ayuda.
   - Se recibe información de Cristian Garzon.

## Virtual Story Mapping [Jaime Bernal]:
   - Se completa el VSM de los Sprint 6, 7 y 8. 
   - Se realiza la actualización hasta el día de hoy del Product Backlog

## Issue #197 Realizar propuesta final de interacciones sociales [Cristian Garzon]:
   - Se hace la implementacion de los códigos alfanuméricos, se entrega un documento en el que se especifican algunas reglas que tienen que ver con la seguridad y el uso de estos códigos, ademas como se hace la captura de estos datos en la BD.

## Issue #278 Implementacion de códigos alfanuméricos [Cristian Garzon]:
   - Se hacen los mockups del desbloqueo de personajes por medio de interacciones sociales, en ellos se muestran cada una de las pantallas y textos que se muestran al utilizar un código regalad por un amigo.
   - Se realizara un mockup faltante, pues solo se puede regalar un codigo por cuenta.


## Issue #210 Implementacion para móviles [David Yepes]:
   - Se recibe un documento en el cual se muestra el código de funcionamiento del joystic con un ejemplo en un juego de Phaser, sin embargo, en el documento no se encuentra la explicación del funcionamiento.
   - Se empieza a realizar una investigación debido al problema con el documento recibido.


## Organizar carpetas [David Yepes]:
   - Reorganizar algunas carpetas de imágenes y modificar el código para su correcto funcionamiento.

## Documento de reunión con Backend [Nicolas Martinez]:
   - Se entrega el documento en el que se especifica los niveles de los personajes, el documento ya estaba pero después de la reunión se actualizan algunas cosas.

 
## Issue #252  Algoritmo de navegación de juego y batalla [Nicolas Martinez]:
   - Revisar el código para solucionar errores y pulir el código.


## Issue #220 Login funcional y modificado (Ivan Barrantes):
   - Se sigue realizando investigación, pues no se tienen claros los nuevos conceptos.
   - Se logra obtener el ID de la aplicación para agregarlo al login, pero aun no se implementa.


## Issue #265 Leer libro prueba NEO PI-R (Jeimy Sosa):
   - Se realiza la lectura del libro y se entrega el documento resumen de la lectura.

## Otras tareas [Jeimy Sosa]:
   - Las tareas pendientes se entregaran el sábado, es decir, se realizara en el transcurso de la semana.
   - Se realizan tareas asignadas como trabajo de product owner.

**Comment by jrsosago** [comment]
Se cierra debido a que se realizo el reporte.
