### ISSUE TITLE
Login usando Windows Live

### ISSUE THREAD

**Issue by EdnaEspejo** [ISWPOLI/Pacto-de-Honor#27]
Crear botón para ser insertado en el formulario de Login que permita el inicio de sesión a través de una cuenta de Windows Live y agregar la funcionalidad correspondiente.

**Comment by EdnaEspejo** [comment]
Conexión con Cuentas Microsoft
Outlook cuenta con REST API para realizar la conexión con los diferentes usuarios de Outlook con una aplicación creada, con el siguiente procedimiento:
1.	Registre su aplicación. 
2.	Inicie la codificación e implemente las llamadas a la API REST.
Sólo hay un proceso sencillo para Outlook.com y Office 365: regístrese y obtenga la autorización dinámica del usuario para acceder al correo, al calendario y a los contactos de los usuarios.

API REST para JavaScript: se deben seguir los siguientes pasos sobre un servidor http
1.	 Crear la aplicación
2.	Diseñar la aplicación: Cuando un usuario visita el sitio, verá un enlace para iniciar sesión y ver su correo electrónico. Al hacer clic en ese enlace, los llevará a la página de inicio de sesión de Azure, donde podrá iniciar sesión con su cuenta de Office 365 o Outlook.com y conceder acceso a nuestra aplicación. Finalmente, serán redirigidos de nuevo a nuestra aplicación, que mostrará una lista del correo electrónico más reciente en la bandeja de entrada del usuario. Y se agrega el correspondiente código javascript
3.	Registrar la aplicación
4.	Implementar OAuth2
5.	Llamar Mail API
6.	Mostrar los resultados

**Comment by ghost** [comment]
Se verifican el login de Windows Live,  se discute los modelos actuales según las especificaciones indicadas, se están realizando ajustes y modificaciones correspondientes se verán reflejadas en un Spint 2 o en un Spint 3 ya que no contamos con una cuenta con licencia que nos indique los permisos se esta verificando si se logra hacer sin este requerimiento.

**Comment by jolarter** [comment]
¿Qué ha pasado con este issue? por favor adelantar la investigaciónón con los ejemplos de https://developer.microsoft.com/en-us/graph/docs/authorization/auth_overview

**Comment by JuanCheroslan** [comment]
se hace la investigacion de como funciona el API de  office 365 sin utilizar servicios  de Azure
