### ISSUE TITLE
4.1.1 Historias de Usuario Modulo Administración

### ISSUE THREAD

**Issue by zergiozerna81** [ISWPOLI/Pacto-de-Honor#270]
- [x] Escribir las historias de usuario para este modulo.

**Comment by rzambrano112** [comment]
Se anexa historias de usuario
[Historias de usuario.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/880739/Historias.de.usuario.docx)

**Comment by zergiozerna81** [comment]
Se revisan las historias de usuario y se sugiere tener en cuenta que para las siguientes entidades de la BD se requiere generar historias para agregar, modificar y eliminar registros:

- Categoría
- Ciudad
- Frase
- Imagen
- Mundo
- Nivel
- País
- Personaje
- Poder
- Rol Usuario
- Usuario

**Comment by rzambrano112** [comment]
Se anexa una actualización del mockup del modulo de administración
![imagenmodificadamoduloadministracion](https://cloud.githubusercontent.com/assets/20976993/24569191/a73aacde-162a-11e7-968b-9e7b0bf0b930.png)

**Comment by rzambrano112** [comment]
Se anexa una modificación del mockup del modulo de administración

**Comment by rzambrano112** [comment]
Se anexan las historias de usuario del modulo de administración.

[Historias de usuario Modulo administración.xlsx](https://github.com/ISWPOLI/Pacto-de-Honor/files/887054/Historias.de.usuario.Modulo.administracion.xlsx)

**Comment by rzambrano112** [comment]
Se cierra el issues de historias de usuario #270

**Comment by zergiozerna81** [comment]
Se suben historias de usuario corregidas @DiegOliveros @jolarter 

[Historias de Usuario Módulo Administración.xlsx](https://github.com/ISWPOLI/Pacto-de-Honor/files/888874/Historias.de.Usuario.Modulo.Administracion.xlsx)

**Comment by rzambrano112** [comment]
Se realiza actualización de historias de usuario.
Se crea una nueva historia
[Historias.de.Usuario.Modulo.Administracion (4).xlsx](https://github.com/ISWPOLI/Pacto-de-Honor/files/921249/Historias.de.Usuario.Modulo.Administracion.4.xlsx)
