### ISSUE TITLE
4.1.4 Consolidar mockups de modulo administración

### ISSUE THREAD

**Issue by zergiozerna81** [ISWPOLI/Pacto-de-Honor#272]
- [x] Consolidar mockups de modulo administración

**Comment by rzambrano112** [comment]
Se realiza la consolidación de los mockups del modulo de administración.
[MOCKUPS MODULO ADMNISTRADOR.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/887208/MOCKUPS.MODULO.ADMNISTRADOR.docx)

**Comment by rzambrano112** [comment]
Se cierra issues de consolidación de modulo de administración.

**Comment by rzambrano112** [comment]
Se cierra issues #272 consolidar mockups modulo de administración.
