### ISSUE TITLE
4.1.2 Funcionalidad módulo reportes

### ISSUE THREAD

**Issue by zergiozerna81** [ISWPOLI/Pacto-de-Honor#274]
- [x] Definir la funcionalidad para la generación de reportes

**Comment by rzambrano112** [comment]
Funcionalidad para generacion de reportes.

Se realiza investigacion de Jaspersoft y GoogleCharts para la generación de reportes.
Tiempo empleado : 1 hora

Y se toma la decision de trabajar sobre GoogleCharts para los reportes para el juego.
Tiempo empleado: 20 minutos.

**Comment by zergiozerna81** [comment]
Tiempo: 1 hora

Investigación sobre Google Charts y Jaspersoft para poder definir como se van a generar los reportes.

Tiempo: 20 minutos (en clase)

Reunión con @rzambrano112 @alexsabsan @DiegOliveros observando la facilidad de utilizar Google Charts y que este recibe consultas SQL, por lo que estaríamos consumiendo los servicios rest existentes para obtener la información para los reportes.

Tiempo: 20 minutos (en clase)

Reunión con @rzambrano112 @alexsabsan @Lakes1234 Steven se revisan las dos opciones para la generación de soportes y nos decidimos por el uso de Goggle Charts.

**Comment by Lakes1234** [comment]
De acuerdo revisión de los mockups y sugerencias recibidas por parte del grupo y profesor se valido herramientas de BI como jaspersof y googlechart, por lo cual de acuerdo a los ejemplos vistos se escoge la herramienta de googlechart. 

  <html>
  <head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Year', 'Sales', 'Expenses'],
          ['2004',  1000,      400],
          ['2005',  1170,      460],
          ['2006',  660,       1120],
          ['2007',  1030,      540]
        ]);

        var options = {
          title: 'Company Performance',
          curveType: 'function',
          legend: { position: 'bottom' }
        };

        var chart = new google.visualization.LineChart(document.getElementById('curve_chart'));

        chart.draw(data, options);
      }
    </script>
  </head>
  <body>
    <div id="curve_chart" style="width: 900px; height: 500px"></div>
  </body>
</html>

**Comment by alexsabsan** [comment]
Generacion de la primera vesion del modulo de Adminitracion (Portal inicio)
[Modulo Administrador.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/880909/Modulo.Administrador.zip)

**Comment by DiegOliveros** [comment]
@alexsabsan @Lakes1234 @zergiozerna81 @rzambrano112 estos commits deben realizarse sobre el repositorio.

![image](https://cloud.githubusercontent.com/assets/2998313/24571759/f88cc62c-1638-11e7-98b9-d0522b53cde1.png)

**Comment by DiegOliveros** [comment]
- [ ] Esto debe producir un entregable de manera que se justifique la elección y el tiempo invertido. @rzambrano112 


![image](https://cloud.githubusercontent.com/assets/2998313/24571809/5d273608-1639-11e7-9861-972cb8044678.png)

**Comment by zergiozerna81** [comment]
Jaspersoft: Basado en Java, funciona como librería y permite conectarse a la base de datos para posteriormente con base en la información contenida en esta, elaborar los reportes en un ambiente gráfico para posteriormente generar el código.

Google Charts: Permite diseñar diferentes tipos de gráficos para representar la información, se puede trabajr con querys SQL para obtener la información de la base de datos y llevarla a una data table y desde allí generar el gráfico.

Se sube el documento en el issue #259

**Comment by rzambrano112** [comment]
Se cierra módulo por la implementación del modulo de reportes en GoogleChart
