### ISSUE TITLE
1.8.5 Implementación Códigos alfanuméricos.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#278]
**Descripción**
Realizar implementación códigos alfanuméricos para regalar personajes en el juego. 
**Tareas a realizar** 
- [x] Realizar los mockups de  todo lo descrito en el documento de códigos alfanuméricos que se encuentra en la Issue #197.
- [x] Realizar la implementación de  todo lo descrito en el documento de códigos alfanuméricos que se encuentra en la Issue #197

**Comment by CristianGarzonBernal** [comment]
![1](https://cloud.githubusercontent.com/assets/22016808/24387815/f9bbd3b6-133c-11e7-833f-144d556dddc9.PNG)
![2](https://cloud.githubusercontent.com/assets/22016808/24387817/fbccb490-133c-11e7-9b98-8739764c1571.PNG)
![3](https://cloud.githubusercontent.com/assets/22016808/24387819/fe6413e2-133c-11e7-8429-19e5500395ec.PNG)
Tiempo registrado 3hrs

**Comment by jrsosago** [comment]
**Descripción**
Agregar a los mockups botón para ir al mapa de navegación y para ir al perfil del usuario.
**Tareas a realizar**
- [x]  Poner botón para ir al perfil de usuario en todos los mockups.
- [x] Poner botón para ir al mapa de navegación en todos los mockups.

**Comment by CristianGarzonBernal** [comment]
![captura](https://cloud.githubusercontent.com/assets/22016808/24689891/56b3896c-198f-11e7-87a0-2806cc604081.PNG)
![captura2](https://cloud.githubusercontent.com/assets/22016808/24689910/78f3625e-198f-11e7-8152-69343465bf2a.PNG)
![captura3](https://cloud.githubusercontent.com/assets/22016808/24689915/7bba06b4-198f-11e7-82e2-45d2b3f6908c.PNG)
![captura4](https://cloud.githubusercontent.com/assets/22016808/24689918/7e1b0b6a-198f-11e7-8212-66d096e3ed90.PNG)

Se agregaron las indicaciones pedidas para esta tarea y se agrego un nuevo caso de mockup en el que si el jugador ya ha usado el código de regalo aparecerá una nueva pantalla.

Tiempo Registrado 3 hrs.

**Comment by CristianGarzonBernal** [comment]
[Requerimientos de Códigos Alfanuméricos.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/907587/Implementacion.Codigos.Alfanumericos.pdf)
