### ISSUE TITLE
Documentación Requerimientos Servidor y Conectividad

### ISSUE THREAD

**Issue by DanteVDrako** [ISWPOLI/Pacto-de-Honor#29]
Elaborar documento de que tipo de hardware y software se necesitaría para montar el juego

**Comment by DanteVDrako** [comment]
TAREAS:

- [x] Dimensionar servidor.

- [x] Dimensionar conectividad.

- [x] Redactar documento.
[Requerimientos No Funcionales.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/781421/Requerimientos.No.Funcionales.docx)

**Comment by DiegOliveros** [comment]
@DanteVDrako  Si quedan actividades pendientes no puedes cerrar esta historia.
Saludos,

**Comment by manuk160** [comment]
De acuerdo al número de usuarios esperados“30.000” y de acuerdo a los estándares para calcular y dimensionar los equipos para la infraestructura y de acuerdo a los datos iniciales se calcula un 10% de 
usuarios conectados a la aplicación en el mismo momento y un 1% de concurrencia por lo cual serian 3000 usuarios conectados a la aplicación 300 concurrentes en cuanto a procesos y transacciones.

Para realizar un dimensionamiento más ajustado en cuanto a ancho de banda, base de datos y procesamiento debe realizarse una medición de:
 Instalación de servidor de prueba básico.
 Validación de phaser sobre servidor.
 Tiempo de carga de aplicación.
 Numero de procesos generados en la máquina y porcentaje de carga de los mismos.

**Comment by manuk160** [comment]
Actualización de Documento de reequerimientos

[Requerimientos No Funcionales_V2.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/784761/Requerimientos.No.Funcionales_V2.docx)

**Comment by manuk160** [comment]
Adjunto el diagrama de servidores entregado en clase sobre la arquitectura a utilizar en el proyecto.

[DiagramaServidores.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/821204/DiagramaServidores.pdf)
