### ISSUE TITLE
6.2.6 Reporte SRUM Master (Miércoles 5 de Abril)

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#292]
**Descripción:**
Reporte SCRUM Master.
**Tareas a realizar:**
- [x] Reporte Miércoles 5 de Abril

**Comment by ivandav** [comment]
# Reporte miércoles 5 de abril
 Se hace la revisión de los avances de los integrantes, los cuales tienen tareas propuestas para el sábado.

## Issue #263 Realizar propuesta de interacción social con Gmail y Microsoft. [Jaime Bernal]:
   - Se realiza la lectura de los link enviados por Juan Lancheros para complementar la información entregada el día sábado 1 de abril, no se lo logra obtener información relevante así que no se agrega nada.

## Repositorio de horas [Jaime Bernal]:
   - Se realizo una hoja en excel con el calculo de las horas que cada integrante debe.


## Issue #278 Implementan de códigos alfanuméricos [Cristian Garzon]:
   - Se modifican cada uno de los mockups según las indicaciones de la nueva tarea, a estos mockups se les agrega el botón de regresar al perfil de jugador y el botón  de ir al mapa de navegación.
   - Se agrega un mockup en el cual se ve lo que muestra el juego cuando ya se ha utilizado un código.


## Issue #252 Algoritmo de navegación y batalla [David yepes]:
   - Se modifica la pantalla final en la cual se muestra el ganador del juego, y se añaden algunos items como monedas y puntos de experiencias.
   - Se le agrega a la pantalla final el botón de volver a navegación y funciona correctamente.
   - Se agrega la pantalla de selección de personaje, pero falta capturar cual se escoge.


## Ausente con excusa [Nicolas Martinez]:
   - No se presenta reporte de Nicolas Martinez pues se encuentre ausente por un compromiso con a universidad, se presentara el reporte por aparte según lo estipulado con el profesor. 


## Issue #220 Login funcional modificado [Ivan Barrantes]:
   - Se completo la primera versión de los servlets y se suben al repositorio.

## Issue #303 XML y javaScript [Ivan Barrantes]:
   - Se hace una pequeña lectura de XML.
   - Se aclara la tarea con camila pues estaba confusa.

## Issue #220 Login funcional modificado [Ernesto Rodriguez]:
   - Ya se completo la estructura de lo se refiere a la conexión, al servidor.
   - Ya se capturan datos desde el JSP y se hace la persistencia en la base de datos.
   - Se están definiendo los métodos de verificación del control del EntityManager.

**Comment by jrsosago** [comment]
Se cierra está Issue, debido a que SCRUM Master subió el reporte.
