### ISSUE TITLE
1.1.18 Conectar perfil jugador, mapa y monedas

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#293]
**Descripción**
Conectar perfil jugador, con mapa de navegación y monedas.
**Tareas a realizar**
- [x] Conectar perfil jugador con mapa de navegación
- [x] Conectar imagen monedas, que le suministre @CamilaG08 con mapa de navegación
- [x] Poner el label que tendrá la cantidad de monedas

**Comment by CamilaG08** [comment]
Se adjunta la imagen de las monedas:

![monedas](https://cloud.githubusercontent.com/assets/22283896/24641822/550e7134-18c8-11e7-9fc4-136f21210d27.jpg)

**Comment by gabogabbs** [comment]
Se añade la imagen de las monedas modificando su tamaño original y borrando el fondo y se añade el label de la cantidad de monedas. Se pone "999999" hasta que el servicio REST respectivo esté implementado. 
![image](https://cloud.githubusercontent.com/assets/21046810/24781781/9b367da0-1b07-11e7-8e7d-916e14f0ded8.png)

REGISTRO DE TIEMPO: 30 MINUTOS.

**Comment by gabogabbs** [comment]
La conexión del perfil de jugador no se ha realizado debido a que la persona encargada de dicha ventana no ha subido el código al repositorio aún.

**Comment by gabogabbs** [comment]
Se le da ayuda con la implementación y ajustes gráficos a @juankrlos08 para la ventana de Perfil de Jugador.
[perfilJugador.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/906963/perfilJugador.zip)

REGISTRO DE TIEMPO: 30 MINUTOS.

**Comment by CamilaG08** [comment]
Se cierra el Issue debido a la correcta entrega de las tareas.
