### ISSUE TITLE
5.8 Documento detallado implementación del joystick

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#295]
**Descripción:**

- [x] Realizar un documento detallado sobre la implementación del joystick en phaser y en el juego, teniendo en cuenta funcionalidad de botones acordes a los componentes del campo de batalla.

**Comment by KmiArthur** [comment]
Adjunto documento de instalación y explicación para el joystick en phaser. En el ejemplo está el código con las imágenes para ejecutar.
(Trabajo: 5h)

[Joystick para phaser.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/888722/Joystick.para.phaser.zip)

**Comment by CamilaG08** [comment]
@dayepesb y @nicolas96  revisar el documento para dar la tarea como finalizada.

**Comment by CamilaG08** [comment]
Se cierra ya que el documento cumple con lo requerido.
