### ISSUE TITLE
1.8.6 JavaScript, JSON, Base de datos.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#296]
**Descripción**
Averiguar como se conecta y maneja JavaScript con JSON, JSON con Base de datos.
**Tareas a realizar**
- [x] Realizar investigación de como se maneja JavaScript con Base de datos usando como medio de comunicación JSON.
- [x] Documentar item anterior.
- [ ] Realizar un ejemplo del item 1.
- [ ] Realizar pruebas del item 1 con el juego.

**Comment by ghost** [comment]
Se habla con el Profesor Diego Oliveros, y se me asigna como nueva tarea investigar como se consume un servicio REST mediante java script

- [x] Investigar como consumir un servicio REST con javascript
- [x] Realizar un documento explicando esto
- [x] Mostrar un ejemplo

**Comment by ghost** [comment]
## Documentación y explicación de como consumir un servicio REST con JavaScript (Registro de tiempo: hora y media)

[Consumir Servicios REST mediante JavaScript con JSON.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/904693/Consumir.Servicios.REST.mediante.JavaScript.con.JSON.pdf)

**Comment by CamilaG08** [comment]
Se cierra ya que la implementación  pruebas del consumo de servicios se reasigna.
