### ISSUE TITLE
1.2.11 Modificaciones al perfil del jugador

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#297]
**Descripción:**

Realizar modificaciones al perfil de jugador, respecto a la revisión previamente hecha por Dario y Camila.

**Tareas:**

- [x] Ajusta la vista de los botones a los creados en las otras secciones
- [x] Hacer funcional el botón de logros
- [x] Hacer funcional el botón de códigos alfanuméricos
- [x] Agregar botón para volver al mapa de navegación
- [x] Hacer funcional el botón para volver al mapa de navegación
- [x] Hablar con @gsalvarez parra ajustes gráficos

**Comment by juankrlos08** [comment]
![image](https://cloud.githubusercontent.com/assets/25808382/24726039/8bfadd32-1a16-11e7-94aa-9dfac2ab59a6.png)

**Comment by juancelemin** [comment]
2017-04-05 15:43 GMT-05:00 juankrlos08 <notifications@github.com>:

**Comment by juankrlos08** [comment]
Se efectuaron los cambios que se presentaron al inicio de este issue donde se emplearon 4 horas de trabajo
- Ajuste de la vista de los botones a los creados en las otras secciones 
- Funcionamiento del botón de logros
- Funcionamiento el botón de códigos alfanuméricos
- Agrego botón para volver al mapa de navegación 
- Funcionamiento del botón para volver al mapa de navegación 
- Se modificaron unoas imagenes del issue de logros anteriormente desarrollado


Para el desarrollo de este issue se tuvo en cuenta la colaboracion de @gsalvarez para la implementacion del perfil y ajustes gráficos en el proyecto. 30 minutos de trabajo.

**Comment by CamilaG08** [comment]
Se cierra el Issue dado que se entrega el perfil del jugador y se realiza el commit en el repositorio.
