### ISSUE TITLE
5.4.3 Documentación del Código

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#298]
**Descripción**
Documentación del código
**Tareas a realizar**
- [x] Modificar game.js.
- [x] Explicar y documentar invitarAmigos.js.
- [x] Explicar y documentar perfilJugador.js.
- [x] Explicar y documentar logros.js.

**Comment by ghost** [comment]
## Explicación y documentación de game.js, invitarAmigos.js, Logros.js y perfilJugador.js (Registro de tiempo: 2 horas)

[DocumentacionCodigoFront_09-04.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/909102/DocumentacionCodigoFront_09-04.docx)
