### ISSUE TITLE
Pacto de honor división general equipo #1

### ISSUE THREAD

**Issue by ingenieriadelsoftware** [ISWPOLI/Pacto-de-Honor#3]
Pacto de honor división general
![whatsapp image 2017-02-14 at 16 56 48](https://cloud.githubusercontent.com/assets/17440675/22951329/c6282f08-f2d6-11e6-95bb-1bac4089949b.jpeg)

**Comment by nmartinezmarin** [comment]
En el proyecto juego se crean las distintas actividades que fueron asignadas a los distintos sub grupos
https://github.com/ISWPOLI/Pacto-de-Honor/projects/2

**Comment by nmartinezmarin** [comment]
- [x] crear un issues por cada asignación de trabajo 
Cuando se asigno este issue no se había quedado clara la forma en la que íbamos a utilizar en git hub, así que se asignaron estas primeras tareas y después se reorganizaron con las características establecidas
