### ISSUE TITLE
3.1.1 Prototipo Campo de Batalla

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#30]

**Comment by dayepesb** [comment]
[juego.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/784871/juego.zip)

aca va la continnuación del prototipo
ya haciendo que el muñeco se mueva de un lado a otro
Falta:
-Cronometro de un minuto y medio
-golpes cuerpo a cuerpo
-inteligencia artificial del enemigo
-Menu de pausa

**Comment by gabogabbs** [comment]
[AvancePrototipo.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/786190/AvancePrototipo.zip)
 El muñeco ejecuta la animación al moverse y al atacar.
