### ISSUE TITLE
1.1.1 Documento de Control de Cambios

### ISSUE THREAD

**Issue by JuanCheroslan** [ISWPOLI/Pacto-de-Honor#302]
Documento oficial del control de cambios solicitados por el front end

- [ ] Documento

**Comment by CamilaG08** [comment]
Se adjunta la primera versión de las modificaciones: 

[Documento de control de cambios V1.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/892045/Documento.de.control.de.cambios.V1.pdf)

Tiempo empleado: 1 hora y 30 minutos

**Comment by JuanCheroslan** [comment]
se realiza reunion de integracion con el lider de frontend ( @CamilaG08 ) y se definio que sobre el documento presentando solo se deben agregar la tabla de logros y logrosxJugador, esta tabla debe ser administrable desde el modulo administrador.

@CamilaG08  esta pendiente el documento con la descripcion de los campos requeridos  para los logros

tiempo empleado 1 hora

**Comment by CamilaG08** [comment]
Se envía el documento requerido por parte de @juankrlos08 y @juancelemin

**Comment by CamilaG08** [comment]
Se incluye el nuevo documento especificando los requerimientos @JuanCheroslan .

Queda pendiente la discusión de la sección de ránking.

**Tiempo empleado: 2 horas**

[DatosJSON_Servicios.xlsx](https://github.com/ISWPOLI/Pacto-de-Honor/files/912004/DatosJSON_Servicios.xlsx)

**Issue pendiente por cerrar del Sprint 8**
