### ISSUE TITLE
1.8.7 XML y JavaScript

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#303]
**Descripción**
Realizar investigación de como pegar una frase a una imagen usando XML y JavaScript.Reposición 40 minutos
**Tareas a realizar**
- [x] Investigación de como pegar una frase a una imagen usando XML y JavaScript.

**Comment by ivandav** [comment]
Se entrega un documento con la explicación de la tarea.
[javascript imagtext.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/904385/javascript.imagtext.pdf)
