### ISSUE TITLE
4.3 Implementación módulo Administración

### ISSUE THREAD

**Issue by zergiozerna81** [ISWPOLI/Pacto-de-Honor#307]
- Construir el Login al módulo de administración. @zergiozerna81

- Construir la página Home del modulo de Administración. @rzambrano112 

- Construir los módulos que permitan realizar la administración de las siguientes entidades:

- [x] Mundo @rzambrano112 
- [x] Nivel @rzambrano112 
- [x] Personaje @zergiozerna81
- [x] Frase @Lakes1234 
- [x] Categoría @Lakes1234 
- [x] Imagen @Lakes1234 
- [x] Poder @alexsabsan 
- [x] Usuario @alexsabsan 
- [x] Rol usuario @alexsabsan 
- [x] Ciudad @zergiozerna81
- [x] País @rzambrano112 
- [x] Reportes @Lakes1234

**Comment by alexsabsan** [comment]
[Modulo Administrador.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/888889/Modulo.Administrador.zip)

Cargue version de Modulo Administracion
de Rol usuario, Usuario y Poder

Poderian aclararme que llevaria dentro cada una??

**Comment by rzambrano112** [comment]
Carge de versión de Home del Modulo Administración
![image](https://cloud.githubusercontent.com/assets/20976993/24683154/0402ee6e-1963-11e7-9879-43552bee19aa.png)

**Comment by alexsabsan** [comment]
Se carga vesion nueva del modulo de administracion 
[Mod v1 Azul.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/901160/Mod.v1.Azul.zip)

**Comment by alexsabsan** [comment]
[Mod v0.2.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/901334/Mod.v0.2.zip)
Adjunto las siguientes paginas preliminares de navegación del modulo de administración

- [x] Mundo 
- [x] Nivel 
- [x] Personaje 
- [x] Frase 
- [x] Categoría 
- [x] Imagen 
- [x] Poder 
- [x] Usuario 
- [x] Rol usuario

**Comment by alexsabsan** [comment]
[Mod v0,3.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/915357/Mod.v0.3.zip)

Modulo de administración navegación  completo

**Comment by rzambrano112** [comment]
Se cierra issue #307 debido a la implementación de los módulos de administración.

**Comment by rzambrano112** [comment]
Se cierra issue #307 debido a la implementación de los módulos de administración.
