### ISSUE TITLE
7.1.2 Identificar campos del formulario de login.

### ISSUE THREAD

**Issue by ghost** [ISWPOLI/Pacto-de-Honor#308]
- [x] Identificar del Modelo de ER cuales son los datos a persistir

- [x] Identificar de las redes sociales cuales datos se persisten para el login.

- [x] Determinar la funcionalidad y persistencia de los datos

**Comment by DiegOliveros** [comment]
Estas funciones deben ser acordadas con el equipo de gestión de proyecto, no son auto gestionadas.

**Comment by ghost** [comment]
@DiegOliveros  Estas funciones, se determinaron con los product owner Juan camilo y Yeimi ya que se requerían para poder continuar con las gestiones en conexión JPA con la administración de persistencia ya  si se requiere de una contextualización se puede realizar.

**Comment by ghost** [comment]
- [ ]  Identificar del Modelo de ER cuáles son los datos a persistir
- [ ]  Determinar la funcionalidad y persistencia de los datos

Según modelo ER.

![image](https://cloud.githubusercontent.com/assets/25758763/24713177/75c3e49a-19ea-11e7-8c84-503cadd74917.png)

Y lo determinado en las conversaciones con los product owner del equipo de gestión de proyecto se determinaron los datos a persistir, por lo que el login se realizo en función de estos.

**Comment by ghost** [comment]
- [x]  Identificar de las redes sociales cuales datos se persisten para el login.

De lo determinado con los product owner del equipo de gestión del proyecto se determinaron que los datos a persistir son: el **ID** de la aplicación en cada red social y el **Token** generado por la red social, y poder determinar de estos si se usan nombres de usuario de redes sociales  y correo, esta gestión continua en verificación ya que se determina que el relogueo de todas las redes no es claro.

**Comment by ghost** [comment]
Se define que los datos en cuanto a redes sociales que van a tener una permanencia son ID de aplicación Token para consultas al api, y del relogin los datos serian usuario y correo como opción pero queda a disposición para poder elegir.
