### ISSUE TITLE
3.1.2 Escenarios, Mockups e historias de Usuario Campo de Batalla

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#31]
**Descripción**

Como el grupo asignado a la selección de personajes vamos a realizar los mockups para dar mostrar como va ser la navegación de los usuarios por el juego, luego se realizara la codificación y sus respectivas pruebas.
El grupo también se encargara de animar los escenarios correspondientes a diferentes instalaciones del Politécnico Grancolombiano.
Por ultimo se crearan las historias de usuario.

**Caracteristicas**

- [x] Escenarios
- [x] Mockups
- [x] Historias de Usuario
- [x] Informe

**Comment by ghost** [comment]
# **ESCENARIOS** (Registro de Tiempo: 6 horas)

![bienestar lluvia](https://cloud.githubusercontent.com/assets/22629833/23090370/f79151c8-f56a-11e6-838a-ef152df09c84.gif)
![bienestar nieve](https://cloud.githubusercontent.com/assets/22629833/23090368/f790f872-f56a-11e6-8a15-e28dd85eadd4.gif)
![bienestar sol](https://cloud.githubusercontent.com/assets/22629833/23090367/f78e6f44-f56a-11e6-8eca-b9a24a8c3cad.gif)
![bloque c lluvia](https://cloud.githubusercontent.com/assets/22629833/23090371/f7940fee-f56a-11e6-8d26-69b23ae9ddc8.gif)
![bloque c nieve](https://cloud.githubusercontent.com/assets/22629833/23090369/f7910d26-f56a-11e6-89b0-8001833ebf19.gif)
![bloque c sol](https://cloud.githubusercontent.com/assets/22629833/23090366/f78adf1e-f56a-11e6-92e8-1a4471543a2c.gif)
![bloque g lluvia](https://cloud.githubusercontent.com/assets/22629833/23090373/f7ce25a8-f56a-11e6-9901-c9b49b75a2b7.gif)
![bloque g nieve](https://cloud.githubusercontent.com/assets/22629833/23090372/f7cd421e-f56a-11e6-9ae3-8fa13b9b114a.gif)
![bloque g sol](https://cloud.githubusercontent.com/assets/22629833/23090375/f7d1bd9e-f56a-11e6-94a6-cb0aee18e386.gif)
![bloque j lluvia](https://cloud.githubusercontent.com/assets/22629833/23090383/f7f35efe-f56a-11e6-9f18-794a4f888e79.gif)
![bloque j nieve](https://cloud.githubusercontent.com/assets/22629833/23090378/f7f0bca8-f56a-11e6-91ac-aa9315f170b1.gif)
![bloque j sol](https://cloud.githubusercontent.com/assets/22629833/23090379/f7f0cd74-f56a-11e6-9d00-38b045c29dba.gif)
![bloque k lluvia](https://cloud.githubusercontent.com/assets/22629833/23090381/f7f29ec4-f56a-11e6-9fe8-f15bef8929ac.gif)
![bloque k nieve](https://cloud.githubusercontent.com/assets/22629833/23090380/f7f29d0c-f56a-11e6-850e-9ef6643b2e8e.gif)
![bloque k sol](https://cloud.githubusercontent.com/assets/22629833/23090382/f7f38a82-f56a-11e6-9804-e9d657a5ab81.gif)
![cancha lluvia](https://cloud.githubusercontent.com/assets/22629833/23090384/f806250c-f56a-11e6-8a6c-3d6eacf4cc69.gif)
![cancha nieve](https://cloud.githubusercontent.com/assets/22629833/23090385/f8064c30-f56a-11e6-8db3-d3bdee1ebd58.gif)
![cancha sol](https://cloud.githubusercontent.com/assets/22629833/23090386/f806a14e-f56a-11e6-9d3e-8230464c875a.gif)
![paradero lluvia](https://cloud.githubusercontent.com/assets/22629833/23090388/f80a1306-f56a-11e6-9527-ec2cde9955ef.gif)
![paradero nieve](https://cloud.githubusercontent.com/assets/22629833/23090387/f8082ad2-f56a-11e6-86e1-acf3f6312b50.gif)
![paradero sol](https://cloud.githubusercontent.com/assets/22629833/23090389/f80ef9ca-f56a-11e6-87ea-abd5a648bf3a.gif)
![plazoleta lluvia](https://cloud.githubusercontent.com/assets/22629833/23090391/f817f1f6-f56a-11e6-9e96-7b82b4ebd812.gif)
![plazoleta nieve](https://cloud.githubusercontent.com/assets/22629833/23090392/f8181dac-f56a-11e6-80d9-c354dad07286.gif)
![plazoleta sol](https://cloud.githubusercontent.com/assets/22629833/23090390/f817102e-f56a-11e6-875c-3ff1365b61b3.gif)
![poli medellin lluvia](https://cloud.githubusercontent.com/assets/22629833/23090393/f818ccac-f56a-11e6-8ecf-78b9e8d32f75.gif)
![poli medellin nieve](https://cloud.githubusercontent.com/assets/22629833/23090394/f81c7834-f56a-11e6-9db8-90f09f4b99d8.gif)
![poli medellin sol](https://cloud.githubusercontent.com/assets/22629833/23090395/f81f842a-f56a-11e6-8aa0-e4752355be21.gif)
![sede excelencia lluvia](https://cloud.githubusercontent.com/assets/22629833/23090397/f82c446c-f56a-11e6-9d28-9df6513e4067.gif)
![sede excelencia nieve](https://cloud.githubusercontent.com/assets/22629833/23090398/f82c9174-f56a-11e6-914a-1672b8d8d249.gif)
![sede excelencia sol](https://cloud.githubusercontent.com/assets/22629833/23090399/f82ca736-f56a-11e6-885c-6b33993be043.gif)
![sede postgrados lluvia](https://cloud.githubusercontent.com/assets/22629833/23090396/f82c7a68-f56a-11e6-9ad5-c415ea8189b3.gif)
![sede postgrados nieve](https://cloud.githubusercontent.com/assets/22629833/23090400/f833f4b4-f56a-11e6-8e20-bd60c3784cc9.gif)
![sede postgrados sol](https://cloud.githubusercontent.com/assets/22629833/23090401/f83485e6-f56a-11e6-857f-03b91e5bbb5b.gif)
![faculad de mercadeo](https://cloud.githubusercontent.com/assets/22629833/23539491/c47be246-ffa9-11e6-93fa-a297ab4d3bb4.gif)
![facultad de ciencias administrativas](https://cloud.githubusercontent.com/assets/22629833/23539492/c47dd43e-ffa9-11e6-8009-e888786ac0ab.gif)
![facultad de ciencias sociales](https://cloud.githubusercontent.com/assets/22629833/23539493/c497baa2-ffa9-11e6-9bcf-85dd8e174831.gif)
![facultad de ingenieria](https://cloud.githubusercontent.com/assets/22629833/23539494/c49837c0-ffa9-11e6-9604-cd2b5cd7c54a.gif)

**Comment by ivandav** [comment]
# **MOCKUPS** (Registro de Tiempo: 4 horas, 30 minutos)

![16790454_10210901121819191_89861060_n](https://cloud.githubusercontent.com/assets/22629584/23090458/b4beb2c6-f56c-11e6-8e58-b6e3b1f350f7.png)
![16790498_10210901122779215_1715342859_n](https://cloud.githubusercontent.com/assets/22629584/23090459/b4bf675c-f56c-11e6-9d0e-7ed172cface9.png)
![16790698_10210901122979220_1409603747_n](https://cloud.githubusercontent.com/assets/22629584/23090457/b4be88fa-f56c-11e6-929c-db3828fc2680.png)
![16808393_10210901123099223_973359135_n](https://cloud.githubusercontent.com/assets/22629584/23090461/b4c07f7a-f56c-11e6-8512-77c790e72a3c.png)
![16809097_10210901121379180_2131235302_n](https://cloud.githubusercontent.com/assets/22629584/23090460/b4c08f4c-f56c-11e6-8e43-7f7ccf573f92.png)
![16809522_10210901122859217_938486899_n](https://cloud.githubusercontent.com/assets/22629584/23090462/b4c0afea-f56c-11e6-9aa8-1efd31f4d12d.png)
![16830567_10210901121259177_376286152_n](https://cloud.githubusercontent.com/assets/22629584/23090463/b4dc6ea6-f56c-11e6-8fa0-847cb33de71a.png)
![16831382_10210901121899193_559648240_n](https://cloud.githubusercontent.com/assets/22629584/23090464/b4e0192a-f56c-11e6-9853-8b5d21e1e4c1.png)
![16831626_10210901123059222_2003030678_n](https://cloud.githubusercontent.com/assets/22629584/23090465/b4e18b20-f56c-11e6-8bb0-8300c4174637.png)
![16831691_10210901122659212_201230010_n](https://cloud.githubusercontent.com/assets/22629584/23090466/b4e72d64-f56c-11e6-9d4d-f701c7e8f6d4.png)
![16837853_10210901122219201_394946649_n](https://cloud.githubusercontent.com/assets/22629584/23090467/b4ed75f2-f56c-11e6-9bcb-6b193d1d0bb9.png)

**Comment by CristianGarzonBernal** [comment]
# **HISTORIAS DE USUARIO** (Registro de Tiempo: 2 Horas)

[Historias-de-usuario-nuevas.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/784792/Historias-de-usuario-nuevas.docx)

**Comment by CristianGarzonBernal** [comment]
# **INFORME**

[Informe.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/784793/Informe.docx)
