### ISSUE TITLE
2.6 Servicio REST Personaje

### ISSUE THREAD

**Issue by EdnaEspejo** [ISWPOLI/Pacto-de-Honor#313]
- [x] Documentación
- [x] Código
- [x] Pruebas

**Comment by DiegOliveros** [comment]
Por favor incluir tiempos de estimación en las historias. @jnrubiano @EdnaEspejo

**Comment by jnrubiano** [comment]
Desarrollo en el commit 066a42ea79e0a11419546aea8cc39bfcbb13d79e
Pruebas en el commit a9df9b5ba795071808e394c7ce0a8a62ece92a4b
Documentación en el commit e198f4ca92e001331250183391cc76d18364ccbd
