### ISSUE TITLE
2.7 Servicio REST Personaje

### ISSUE THREAD

**Issue by EdnaEspejo** [ISWPOLI/Pacto-de-Honor#314]
- [x] Documentación
- [x] Código
- [x] Pruebas

**Comment by jnrubiano** [comment]
Se culmina el servicio Personaje (a9df9b5ba795071808e394c7ce0a8a62ece92a4b) con el respectivo método solicitado por el profesor Diego, éste último fue el que primero se entregó el día sábado 8 de Abril en el commit 066a42ea79e0a11419546aea8cc39bfcbb13d79e

**Comment by jnrubiano** [comment]
Se sube la documentación del servicio en el Branch "Consolidacion" en la carpeta "Documentación" en el commit e198f4ca92e001331250183391cc76d18364ccbd

**Comment by jnrubiano** [comment]
Se actualiza el servicio (Código) y la documentación generando el archivo versión 0.2
Commit: 93eb06a3d6802351584755206b10837e67094e27 @jnrubianoqantica jnrubianoqantica committed 4 hours ago

**Comment by jnrubiano** [comment]
Se deben realizar los cambios de acuerdo a los requisitos que se acordaron entre Frontend y Juan Camilo.
Se pasa a Sprint 11
