### ISSUE TITLE
2.9 Servicio REST Pruebas

### ISSUE THREAD

**Issue by EdnaEspejo** [ISWPOLI/Pacto-de-Honor#315]
- [x] Documentación
- [x] Código
- [x] Pruebas

**Comment by DanteVDrako** [comment]
Documentación

![image](https://cloud.githubusercontent.com/assets/25806785/25049158/f057d294-2105-11e7-8e6b-714189a9f20b.png)

**Comment by DanteVDrako** [comment]
Código

![image](https://cloud.githubusercontent.com/assets/25806785/25049175/053115ea-2106-11e7-8aa9-9c18ef9f378f.png)

**Comment by DanteVDrako** [comment]
Pruebas

![image](https://cloud.githubusercontent.com/assets/25806785/25060714/d6484d70-2169-11e7-9617-e5c5ca7cf6ff.png)
