### ISSUE TITLE
Definición de las estructuras de JSON

### ISSUE THREAD

**Issue by JuanCheroslan** [ISWPOLI/Pacto-de-Honor#318]
de los JSON generados, solo se necesitan la estructura de la respuesta

- [x] Poder

- [x] Mundo

- [x] Ciudad

- [x]  Nivel

**Comment by DanteVDrako** [comment]
Adjunto estructura JSON generada para entidad Poder

{"descripcionPoder":"OndaVital","formaPoder":38,"imagen":{"foto":"/personaje2/foto1","idImagen":2},"nombrePoder":"KameHameHa","poderPK":{"idImagen":2,"idPoder":55},"potenciaPoder":44,"tipoPoder":32}

**Comment by EdnaEspejo** [comment]
Estructura Nivel
[Estructura - Nivel.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/901166/Estructura.-.Nivel.txt)

**Comment by wpradere** [comment]
Estructura Mundo 

[{"idMundo":1,"nombreMundo":"Cafeteria"},{"idMundo":2,"nombreMundo":"Bloque K"},{"idMundo":3,"nombreMundo":"Plazoleta Principal"}]

**Comment by wpradere** [comment]
Estructura Ciudad 

[{"idCiudad":1,"nombreCiudad":"Bogota"},{"idCiudad":2,"nombreCiudad":"Medellin"},{"idCiudad":3,"nombreCiudad":"Cali"}]
