### ISSUE TITLE
4.2.9 Modificación de las imágenes mundo 1 y 2

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#320]
### Descripción:
Realizar las imágenes de frases retadoras que son al inicio de cada mundo y las frases de victoria o derrota que aparecerían según el resultado de la batalla final. REFERENCIA ISSUE #221

### Tareas:
- [x] Actualización de imagen de Andrés Zorro: Derrota.
- [x] Actualización de imagen de Andrés Zorro: Victoria.
- [x] Actualización de imagen de Andrés Zorro: Frase
- [x] Actualización de imagen de Felipe Oso: Derrota.
- [x] Actualización de imagen de Felipe Oso: Victoria.
- [x] Actualización de imagen de Felipe Oso: Frase

**Comment by KmiArthur** [comment]
Imágenes de Andrés Zorro y Felipe el Oso actualizadas:
`(Trabajo: 4h)`

![halftone2_1](https://cloud.githubusercontent.com/assets/17441569/24734300/33e25a72-1a42-11e7-849f-a03edd0a0728.jpg)
![halftone2_2](https://cloud.githubusercontent.com/assets/17441569/24734303/33e408fe-1a42-11e7-8f6f-f834849ce9c2.jpg)
![halftone2_3](https://cloud.githubusercontent.com/assets/17441569/24734304/33e6091a-1a42-11e7-9780-f9e4b0074503.jpg)
![halftone2_4](https://cloud.githubusercontent.com/assets/17441569/24734302/33e35490-1a42-11e7-85d6-671e844556d4.jpg)
![img_2300](https://cloud.githubusercontent.com/assets/17441569/24734305/33e7101c-1a42-11e7-8027-81f3aa25be83.JPG)
![img_2301](https://cloud.githubusercontent.com/assets/17441569/24734301/33e25996-1a42-11e7-9d94-d2ace39f6c39.JPG)

**Comment by KmiArthur** [comment]
## EXTRA:
Imágenes de Julian el Burro:
`(Trabajo: 1.5h)`

![img_2305](https://cloud.githubusercontent.com/assets/17441569/24734346/6d343f2a-1a42-11e7-8553-bca97dbeb21e.JPG)
![img_2306](https://cloud.githubusercontent.com/assets/17441569/24734347/6d49abd0-1a42-11e7-9270-5ef028b45dd4.JPG)
![img_2307](https://cloud.githubusercontent.com/assets/17441569/24734348/6d5507d2-1a42-11e7-8bdd-3113e96be463.JPG)

**Comment by CamilaG08** [comment]
Se cierra dado que se realizan las imágenes realizadas y corresponden a los textos del mundo1 y 2.
