### ISSUE TITLE
4.3.1 Login

### ISSUE THREAD

**Issue by EdnaEspejo** [ISWPOLI/Pacto-de-Honor#324]
Login para el modulo de administración
- [x] Código
- [x] Pruebas
- [x] Commit al branch respectivo, con evidencia

**Comment by rzambrano112** [comment]
Teniendo en cuenta los css de cada diseño del modulo de administración junto con los css del equipo que esta programando los diseños de los personajes es importante revisar el issue #167 para sincronizar diseños.

**Comment by rzambrano112** [comment]
Se sube un versión temporal del loggin

**Comment by rzambrano112** [comment]
Se anexan avances en la captura de datos de los submodulos del modAdminsitración

**Comment by rzambrano112** [comment]
![image](https://cloud.githubusercontent.com/assets/20976993/25552632/c258c8d4-2c64-11e7-839c-79da810e5760.png)

**Comment by rzambrano112** [comment]
![image](https://cloud.githubusercontent.com/assets/20976993/25552635/d3df00aa-2c64-11e7-8155-941d2d3987d0.png)

**Comment by rzambrano112** [comment]
![image](https://cloud.githubusercontent.com/assets/20976993/25552639/e37f0ee2-2c64-11e7-8278-8bb935185948.png)

**Comment by rzambrano112** [comment]
Se debe realizar una nueva re asignación del issues de login debido a que fue asignado a unos de los compañeros del grupo de administración del modulo durante el segundo corte #324
.

**Comment by rzambrano112** [comment]
Se cierra issues en la espera de una nueva reasignacion #324
