### ISSUE TITLE
4.3.2 Administración Mundos

### ISSUE THREAD

**Issue by EdnaEspejo** [ISWPOLI/Pacto-de-Honor#325]
- [x] Código
- [x] Pruebas
- [x] Commit GitHub + Evidencia

**Comment by rzambrano112** [comment]
En relación al modulo de administración de reportes se realiza el codigo más los commit en Github.
Se anexa las evidencias.

![image](https://cloud.githubusercontent.com/assets/20976993/24826717/d69a1ba4-1c01-11e7-9114-be8cdfe0dcbc.png)
`

**Comment by alexsabsan** [comment]
Navegabilidad del modulo de administración 

[Mod v03.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/915481/Mod.v03.zip)

**Comment by rzambrano112** [comment]
se anexa la evidencia de la navegabilidad del modulo de administración con evidencia en GitHub

Primera versión

![image](https://cloud.githubusercontent.com/assets/20976993/24943296/9354f996-1f1b-11e7-8d4e-e38bb324ee44.png)

**Comment by rzambrano112** [comment]
se anexa la evidencia de la navegabilidad del modulo de administración con evidencia en GitHub

Segunda versión

![image](https://cloud.githubusercontent.com/assets/20976993/24943361/f05a95ba-1f1b-11e7-8e75-4b34e10a11da.png)

**Comment by rzambrano112** [comment]
se anexa la evidencia de la navegabilidad del modulo de administración con evidencia en GitHub

Tercera versión

![image](https://cloud.githubusercontent.com/assets/20976993/24943389/1a5242dc-1f1c-11e7-9e81-f7d78a17d902.png)

**Comment by rzambrano112** [comment]
Se cierra Issues  #325

**Comment by rzambrano112** [comment]
se anexa avances en la navegabilidad del modulo de administración con evidencia en GitHub

[Mod v1.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/924050/Mod.v1.zip)

**Comment by rzambrano112** [comment]
Se anexa avances en la captura de datos en el módAdministración

**Comment by rzambrano112** [comment]
![image](https://cloud.githubusercontent.com/assets/20976993/25552678/a6b68020-2c65-11e7-8614-2d8074ebf952.png)

**Comment by rzambrano112** [comment]
![image](https://cloud.githubusercontent.com/assets/20976993/25552681/b5a73052-2c65-11e7-90b4-e6aca78ac6f6.png)

**Comment by rzambrano112** [comment]
![image](https://cloud.githubusercontent.com/assets/20976993/25552685/c389e098-2c65-11e7-9b87-a1d5f0aaf70b.png)

**Comment by rzambrano112** [comment]
![image](https://cloud.githubusercontent.com/assets/20976993/25552831/9ce8ab28-2c69-11e7-9334-af865e996e7d.png)

**Comment by rzambrano112** [comment]
![image](https://cloud.githubusercontent.com/assets/20976993/25552838/a814b7d0-2c69-11e7-9629-8b50ccbaf01b.png)

**Comment by rzambrano112** [comment]
![image](https://cloud.githubusercontent.com/assets/20976993/25552842/b5db8a1a-2c69-11e7-8475-fe134d46d59a.png)

**Comment by rzambrano112** [comment]
![image](https://cloud.githubusercontent.com/assets/20976993/25552843/c06b98f8-2c69-11e7-9cd6-7775fc698e14.png)

![image](https://cloud.githubusercontent.com/assets/20976993/25552844/ce342c2a-2c69-11e7-8c88-c9de3288aa28.png)

![image](https://cloud.githubusercontent.com/assets/20976993/25552845/d4838238-2c69-11e7-844b-ae3aac972c74.png)

![image](https://cloud.githubusercontent.com/assets/20976993/25552846/dbcd5c44-2c69-11e7-8165-163618c66a5e.png)

![image](https://cloud.githubusercontent.com/assets/20976993/25552847/e24f799e-2c69-11e7-9158-6e6134bbf135.png)

![image](https://cloud.githubusercontent.com/assets/20976993/25552849/e98559d6-2c69-11e7-853b-1f3224ad9278.png)


![image](https://cloud.githubusercontent.com/assets/20976993/25552850/eee84460-2c69-11e7-96e8-112cffbb8485.png)

**Comment by rzambrano112** [comment]
Se realiza avances en la funcionalidad del módulo de administración y la sincronización con Netbeans. Adicionalmente se realiza la captura de datos a través de la funcionalidad del botón agregar desde la base de datos.

**Comment by rzambrano112** [comment]
Se realiza avances en el tema de la integración de la base de datos con el modulo administración.
Se anexa la version de los modulos a la rama consolidacion para el despliegue.

**Comment by rzambrano112** [comment]
![image](https://cloud.githubusercontent.com/assets/20976993/25774054/4ce78b36-324e-11e7-91f1-3359018c3c1c.png)

**Comment by rzambrano112** [comment]
Se da cumplimiento al issues #325.
