### ISSUE TITLE
4.3.3 Navegabilidad Home Modulo Administración

### ISSUE THREAD

**Issue by EdnaEspejo** [ISWPOLI/Pacto-de-Honor#326]
Administración de reportes
- [x] Historia de usuario
- [x] Navegabilidad historia de usuario

**Comment by rzambrano112** [comment]
Se realiza las historias de usuario de la administración de reportes.
Lo anterior teniendo en cuenta aportes de issues anteriores y complementación de los mismos.
Se anexa dichas historias de usuario susceptibles de modificaciones.

**Comment by rzambrano112** [comment]
Historias de usuario de administración de reportes
[Historias de usuario de administración de reportes.xlsx](https://github.com/ISWPOLI/Pacto-de-Honor/files/907171/Historias.de.usuario.de.administracion.de.reportes.xlsx)

**Comment by Lakes1234** [comment]
Se realiza historia de usuario de los primeros reportes a implementar, sujetas a ajustes de acuerdo a revisión con el grupo de trabajo y prioridad del mismo.
[Historias.de.Usuario.Modulo.Reportes V1.xlsx](https://github.com/ISWPOLI/Pacto-de-Honor/files/907190/Historias.de.Usuario.Modulo.Reportes.V1.xlsx)

**Comment by rzambrano112** [comment]
Se anexa mockup provisional al repositorio del modulo de administración de reportes.
![image](https://cloud.githubusercontent.com/assets/20976993/24826667/c8354d82-1c00-11e7-8e8a-8106dd951299.png)

**Comment by rzambrano112** [comment]
Se cierra el issue #326
