### ISSUE TITLE
2.6.2 Servicio Rest Jugador: Codigo Versionado

### ISSUE THREAD

**Issue by JuanCheroslan** [ISWPOLI/Pacto-de-Honor#328]
se debe integrar el codigo al proyecto base y debe garantizarse la funcionalidad de todo el proyecto

- [x] Evidencia de los commits

**Comment by jnrubiano** [comment]
Hola @JuanCheroslan 

Este servicio no tuvo asignación. Lo cogeré ya que dependo de éste para poder realizar el método descrito en el issue #478 

Saludos.

**Comment by jnrubiano** [comment]
Commit 632ffbacca7173d92c6dcefb5d9113fee781c3cf
