### ISSUE TITLE
4.1.1 Realización de Sprites

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#33]
**Descripción**

Realizar los sprites correspondientes a los personajes, buenos, malos y los mini personajes que se utilizarán en el primer prototipo.

**TAREAS**

- [x] Sprite para Andrés Zorro
- [x] Sprite para Felipe Oso
- [x] Sprite mini zorritos
- [x] Sprite mini ositos
- [x] Sprite para Carlos Buitre
- [x] Sprite para Luis Víbora
- [x] Sprite para Camilo Perezoso
- [x] Sprite para Nicolás Lagarto
- [x] Sprite para Víctor Hiena
- [x] Sprite para Fabián Babuino
- [x] Sprite para Julián Burro
- [x] Sprite para Juan Camaleón
- [x] Sprite para Juan Rata
- [x] Sprite para Ana Abeja
- [x] Sprite para Sara Abeja
- [x] Sprite para Iván Ruiseñor
- [x] Sprite para Tati Hormiga
- [x] Sprite para Andrés Gallo
- [x] Sprite para Ana Pantera
- [x] Sprite para Fabián Canario
- [x] Sprite para Cata Cierva
- [x] Sprite para Daniela Jirafa
- [x] Sprite para Daniel León
- [x] Sprite para Pedro Ratón

**Comment by gabogabbs** [comment]
![gallo](https://cloud.githubusercontent.com/assets/21046810/23108304/797b633a-f6d9-11e6-928b-0b2735e6fd2a.png)
Se realiza la primera versión del sprite para Andrés Gallo.

REGISTRO DE TIEMPO: 2 HORAS.

**Comment by ghost** [comment]
Se realiza la primera version del sprite para JUAN RATA. A la espera de una seleccion final de estilos de los personajes.
![juan rata](https://cloud.githubusercontent.com/assets/12540451/23134046/4d91ec98-f761-11e6-8969-c7d683cc2c2f.jpg)

**Comment by KmiArthur** [comment]
PROPUESTA PARA FELIPE EL OSO: TIPO PERSONA REAL (2H)

![oso](https://cloud.githubusercontent.com/assets/17441569/23135801/0264dec2-f768-11e6-9841-3e00292ef890.gif)
![oso](https://cloud.githubusercontent.com/assets/17441569/23135815/09c59f08-f768-11e6-976f-5851b316913b.png)

**Comment by CamilaG08** [comment]
Chicos @gsalvarez , @JuanSebastianRodriguezJ , @KmiArthur , recuerden que los dos primeros mundos necesitan a Andrés Zorro , Felipe oso y al menos 3 buenos.

**Comment by gabogabbs** [comment]
![canario](https://cloud.githubusercontent.com/assets/21046810/23194716/ca76b49c-f87d-11e6-9d3c-e8d044b8e66e.png)
![cierva](https://cloud.githubusercontent.com/assets/21046810/23194717/ca7b85ee-f87d-11e6-95cf-6d576e65405c.png)
![gallo](https://cloud.githubusercontent.com/assets/21046810/23194718/ca85efca-f87d-11e6-80ba-2a7be654a5b0.png)
![hormiga](https://cloud.githubusercontent.com/assets/21046810/23194721/ca8a793c-f87d-11e6-9dc8-3636a8638833.png)
![jirafa](https://cloud.githubusercontent.com/assets/21046810/23194719/ca86de1c-f87d-11e6-938c-83812a276532.png)
![leon](https://cloud.githubusercontent.com/assets/21046810/23194720/ca897398-f87d-11e6-93a6-daec5d15d3ab.png)
![pantera](https://cloud.githubusercontent.com/assets/21046810/23194722/ca8cc782-f87d-11e6-82d2-bba430c0655c.png)
![raton](https://cloud.githubusercontent.com/assets/21046810/23194723/ca963ce0-f87d-11e6-8213-227c77c5a8cf.png)

Se adjuntan los Spritesheets de Cata Cierva, Daniel León, Pedro Ratón, Ana Pantera, Daniela Jirafa, Tati Hormiga, Fabián Canario y la actualización del especial de Andrés Gallo.

REGISTRO DE TIEMPO: 8 HORAS.

**Comment by KmiArthur** [comment]
SPRITE: _Andrés Zorro_ (1H)

![zorro](https://cloud.githubusercontent.com/assets/17441569/23199675/d531aaf2-f89d-11e6-9d30-eff4ad253d3a.png)

**Comment by KmiArthur** [comment]
SPRITE: Felipe Oso (1H)

![plantilla sprites 001](https://cloud.githubusercontent.com/assets/17441569/23218998/d8cb1916-f8eb-11e6-9fbe-9730df4d1478.png)

**Comment by CamilaG08** [comment]
Se cierra a pesar de no estar completo, con el fin de crear nuevas tareas individuales y así seguir la metodología y el registro de tiempo de trabajo.
