### ISSUE TITLE
2.7.1  Servicio REST Personaje: Documentacion

### ISSUE THREAD

**Issue by JuanCheroslan** [ISWPOLI/Pacto-de-Honor#330]
Documento del servicio, incluyento todos los metodos que se necesitan en la entidad

- [x] Documento

**Comment by wpradere** [comment]
[javadoc.rar.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/923976/javadoc.rar.txt)
Se crea la documentación para el servicio Rest Personaje Java doc
