### ISSUE TITLE
1.1.19 Textos tipo plagio

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#338]
**Descripción**
Textos tipo plagio.
**Tareas a realizar**
- [x] Documento con especificación de los textos que acompañaran cada imagen de tipos de plagio.
- [x] Realizar mockups de cada tipo de plagio con su imagen y texto.

**Comment by jrsosago** [comment]
**No se asignan más actividades hasta que se termine está.**

**Comment by jrsosago** [comment]
La imagen de cada tipo de plagio se encuentra en la Issue #134 y la información respectiva de cada imagen se encuentra en la Issue #26

**Comment by jdbernalv** [comment]
Se realiza el documento completo con las descripciones solicitadas. Quedo atento para realizar cualquier modificación en caso de ser necesario. @jrsosago @CamilaG08 
[1.1.19 Textos tipo plagio #338 - Jaime D. Bernal.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/924055/1.1.19.Textos.tipo.plagio.338.-.Jaime.D.Bernal.docx)

**Comment by jrsosago** [comment]
**Descripción**
Separar texto de Imágenes para implementación XML
**Tareas a realizar**
- [x] Documento con textos de cada Imagen.
- [x] Imágenes de cada tipo de plagio sin texto.

**Comment by jdbernalv** [comment]
Se adjunto documento en Word con las imágenes sin el texto de los tipos de plagio por solicitud de @jrsosago 
[Issue 338 - Imagenes sin Texto..docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/953493/Issue.338.-.Imagenes.sin.Texto.docx)
