### ISSUE TITLE
1.1.20 Finalizar módulo de batalla / Responsive

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#339]
**Descripción**

Terminar el módulo de Batallas y agregarle la función responsive.

**TAREAS**
- [x] Integrar botones de poderes @gsalvarez
- [x] Mejorar el movimiento del villano , agregar los poderes restantes y arreglar bugs @nicolas96 tiempo empleado: 7 horas.
- [x] Asegurarse que el juego se vea bien en diferentes pantallas (Ajustar componentes del campo de batalla)@dayepesb @nicolas96
- [x] Cambiar la estructura del campo de batalla para que se pueda construir a partir de Json @nicolas96 5 horas

**Comment by CamilaG08** [comment]
**Recuerden que no se asignan nuevas tareas si esta no está terminada**

**Comment by nmartinezmarin** [comment]
En el merge #400 se añaden  funciones para que se pueda visualizar el juego en diferentes pantallas
*Se añaden las funciones para mover la orientación del dispositivo

*Se añade un estado con una barra de carga para configurar todos los
ajustes de la pantalla

*Se añaden funciones para saber desde que dispositivo se visualiza 
https://github.com/ISWPOLI/Pacto-de-Honor/pull/400
Tiempo registrado : 5 horas

**Comment by jrsosago** [comment]
Se cierra Issue, por actividades realizadas.
