### ISSUE TITLE
5.3.2 Recopilar y consolidar la documentación

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#34]
**Descripción**

Recopilación de la documentación que se encuentra en GitHub y que será subida a través del desarrollo del proyecto; consolidar los fragmentos en un sólo documento y crear un repositorio de documentación.

**TAREAS**

- [x] Recopilar historias de usuario de combates
- [x] Recopilar historias de usuario de escenarios y navegación
- [x] Recopilar documentos del equipo de combate
- [x] Recopilar Mockups del equipo de combate
- [x] Recopilar documento equipo de escenarios y navegación
- [x] Recopilar Mockups del equipo de escenarios y navegación
- [x] Recopilar documento del equipo de tipos de plagio
- [x] Recopilar documento del equipo de personajes
- [x] Estar pendiente de la documentación que se suba en los nuevos Issues (11 - 12)

**Comment by jdbernalv** [comment]
- Se definen los Issues para analizar y posteriormente realizar las descargas
 1) Prototipo Campo de Batalla, 2) Escenarios Mockups e historias de usuario campo de batalla, 3) Definir Perfil Psicológico personajes.
- Se realiza la descarga de las historias de usuario de combates, historias de usuario de escenarios y navegación, documentos y Mockups del equipo de combate, documento y Mockups del equipo de escenarios y navegación, documento del equipo de tipos de plagio y documento del equipo de personajes.
- Se realiza la revisión de todos los archivos, imagenes y textos de cada Issue. 
- Se realiza la revisión de la plantilla del documento con normas IEEE.
- Se realiza reunión con un integrante del grupo "Prototipo Campo de Batalla" para entender un poco mas la idea y la ejecución de lo realizado.
- Se solicita al docente Diego Oliveros un reporte con las tareas realizadas por cada estudiante, con el fin de detallar el documento puntualmente.

**Comment by jdbernalv** [comment]
Se realiza la consolidación en un documento de :
 - Las historias de usuario, documentos y Mockups de combates.
 - Las historias de usuario, escenarios, navegación y Mockups de navegación.
 - Documento del equipo de tipos y estandarización del tipo de plagio. 
 - Documento de comportamiento de personajes buenos y malos con los poderes asociados.

Observaciones: Se analizara con mas detenimiento el formato IEE830 para incluir el documento adjunto y desglosar mas el contenido de otras actividades.
[Recopilar y Consolidar la Documentación.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/802423/Recopilar.y.Consolidar.la.Documentacion.pdf)

**Comment by CamilaG08** [comment]
De ahora en adelante, se manejará la documentación en la Épica creada la semana pasada, por lo tanto este Issue se cierra debido a la correcta entrega de lo solicitado.
