### ISSUE TITLE
5.4.5 Creación de la librería del juego

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#340]
### **Descripción**

Crear la librería del juego, basado en el código que se encuentra en el repositorio.

### **TAREAS**

- [x] Investigar sobre la creación de librerías
- [x] Revisar el código de batalla
- [x] Revisar el código de historieta
- [x] Revisar el código de navegación
- [x] Revisar el código del perfil del jugador
- [x] Revisar en código de la sección de logros
- [x] Revisar el código de la sección de selección de avatar
- [x] Revisar el código de la sección de selección de personaje
- [x] Revisar el código del módulo de compra de personajes
- [x] Crear la librería del juego

**Comment by KmiArthur** [comment]
Revisión de librerías y se crea una a partir del código de la historieta, aún no se unifican funciones.
`Trabajo: 12h`

[library.js.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/921435/library.js.zip)

**Comment by CamilaG08** [comment]
Se mueve al Sprint 9 dado que el tiempo de la creación de la librería es extenso.

**Comment by KmiArthur** [comment]
Revisión de librerías y se crea una a partir del código de la navegación, aún no se unifican funciones.
`Trabajo: 7h`

[library.js.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/924045/library.js.zip)

**Comment by CamilaG08** [comment]
Para completar esta tarea, apoyarse con @jdma0440 quien documenta el código.

**Comment by CamilaG08** [comment]
Se cierra dado el avance presentado por @KmiArthur y se asignará más adelante a @jdma0440 que es el encargado de la documentación y estructuración del código.
