### ISSUE TITLE
1.12 Propuesta de manejo de las cajas sorpresa

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#341]
**Descripción**

Crear un documento con una propuesta detallada del manejo de las caja sorpresa dentro del juego.

**TAREAS**

- [x] Definir cuántas cajas sorpresa aparecerán
- [x] Definir el contenido (las recompensas) de cada caja
- [x] Definir el criterio de aparición de las cajas en el juego
- [x] Detallar en pseudo - código el manejo de estas cajas

**Comment by juankrlos08** [comment]
Se propone que aparezcan 7 tipos de cajas sorpresas cada una de ellas con diferentes sorpresas para nuestros usuarios. 

![mysterybox7](https://cloud.githubusercontent.com/assets/25808382/24920002/38a5d4fe-1eab-11e7-8f78-64dd51f8b3a5.png)
![mysterybox1](https://cloud.githubusercontent.com/assets/25808382/24920003/38b6a2a2-1eab-11e7-97c5-402160fc4640.png)
![mysterybox2](https://cloud.githubusercontent.com/assets/25808382/24920004/38b742ac-1eab-11e7-946d-5da83fd9b5aa.png)
![mysterybox3](https://cloud.githubusercontent.com/assets/25808382/24920006/38ba344e-1eab-11e7-8f44-fb080bf07610.png)
![mysterybox4](https://cloud.githubusercontent.com/assets/25808382/24920005/38b8a4d0-1eab-11e7-9344-34f7e228a179.png)
![mysterybox5](https://cloud.githubusercontent.com/assets/25808382/24920007/38ba5000-1eab-11e7-9088-bdd3a7535be6.png)
![mysterybox6](https://cloud.githubusercontent.com/assets/25808382/24920008/38bed4b8-1eab-11e7-8470-8fe1a1bd6f19.png)

**Comment by juankrlos08** [comment]
[jueves 13.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/920073/jueves.13.pdf)

Se escriben cada una de las carateristicas de las cajas que se van a desarrollar y tambien el tiempo en el que se pueden activar estas cajas sorpresas

**Comment by CamilaG08** [comment]
**Modificaciones**

- Sólo una caja por pelea.
- Cada tipo de caja está disponible una vez por cada 2 mundos.
- Respecto a la segunda caja, lo que se puede es aumentar porcentaje en la barra de energía, ya que no se pueden agregar poderes.
- Probar el funcionamiento de la 4ta caja con los chicos de combates.
- Las últimas 3 cajas tienen como descripción afectar al usuario, corregir eso ya que queremos afectar al oponente no al mismo usuario.
- Agregar una caja más que aparecerá en algunos niveles/escenarios que tendrá recompensas como: Puntos de vida, puntos de experiencia y monedas.

**Comment by CamilaG08** [comment]
**Recuerda que no se asignan más tareas hasta estar esta finalizada y que la fecha de finalización era el día 14 de abril**

**Comment by juankrlos08** [comment]
Se modificaron las cajas sorpresas segun la peticion asignada: 

- Caja numero dos ayuda al usuario con la barra del poder a la hora de ser obtenida.
- Las ultimas tres cajas quedan de la misma manera como se habían descrito, ya que se decidió con Camila que le da algo de emoción al juego.
- Se adjuntan modificaciones de las cajas cuando se abren por el usuario.
- Se agrega una caja mas donde el usuario va a ganar monedas o puntos de experiencia o puntos de vida.

**Comment by juankrlos08** [comment]
![caja7explosion](https://cloud.githubusercontent.com/assets/25808382/25286914/060c53ec-2685-11e7-9bb2-a49e40418dee.png)
![caja8explosion](https://cloud.githubusercontent.com/assets/25808382/25286918/060eb9ca-2685-11e7-95b5-e3bbbb96044f.png)
![caja9](https://cloud.githubusercontent.com/assets/25808382/25286915/060c2c46-2685-11e7-9aff-8c52f4c9a613.png)
![caja9explosion](https://cloud.githubusercontent.com/assets/25808382/25286916/060d2f6a-2685-11e7-97d2-e80315c4b7bc.png)
![caja1explosion](https://cloud.githubusercontent.com/assets/25808382/25286919/0611426c-2685-11e7-80d4-0f6148fa088d.png)
![caja2explosion](https://cloud.githubusercontent.com/assets/25808382/25286917/060e8f04-2685-11e7-99ce-be21e5a01ee6.png)
![caja3explosion](https://cloud.githubusercontent.com/assets/25808382/25286920/062c77d0-2685-11e7-947d-b63890fa9982.png)
![caja4explosion](https://cloud.githubusercontent.com/assets/25808382/25286923/063f7f7e-2685-11e7-94e8-e7c1f6e63342.png)
![caja6explosion](https://cloud.githubusercontent.com/assets/25808382/25286921/062ee42a-2685-11e7-9fec-83622d687801.png)

Se adjunta las cajas modificadas a la hora de accionarlas y adicionalmente se adjunta la novena caja que dara puntos de vida o puntos de experiencia o monedas al jugador.

**Comment by DiegOliveros** [comment]
@juankrlos08 Los archivos deben ser cargados al repositorio no sobre las issues a menos que sean documentos de soporte al dialogo.
Si no se hace de esta manera se afecta el control y la gestión documental.

@CamilaG08 @jrsosago

**Comment by DiegOliveros** [comment]
@juancelemin No se evidencia revisión del documento 26-04-2017.
