### ISSUE TITLE
1.6.6 Construcción final del módulo de logros

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#342]
**Descripción**

Entregar el módulo de logros totalmente funcional y ajustado al manual de diseño.

**TAREAS**

- [x] Ajustar las imágenes a escalas de grises
- [x] Definir la clasificación de cómo se obtienen los logros
- [x] Definir los datos que se van a consumir del servicio  los que se van a devolver
- [x] Ajustar los botones al manual de diseño
- [x] Implementar el código para el desbloqueo de logros automático

**Comment by juancelemin** [comment]
**prouesta** para los logros
[LogrosV3.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/923783/LogrosV3.pdf)

**Comment by CamilaG08** [comment]
**No se asignan más tareas hasta que esta se finalice y se muestre la implementación**

**Comment by juancelemin** [comment]
**Se Realiza en pull request de  la implentacion de logros**
