### ISSUE TITLE
5.10 Documento de control de cambios en los requerimientos de los servicios

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#346]
**Descripción**

Esta Issue está planteada para agregar los cambios resultantes en cada módulo al final de la semana de trabajo individual , con cambios se hace referencia a los datos de consumo de los servicios REST correspondientes a cada módulo.

**Comment by juankrlos08** [comment]
Perfil del jugador: [REQUERIMIENTOS.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/913985/REQUERIMIENTOS.pdf)

Se adjuntan los requerimientos de los serivicios que se requieren en cuanto al perfil del jugador.

**Comment by CamilaG08** [comment]
Se realizan cambios en la sección de compra de personajes y se suben los documentos que contienen los requerimientos hasta ahora:

General: [DatosJSON_Servicios.xlsx](https://github.com/ISWPOLI/Pacto-de-Honor/files/923119/DatosJSON_Servicios.xlsx)

Logros: [requerimientosPerfilLogros.xlsx](https://github.com/ISWPOLI/Pacto-de-Honor/files/923120/requerimientosPerfilLogros.xlsx)

**Comment by CamilaG08** [comment]
Quedan los 3 documentos de los datos a consumir de los servicios @JuanCheroslan .

General actualizado: [DatosJSON_Servicios.xlsx](https://github.com/ISWPOLI/Pacto-de-Honor/files/923318/DatosJSON_Servicios.xlsx)
