### ISSUE TITLE
4.4 Navegación - Reportes - Módulo reportes

### ISSUE THREAD

**Issue by EdnaEspejo** [ISWPOLI/Pacto-de-Honor#347]
- [x] Crear navegabilidad
- [x] Crear árbol de reportes

**Comment by rzambrano112** [comment]
Se anexa versión temporal del módulo reportes.
[Mod v1.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/924047/Mod.v1.zip)

**Comment by rzambrano112** [comment]
Teniendo en cuenta los css de cada diseño del modulo de administración junto con los css del equipo que esta programando los diseños de los personajes es importante revisar el issue #167 para sincronizar diseños.

**Comment by rzambrano112** [comment]
Se habla con Jeimy en relación a las pruebas psicotecnicas.
Se acuerda anexar una nueva historia en el modulo de administración llamada pruebas psicotecnicas.
La finalidad de conocer cual es el numero de jugadores buenos y malos de acuerdo a los parámetros actuales de las mismas.

**Comment by rzambrano112** [comment]
Se habla con Camila en relación a los css que ellos están utilizando para el aplicativo.
Y como lo describí anteriormente debemos validar con el módulo de administración los estilos de forma unificada.

**Comment by rzambrano112** [comment]
Adicionalmente, es necesario revisar nuevamente el informe, para la realización de la implementacion de los servicios y pruebas con SoapUl

**Comment by rzambrano112** [comment]
Juan Camilo realiza comentarios para que el panel de opciones del módulo de opciones (modulo_admonModulos) de la administración sea desplegable.

**Comment by alexsabsan** [comment]
Carga Modulo Adminstracion Version 0.5
Para funcionalidad JS Submodulos Poder y Usuari
[versio 0.5.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/948750/versio.0.5.zip)
o

**Comment by rzambrano112** [comment]
se realiza evidencia de la implementación con código en la rama consolidación en Github de los html
![image](https://cloud.githubusercontent.com/assets/20976993/25302444/c87059aa-2703-11e7-9d70-c73177714412.png)

**Comment by rzambrano112** [comment]
se realiza evidencia de la implementación con código en la rama consolidación en Github de los Css
![image](https://cloud.githubusercontent.com/assets/20976993/25302452/0b19f90a-2704-11e7-961a-9bafad6fc271.png)

**Comment by alexsabsan** [comment]
Modulo de administración Navegable Version 0.5
Modificaciones de formulario según historias de usuario y menu desplegable
[Modulo Administracion.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/948831/Modulo.Administracion.zip)

**Comment by rzambrano112** [comment]
Se cierra issue #347

**Comment by rzambrano112** [comment]
Se cierra issue #347
