### ISSUE TITLE
7.2 Login Facebook

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#348]
**Descripción**
Login para Facebook.
**Tareas a realizar**
- [x] Realizar Login de Facebook.

**Comment by ivandav** [comment]
# Codigo login con Facebook

[loginFB.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/923326/loginFB.txt)

   - Se hacen las configuraciones en la pagina de Facebook developers.
   - Se debe corregir un pequeño error en la configuración, pero el boton ya es funcional.
   - Actualmente se esta tratando de unir el login al juego para asi poder hacer el commit a la rama Master.

**Comment by jrsosago** [comment]
Se cierra está Issue por tareas terminadas
