### ISSUE TITLE
5.6.12 Modelo entidad-relación de pruebas Psicotécnicas

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#349]
**Descripción**
Modelo entidad-relación de las pruebas Psicotécnicas.
**Tareas a realizar**
- [x] Realizar modelo entidad relación

**Comment by jrsosago** [comment]
Se hace borrador en papel del modelo de entidad-relación para que Juan Sebastián lo complete y lo suba a está Issue.

**Comment by ghost** [comment]
Se realiza un modelo entidad relación, 
![captura de pantalla 2017-04-10 a la s 9 28 48 a m](https://cloud.githubusercontent.com/assets/12540451/24866612/3f56b9ca-1dd0-11e7-9276-dfdf55af73f0.png)

[preguntas_psicotecnicas.mdj.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/910382/preguntas_psicotecnicas.mdj.zip)

Cualquier comentario hacerlo en este Issue.
tiempo empleado: 1 hora.

**Comment by jrsosago** [comment]
Se realiza modelo entidad-relación. **Tiempo empleado: 40 minutos**
[Modelo entidad-relación.pptx](https://github.com/ISWPOLI/Pacto-de-Honor/files/923121/Modelo.entidad-relacion.pptx)

Se modifica diagrama de clases.**Tiempo empleado: 1 hora y 30 minutos**
![diagramaclasespruebaspsicotecnicas](https://cloud.githubusercontent.com/assets/22827594/25058636/9b14fc12-2141-11e7-9d16-987638fab907.PNG)

**Comment by jrsosago** [comment]
@JuanCheroslan Juan Camilo, el modelo entidad-relación y el diagrama de clases son la base para la construcción de los scripts.

Saludos.
