### ISSUE TITLE
1.6.3 Creación de Mockups y descripción de las recompensas

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#35]
**Descripción**

Crear las recompensas en mockups, cómo van a funcionar y su descripción.

**TAREAS**

- [x] Mockup de las monedas
- [x] Descripción de uso y obtención de las monedas
- [x] Mockup de los puntos de experiencia
- [x] Descripción de uso y obtención de los puntos de experiencia
- [x] Mockup de los puntos de vida
- [x] Descripción de uso y obtención de los puntos de vida

**Comment by CristianGarzonBernal** [comment]
[Monedas.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/795214/Monedas.docx)
