### ISSUE TITLE
1.1.21 Sonidos finales del juego.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#350]
**Descripción**
Sonido Finales del juego.
**Tareas a realizar**
- [x] Selección de sonidos finales de todo el juego. Preguntarle sonidos escogidos @jdma0440 y @juancelemin 
- [x] Reunirse con los encargados de la batalla y la navegación para implementar sonidos en el juego.

**Comment by jrsosago** [comment]
**No se asignan más actividades hasta que se termine está.**

**Comment by ghost** [comment]
Se hace una selección de los sonidos que se implementaran en el juego, en las fases de perfil de usuario, mapa, puños lanzados, login e introducción, historieta, botones, batalla final; también se hizo una prueba practica de lo que podía ser la versión final con los sonidos en una animación aparte. Se utilizan elementos de tareas anteriores de Juan Celemin y Jair Dario.

## Los archivos de sonido son muy grandes para subir a este issue, por lo que se pasaran los archivos a los encargados de desarrollo de batallas y navegación. 

Tiempo empleado: 6 horas 10 min.

**Comment by ghost** [comment]
Debido a que no se puedo realizar la reunión con los encargados de desarrollo, se creo un nuevo ISSUE el numero #374, para la implementacion final en conjunto con @ivandav,

**Comment by DiegOliveros** [comment]
@jolarter

**Comment by jrsosago** [comment]
**Descripción**
Debido a que el archivo es muy grande, se debe compartir o publicar en un drive, para que todos tengan acceso por medio de un link público.
**Tareas a realizar**
- [x] Publicar link donde se encuentran todos los sonidos del juego (este archivo puede ser un zip subido a drive en gmail, y ponerle en la configuración que cualquiera con el link puede ver el archivo).
- [x] Cerrar Issue, después de realizar el punto anterior.

**Comment by ghost** [comment]
https://drive.google.com/open?id=0B3ioxhSl2F0yRGU4TWJNYmxaMFE
link de los archivos sonoros para el juego poli_fighters.
