### ISSUE TITLE
5.6.13 Definir servicios que necesitan las pruebas Psicotécnicas

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#351]
**Descripción** 
Definir cambios en la base de datos, servicios y reunirme con Administración y Backend.
**Tareas a realizar**
- [x] Definir cambios en la base de datos.
- [x] Realizar documento petición servicios.
- [x] Realizar documento consolidado para Administración.
- [x] Documento de preguntas relacionadas con las acciones en el juego.
- [x] Realizar simulación de pruebas Psicotécnicas en Eclipse.

**Comment by jrsosago** [comment]
Adjuntó envió documento consolidado para Backend. **Tiempo empleado: 41 minutos**
[CAMBIOS EN LA BASE DE DATOS PRUEBA PSICOTÉCNICAS.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/923329/CAMBIOS.EN.LA.BASE.DE.DATOS.PRUEBA.PSICOTECNICAS.pdf)

**Comment by jrsosago** [comment]
Adjuntó envió excel donde se relacionan acción-preguntas. **Tiempo empleado: 2 horas y 3 minutos**
[Acciones juego con preguntas.xlsx](https://github.com/ISWPOLI/Pacto-de-Honor/files/923819/Acciones.juego.con.preguntas.xlsx)

**Comment by jrsosago** [comment]
Se realiza documento resumen de implementación pruebas Psicotécnicas. **Tiempo empleado: 1 hora y 39 minutos.**
[IMPLEMENTACIÓN PRUEBAS PSICOTÉCNICAS.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/923932/IMPLEMENTACION.PRUEBAS.PSICOTECNICAS.pdf)
Quedo atenta a los comentarios por parte del módulo administración @rzambrano112.

**Comment by jrsosago** [comment]
Simulación. **Tiempo empleado: 5 horas y 36 minutos**

**Comment by jrsosago** [comment]
Se cierra está Issue por culminación de tareas.

**Comment by rzambrano112** [comment]
Hola
Jeimy 
Como estás ?
Mira me gustaría saber como seria dicha integración con el módulo de administración.  No se si hay la posibilidad de que hablemos por este medio o el día miércoles. Quedo atento a cualquier comentario.
@jrsosago 

Así mismo, me gustaría como validamos que los estilos css utilizados por ustedes son uniformes con los del modulo de adminsitracion @CamilaG08. Quedo atento a cualquier comentario

**Comment by jrsosago** [comment]
Reunión con Juan Carlos líder de Backend para definir cambios en la base de datos y un entregable más por parte mía para poder realizar los Script de manera correcta.

**Comment by jrsosago** [comment]
Reunión con Ricardo Zambrano para definir el modulo de las pruebas en el portal de Administración

**Comment by jrsosago** [comment]
Adjuntó se envió cuadro solicitado por @JuanCheroslan el día miércoles. Quedo atenta a comentarios. 
**Tiempo empleado:30 minutos**
[TablasFinalesBackend.xlsx](https://github.com/ISWPOLI/Pacto-de-Honor/files/948609/TablasFinalesBackend.xlsx)
