### ISSUE TITLE
1.1.8 Creación de la historieta de introducción al juego

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#36]
**Descripción**

Creación de la historieta que narrará la historia al jugador justo después de loguearse y antes de crear el avatar.

**TAREAS**

- [x] Leer la historia y si es el caso realizar modificaciones
- [x] Crear los diálogos
- [x] Definir cuáles o cuál personaje contará(n) la historia
- [x] Definir el fondo (imagen) de la historia
- [x] Asignar la cronología y personaje a cada diálogo
- [x] Consolidación de la historieta

**Comment by ghost** [comment]
# **HISTORIETA**  (Registro de Tiempo: 3 horas)

![1](https://cloud.githubusercontent.com/assets/22629833/23109522/eb000f84-f6e7-11e6-969a-1c01522c86e6.jpg)
![2](https://cloud.githubusercontent.com/assets/22629833/23109521/eb0008b8-f6e7-11e6-8820-b4aa14a88f46.jpg)
![3](https://cloud.githubusercontent.com/assets/22629833/23109524/eb052d52-f6e7-11e6-8802-49a03f61eac9.jpg)
![4](https://cloud.githubusercontent.com/assets/22629833/23109523/eb02cd32-f6e7-11e6-978a-463207b3fcb1.jpg)
![5](https://cloud.githubusercontent.com/assets/22629833/23109525/eb057f32-f6e7-11e6-9466-15fdd6442dee.jpg)
