### ISSUE TITLE
4.1.6 Integrar el módulo de compra de personajes al mapa de navegación

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#363]
**Descripción**

Integrar el módulo de compra de personajes al mapa de navegación.

**TAREAS**

- [x] Crear el botón de compra de personajes
- [x] Integrar el botón al mapa de navegación
- [x] Conectar el botón a la sección de compra de personajes
- [x] Crear e integrar el botón de volver al mapa de navegación

**Comment by CamilaG08** [comment]
Módulo de compra de personajes: 

[Compra personajes.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/921384/Compra.personajes.zip)

**Comment by gabogabbs** [comment]
Se crea el botón en el mapa de navegación, se enlaza con la sección de compra de personaje realizada por @CamilaG08 , y se hacen los ajustes de variables y funciones.
[CompraPersonajesIntegrado.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/921437/CompraPersonajesIntegrado.zip)

Se da como concluido este issue.
REGISTRO DE TIEMPO: 1 HORA Y 30 MINUTOS.

**Comment by CamilaG08** [comment]
Se cumple con las tareas satisfactoriamente, por lo tanto se cierra el Issue.
