### ISSUE TITLE
7.1.6 Realizar pruebas funcionales sobre el registro login de la autentificación.

### ISSUE THREAD

**Issue by ghost** [ISWPOLI/Pacto-de-Honor#364]
Se deben realizar pruebas funcionales del registro login de la autenticación en su primera versión, para determinar que los usuarios se están registrando de forma exitosa,  y sean notificados mediante Jsp, que se puedan loguear y pasar a la historieta de usuario, y que si olvidan su clave sean notificados mediante correo retornando la clave a su correo registrado, y sean notificados en un jsp.

- [x] Pruebas funcionales registro exitoso.

- [x] Pruebas funcionales login exitoso.

- [x] Pruebas funcionales olvido de clave exitoso.

**Comment by ghost** [comment]
Se realizan las  pruebas funcionales del registro login donde se pudo determinar que el registro esta de forma correcta con todo lo establecido en el marco de trabajo y se realizan las pruebas de funcionamiento que son mostradas en el reporte del dia sábado y son subidas al repositorio.

**Comment by DiegOliveros** [comment]
@Basespoli  favor incluir los logs de prueba y repostes de la aplicación.

**Comment by ghost** [comment]
Se incluye el logs de las pruebas y los reportes de la aplicación en fotografías.

![image](https://cloud.githubusercontent.com/assets/25758763/25300393/c1d3ceb8-26d3-11e7-8bce-49c45c815fba.png)


[Logs prueba.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/948654/Logs.prueba.txt)

**Comment by ghost** [comment]
Se realizan las pruebas funcionales del registro login donde se pudo determinar que el despliegue local de recuperar_Clave esta de forma correcta con todo lo establecido en el marco de trabajo y se realizan las pruebas de funcionamiento que serán socializadas mostradas en los logs a continuación y los reportes del la aplicación, se actualiza el repositorio.

**Comment by ghost** [comment]
Reportes de aplicación:

![image](https://cloud.githubusercontent.com/assets/25758763/25552028/c6b6ddea-2c54-11e7-9a7d-da32791108b3.png)

Si olvido clave nos dirigimos al siguiente Jsp el cual le indicamos el email registrado y nos enviara a este email un mensaje indicándonos la calve para poder ingresar.

![image](https://cloud.githubusercontent.com/assets/25758763/25552056/6112d948-2c55-11e7-906f-dd9f636c2757.png)

Si el correo esta correctamente escrito y esta en la base de datos, nos informara que el correo fue enviado al correo y que por favor se logue.

![image](https://cloud.githubusercontent.com/assets/25758763/25552107/fbae8140-2c56-11e7-802d-fce3da072c74.png)

En caso de que el correo este mal escrito, o no este en la base de datos, es decir que No sea el correo registrado nos indicara que por favor realicemos el registro.


![image](https://cloud.githubusercontent.com/assets/25758763/25552103/e4df6ea2-2c56-11e7-8771-2262156210dd.png)

**Comment by ghost** [comment]
Se cargan las pruebas funcionales con el reporte de logs.


[Pruebas funcionales.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/965838/Pruebas.funcionales.txt)

**Comment by ghost** [comment]
Se realizan las pruebas funcionales del registro login donde se pudo determinar que el despliegue local de Login esta de forma correcta con todo lo establecido en el marco de trabajo y se realizan las pruebas de funcionamiento que serán socializadas en los logs a continuación y los reportes del la aplicación, se actualiza el repositorio.

**Comment by ghost** [comment]
Reporte de aplicación: 

![image](https://cloud.githubusercontent.com/assets/25758763/25552236/1e91237c-2c5a-11e7-889d-1ea684235718.png)

El home de la autentificación del juego nos solicita el usuario y la clave, las cuales son validadas en el JSP que hacer persistencia a la base compara los datos e indica de ser incorrectos.

![image](https://cloud.githubusercontent.com/assets/25758763/25552280/c5710464-2c5a-11e7-901c-1ae466bfae45.png)


De ser correctos  pasamos a la historieta de introducción del juego creada en el #36

**Comment by ghost** [comment]
Se cargan los logs.
[PrubasfuncionalesLogin.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/965855/PrubasfuncionalesLogin.txt)
