### ISSUE TITLE
1.1.22 Implementación Sección Ranking

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#368]
**Descripción**
Realizar Implementación de la Sección de Ranking. Tarea asignada para reponer las 6 horas de clase (Miércoles 5 de Abril y Sábado 8 de Abril) debido al concurso de robótica. 
**Tareas a realizar**
- [x] Implementación ranking diario.
- [x] Implementación ranking semanal.
- [x] Implementación ranking poli.
- [x] Implementación ranking general.

**Comment by gabogabbs** [comment]
Se agrega la interfaz de la sección de Rankings al mapa de navegación. 
![image](https://cloud.githubusercontent.com/assets/21046810/25068622/0f0d988e-222f-11e7-83a5-8084e7e0ba62.png)

La tarea está por terminar ya que hace falta corregir los archivos JSON de prueba.
REGISTRO DE TIEMPO: 5 HORAS.

**Comment by gabogabbs** [comment]
Se realiza el archivo JSON de pruebas y se empieza a modificar el módulo de rankings para implementar dicho JSON. Además, se crea la imagen del top 5. 
<img width="799" alt="captura de pantalla 2017-04-19 a las 9 44 06 p m" src="https://cloud.githubusercontent.com/assets/21046810/25211152/68e70b70-2549-11e7-9bd0-25fa7b73cf13.png">

REGISTRO DE TIEMPO: 2 HORAS Y 30 MINUTOS.

**Comment by gabogabbs** [comment]
- Se modifica la imagen del top 5 para añadir marcos.
- Se realizan cambios en el JSON de prueba de jugadores.
- Se implementa el Ranking diario, semanal, poli y general.

[rankings.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/948365/rankings.zip)

Se da como concluido el issue.
REGISTRO DE TIEMPO: 5 HORAS Y 35 MINUTOS.

**Comment by jrsosago** [comment]
Se cierra está Issue, por tareas terminadas.
