### ISSUE TITLE
5.1.5 Historias de Usuario

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#369]
**Descripción**
Revisar History mapping realizado por @jdbernalv, crear todas las historias de usuario (las cuales son diferentes a las tareas que son creadas en cada sprint) para los siguientes Sprints, Tarea asignada para reponer 3 horas de clase (Sábado 8 de Abril), debido a concurso de robótica.

**Tareas a realizar**
- [x] Revisar History Mapping realizado por @jdbernalv.
- [x] Crear todas las historias de usuario (generales) para los siguientes Sprints.
- [x] Realizar documento con entregables de cada Sprint y pasárselo a @jdbernalv

**Comment by CamilaG08** [comment]
- [x] Dar las tareas a @jrsosago y a mí para revisión

**Comment by jrsosago** [comment]
Se cierra esta Issue, por actividad completa.
