### ISSUE TITLE
1.2.5 Sección del avatar y mini personajes

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#37]
**Descripción**

Crear el Mockup y las imágenes que corresponden a la sección del avatar y de los mini enemigos de los 2 primeros mundos.

**TAREAS**

- [x] Listar los ítems necesarios para llenar el tablero del avatar
- [x] Crear los ítems previamente listados
- [x] Realizar el mockup del tablero con todos los ítems
- [x] Crear los 4 mini personajes relacionados a Andrés Zorro (mini zorritos de colores)
- [x] Realizar la descripción de dichos personajes (Está descripción debe estar relacionada con Andrés Zorro)
- [x] Crear los 4 mini personajes relacionados a Felipe Oso (mini ositos de colores)
- [x] Realizar la descripción de dichos personajes (Está descripción debe estar relacionada con Felipe Oso)
- [x] Presentar los mini personajes al equipo de Sprites

**Comment by ivandav** [comment]
**MOCKUPS**
40 minutos
![new mockup 1 copy](https://cloud.githubusercontent.com/assets/22629584/23193442/06759028-f877-11e6-8784-6564babe097e.png)
![new mockup 1](https://cloud.githubusercontent.com/assets/22629584/23337153/90de16f2-fbb2-11e6-853b-d6426a8bf018.png)

**Comment by ivandav** [comment]
**LISTA DE ITEMS**
5 minutos

°Escudo
°Casco
°Espada
°Arco y Flecha
°Caballo con armadura
°Corona

**Comment by ivandav** [comment]
**DESCRIPCIÓN DE MINI PERSONAJES REFERENTES A ANDRES ZORRO Y FELIPE OSO**
30 minutos
[Descripcion de minipersonajes.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/792120/Descripcion.de.minipersonajes.docx)

**Comment by ivandav** [comment]
**ITEMS**
20 minutos
![captura de pantalla 2017-02-22 a las 7 31 44 p m](https://cloud.githubusercontent.com/assets/22629584/23331802/765daa08-fb3b-11e6-906d-d0258d8b5fb4.png)
![captura de pantalla 2017-02-22 a las 7 32 12 p m](https://cloud.githubusercontent.com/assets/22629584/23331803/765e4eb8-fb3b-11e6-94e9-a4c9967f98bb.png)
![captura de pantalla 2017-02-22 a las 7 32 52 p m](https://cloud.githubusercontent.com/assets/22629584/23331804/766b83d0-fb3b-11e6-80da-aa090e93b805.png)
![captura de pantalla 2017-02-22 a las 7 33 08 p m](https://cloud.githubusercontent.com/assets/22629584/23331805/7676a314-fb3b-11e6-8079-57c79123dd77.png)
![captura de pantalla 2017-02-22 a las 7 33 21 p m](https://cloud.githubusercontent.com/assets/22629584/23331806/767bae18-fb3b-11e6-9d90-00b77f101734.png)
![captura de pantalla 2017-02-22 a las 7 35 42 p m](https://cloud.githubusercontent.com/assets/22629584/23331807/76829214-fb3b-11e6-9825-79e587a750f7.png)

**Comment by ivandav** [comment]
**MINI PERSONAJES**
3 horas
![spriteanteojos](https://cloud.githubusercontent.com/assets/22629584/23337198/078df9c0-fbb3-11e6-81e1-46e4d2698779.png)
![spritehormiguero](https://cloud.githubusercontent.com/assets/22629584/23337197/078da7a4-fbb3-11e6-809a-d8b96f7ef4be.png)
![spritepanda](https://cloud.githubusercontent.com/assets/22629584/23337199/078f0a0e-fbb3-11e6-8f1f-430091799aca.png)
![spritepolar](https://cloud.githubusercontent.com/assets/22629584/23337202/07913b94-fbb3-11e6-846e-a0cf440d439b.png)
![zorro](https://cloud.githubusercontent.com/assets/22629584/23337200/078f1990-fbb3-11e6-9dba-f8df2b6cd325.png)
![zorro2](https://cloud.githubusercontent.com/assets/22629584/23337201/07900eae-fbb3-11e6-834a-0f48d611e3b6.png)
![16930711_10207026243855034_1090786498_o](https://cloud.githubusercontent.com/assets/22629584/23337207/29db8cd6-fbb3-11e6-962b-0b75884392ef.png)
![16936038_10207026355137816_1453819674_o](https://cloud.githubusercontent.com/assets/22629584/23337206/29db84e8-fbb3-11e6-9033-0b40e1183399.png)
