### ISSUE TITLE
1.1.23 Implementación móvil del juego

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#373]
#**Descripción:**

Realizar todo lo necesario para la implementación móvil y dejar esta versión lista para crear el apk.

**TAREAS**
Las tareas individuales quedan a cargo de @dayepesb, recordar que cada tarea que se agregue debe tener una persona asignada.

- [x] Asegurarse que el juego reconozca desde que tipo de dispositivo de visualiza @nicolas96

- [x] Cambiar posición de componentes cuando se entre desde un móvil @dayepesb 

- [x] Obligar al juego a visualizarse en landscape @gsalvarez 

- [x] Implementar joystick en versión móvil @nicolas96

**Comment by nmartinezmarin** [comment]
Se hace merge https://github.com/ISWPOLI/Pacto-de-Honor/pull/420
*Se asignan funciones que ya reconocen si el juego se visualiza desde
un móvil
*Se corrigen bugs que no permitían que funcionara el campo de batalla
al entrar por segunda vez
Tiempo registrado : 4 horas

**Comment by nmartinezmarin** [comment]
Se hace merge https://github.com/ISWPOLI/Pacto-de-Honor/pull/422
*se implementa el joystick en la versión móvil del juego
Tiempo registrado: 2 horas

**Comment by gabogabbs** [comment]
Se investiga sobre poner el juego en modo Landscape en la versión móvil.
Dado que no es posible forzar un juego HTML5 a verse en modo Landscape, se planea poner un mensaje que avise al usuario que debe girar el dispositivo en modo Landscape.

**Comment by gabogabbs** [comment]
Se implementa un script para que en modo Portrait el usuario vea un aviso que le dice que debe girar su dispositivo para jugar en modo Landscape. Se hace merge en la rama Master (#428).
REGISTRO DE TIEMPO: 3 horas.
