### ISSUE TITLE
1.1.24 Implementación de sonidos en el juego.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#374]
**Descripción** 
Implementar sonidos en todo el juego. Issue #350 
**Tareas a realizar**
- [x] Implementar todos los sonidos en el juego

**Comment by ghost** [comment]
Se envia sonidos seleccionados para la implementacion final del juego a @ivandav por un medio aparte a github ya que los archivos son muy pesados para subirlos por este medio.

**Comment by jrsosago** [comment]
No se evidencia trabajo de el Sprint 10

**Comment by ivandav** [comment]
# Avances
Se presento un problema con la implementacion de los sonidos, por lo cual no se pudo subir avances pero con ayuda de @gsalvarez se soluciona el problema y se esta avanzando en la codificacion.

**Comment by ivandav** [comment]
[ ] kj

**Comment by jrsosago** [comment]
Se cierra está Issue por tareas realizadas.
