### ISSUE TITLE
1.13 Implementación de las cajas sorpresa

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#375]
**Descripción:**

Realizar la implementación de las caja sorpresa dentro del juego.

**TAREAS**
- [x] Revisar el documento en el Issue #341 
- [x] Validar que dicha implementación sea posible con @dayepesb 
- [x] Realizar la implementación que sea acorde con el juego

**Comment by juankrlos08** [comment]
![image](https://cloud.githubusercontent.com/assets/25808382/25552371/4fa11f28-2c5d-11e7-8a40-275c0af8acb5.png)

 Se implementa una muestra de como aparecerían las cajas sopresas en el transcurso de las batallas. 

Elaborado por @juancelemin  y @juankrlos08

**Comment by juankrlos08** [comment]
![image](https://cloud.githubusercontent.com/assets/25808382/25552415/0535da94-2c5f-11e7-8903-1918130c4eb0.png)

![image](https://cloud.githubusercontent.com/assets/25808382/25552419/10bbf268-2c5f-11e7-9502-c06d6254142b.png)

Se muestra la segunda opción requerida donde aparece un botón en el mapa de navegación y direcciona a una ventana donde están cada una de las cajas, son explicadas y muestra si estan bloqueadas o desbloqueadas.

Elaborado por @juancelemin y @juankrlos08

**Comment by juancelemin** [comment]
![](https://cloud.githubusercontent.com/assets/25808382/25552415/0535da94-2c5f-11e7-8903-1918130c4eb0.png)

![](https://cloud.githubusercontent.com/assets/25808382/25552419/10bbf268-2c5f-11e7-9502-c06d6254142b.png)
Se muestra la segunda opción requerida donde aparece un botón en el mapa de navegación y direcciona a una ventana donde están cada una de las cajas, son explicadas y muestra si estan bloqueadas o desbloqueada

**Comment by jrsosago** [comment]
Se cierra está Issue, por tareas terminadas.
