### ISSUE TITLE
5.3.5 Derechos de Autor

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#377]
**Descripción**
Realizar documentación de derechos de autor.
**Tareas a realizar**
- [x] Investigar con todo lo referente a derechos de autor para el juego (Proceso de legalización).
- [x] Realizar documento con todo lo referente a derechos de autor.

**Comment by jdbernalv** [comment]
Se realiza la entrega del procedimiento completo para registrar el código fuente de la aplicación con los formatos adecuados para tramitar con DERECHOSDEAUTOR.GOV.CO @jrsosago @CamilaG08 

[5.3.5 Derechos de Autor #377 - Procedimiento.docx.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/944927/5.3.5.Derechos.de.Autor.377.-.Procedimiento.docx.pdf)
[(Formato) Formulario de Registro de Soporte Lógico o Software..pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/944932/Formato.Formulario.de.Registro.de.Soporte.Logico.o.Software.pdf)
[(Formato) Solicitud Inscripción Soporte Lógico(Software)..pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/944933/Formato.Solicitud.Inscripcion.Soporte.Logico.Software.pdf)

**Comment by jrsosago** [comment]
Se cierra está Issue por tareas terminadas
