### ISSUE TITLE
1.1.25 Realizar implementación Pruebas Psicotécnicas

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#378]
**Descripción**
Realizar implementación, basada en la Issue #351, cualquier duda preguntarle a @jrsosago.
**Tareas a realizar**
- [x] Realizar implementación prueba psicotécnica. basada en la Issue #351

**Comment by gabogabbs** [comment]
Trabajando en colaboración con @nicolas96 se realiza la primera implementación de las pruebas Psicotécnicas según lo planteado por @jrsosago. 
Por lo tanto, se da como concluido el issue.

REGISTRO DE TIEMPO: 3 horas.

**Comment by jrsosago** [comment]
Se cierra está Issue, por tareas finalizadas
