### ISSUE TITLE
Servicio REST Usuario: Documentación

### ISSUE THREAD

**Issue by EdnaEspejo** [ISWPOLI/Pacto-de-Honor#379]
- [x] Documentación

**Comment by EdnaEspejo** [comment]
[DOCUMENTACIÓN SERVICIO REST PARA LA ENTIDAD USUARIO.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/923995/DOCUMENTACION.SERVICIO.REST.PARA.LA.ENTIDAD.USUARIO.docx)

**Comment by DiegOliveros** [comment]
Las historias no se deben cerrar hasta tanto no se realicen todas las tareas asociadas.
importante garantizar el funcionamiento del servicio mediante las pruebas y el consumo de los mismos por parte de los módulos que lo consumen.
