### ISSUE TITLE
1.6.4 Pantallas de rankings y creación de escudos

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#38]
**Descripción**

Mockups de las pantallas de los 4 rankings y creación de escudos por cada tipo de poder.

**TAREAS**

- [x] Definir los ítems que pertenecerán al tablero
- [x] Crear los ítems previamente definidos
- [x] Crear el mockup de cada ranking
- [x] Definir escudos para los diferentes tipos de poder (lanzar, caer del cielo, golpe directo, tipo de plagio)
- [x] Crear los escudos previamente definidos
- [x] Realiza una descripción de los escudos previamente definidos y creados

**Comment by gabogabbs** [comment]
Se adjunta el archivo con la definición de los ítems presentes en los rankings, además de sus mockups.
También, se añaden los distintos tipos de escudos para los diferentes plagios que hay.

[Rankings y escudos.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/788692/Rankings.y.escudos.docx)

REGISTRO DE TIEMPO: 3 HORAS
