### ISSUE TITLE
Servicio REST Usuario: Pruebas

### ISSUE THREAD

**Issue by EdnaEspejo** [ISWPOLI/Pacto-de-Honor#382]
- [ ] Pruebas de los diferentes Métodos que contiene el servicio

**Comment by DiegOliveros** [comment]
@EdnaEspejo Favor incluir descripción de la historia, estimaciones y usar el formato definido para historia:
**Titulo de la Historia:**
Descripción:
**Tareas:**
- [ ] tarea1
- [ ] tarea2
- [ ] ...
- [ ] tarean
![image](https://cloud.githubusercontent.com/assets/2998313/25286989/444a922c-2685-11e7-90e2-90d1b3785b5f.png)
![image](https://cloud.githubusercontent.com/assets/2998313/25287030/6deaac0c-2685-11e7-9916-14f21c4e51fb.png)

**Comment by EdnaEspejo** [comment]
Por funcionalidad se trabajará con la siguiente issue
Servicio REST Usuario #383
