### ISSUE TITLE
1.6.1 Creación y definición de logros

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#39]
**Descripción**

Crear y describir los logros que podrán ser obtenidos, acompañados de sus respectivos logos.

**TAREAS**

- [x] Complementar/Modificar los logros ya existentes
- [x] Crear un nombre para cada logo
- [x] Describir detalladamente cada logro (qué es, cómo se obtiene y recompensas que genera)
- [x] Crear los logos de cada logro
- [x] Realizar el mockup del tablero donde se verán los logros

**Comment by rzambrano112** [comment]
De acuerdo a la creación y definición de logros para el juego planteado se realizan los siguientes aportes para el avance en cada nivel de cada combate. Logros que pueden especificarse por cada nivel como los siguientes para llegar a la batalla final.
[Creaciòn y definiciòn de logros. Ricardo.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/794538/Creacion.y.definicion.de.logros.Ricardo.docx)

**Comment by rzambrano112** [comment]
Se van a realizar modificaciones sobre la propuesta de la creaciòn y definiciòn de logros bajo recomendaciones del equipo de trabajo. De la misma manera, quedo pendiente de entregar los mockup de   cada uno de los logros propuestos para cada mundo.

**Comment by rzambrano112** [comment]
Las modificaciones de la creaciòn y definiciòn de logros se hace de acuerdo al archivo original del juego.

**Comment by rzambrano112** [comment]
Se anexan las modificaciones sobre la primera versión de los logros.
Así mismo, se realiza el mockup del tablero donde se verán los mismos.
[Creacion.y.definicion.de.logros.Ricardo.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/800864/Creacion.y.definicion.de.logros.Ricardo.pdf)
[MOCKUP DEL TABLERO DE LOGROS..pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/800865/MOCKUP.DEL.TABLERO.DE.LOGROS.pdf)

**Comment by rzambrano112** [comment]
En relación a las  actividades del 22 al 25 de febrero, quiero aclarar que ya se envió un mensaje aclaratorio dado que se me había comunicado que durante esta semana no había realizado el trabajo de dicha semana. Sin embargo,  a través de los siguientes link

[Creacion.y.definicion.de.logros.Ricardo.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/801452/Creacion.y.definicion.de.logros.Ricardo.pdf)
[MOCKUP DEL TABLERO DE LOGROS..pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/801453/MOCKUP.DEL.TABLERO.DE.LOGROS.pdf)

Se puede constatar la entrega de las evidencias de esta semana.

De la misma manera, anexo el mensaje aclaratorio enviado.

El motivo del mensaje es para notificar que la actividad asignada para esta semana del 22 al 25 de febrero era realizar la creación y modificación de los logros y también los ajustes respectivos a los mismos debido a que se tuvo que realizar diferentes cambios.
La tarea asignada tal cual se prescribe en la los reportes Scrum Master era la siguiente :

![image](https://cloud.githubusercontent.com/assets/20976993/23334303/c66081b4-fb69-11e6-89ce-d2d1a1f76f53.png)


Esta actividad fue realizada a cabalidad durante la semana mencionada es decir hasta el 22 de febrero realizando un avance significativo para dicho día. Sin embargo, la tarea asignada el 25 de febrero era realizar las modificaciones de los logros propuestos dado que se hicieron a los mismos por petición de los compañeros del modulo de combate y del de poderes. Razón por la cual la tarea asignada para el 25 de febrero respecto a las modificaciones a dicha actividad como segunda actividad se entrego el día 24 de febrero, completando la entrega de los item solicitados.
image.

Ahora bien de manera respetuosa recibi el siguiente mensaje :
![image](https://cloud.githubusercontent.com/assets/20976993/23334304/d9e4d032-fb69-11e6-8a23-43d6c47d23d4.png)

En donde se expresa que no he realizado trabajo durante los dias 22 al 25 de febrero cuando dicha actividad no me correspondía tal cual se especifica en Reportes SCRUM MASTER


Razón por la cual de forma respetuosa envió este mensaje aclaratorio dado que las actividades asignadas las he cumplido a cabalidad.
