### ISSUE TITLE
4.1.7 Modificación módulo compra de personajes

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#392]
**Descripción:**

Realizar modificaciones finales al módulo de compra de personajes.

**TAREAS:**
- [x] Modificar las variables (Camila)
- [x] Verificar que funcione con los demás módulos @gsalvarez 
- [x] Si hay modificaciones, realizarlas (Camila)
- [x] Hacer el Merge con el módulo en el repositorio @gsalvarez

**Comment by CamilaG08** [comment]
Modificación de variables:

[CompraPersonajesIntegrado.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/931345/CompraPersonajesIntegrado.zip)

**Tiempo empleado: 30 minutos**

**Comment by gabogabbs** [comment]
Se realiza la implementación de la sección de compra de personajes y se verifica que no hayan conflictos. Se realiza Merge a la rama master.
Se da como concluido el issue.

REGISTRO DE TIEMPO: 30 MINUTOS.
