### ISSUE TITLE
6.1 Seguimiento semana 17 Abr- 22 Abr

### ISSUE THREAD

**Issue by JuanCheroslan** [ISWPOLI/Pacto-de-Honor#397]
Issue relacionado al avance del desarrollo del equipo backend

en este momento se tienen dentro de la codificacion los siguientes modulo

- [x] Servicios

- [x] Modulo Administrador

- [x] Base de Datos

**Comment by JuanCheroslan** [comment]
![image](https://cloud.githubusercontent.com/assets/25808683/25210799/403bb6a0-2547-11e7-98e4-d9a8836e6c5c.png)

![image](https://cloud.githubusercontent.com/assets/25808683/25210805/47cf1e34-2547-11e7-9501-83ab85d9206b.png)

**Comment by JuanCheroslan** [comment]
adjunto documento  con la data

[Bitacora de Avance.xlsx](https://github.com/ISWPOLI/Pacto-de-Honor/files/939569/Bitacora.de.Avance.xlsx)

**Comment by alexsabsan** [comment]
Modulo de administración Navegable Version 0.5
Modificaciones de formulario según historias de usuario y menu desplegable (Proyecto Netbeans) 
[Modulo Administracion.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/948834/Modulo.Administracion.zip)

**Comment by JuanCheroslan** [comment]
despues de hacer el deploy del dia sabado aun no tenemos un producto concreto

-no hay deploy de servicios

-  el modulo administrador no se conecta a la base de datos

- los ajustes de la base de datos no estan completados

muchachos necesitamos ser mas eficientes con las entregas
