### ISSUE TITLE
Servicio REST Mundo 

### ISSUE THREAD

**Issue by wpradere** [ISWPOLI/Pacto-de-Honor#398]
- [x] Código

- [x] Pruebas

- [x] Documentación

**Comment by DiegOliveros** [comment]
@wpradere  Favor incluir tiempos de fiscalización y estimación en todas las historias.

**Comment by wpradere** [comment]
Se sube el documento relacionado a este Servicio 
[ServicioMundo_v0.2.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/963335/ServicioMundo_v0.2.pdf)
