### ISSUE TITLE
1.1.10 Creación de la estructura del código fuente

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#40]
**Descripción**

Creación de las plantillas en HTML y JavaScript, que serán utilizadas para la realización del primer prototipo. 

**TAREAS**
- [x] Marco de trabajo @Basespoli 
- [x] Mockups Ventana combate @dayepesb. 
- [x] Diagrama de clases ventana combate @dayepesb.
- [x] Investigar sobre phaser.io y modulación @Basespoli 
- [x] Modelado en objetos sobre JS de los personajes @juankrlos08.
- [x] Modelado en atributos sobre JS de las propiedades de los personajes @juankrlos08.
- [x] Modelado en métodos sobre JS de los comportamientos de los personajes @juankrlos08.

**Comment by ghost** [comment]
[MarcoTrabajo JavaScript Documentacion.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/789172/MarcoTrabajo.JavaScript.Documentacion.docx)

Se adjunta el marco de trabajo propuesto,no exento a modificaciones, el cual indica como se esta manejando las tareas, la división interna del trabajo, definiciones y especificaciones.

**Comment by dayepesb** [comment]
![mockupmenubatalla](https://cloud.githubusercontent.com/assets/21086402/23152574/dbd6149c-f7d0-11e6-92e3-f617c3ce0820.png)
![mockupcampodebatalla](https://cloud.githubusercontent.com/assets/21086402/23152575/dbd8af68-f7d0-11e6-9cd3-a3beef05d00f.png)
Mockups del campo de batalla, detallando botones ubicación de cada componente y un menú que se  desplegará al presionar un botón de pausa. 
Tiempo empleado : 1 hora

**Comment by juankrlos08** [comment]
[Actores.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/791269/Actores.pdf)

modelado de atributos y metodos de los comportamientos y propiedades de dos de los personajes propuestos en JS

**Comment by dayepesb** [comment]
[Diagrama de clases ventana batalla.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/792210/Diagrama.de.clases.ventana.batalla.pdf)
descripción, de cada clase(nombre,atributos, y metodos), que se tienen que realizar como plantillas para realizar un escenario de batalla en el juego, cada clase viene con nombres que describen su funcionalidad igual que sus metodos.
Tiempo Empleado : 1 hora

**Comment by ghost** [comment]
Se realiza la investigación sobre phaser y modulación.

[Investigacion Phaser.pptx](https://github.com/ISWPOLI/Pacto-de-Honor/files/792361/Investigacion.Phaser.pptx)

**Comment by CamilaG08** [comment]
Se re abre el Issue con el fin de realizar la estructura base (con módulos) del juego. Los archivos gráficos y las especificaciones del juego serán subidas en el Issue #129 para la segunda etapa de esta estructuración.

Esta vez el equipo de trabajo está conformado por: @Basespoli , @juankrlos08 y @JuanSebastianRodriguezJ

**Comment by CamilaG08** [comment]
Se cierra el Issue para re-asignar las tareas faltantes con más detalle, basándose en esta tarea.

**Comment by ghost** [comment]
Se trabajó según lo pensado para implementar, según el feedback no era lo mejor como se pensó y se declararon las tareas a otro grupo.

**Comment by ghost** [comment]
Se sube todo el material que se trabajo, se pensaba que se necesitaban estos insumos para crear las plantillas pero no era necesario según el feedback  y se asignaron a otros integrantes.
