### ISSUE TITLE
5.3.6 Realizar proceso de derechos de autor

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#410]
**Descripción**
Realizar proceso de derechos de autor.
**Tareas asociadas**
- [x] Diligenciar todos los documentos que se encuentran ubicados en la Issue #377

**Comment by jdbernalv** [comment]
Se diligencia el formato para solicitud de Derechos de Autor. 
[Issue # 410 - Realizar Proceso de Derechos de Autor.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/966272/Issue.410.-.Realizar.Proceso.de.Derechos.de.Autor.pdf)
