### ISSUE TITLE
1.8.11 Creación de los JSON para todos los módulos

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#412]
**Descripción**

Creación de todos los archivos JSON necesarios para consumir los servicios REST.

**TAREAS**

- [x] Crear JSON del campo de batalla 
- [x] Crear JSON del perfil del jugador **Camila**
- [x] Crear JSON de personajes desbloqueados @dayepesb 
- [x] Crear JSON de jefes derrotados **Camila**
- [x] Crear JSON de la sección de logros @dayepesb 
- [x] Crear JSON de la selección de avatar @dayepesb 
- [x] Crear JSON del resultado de la batalla @dayepesb 
- [x] Crear JSON de la compra de personajes **Camila**
- [x] Crear JSON de los códigos alfanuméricos **Camila**
- [x] Crear el JSON de las cajas sorpresa (Pendiente debido a que aún falta definir el funcionamiento de este módulo)

**Comment by CamilaG08** [comment]
El JSON de campo de batalla se encuentra previamente creado por @nicolas96

**Comment by CamilaG08** [comment]
**Tiempo estimado: Creación del archivo JSON de compra de personajes** 30 minutos

**Comment by CamilaG08** [comment]
Las tareas asignadas a David Yepes, pasan a ser de @jrsosago

**Comment by jrsosago** [comment]
Se revisan js de las clases donde pertenece cada JSON asignado, documentación de código realizada por Dario y tabla "DatosJSON_Servicios.xlsx " realizada por Camila en el Issue #346. **Tiempo empleado: 1 hora y media**

**Comment by CamilaG08** [comment]
Definición de las estructuras de los JSON faltantes: **2 horas**

**Comment by CamilaG08** [comment]
Creación de JSON faltantes (perfil del jugador, códigos alfanuméricos y jefes derrotados)
**1 hora**

[JSON.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/965789/JSON.zip)

**Comment by CamilaG08** [comment]
El archivo JSON de las cajas sorpresa queda pendiente debido a que falta definir el funcionamiento de estas, y la implementación de los archivos ya creados, depende de una reunión el sábado 29 de abril con integrantes del grupo de frontend y backend.

**Comment by jrsosago** [comment]
Adjuntó envió creación de JSON (personajes desbloqueados, sección logros, selección de avatar, resultado de batalla). **Tiempo empleado: 1 hora** Se sube en la carpeta de documentación porque no me deja subir en este medio

**Comment by jrsosago** [comment]
Se cierra esta  Issue, debido a que se completaron todas las tareas.
