### ISSUE TITLE
1.14 Estandarización de botones

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#421]
### Descripción

Revisar y estandarizar los botones del juego.

### Tareas

- [x] Revisar los botones creados por @gsalvarez y @jdma0440 dentro del juego
- [x] Crear los botones de los demás módulos
- [x] Poner los botones en los diferentes módulos
- [x] Pedir la ayuda de @gsalvarez para asegurarse que no hay conflictos entre las imágenes y los módulos

**Comment by jrsosago** [comment]
Debido a una reunión que se hizo con @KmiArthur, se alarga esta tarea para el siguiente Sprint, ya que falta el 40% de botones por cambiar.

**Comment by KmiArthur** [comment]
Botones estandarizados bajo el manual de diseño y completos.
`Tiempo de trabajo: 10h`

-> Pendiente a revisión
[Botones.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/974965/Botones.zip)

**Comment by KmiArthur** [comment]
#Botones completamente actualizados bajo nuevo estándar. 
`Tiempo de trabajo: 5h`
_(no fue referenciado este issue, pero fue actualizado con éxito)_


[Botones.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/980638/Botones.zip)

**Comment by KmiArthur** [comment]
# Nuevos botones agregados por requerimiento de @gsalvarez 

- [x] Botón de herramientas
- [x] Botón de sonido
- [x] Ajuste de menú de pausa con botón de sonido
- [x] Botón de cierre de sesión

`Tiempo trabajo: 1h`

![captura de pantalla 2017-05-09 a la s 8 47 16 p m](https://cloud.githubusercontent.com/assets/17441569/25879703/ba6f2be4-34f8-11e7-87f3-57a28c409b71.png)
