### ISSUE TITLE
Pruebas SoapUI Servicio REST Nivel

### ISSUE THREAD

**Issue by EdnaEspejo** [ISWPOLI/Pacto-de-Honor#426]
- [x] Testweb en Netbeans
- [x] SoapUI Test

**Comment by DiegOliveros** [comment]
@JuanCheroslan ¿Quién está encargado de hacer las asignaciones de historias?
@EdnaEspejo @JuanCheroslan  Favor estimar las historias de acuerdo al formato solicitado para servicios.
Se evidencia re trabajo en la administración de esta historia.

**Comment by EdnaEspejo** [comment]
Se realiza commit de las modificaciones realizadas, se adjunta documentacion realizada hasta el momento
[ServicioNivel_v0.1.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/965880/ServicioNivel_v0.1.docx)
