### ISSUE TITLE
1.4.1 Diálogos pre - combate y mockup de componentes de un combate

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#43]
**Descripción**

Creación de los diálogos de cada jefe final previos a los combates y de la pantalla detallada de un combate.

**TAREAS**

- [x] Listar los mundos con sus respectivos personajes
- [x] Crear los diálogos de acuerdo al tipo de plagio de dicho personaje y su personalidad
- [x] Realización de los mockups de dichos diálogos para los 2 primeros mundos
- [x] Detallar y listar los componentes que harán parte del combate (botón y menú de pausa, barra de vida, poderes)
- [x] Realizar el mockup de los combates detalladamente, dando prioridad a los pertenecientes a los 2 primeros mundos

**Comment by CamilaG08** [comment]
![mundo2](https://cloud.githubusercontent.com/assets/22283896/23196783/bb509e90-f889-11e6-99dd-897b59e37734.jpg)

![mundo2pausa2](https://cloud.githubusercontent.com/assets/22283896/23197074/b7113dd8-f88b-11e6-8fa9-02aef9e2c648.jpg)

**Mockups Combate Mundo 2**

Tiempo empleado: 2 horas

**Comment by CamilaG08** [comment]
**Componentes**

1. Imágenes avatares 
2. Barra de vida
3. Barra de escudo
4. Botón de golpe directo
5. Botón de escudo (Personaje bueno)
6. Botón poder de personalidad (Ambos)
7. Botón de poder de plagio (Personaje malo)
8. Botón de pausa
9. Avatares
10. Menú de pausa

**Comment by CamilaG08** [comment]
**Diálogo pre - combate Felipe Oso**

![dialogofelipe](https://cloud.githubusercontent.com/assets/22283896/23197410/346f8ecc-f88e-11e6-8d78-b5daf25bacdb.jpg)

Tiempo empleado: 30 minutos

**Comment by jrsosago** [comment]
Dialogo Primer Mundo. Andrés Zorro. **Tiempo empleado: 40 minutos**
![pre-historia](https://cloud.githubusercontent.com/assets/22827594/23230194/0b4e930c-f911-11e6-92bd-ef3265190fbb.png)

**Comment by jrsosago** [comment]
Mockup campo de batalla. **Tiempo empleado: 1 hora y 10 minutos**

![sin titul](https://cloud.githubusercontent.com/assets/22827594/23237839/33086c26-f92d-11e6-9194-48554bd118ef.png)

![pantalla menu](https://cloud.githubusercontent.com/assets/22827594/23237730/9e632b06-f92c-11e6-8640-f419fccbd55c.png)

**Componentes**

1. Imágenes avatares
2. Barra de vida
3. Botones poderes
4. Botón de pausa
5. Avatares
6. Menú de pausa
