### ISSUE TITLE
1.4.3 Consolidación de escenarios

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#44]
**Descripción**

Complementar los escenarios faltantes según el documento presentado en la clase del 18 de febrero, siguiendo el modelo de caricaturización y teniendo en cuenta que los escenarios correspondientes a los mundos son los únicos que no se repiten.

**TAREAS**

- [x] Crear escenario para la Facultad de Ciencias Sociales
- [x] Crear escenario para la Facultad de Ciencias Administrativas, Económicas y Contables
- [x] Crear escenario para la Facultad de Mercadeo, Comunicación y Artes
- [x] Crear escenario para la Facultad de Ingeniería y Ciencias Básicas
- [x] Modificar el formato de los escenarios existentes para que sean compatibles con Phaser
- [x] Crear/Completar escenarios faltantes correspondientes a los mundos

**Comment by ghost** [comment]
# **Facultad de Ciencias Administrativas, Económicas y Contables** (Registro de Tiempo: 25 minutos)
![facultad de ciencias administrativas](https://cloud.githubusercontent.com/assets/22629833/23539523/e7a2e576-ffa9-11e6-89c9-40e8c3fe28d5.gif)

# **Facultad Ciencias Sociales** (Registro de Tiempo: 25 minutos)
![facultad de ciencias sociales](https://cloud.githubusercontent.com/assets/22629833/23539518/e21c3f9e-ffa9-11e6-91e5-3e65a69026aa.gif)

# **Facultad de Ingeniería y Ciencias Básicas** (Registro de Tiempo: 25 minutos)
![facultad de ingenieria](https://cloud.githubusercontent.com/assets/22629833/23539514/dc42f0c2-ffa9-11e6-9885-488882262a9b.gif)

# **Facultad de Mercadeo, Comunicación y Artes** (Registro de Tiempo: 25 minutos)
![faculad de mercadeo](https://cloud.githubusercontent.com/assets/22629833/23539510/d6627e48-ffa9-11e6-99f3-0ff41dad9614.gif)

**Comment by ghost** [comment]
# **Escenarios en Sprites** (Registro de Tiempo: 1 hora)

![bienestar lluvia](https://cloud.githubusercontent.com/assets/22629833/23151366/1cb81270-f7c8-11e6-9425-6d75807503e5.png)
![bienestar nieve](https://cloud.githubusercontent.com/assets/22629833/23151361/1cb5c4de-f7c8-11e6-95b3-5f3547262697.png)
![bienestar sol](https://cloud.githubusercontent.com/assets/22629833/23151362/1cb5f6fc-f7c8-11e6-873c-0df03522c6b3.png)
![bloque c lluvia](https://cloud.githubusercontent.com/assets/22629833/23151363/1cb64b20-f7c8-11e6-81ea-81f880eb7636.png)
![bloque c nieve](https://cloud.githubusercontent.com/assets/22629833/23151364/1cb6b830-f7c8-11e6-9072-5728070e6685.png)
![bloque c sol](https://cloud.githubusercontent.com/assets/22629833/23151365/1cb80032-f7c8-11e6-921a-44a9accf93b1.png)
![bloque g lluvia](https://cloud.githubusercontent.com/assets/22629833/23151367/1cd3495a-f7c8-11e6-88d5-8139893595eb.png)
![bloque g nieve](https://cloud.githubusercontent.com/assets/22629833/23151371/1cd49bf2-f7c8-11e6-845f-1aa9d0fbda33.png)
![bloque g sol](https://cloud.githubusercontent.com/assets/22629833/23151370/1cd48a7c-f7c8-11e6-82bd-7ae2824e2789.png)
![bloque j lluvia](https://cloud.githubusercontent.com/assets/22629833/23151368/1cd45e44-f7c8-11e6-82bc-23827b603c19.png)
![bloque j nieve](https://cloud.githubusercontent.com/assets/22629833/23151369/1cd48e8c-f7c8-11e6-9d7d-81004fac2fac.png)
![bloque j sol](https://cloud.githubusercontent.com/assets/22629833/23151372/1cd8f706-f7c8-11e6-9664-a088a7812c06.png)
![bloque k lluvia](https://cloud.githubusercontent.com/assets/22629833/23151373/1cf664da-f7c8-11e6-8e1a-65c73f7cb0a2.png)
![bloque k nieve](https://cloud.githubusercontent.com/assets/22629833/23151374/1cf6896a-f7c8-11e6-835b-11599d7f3f71.png)
![bloque k sol](https://cloud.githubusercontent.com/assets/22629833/23151375/1cf71d80-f7c8-11e6-904b-3a5e70b17fa2.png)
![cancha lluvia](https://cloud.githubusercontent.com/assets/22629833/23151376/1cf8740a-f7c8-11e6-9801-cefaf2f1371a.png)
![cancha nieve](https://cloud.githubusercontent.com/assets/22629833/23151377/1cf89fd4-f7c8-11e6-84e9-5ca539b6e4e1.png)
![cancha sol](https://cloud.githubusercontent.com/assets/22629833/23151378/1cfa4262-f7c8-11e6-9ca7-ff2be73f9f4a.png)
![facultad de ciencias administrativas](https://cloud.githubusercontent.com/assets/22629833/23151379/1d06f818-f7c8-11e6-93d2-eb94e0c73d4b.png)
![facultad de ciencias sociales](https://cloud.githubusercontent.com/assets/22629833/23151380/1d07af74-f7c8-11e6-8e00-073d4a118754.png)
![facultad de ingenieria](https://cloud.githubusercontent.com/assets/22629833/23151381/1d0837be-f7c8-11e6-8b8b-7767008d1785.png)
![facultad de mercadeo](https://cloud.githubusercontent.com/assets/22629833/23151382/1d091404-f7c8-11e6-8150-49ba5925823e.png)
![paradero lluvia](https://cloud.githubusercontent.com/assets/22629833/23151383/1d0a2b46-f7c8-11e6-8278-2ded02d91a53.png)
![paradero nieve](https://cloud.githubusercontent.com/assets/22629833/23151384/1d0e276e-f7c8-11e6-9168-22b600802e67.png)
![paradero sol](https://cloud.githubusercontent.com/assets/22629833/23151386/1d192146-f7c8-11e6-8423-69a60110f921.png)
![plazoleta lluvia](https://cloud.githubusercontent.com/assets/22629833/23151385/1d18a0c2-f7c8-11e6-97f5-9cee10662eec.png)
![plazoleta nieve](https://cloud.githubusercontent.com/assets/22629833/23151388/1d199126-f7c8-11e6-90d5-73fc4024d36b.png)
![plazoleta sol](https://cloud.githubusercontent.com/assets/22629833/23151387/1d198b72-f7c8-11e6-96e3-a41459270f57.png)
![poli medellin lluvia](https://cloud.githubusercontent.com/assets/22629833/23151389/1d1a4f58-f7c8-11e6-8ff5-a6dfbed3a731.png)
![poli medellin nieve](https://cloud.githubusercontent.com/assets/22629833/23151390/1d22bcba-f7c8-11e6-8f3f-fa30c066aa0b.png)
![poli medellin sol](https://cloud.githubusercontent.com/assets/22629833/23151391/1d28e4a0-f7c8-11e6-9096-966322dc67c5.png)
![sede excelencia lluvia](https://cloud.githubusercontent.com/assets/22629833/23151394/1d2cc700-f7c8-11e6-901e-62412825c59b.png)
![sede excelencia nieve](https://cloud.githubusercontent.com/assets/22629833/23151392/1d2a3904-f7c8-11e6-95dc-8d840879df13.png)
![sede excelencia sol](https://cloud.githubusercontent.com/assets/22629833/23151393/1d2c2e9e-f7c8-11e6-96ef-234a669ece2e.png)
![sede postgrados lluvia](https://cloud.githubusercontent.com/assets/22629833/23151395/1d2cf568-f7c8-11e6-99d6-b84261438baa.png)
![sede postgrados nieve](https://cloud.githubusercontent.com/assets/22629833/23151396/1d33b5a6-f7c8-11e6-829a-93a0470328a5.png)
![sede postgrados sol](https://cloud.githubusercontent.com/assets/22629833/23151397/1d38ee4a-f7c8-11e6-9552-3252ee00f632.png)
![facultad de ciencias adinistrativas](https://cloud.githubusercontent.com/assets/22629833/23539537/f3e6502a-ffa9-11e6-82ef-4d707ac92864.png)
![facultad de ciencias sociales](https://cloud.githubusercontent.com/assets/22629833/23539539/f402c4d0-ffa9-11e6-9894-5e1d04fb7995.png)
![facultad de ingenieria](https://cloud.githubusercontent.com/assets/22629833/23539540/f402d36c-ffa9-11e6-84bf-24cf706c5367.png)
![facultad de mercadeo](https://cloud.githubusercontent.com/assets/22629833/23539541/f402e366-ffa9-11e6-98a7-5ae2256bfb74.png)

**Comment by ghost** [comment]
# INFORME

[Informe 2.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/792267/Informe.2.docx)
