### ISSUE TITLE
Despliegue Version 1.2 de base de datos.

### ISSUE THREAD

**Issue by manuk160** [ISWPOLI/Pacto-de-Honor#446]
Procesos de despliegue de base de datos versión 2.

- [x] Enviar versión 1.1 con los cambios realizados.  asignada a @jnrubiano 

- [x] integrar los cambios para generar la versión 1.2. asignada a @manuk160

- [x] Despliegue en servidor y pruebas funcionales. asignada a @manuk160

**Comment by jnrubiano** [comment]
Hola Manuel:

Se realizó commit 79c6e1e974cce16797cf4f32d248331b8b20bf12 en el branch Consolidación. Encontraras el script de la DB versión 1.1
La ruta del script es:
Pacto-de-Honor/BACKEND/BASES/

Saludos.

**Comment by manuk160** [comment]
Se valida el scrip enviado y se inicia el proceso de consolidación con los cambios requeridos.

**Comment by manuk160** [comment]
Se realizo el despliegue en el servidor de acuerdo a lo propuesto.
