### ISSUE TITLE
6.2.18 Reporte SCRUM Master (Miércoles 3 de mayo)

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#451]
**Descripción**
Reporte SCRUM Master.

**Tareas a realizar**
- [x] Realizar reporte SCRUM Master, día miércoles 3 de mayo.

**Comment by ghost** [comment]
# Reporte 3 de Mayo

## Issue #451 - Reporte SCRUM MASTER (Miércoles 3 de Mayo) [Dario Muñoz]:
- Se revisaron y reportaron avances en las tareas de 8 integrantes del grupo de Frontend.
- Se subieron reportes a la Issue.

## Issue #447 - Documentación del codigo [Dario Muñoz]:
- Se explicó y documentó el archivo **boot.js**.
- Se explicó y documentó el archivo **box.js**.
- Se explicó y documentó el archivo **pruebasPsicotecnicas.js**.
- Se explicó y documentó el archivo **logros.js**.
- Se modificó el archivo **game.js**, ya que se agregaron nuevas lineas de código.

## Issue #421 - Estandarización de botones [Camilo D'achiardi]:
- Se diseñarón los sprites de los botones faltantes.

## Issue #471 - Cookies [Gabriel Álvarez]:
- Se implementó un script para el manejo de cookies.
- Se intenta implementar con la seleccion de personajes pero no se logra debido a que los botones estaban en un arreglo.

## Issue #469 - Integración Login y juego [Gabriel Álvarez, David Yepes y Julio Ernesto]:
- Se intento modificar la extension del archivo .jsp a .html.
- Se plantea una reunión con David Yepes y Julio Ernesto para hoy 3 de Mayo.
- Se habla con William Tautiva y el recomienda usar netbeans para ejecutar el juego.

## Issue #477 - Barra de carga [Sebastian Rodriguez]:
- Se implementó una barra de carga con un archivo html de prueba.
- Funciona, pero no como se espera, ya que hay algun error en el código.
- No se sabe si hay que modificar la barra de carga ya existente, o si hay que crear una nueva.

## Issue #476 - Implementación de sonidos faltantes en el juego [Sebastian Rodriguez]:
- Se realizo la implementación de sonidos de la batalla.
- Hay un problema con la sincronización con Git Hub Desktop, por lo tanto no se ve reflejada esta implementación.

## Issue #452 - Implementación de la caja sorpresa en el mapa [Juan Carlos y Juan Guillermo]:
- Se agrego un botón en el mapa de navegación que al ser presionado abre un estado en el que aparecen los tipos de cajas sorpresas.
- Se definio las recompensas de cada caja sorpresa.
- Se cambio el tamaño de las imagenes de las cajas para que sea mas agradable visualmente.
- Se implemento que se añadan recompensas al presionar dos cajas sorpresa.
- Aún falta implementar que se añadan las recompensas de 6 cajas sorpresa.

## Issue #481 - Acciones anteriores a guardar en la base de datos [Jeimy Sosa]:
- Aún no se ha tenido avances en esta tarea, porque aún no se ha hablado con Juan Camilo.

## Issue #482 - Realizar descripción de Servicios de pruebas Psicotecnicas y su JSON [Jeimy Sosa]:
- Se realizó un documento en el que hay descripción de servicios para las pruebas psicotecnicas.
- Se esta en espera de hablar con Juan Camilo para tener aprobación de cerrar la Issue.

## Issue #480 - Modificación módulo compra [Camila Gutiérrez]:
- Se realizaron 3 metodos que reciben cada uno recibe un JSON.
- Se realizarón pruebas de uno por uno.
- Falta realizar la prueba general.
