### ISSUE TITLE
1.1.28 Implementación de la caja Sorpresa en el mapa.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#452]
**Descripción**
Implementación de la cajas sorpresa en el mapa de navegación y definir sorpresas de cada caja.

**Tareas a realizar**
- [x] Implementación de las cajas sorpresa en el mapa de navegación.
- [x] Definir sorpresas que saldrán en cada caja.
- [x] Implementar aleatoriedad de las sorpresas que salen en cada caja.

**Comment by juankrlos08** [comment]
![image](https://cloud.githubusercontent.com/assets/25808382/25645912/9af3a680-2f78-11e7-895c-90142ee8da4c.png)

Se modifica el tamaño de la cajas para mejor visualización.

**Comment by juankrlos08** [comment]
![captura1](https://cloud.githubusercontent.com/assets/25808382/25733184/37042078-311c-11e7-913e-dc4ec5c80e6e.PNG)
![captura2](https://cloud.githubusercontent.com/assets/25808382/25733181/3702905a-311c-11e7-92af-f7175157b0c3.PNG)
![captura3](https://cloud.githubusercontent.com/assets/25808382/25733183/3703d758-311c-11e7-825f-20922a55bcb3.PNG)
![captura4](https://cloud.githubusercontent.com/assets/25808382/25733185/37048252-311c-11e7-8864-0c835f394785.PNG)
![captura6](https://cloud.githubusercontent.com/assets/25808382/25733180/37012bf2-311c-11e7-9cbb-b13bbc30d449.PNG)
![captura8](https://cloud.githubusercontent.com/assets/25808382/25733182/37039252-311c-11e7-965d-ced63c17a00d.PNG)

**Comment by juancelemin** [comment]
caja 5
![caja 5](https://cloud.githubusercontent.com/assets/17105514/25747506/50fafe24-316d-11e7-9258-367301b8af83.PNG)
![caja 5 1](https://cloud.githubusercontent.com/assets/17105514/25747508/51dacf54-316d-11e7-9999-e1093bb98572.PNG)
