### ISSUE TITLE
1.1.29 Imágenes de diálogos e imágenes que están por separado

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#453]
**Descripción**
Imágenes de diálogos e imágenes que estás por separado, XML.

**Tareas a realizar**

- [x] Separar cada una de las imágenes del texto.
- [x] Usando JavaScript y XML pegar el texto a la imagen. Issue  #303

**Comment by ivandav** [comment]
@jrsosago cuales imagenes y textos?

**Comment by CamilaG08** [comment]
@ivandav Las imágenes y textos tales como diálogos y frases previamente realizadas por Jeimy, Juan Guillermo y Jaime en los Issues #148 , #221 , #256 y #338

**Comment by jrsosago** [comment]
No se ven evidencias del trabajo realizado en esta Issue.

**Comment by ivandav** [comment]
@jrsosago 
En breves momentos se subiré el 75% del trabajo, ya que la tarea ha requerido mas tiempo del que estime.

**Comment by ivandav** [comment]
# Imágenes y textos unidos en javaScript
   - Se entregan lo archivos js de la imagenes que fueron modificadas y unidas a sus respectivos textos.
 


[dialogosPersonajesMalos.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/978197/dialogosPersonajesMalos.txt)
[frasesRetadoras.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/978196/frasesRetadoras.txt)
[tiposDePlagio.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/978195/tiposDePlagio.txt)

![busquedareemplazo](https://cloud.githubusercontent.com/assets/22629584/25978336/427c8204-3687-11e7-9c25-436f28683b05.png)
![clonacion](https://cloud.githubusercontent.com/assets/22629584/25978339/428149c4-3687-11e7-9fd4-a05ae8aec7a6.png)
![copiadopegado](https://cloud.githubusercontent.com/assets/22629584/25978337/428024b8-3687-11e7-8f12-c85f563d8d9b.png)
![dialogoabejas](https://cloud.githubusercontent.com/assets/22629584/25978340/42827394-3687-11e7-81da-50eec4bf9131.png)
![dialogobabuino](https://cloud.githubusercontent.com/assets/22629584/25978341/42868e20-3687-11e7-9718-880ddb0449c1.png)
![dialogobuitre](https://cloud.githubusercontent.com/assets/22629584/25978338/42806806-3687-11e7-9ce8-447dcf0a71e4.png)
![dialogoburro](https://cloud.githubusercontent.com/assets/22629584/25978342/429f8c9a-3687-11e7-81c4-890f1c89c5ab.png)
![dialogocamaleon](https://cloud.githubusercontent.com/assets/22629584/25978344/42a5cef2-3687-11e7-93d8-bdc48363ea49.png)
![dialogohiena](https://cloud.githubusercontent.com/assets/22629584/25978343/42a31edc-3687-11e7-953d-7983e5c6a42f.png)
![dialogolagarto](https://cloud.githubusercontent.com/assets/22629584/25978346/42b2d98a-3687-11e7-8139-a9551e2871c6.png)
![dialogoperesozo](https://cloud.githubusercontent.com/assets/22629584/25978345/42b25af0-3687-11e7-85b5-5a3098ce8901.png)
![dialogorata](https://cloud.githubusercontent.com/assets/22629584/25978347/42c20e8c-3687-11e7-855f-323a1554bdfc.png)
![dialogovibora](https://cloud.githubusercontent.com/assets/22629584/25978350/42c7784a-3687-11e7-90c4-59022b78bbb6.png)
![dialogozorro](https://cloud.githubusercontent.com/assets/22629584/25978349/42c705e0-3687-11e7-95dc-b9c4c74c5fae.png)
![error404](https://cloud.githubusercontent.com/assets/22629584/25978348/42c4acc8-3687-11e7-928c-f1b9c2d82b78.png)
![fraseabejas](https://cloud.githubusercontent.com/assets/22629584/25978351/42c96a42-3687-11e7-85b5-0dd1478f2688.png)
![fraseabejas2](https://cloud.githubusercontent.com/assets/22629584/25978352/42cdd37a-3687-11e7-9121-70def32f1042.png)
![fraseabejas3](https://cloud.githubusercontent.com/assets/22629584/25978353/42d86be6-3687-11e7-9ec8-c40d94f4ba7b.png)
![fraseburro](https://cloud.githubusercontent.com/assets/22629584/25978355/42e5f04a-3687-11e7-8bb2-9c79e503e910.png)
![fraseburro2](https://cloud.githubusercontent.com/assets/22629584/25978354/42e5c4a8-3687-11e7-979f-eb2fc7b8cd73.png)
![fraseburro3](https://cloud.githubusercontent.com/assets/22629584/25978356/42e82220-3687-11e7-9c57-4afc54e677b4.png)
![frasecamaleon](https://cloud.githubusercontent.com/assets/22629584/25978357/42ebc218-3687-11e7-957f-47da43310dbd.png)
![frasecamaleon2](https://cloud.githubusercontent.com/assets/22629584/25978358/42f07a4c-3687-11e7-80fb-8b43a1955ddc.png)
![frasecamaleon3](https://cloud.githubusercontent.com/assets/22629584/25978359/42f545ea-3687-11e7-9252-efc9d686e4ee.png)
![fraseoso](https://cloud.githubusercontent.com/assets/22629584/25978361/42fead42-3687-11e7-9cb9-afa21aa09db8.png)
![fraseoso2](https://cloud.githubusercontent.com/assets/22629584/25978360/42fe365a-3687-11e7-898a-19ab9eaa5f57.png)
![fraseoso3](https://cloud.githubusercontent.com/assets/22629584/25978362/4304fcec-3687-11e7-8a93-b37a0c967195.png)
![fraseperesozo](https://cloud.githubusercontent.com/assets/22629584/25978363/430698fe-3687-11e7-9bb0-049f5e315674.png)
![fraseperesozo2](https://cloud.githubusercontent.com/assets/22629584/25978364/4313e310-3687-11e7-8e79-93f70bc0cd9f.png)
![fraseperesozo3](https://cloud.githubusercontent.com/assets/22629584/25978365/43160f28-3687-11e7-8c66-33f5670431f4.png)
![frasezorro](https://cloud.githubusercontent.com/assets/22629584/25978367/431e3db0-3687-11e7-8359-b4f7ccb72a18.png)
![frasezorro2](https://cloud.githubusercontent.com/assets/22629584/25978366/431b61e4-3687-11e7-8a45-81d886ada63c.png)
![frasezorro3](https://cloud.githubusercontent.com/assets/22629584/25978368/431fdc7e-3687-11e7-8b12-b664bede3d7c.png)
![fuenterss](https://cloud.githubusercontent.com/assets/22629584/25978369/432221d2-3687-11e7-9062-fd43989af26c.png)
![hibrido](https://cloud.githubusercontent.com/assets/22629584/25978370/4327a7f6-3687-11e7-9851-51667361b20a.png)
![mosaico](https://cloud.githubusercontent.com/assets/22629584/25978371/432c3794-3687-11e7-98a4-9c84356a18eb.png)
![reciclado](https://cloud.githubusercontent.com/assets/22629584/25978372/432f6068-3687-11e7-9006-d2c8507c4520.png)
![remix](https://cloud.githubusercontent.com/assets/22629584/25978373/4337fc28-3687-11e7-9d21-62d455e48450.png)
![reutilizacion](https://cloud.githubusercontent.com/assets/22629584/25978374/4338b230-3687-11e7-875c-49aaaa27040b.png)
