### ISSUE TITLE
Formulario login- registro-recuperacion contraseña

### ISSUE THREAD

**Issue by alexsabsan** [ISWPOLI/Pacto-de-Honor#46]
Prototipo funcional de :
Loggin 
Registro
Olvidar Contraseña

**Comment by alexsabsan** [comment]
Formularios versión  1

[Formulario Registro.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/791997/Formulario.Registro.zip)

**Comment by ghost** [comment]
Se verifican los formularios, y se discuten con los mokups actuales que están se hacen las modificaciones correspondientes  se crean los nuevos todo se concluirá en el issues #149 .
