### ISSUE TITLE
2. Crear metodo buscar personajes tipo jefe

### ISSUE THREAD

**Issue by JuanCheroslan** [ISWPOLI/Pacto-de-Honor#463]
Este método hace parte del servicio personaje, donde según un id de usuario deben entregarse los personajes de tipo jefe que este posee.

- [x] Desarrollar método dentro del servicio Personaje
- [x] Generar las pruebas dentro del soapui-project
- [x] Documentar el método

**Comment by jnrubiano** [comment]
Para el método "perfil", se generó el issue #478 
Para el método "comprar" , se generó el issue #479

**Comment by jnrubiano** [comment]
Desarrollo: commit 5858a5aa6a1c8132902dae147dbf98155c8ad452
Pruebas y documentación: commit f886675f3e06791dacd06b911bdd28c1f106f732
