### ISSUE TITLE
1.1.30 Implementación Escudos

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#464]
**Descripción**
Implementar Escudos en el campo de batalla.

**Tareas a realizar**
- [x] Implementar escudos en el campo de batalla.

**Comment by nmartinezmarin** [comment]
Se hace commit en la rama Nicolas Martinez de el primer avance en la implementación de los escudos, no se hace merge porque la tarea no esta terminada

**Comment by nmartinezmarin** [comment]
Se hace merge con la implementación de los escudos https://github.com/ISWPOLI/Pacto-de-Honor/pull/507

Tiempo registrado: 2 horas

**Comment by jrsosago** [comment]
Se cierra está Issue, por actividades terminadas
