### ISSUE TITLE
Servicio REST log

### ISSUE THREAD

**Issue by JuanCheroslan** [ISWPOLI/Pacto-de-Honor#465]
Este servicio debe tener todos los metodos que se necesitan para poder manejar la informacion de trazabilidad del juego.

inicialmente se tiene claro por parte del equipo de front end que se necesitan saber cuantas veces un jugador ha entrado a un nivel, para esto se deben realizar las siguientes tareas

- [x] analizar la estructura actual de la base de datos

- [x] si no hay cambios proponer metodos diferentes al CRUD para poder entregar toda la información que pudiera necesitar el equipo de front end

- [x] generar el codigo

- [ ] generacion de documento explicativo

- [ ] documento de pruebas SOAPUI

**Comment by EdnaEspejo** [comment]
Se realiza revisión de la información que actualmente tiene la entidad Log encontrando que muestra con respecto a cada jugador, la fecha de inicio, final y realiza un cálculo sobre el tiempo que se encuentra en línea. Dado a lo solicitado por el equipo de Frontend es necesario identificar cuantas veces está accediendo a un determinado nivel; por lo que se hace necesario realizar una modificación en la tabla que permita identificar el nivel.

**Comment by JuanCheroslan** [comment]
@EdnaEspejo  adjunto script de modificacion de la base de datos para la tabla log

ALTER TABLE `log` ADD `id_nivel` INT  NULL ;
ALTER TABLE `log` ADD `id_mundo` INT NULL ;
ALTER TABLE `log` ADD `id_personje` INT NULL ;

**Comment by EdnaEspejo** [comment]
Se esta generando el código para la implementación del servicio, sin embargo al momento de agregar servicios adicionales para generar la información solicitada no realiza el deploy de manera efectiva.

**Comment by EdnaEspejo** [comment]
Se genera codigo pendiente incluir metodos especiales

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rest;

import entities.Log;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.ArrayList;
import java.util.List;
import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;

/**
 *
 * @author 1013608348
 */
@Stateless
public class LogFacadeREST extends AbstractFacade<Log> {
    @PersistenceContext(unitName = "RestLogPU")
    private EntityManager em;

    
    @GET
    @Override
    @Produces({"application/json"})
    public List<Log> findAll() {
        Log log = new Log();
        List<Log> list = new ArrayList<>();
        list.add(log);
        return list;
    }
    
    @GET
    @Path("findRange")
    @Produces({"application/json"})
    public List<Log> findRange(@QueryParam("from") Integer from, @QueryParam("to") Integer to) {
        return super.findRange(new int[]{from, to});
    }
    
    @GET
    @Path("count")
    @Produces("text/plain")
    public String countREST() {
        return String.valueOf(super.count());
    }
    
    @Override
    protected EntityManager getEntityManager() {
        return em;
    }

    public LogFacadeREST() {
        super(Log.class);
    }
    
}

**Comment by DiegOliveros** [comment]
Esta historia no debe ser cerrada hasta tanto no se tengan las tareas terminadas:
Generación de documento explicativo,  documento de pruebas SOAPUI

**Comment by DiegOliveros** [comment]
Los cambios deben ser llevados al repositorio no adjuntos como comentario.

**Comment by EdnaEspejo** [comment]
@DiegOliveros Se genera isse #530 para continuar con los puntos pendientes en el sprint 13 con una estimación corta ya que no me tomará mucho tiempo finalizar la actividad.
