### ISSUE TITLE
1.1.31 Encapsulamiento de variables Campo batalla

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#466]
**Descripción**
Encapsulamiento de variables campo batalla.
**Tareas a realizar**
- [x] Realizar encapsulamiento de variables campo de batalla.
- [x] Realizar formato de encapsulamiento de variables para aplicarlo al resto del juego.

**Comment by jrsosago** [comment]
No se evidencia avance en esta Issue.

**Comment by nmartinezmarin** [comment]
Se Hace el encapsulamiento de las variables en el campo de batalla y se ajusta para que funcione correctamente de esta forma https://github.com/ISWPOLI/Pacto-de-Honor/pull/505
[Encapsulamiento de variables.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/979413/Encapsulamiento.de.variables.pdf)
Se adjunta el formato utilizado para realizar la tarea

Registro de tiempo : 2 Horas

**Comment by jrsosago** [comment]
Se cierra esta Issue, por tareas terminadas.
