### ISSUE TITLE
7.3 Integración Login y juego

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#469]
**Descripción**
Integrar el Login del juego con el juego.

**Tareas a realizar**

- [x] Realizar descripción de tareas a realizar. @Basespoli 

- [ ] Integrar el Login del juego con el juego. @dayepesb @gsalvarez

- [x] Consumir servicio REST de Login. @dayepesb @gsalvarez

**Comment by ghost** [comment]
Se realiza las tareas que se consideran pertinentes según lo conversado con el equipo de integración para la integración de la autentificación del registro de login con la aplicación en el juego.

tiempo empleado 10 min

**Comment by gabogabbs** [comment]
Se revisan los archivos del Login para hacer la conexión con los archivos del juego. Al no lograrlo, se plantea una reunión con @Basespoli y @dayepesb el día miércoles para cumplir la tarea.

**Comment by ghost** [comment]
Se revisa la clase StringTokenizer y UUID para poder realizar el token aleatorio cifrado, para poder llevar a cabo la integración y ya se esta decodificando el método para poder realizarla el dia sabado.

tiempo empleado 1 hora

**Comment by gabogabbs** [comment]
Se realiza una reunión con @Basespoli y @dayepesb para hacer la unificación del login con el juego.
@Basespoli nos explicó a @dayepesb y a mi cómo funciona los archivos .jsp y .java del login, para que nosotros podamos tener acceso a estos archivos, manejarlos y unirlos con el trabajo que se tiene del juego.
Sin embargo, hace falta el servidor, así que se planea hacer un servidor local para avanzar en las pruebas.

REGISTRO DE TIEMPO: 30 minutos.

**Comment by ghost** [comment]
Se crea token con la clase StringTokenizer y UUID ya está determinando cómo se puede realizar para encriptarlo y para que sea aleatorio.

Tiempo empleado 1:10 horas

**Comment by ghost** [comment]
`package Controlador.token;
import java.util.Random;
import java.util.UUID;

/**
 *
 * @author JERR
 */

public class token {
    String token="";
    UUID tokenUUID;

    public token(UUID tokenUUID) {
        this.tokenUUID = tokenUUID;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public UUID getTokenUUID() {
        return tokenUUID;
    }

    public void setTokenUUID(UUID tokenUUID) {
        this.tokenUUID = tokenUUID;
    }
    
    
    public token() {
    }
    
    
    
String  getCadenaAlfanumAleatoria (int longitud){
long milis = new java.util.GregorianCalendar().getTimeInMillis();
    System.out.println(milis);
Random r = new Random(100);// aleatoriedad
System.out.println(r);
int i = 0;
while ( i < longitud){ // según la longitud
char c = (char)r.nextInt(255);//se generan caracteres
if ( (c >= '0' && c <='9') || (c >='A' && c <='Z') ){ //validando numeros o letras
token += c;// los guardo en token
i ++;
}
}
return token;//devuelvo el token
}   

    public static void main(String[] args) {
        token token1=new token();
        String token =token1.getCadenaAlfanumAleatoria (16);
        
        UUID TokenUuid= UUID.randomUUID();
        System.out.println(token);
        System.out.println(UUID.randomUUID());
        System.out.println();
    }

}
`

Teimepo empleado 1 hora

**Comment by ghost** [comment]
Se verifican las dos posibilidades de realizar token, se determinan  que se puede crear por el método tradicional creando una cadena alfanumérica y aleatoria  pero se identifica que la clase UUID implementada años posteriores realiza la misma función con una segmentación de la clase  StringTokenizer como un identificador único universal    que maneja un bit de 128 bit donde tiene una representación textual canónica los dieciséis octetos de un UUID se representan como 32 hexadecimal (base 16) dígitos 8-4-4-4-12.

**Comment by CamilaG08** [comment]
Se cierra este Issue dado al cambio de asignaciones por @DiegOliveros
