### ISSUE TITLE
6.1 Reportes Product Owner

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#47]
Reportes, reuniones y sugerencias dadas.

**Comment by jrsosago** [comment]
Buenas noches, el día de hoy ayude a Jaime Bernal con una pequeña explicación acerca de como realizar la documentación vía Skype.

Tiempo empleado: 15 minutos.

**Comment by CamilaG08** [comment]
**Reporte sábado 18 Febrero**

- Envío del documento a Dario y Nicolás para estandarización del juego y aclaración de dudas
- Explicación de la tarea asignada a Nicolás

Tiempo empleado: 15 minutos

**Comment by CamilaG08** [comment]
**Reporte domingo 19 Febrero**

- Aclaración de dudas a Dario sobre los mockups, formato de los escenarios en Phaser y los escenarios
- Revisión de Issues para cerrar algunos
- Guía a Jaime para la documentación
- Guía a Ernesto para revisar permisos y funcinamiento de GitHub

Tiempo empleado: 1 hora

**Comment by CamilaG08** [comment]
**Reporte lunes 20 Febrero**

- Aclaraciones a Gabriel sobre los tipos de ataque para le creación de los escudos
- Guía a Juan Carlos para la realización de su parte en la estandarización del código fuente
- Ayuda a Dario para su reporte como Scrum Master
- Actualización de los documentos de soporte en el Issue de Nicolás
- Revisión de Issues, aportes y cierre de algunos

Tiempo empleado: 30 minutos

**Comment by CamilaG08** [comment]
**Reporte martes 21 Febrero**

- Ayuda a Dario con las asignaciones para su reporte como Scrum Master
- Ayuda y aclaraciones a Camilo y Gabriel para la realización de los Sprites
- Aclaraciones sobre la asignación a Nicolás
- Aclaración de dudas a Jaime sobre su asignación

Tiempo empleado: 20 minutos

**Comment by CamilaG08** [comment]
**Reporte del 22 de Febrero al 1 de Marzo**

- Revisión de Issues sin cerrar (1 hora)
- Estandarización de mockups (2 horas)
- Guía de documentación a Jaime (1 hora)
- Aclaración de dudas a Ernesto y Juan Sebastián (2 horas)
- Revisión de Issues sin cerrar y seguimiento a los antiguos (2 horas)
- Creación y asignación de tareas (2 horas)
- Modificar y organizar el tablero del proyecto en GitHub (1 hora y 30 minutos)
- Estandarización y detalle del juego en un documento (2 horas y 30 minutos)

**Comment by jrsosago** [comment]
Se realiza organización últimos Issues Antiguos, se elimina dicha columna. **Tiempo empleado: 15 minutos**

**Comment by jrsosago** [comment]
Reunión con @CamilaG08, el día 14 de Marzo para definir actividades para los Sprints 5 y 6.                    

**Tiempo empleado:30 minutos**

**Comment by jrsosago** [comment]
Reunión con Camila para recibir informe Jaime y definir tareas Sprint 8.

**Comment by jrsosago** [comment]
Reunión con SCRUM Master Dario para mostarle tareas realizadas para el Sprint 7

**Comment by jrsosago** [comment]
El día 5 de Abril, se hace reunión con Camila, para organizar, Sprint Trabajo Individual y Sprint 9. **Tiempo empleado: 30  minutos**

**Comment by jrsosago** [comment]
Se crea Issue #357 . **Tiempo empleado:17 minutos**

**Comment by jrsosago** [comment]
Reunión con Camila vía Skype el día 14 de Abril del 2017, para planeación y asignación de tareas Sprint 9. **Tiempo empleado: 2 horas**

**Comment by jrsosago** [comment]
Se resuelven dudas sobre la Issue #378.

**Comment by jrsosago** [comment]
Se realiza reunión con Camila vía Skype para planear actividades Sprint 11, el día 21 de Abril 2017. **Tiempo empleado: 1 hora.**

**Comment by jrsosago** [comment]
Se realiza segunda evaluación. **Tiempo empleado:40 minutos**

**Comment by jrsosago** [comment]
Se revisa  y acepta entrega de la Issue #338. **Tiempo empleado:5 minutos**

**Comment by jrsosago** [comment]
Revisar reportes de SCRUM Master del día Sábado 22 de Abril y se siguen sugerencias. **Tiempo empleado:12 minutos**

**Comment by jrsosago** [comment]
Se realiza planeación de algunas actividades de los siguientes Sprints con @CamilaG08.

**Comment by jrsosago** [comment]
Se realiza reunión en clase el día miércoles con Camila para definir los Sprints siguientes.

**Comment by jrsosago** [comment]
Se realiza reunión con el profesor Diego para pruebas Psicotécnicas

**Comment by jrsosago** [comment]
Se realiza reunión con Camila para mirar el juego y el sonido implementado

**Comment by jrsosago** [comment]
Reunión con los profesores para definir exposición día viernes y reunión vicerrector la cual se realizara al finalizar el semestre.

**Comment by jrsosago** [comment]
Se realizo reunión con el profesor Diego Oliveros, el día 12 de Mayo está reunión fue referente a las pruebas Psicotécnicas.**Tiempo empleado: 1 hora y 20 minutos.**

**Comment by jrsosago** [comment]
Se realiza reunión en la clase del sábado 13 de Mayo para planeación de los siguientes Sprint y reasignación de tareas del presente Sprint, dicha reunión se lleva acabo con @CamilaG08

**Comment by jrsosago** [comment]
Se realiza reunión con el profesor Diego para revisar respuesta del Departamento de Psicología sobre las pruebas Psicotécnicas que se implementarán en el juego.

**Comment by jrsosago** [comment]
Se realiza reunión con Ernesto para aclarar dudas sobre pruebas Psicotécnicas y su servicio referente.

**Comment by jrsosago** [comment]
Se realiza reunión con Juan Camilo y Nicolás para explicar servicios puntos pruebas Psicotécnicas.

**Comment by jrsosago** [comment]
Se realiza reunión con Juan Camilo, Nicolás Martínez y Julio Ernesto, para explicación pruebas Psicotecnica.

**Comment by jrsosago** [comment]
En está Issue, Camila y yo realizábamos comentarios de reuniones, sugerencias dadas a nuestros compañeros y todo lo referente a el cargo de Product Owner, se cierra está Issue debido a que se termina el semestre.
