### ISSUE TITLE
Servicio REST Mundo Token Pruebas de Casos

### ISSUE THREAD

**Issue by wpradere** [ISWPOLI/Pacto-de-Honor#470]
- [x] Creación método token

- [x] Prueba Datos null

- [x] Prueba Dato errado 

- [x] Actualizar documentación

**Comment by rzambrano112** [comment]
Este issues queda pendiente para desarrollo para el próximo semestre. Quiero manifestar que se cierra pero el modulo queda para inicio de desarrollo. De la misma manera, en el módulo administración queda pendiente la parte de reportes y el login del módulo. #470
