### ISSUE TITLE
1.1.32 Cookies

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#471]
**Descripción**
Cookies y Tokens.

**Tareas a realizar**
- [x] Incluir script para manejar Cookies.
- [x] Crear la estructura de las Cookies.
- [x] Usar Cookie para guardar el Token de Login y usarlo en consumos de servicios.

**Comment by gabogabbs** [comment]
Se incluye un script para manejar Cookies y se hace Merge en la rama Master. REGISTRO DE TIEMPO: 2 horas.

**Comment by gabogabbs** [comment]
Se implementan unas líneas de código para usar cookies al momento de seleccionar el personaje para la batalla. Se presentan problemas ya que los botones de los personajes están en un arreglo. REGISTRO DE TIEMPO: 1 hora.

**Comment by CamilaG08** [comment]
Este Issue se ve afectado debido al retraso de infraestructura, queda pendiente su aplazamiento o cierre.

**Comment by CamilaG08** [comment]
Se mueve al Sprint 13, contando con que se va a tener el servidor pronto.

**Comment by DiegOliveros** [comment]
@CamilaG08 Para cualquiera de los servicios que no estén funcionando, definan la estructura Json, denle valores provisionales y sigan adelante con la codificación.

**Comment by jrsosago** [comment]
@gsalvarez se debe entregar el día miércoles 10 de mayo, para asignación de nuevas tareas.

**Comment by gabogabbs** [comment]
Se implementa la cookie para guardar el Token de Login, que se usará en consumos de servicios.
Se da como concluido este issue.
REGISTRO DE TIEMPO: 30 minutos.
