### ISSUE TITLE
1.1.33 Encriptar datos

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#472]
**Descripción**
Encriptación de datos.

**Tareas a realizar**
- [x] Realizar listado de tareas con asignación.  @dayepesb 
- [x] Investigar sobre algoritmos de cifrado. @dayepesb
- [x] Implementar un algoritmo de cifrado hash en javascript@dayepesb
- [x] Implementar un allgoritmo de cifrado Simetrico en javascript @dayepesb

**Comment by dayepesb** [comment]
[cifrado.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/972407/cifrado.zip)

se suben los dos tipos de cifrado que se vana a tener en cuenta para la aplicación.

**Comment by dayepesb** [comment]
[Cifrado SHA.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/972415/Cifrado.SHA.zip)

Se presenta el cifrado que se eligió para el proyecto con un ejemplo de como debe implementarse la librería descargada en html con javascrip y un informe dando a conocer las razones de porque se escogió este.

**Comment by jrsosago** [comment]
Se cierra está Issue, por tareas terminadas
