### ISSUE TITLE
1.2.12 Algoritmo desbloqueo de personajes por mundo.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#473]
**Descripción**
Algoritmo desbloqueo de personajes por mundo. 

**Tareas a realizar**

- [x] Implementación algoritmo desbloqueo de personajes por mundo.
- [x] Implementación de Json de desbloqueo.

**Comment by CristianGarzonBernal** [comment]
[compra.json.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/975089/compra.json.txt)

**Comment by CristianGarzonBernal** [comment]
[compra.json.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/977882/compra.json.txt)
