### ISSUE TITLE
7.3.1 Integración Login con otros esquemas Login

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#475]
**Descripción**
Integración Login con otros esquemas Login.

**Tareas a realizar**
- [x] Realizar listado de tareas a realizar. @Basespoli 

- [x]  Identificar los datos para el consumo de los servicios. @Basespoli 

- [x] Realizar el socket de comunicaciones al servidor para consumir los servicios desde la autentificación de usuario. @Basespoli 

- [ ] Verificar el envio de  informacion a traves del socket para poder hacer el consumo de servicios y el envío del token alfanumérico de forma satisfactoria.   @Basespoli

**Comment by ghost** [comment]
Se realiza las tareas que se consideran pertinentes según lo conversado con el equipo de integración para la integración de la autentificación con registro de login con la aplicación en los esquemas de login. 

Tiempo estimado 15 min

**Comment by ghost** [comment]
Se revisa ServerSocket para poder realizar el socket con el servidor local, para poder llevar a cabo la integración y ya se está decodificando el método para poder consumir servicios.

tiempo empleado 1 hora

**Comment by ghost** [comment]
Se revisa la documentación para consumir los servicios propuestos por el equipo de BackEnd pero al no lograr verificar la estructura con la estructura del login se programa reunión con @jnrubiano para poder terminar la tarea de forma correcta.  

Tiempo empleado 30 min

**Comment by ghost** [comment]
Se realiza reunión con @jnrubiano  donde se determina que ya están definidos los servicios para consumir,  me los explico pero tengo que investigar cómo consumirlos mediante el token y transportar por un socket la información de modo cifrado se realiza la investigación.  

Tiempo empleado 1 hora.

**Comment by ghost** [comment]
`/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sockets;

import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;


/**
 *
 * @author JERR
 */

/**
 Conexión proporciona datos de sockets, mesaje, flojos
 * proporciona la conexion del cliente por con el servidor
 * los flujhos son manejados desde el constructor
  */

public class Conexion {//cliente Servidor flujhos y socket asociados
private final int PUERTO = 8080; //Puerto para la conexión
    private final String HOST = "localhost"; //Host para la conexión
    protected String mensajeServidor; //Mensajes entrantes a el servidor
    protected ServerSocket ss; //Socket del servidor
    protected Socket cs; //Socket del cliente
    protected DataOutputStream salidaServidor, salidaCliente; //Flujo de datos de salida
    
    public Conexion(String tipo) throws IOException //Constructor con control excelciones
    {
        if(tipo.equalsIgnoreCase("servidor"))
        {
            ss = new ServerSocket(PUERTO);//Se crea el socket para el servidor en puerto 8080 indicado
            cs = new Socket(); //Socket para el cliente
        }
        else
        {
            cs = new Socket(HOST, PUERTO); //Socket para el cliente en localhost puerto 8080
        }
    }
}`

Tiempo empleado 30 minutos

**Comment by ghost** [comment]
`/**
 * @author JERR
 */
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import sockets.Conexion;

/**
 Hereda de conexión para hacer uso de los sockets y establece conexion con servidor
 * Envia los mensajes el servidor los recibe y ciera la conexion.
 */

public class Servidor extends Conexion 

        
{
    public Servidor() throws IOException{super("servidor");} //Se usa el constructor para servidor de Conexion

    public void startServer()//iniciar el servidor
    {
        try
        {
            System.out.println("Esperando..."); //Esperando conexión

            cs = ss.accept(); //Accept inicia el socket y espera una conexión desde cliente.

            System.out.println("Cliente en línea");

            //Flujo de salida del cliente para enviarle mensajes
            salidaCliente = new DataOutputStream(cs.getOutputStream());

            //Envío un mensaje al cliente usando su flujo de salida
            salidaCliente.writeUTF("Petición recibida y aceptada");
            
            //Flujo entrante desde el cliente get en entrada
            BufferedReader entrada = new BufferedReader(new InputStreamReader(cs.getInputStream()));
            
            while((mensajeServidor = entrada.readLine()) != null) //Mientras el cliente emita mensajes
            {
                //Se publica el mensaje recibido
                System.out.println(mensajeServidor);
            }
            
            System.out.println("Fin de la conexión");
            
            ss.close();//Se finaliza la conexión con el cliente
        }
        catch (Exception e)
        {
            System.out.println(e.getMessage());
        }
    }
}
    `

Tiempo empleado 30 min

**Comment by ghost** [comment]
`/**
  * @author JERR
 */
import java.io.DataOutputStream;
import java.io.IOException;

/**
 Hereda de conexión para hacer uso de los sockets
 * Espera la conexion del cliente por el puerto 8080 con metodo accept
 * Envia mensade confirmacion y Recepcion de mensajes enviados por cliente
 * y publicacion, cierre de conexión.
 */
public class Cliente extends Conexion
{
    //Se usa el constructor para cliente de Conexion
    public Cliente() throws IOException{super("cliente");} 

    public void startClient() //iniciar el cliente
    {
        try
        {            
            //Flujo de datos hacia el servidor
            salidaServidor = new DataOutputStream(cs.getOutputStream());

            //Envio dos mensajes
            for (int i = 0; i < 2; i++)
            {
                //Se escribe en el servidor con el su flujo de datos
                salidaServidor.writeUTF("Este es el mensaje número " + (i+1) + "\n");                
            }           

            cs.close();//Fin de la conexión

        }
        catch (Exception e)
        {
            System.out.println(e.getMessage());
        }
    }
}`

Tiempo empleado 30 min

**Comment by ghost** [comment]
`/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sockets;

import java.io.IOException;

/**
 *
 * @author JERR
 */

//Clase principal que hará uso del cliente
public class MainCliente
{
    public static void main(String[] args) throws IOException
    {  
        Cliente cli = new Cliente(); //Se crea el cliente
        
        System.out.println("Iniciando cliente\n");
        cli.startClient(); //Se inicia el cliente
    }
}`

Tiempo empleado 15 min

**Comment by ghost** [comment]
`/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sockets;

import java.io.IOException;

/**
 *
 * @author JERR
 */

//Clase principal que hará uso del servidor
public class MainServidor
{
    public static void main(String[] args) throws IOException
    {        
        Servidor serv = new Servidor(); //Se crea el servidor
        
        System.out.println("Iniciando servidor\n");
        serv.startServer(); //Se inicia el servidor
    }
}
  `

Tiempo empleado 15 min con pruebas

**Comment by ghost** [comment]
`package serviciosRest;

import static javax.ws.rs.HttpMethod.POST;
import javax.ws.rs.Path;

/**
 *
 * @author JERR
 */

@Path("/Registrar")
public class ServicioRegistro {

@POST
@Path("/Registrar")
@Consumes(MediaType.APPLICATION_JSON)
    public void addUsuario(Registrologin registro) {
        System.out.println(registro.getNombre() + registro.getClave());
    }
}`

Tiempo empleado 1 hora

**Comment by ghost** [comment]
`@Path("/Registrar")

public class ServicioRegistro {

    @POST
    @Path("/Registrar")
    @Consumes(MediaType.APPLICATION_JSON)
    public void addUsuario(Registrologin registro) {
        System.out.println(registro.getNombre() + registro.getClave());
    }
}`

Esta tarea toma una hora adicional por la capacitación y 30 min de implementación y prueba.

**Comment by CamilaG08** [comment]
Se cierra debido al cambio de asignaciones por @DiegOliveros
