### ISSUE TITLE
1.1.34 Implementación de sonidos faltantes en el juego.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#476]
**Descripción**
 Implementación de sonidos faltantes en el juego.

**Tareas a realizar**
- [x] Seleccionar y implementar sonidos faltantes en el juego. (Todo el juego debe tener sonido).

**Comment by jrsosago** [comment]
No se evidencia avance de está Issue.

**Comment by ghost** [comment]
Se realiza la implementación de los sonidos del juego, ya el codigo se dubio por github desktop. Y el detalle de la implementacion esta en el informe semanal de trabajo.

**Comment by jrsosago** [comment]
@JuanSebastianRodriguezJ recordar nombrar el número de la Issue al momento de hacer commit. Se cierra está Issue por actividades realizadas.
