### ISSUE TITLE
1.1.35 Barra de carga

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#477]
**Descripción**
Realizar barra de carga para los niveles del juego, visualmente bonita.

**Tareas a realizar**
- [x] Realizar barra de carga para los niveles del juego, visualmente bonita. Recibir sugerencias de @gsalvarez  Gabriel

**Comment by jrsosago** [comment]
No se evidencia avance de está Issue

**Comment by ghost** [comment]
Se realiza la implementación de la barra de carga o pre-loader. Toda la descripción del desarrollo de la tarea esta en el informa semanal. Ya se subió el código por Github desktop.

**Comment by jrsosago** [comment]
@JuanSebastianRodriguezJ recordar al momento de hacer el commit poner el nombre de la Issue. Se cierra está Issue por actividades realizadas
