### ISSUE TITLE
Crear el método "comprar" dentro del servicio Personaje

### ISSUE THREAD

**Issue by jnrubiano** [ISWPOLI/Pacto-de-Honor#479]
Pre requisitos:
- [x] Listar los personajes con el id.
- [x] Listar los jugadores con el id.

Desarrollo:
- [x] Desarrollar el método "comprar"
- [x] Generar las pruebas dentro del soapui-project
- [x] Documentar el método

**Comment by jnrubiano** [comment]
Se pasa el método "comprar" al Sprint 13 ya que no se tiene conocimiento pleno del campo "estado"
@JuanCheroslan @CamilaG08 por fa su amable colaboración en la explicación de dicho campo.

Saludos.

**Comment by CamilaG08** [comment]
Hola @jnrubiano el campo estado se refiere a si el jugador posee (1) ese personaje o no (0).
