### ISSUE TITLE
Servicio REST StatusPlayer

### ISSUE THREAD

**Issue by jnrubiano** [ISWPOLI/Pacto-de-Honor#48]
Crear servicio REST en Java que retorne el estado general de un jugador. Se realiza un objeto jugador con atributos de prueba según los requerimientos que se tienen actualmente.

**Comment by jnrubiano** [comment]
- [x] Servicio REST usando Tomcat 8
- [x] Commit con el código fuente del prototipo

**Comment by jolarter** [comment]
Para finalizar construyamos un documento que describa el directorio de metodos disponibles y las formas de invocarlo. Se realizara el consumo de los servicios desde JS.

**Comment by jnrubiano** [comment]
Hola @jolarter 

Adjunto el documento propuesta para los servicios REST, se iniciará con el desarrollo de ellos y de acuerdo al control de cambios y los change request que se vayan presentando se harán los correspondientes upgrades del mismo. En el objetivo se propone un pequeño proceso para el mismo teniendo en cuenta los datos de la sección "Control de versiones".

Quedo atento a sus comentarios.

Saludos.

[PropuestaServiciosREST.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/809672/PropuestaServiciosREST.docx)
