### ISSUE TITLE
1.1.36 Modificación módulo compra

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#480]
**Descripción**
Realizar modificación módulo compra.

**Tareas a realizar**
- [x] Listar tareas a realizar. @CamilaG08  
- [x] Revisar los cambios en el JSON de compras
- [x] Modificar el módulo de acuerdo a los 2 JSON que retorna cada servicio

**Comment by CamilaG08** [comment]
Se propondrá el día miércoles un cambio en el JSON del servicio de personajes.

[Compra.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/972431/Compra.zip)

**Son necesarias las URL de los servicios para correctas pruebas y merge del módulo en el proyecto**

**AÚN NO SE CIERRA LA TAREA**

**Comment by CamilaG08** [comment]
[Compra.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/978143/Compra.zip)

Se realiza la modificación del módulo, quedan pendientes las pruebas con el juego general.
**Tiempo empleado: 1 hora**
