### ISSUE TITLE
1.1.39 Servicios REST campo de batalla

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#483]
**Descripción**
Servicios REST campo de batalla. Tarea asignada para reposición de horas.

**Tareas a realizar**
- [ ] Realizar lista de tareas. @nicolas96 

- [ ] Se tiene que modificar la selección de personaje para saber la elección del usuario

**Comment by jrsosago** [comment]
No se evidencia trabajo en esta Issue

**Comment by nmartinezmarin** [comment]
esta tarea no se pudo realizar porque no había una url con los servicios montados

**Comment by CamilaG08** [comment]
La tarea se congela esperando que las url se encuentren la otra semana

**Comment by CamilaG08** [comment]
Se mueve al siguiente sprint.

**Comment by CamilaG08** [comment]
Debido al cambio de asignaciones por @DiegOliveros , se reasigna esta tarea en el Issue #600  y se cierra esta tarea.
