### ISSUE TITLE
Modificación tabla Log

### ISSUE THREAD

**Issue by EdnaEspejo** [ISWPOLI/Pacto-de-Honor#487]
Se requiere que la tabla Log contenga la información del Nivel al que accede cada usuario y el mundo al que pertenece.

- [x] Creación del script
- [x] Pruebas
- [x] Despliegue

**Comment by JuanCheroslan** [comment]
![image](https://cloud.githubusercontent.com/assets/25808683/25646305/c40e44b8-2f7c-11e7-8ff5-5c4ba20989a6.png)
![image](https://cloud.githubusercontent.com/assets/25808683/25646307/c7b61dd4-2f7c-11e7-9275-c39b873fa30b.png)
![image](https://cloud.githubusercontent.com/assets/25808683/25646308/ca1187c6-2f7c-11e7-9095-d5d7fd67a31b.png)

**Comment by JuanCheroslan** [comment]
issue completado martes 2 de mayo
