### ISSUE TITLE
Modelo Entidad Relacion

### ISSUE THREAD

**Issue by EdnaEspejo** [ISWPOLI/Pacto-de-Honor#49]

**Comment by EdnaEspejo** [comment]
`
[modelo entidad relación.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/791885/modelo.entidad.relacion.docx)
 
Adjunto los atributos definidos para la entidad JUGADOR
`

**Comment by juancelemin** [comment]
Atributos Personaje
[jugador.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/791981/jugador.pdf)

**Comment by jnrubiano** [comment]
Para la entidad "Nivel" se definieron los siguientes atributos:
- id
- nombre
- id_mundo
- id_personaje_rival

@Lakes1234  @juancelemin @Ser por favor compartir las entidades asignadas el sábado.

**Comment by JuanCheroslan** [comment]
Estimados,

adjunto el primer draft del modelo entidad relación, use la herramienta microsoft visio 2007, la idea es poder usar una herramienta que despues nos permita generar los scripts de creacion de las tablas y elementos de datos

Tiempo Estimado : 40 Mins

[DiagramaER_files.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/794067/DiagramaER_files.zip)

**Comment by jnrubiano** [comment]
Se crean los issues 55 Creación DB, 56 Población DB y 57 Diseño ER los cuales complementan y cierran este issue.

**Comment by zergiozerna81** [comment]
En conjunto con Nicolas se definieron las entidades Mundo y Nivel así:

Mundo
-NombreMundo
-ID_Mundo
-ID_Jefe

Nivel
-NombreNivel
-ID_Nivel
-ID_Personaje_Rival
-ID_Mundo

**Comment by zergiozerna81** [comment]
Link del issue donde se publicó nueva versión del modelo entidad relación.

https://github.com/ISWPOLI/Pacto-de-Honor/projects/1#card-1860342
