### ISSUE TITLE
1.1.40 Unificar rutas de las imágenes

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#494]
**Descripción**
Unificar rutas de las imágenes. 
**Tareas a realizar**
- [x] Modificar rutas de las imágenes de la Selección de Avatar.
- [x] Modificar rutas de las imágenes de la Selección de Personaje.
- [x] Modificar rutas de las imágenes de los Créditos.
- [x] Modificar rutas de las imágenes del Campo de Batalla.
- [x] Modificar rutas de las imágenes de Códigos Alfanuméricos.

**Comment by gabogabbs** [comment]
Se modifican las imágenes para cuadrar cada módulo y se arreglan las rutas de todas las imágenes de las siguientes secciones:
- Selección de Avatar.
- Selección de Personaje.
- Créditos.
- Campo de Batalla.
- Códigos Alfanuméricos.

Se da como concluido el issue.

REGISTRO DE TIEMPO: 2 horas.
