### ISSUE TITLE
5.11 Creación de manual de usuario

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#495]
**Descripción**

Creación del manual **previo** de usuario.

**TAREAS:**

- [x] Revisión del juego
- [x] Creación del documento (Título - Tabla de contenido - Contenido)
- [x] Desarrollo y creación del manual de usuario

**Comment by dayepesb** [comment]
[Manual de usuario Poli Figthers.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/979185/Manual.de.usuario.Poli.Figthers.docx)

Se deja el manual de usuario creado en un archivo word para posibles modificaciones.

**Comment by dayepesb** [comment]
[Manual de usuario Poli Figthers.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/979188/Manual.de.usuario.Poli.Figthers.pdf)

acá se deja el manual de usuario sin modificar en formato pdf

**Comment by CamilaG08** [comment]
Se cierra ya que se entrega el manual exitosamente

**Comment by DiegOliveros** [comment]
@dayepesb @CamilaG08 estos documentos deben estar en el repositorio. no en un comentario. Cuando realicen el commit no olviden asociar la issue, Saludos,
