### ISSUE TITLE
reporte personificacion #005

### ISSUE THREAD

**Issue by juancelemin** [ISWPOLI/Pacto-de-Honor#50]
Clasificar que personajes son los mas jugados para cada perfil

**Comment by DiegOliveros** [comment]
Favor corregir formato:
Ejemplo ::

**Iván Ruiseñor, Fabián Canario**
Yo como Jugador quisiera que mis personajes (Iván Ruiseñor, Fabián Canario) puedan volar de forma vertical y horizontal para poder manejar mejor mi personaje y hacer más dinámico el juego. 
**Tareas**
- [ ] Actividad 1 (1h)
- [ ] Actividad 2 (1h)
- [ ] Actividad 3 (1h)
- [ ] Actividad 4 (1h)
- [ ] Actividad 5 (1h)
- [ ] Actividad 6 (1h)

**Comment by juancelemin** [comment]
Yo como Jugador quisiera ver cuales son mis personajes mas jugados por medio de un grafico de pastel
**Tareas**

- [x] Identificar librerias en js que faciliten la generacion de graficos.(10min)

- [x] Aprender los conceptos basicos de la libreria (1h)

- [x] Diseñar el Grafico en pastel que con dinamismo.(1:30h)

**Comment by juancelemin** [comment]
[reporte-005.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/801719/reporte-005.txt)
