### ISSUE TITLE
6.2.19 Reporte SCRUM Master (Sábado 6 de Mayo)

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#515]
**Descripción**
Realizar reporte SCRUM Master, sábado 6 de mayo.

**Tareas a realizar**
- [x] Hacer reporte SCRUM Master

**Comment by ghost** [comment]
# Reporte 6 de Mayo

## Issue #515 - Reporte SCRUM MASTER Sabado 6 de Mayo) [Dario Muñoz]:
- Se revisaron y reportaron avances en las tareas de 8 integrantes del grupo de Frontend.
- Se subieron reportes a la Issue.

## Issue #447 - Documentación del codigo [Dario Muñoz]:
- Se explicó y documentó el archivo **verficiacionDeCodigo.js**.
- Se explicó y documentó el archivo **cookies.js**.
- Se explicó y documentó el archivo **desbloqueoPersonajes.js**.
- Se explicó y documentó el archivo **cajaMisteriosa.js**.

## Issue #421 - Estandarizacion de botones [Camilo D'achiardi]:
- Hacia falta el diseño de los sprites de algunos botones.
- Se realizó el diseño de los botones faltantes.
- Se corrigieron los diseños de los botones hechos.

## Issue #471 - Cookies [Gabriel Álvarez]:
- Se habla con Diego Oliveros y el dice que se implemente la estructura de los cookies.
- Esta tarea queda para el Sprint 13.

## Issue #469 - Integración Login y juego [Gabriel Álvarez, David Yepes y Julio Ernesto]:
- Se tuvo una reunión con David Yepes y con Julio Ernesto con el motivo de explicar el código realizado del login.
- Se montó un servidor de prueba local, sin embargo no se logro la integración.

## Issue #494 - Unificar rutas de las imagenes [Gabriel Álvarez]
- Se modificaron las imagenes de los personajes y de los botones ya que tenian diferentes tamaño.
- Se unificaron todas las rutas de las imagenes en una sola carpeta.

## Issue #477 - Barra de carga [Sebastian Rodriguez]:
- Se realizó un preloader circular con html y css.
- Se implementó al juego pero se genera un error debido a la sincronización del GitHub de escritorio.
- Se realizó una segunda implementación usando phaser y sprites para la implementación de barra de precarga dentro del juego.

## Issue #476 - Implementación de sonidos faltantes en el juego [Sebastian Rodriguez]:
- Se implementaron algunos sonidos faltantes funcionando correctamente.
- Hay un error con la sincronización de GitHub de escritorio.

## Issue #452 - Implementación de la caja sorpresa en el mapa [Juan Carlos y Juan Guillermo]:
- Se implementó la funcionalidad de todas las cajas sorpresa al ser presionadas.
- Se ajustaron detalles en las imagenes
- Aún falta borrar variables que no se esten utilizando

## Issue #481 - Acciones anteriores a guardar en la base de datos [Jeimy Sosa]:
- Se realizó un documento en el cual se especifica las acciones anteriores a guardar en la base de datos para el correcto funcionamiento de las pruebas psicotécnicas.

## Issue #482 - Realizar descripción de Servicios de pruebas Psicotecnicas y su JSON [Jeimy Sosa]:
- Se habla con Juan Camilo y surgen nuevas modificaciones.
- Se realizan estas modificaciones en la tabla de excel que explica los servicios.

## Issue #480 - Modificación módulo compra [Camila Gutiérrez]:
- Se realizó la prueba general pero el día 6 de mayo se realizaron cambios después de hablar con Juan Camilo.
- Queda pendiente volver a realizar la pruebas.
