### ISSUE TITLE
6.2.20 Reporte SCRUM Master (Sábado 6 de Mayo)

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#516]
**Descripción**
Realizar reporte SCRUM Master, sábado 6 de mayo.

**Tareas a realizar**
- [x] Hacer reporte SCRUM Master

**Comment by ivandav** [comment]
# Reportes 06 de mayo del 2017
 Se revisan los trabajos que los integrantes del grupo debieron realizar durante la semana. 
 
## Toma de asistencia [Jaime Bernal]:
   - Se realiza la toma de asistencia como es común y se actualiza el excel.
   

## Issue #461 Revisar entregas Sprint 11 [Jaime Bernal]:
   - Se revisan las entregas del sprint 11.
   - Se realiza un documento con las siguientes características: Usuario, ortografía, orden, completud, validez y retiro de marcas.
   - Se entrega el documento directamente al profesor.  


## Issue #449 Reportes Scrum Master miércoles 03 de mayo [Ivan Barrantes]:
   - Se consolidan y se suben a github los reportes de trabajo.


## Issue #452 Imágenes de diálogos e imágenes que están por separado [Ivan Barrantes]:
   - Se termina con la tarea que se venia realizando con las imágenes que tenían dialogo pero que estaban unidos.
   - Se borran los textos usando photoshop para no dañar la imagen.
   - Se crean las funciones mediante vectores para que cada imagen y texto quede como son.
 
## Issue #495 Creación de manual de usuario [David Yepes]:
   - Se Se revisan las características del juego.
   - Se crea un documento detallando las funciones de cada componente del juego.
   - Se verifica que el documento este bien y se sube a la rama master.

## Issue #469 Integración login y juego [David Yepes]:
   - Se tiene una reunión con ernesto y gabriel para revisar y entender el código.
   - Se monto un servidor local de prueba para comprobar el funcionamiento del login.
   - Se tienen problemas con la integración.

## Issue #473 Algoritmo de desbloqueo de personajes por mundo [Cristian Garzon]:
   - Se hizo un JSON el cual representa el estado del personaje es decir si esta desbloqueado o no.
   - Se modifica el algoritmo de desbloqueo pues el JSON que se tenia esta mal definido.

## Issue #464 Implementacion de escudos [Nicolas Martinez]:
   - Se implementan las funcionalidades de los escudos, para diferentes tipos de ataque.

## Issue #466 Encapsulamiento de variables campo de batalla [Nicolas Martinez]:
   - Se investigo sobre encapsulamiento de las variables y las librerías de phaser.
   - Se sube al repositorio una especificación de como se debe hacer el encapsulamiento mediante un objeto que se concluye se debe hacer después de realizar la investigación.

## Issue #483 Servicios REST campo de batalla [Nicolas Martinez]:
   - La tarea se encuentra congelada debido a trabajos en el servidor local. 
 
## Issue #469 Integración login y juego [Ernesto Rodriguez]:
   - Se realiza el token qe se mando hacer.
   - Se trabaja en la case UUID identificador único universal.

## Issue #475 Integración login con otros esquemas de login [Ernesto Rodriguez]:
   - Se realiza la clase conexion donde proporciona datos de los sockets y los flujos de mensaje.
   - Se realiza la clase servidor que maneja el puerto 8080 con el método accept y se cierra la conexión.
   - Se tiene el trabajo de la clase cliente que hereda de la clase conexión para utilizar los sockets, hace la confirmación de la recepción de los mensaje y hace la correcta publicación por consola de los mensajes.
