### ISSUE TITLE
Conexión HTLM5 - PHP - MySQL

### ISSUE THREAD

**Issue by DanteVDrako** [ISWPOLI/Pacto-de-Honor#52]

**Comment by DanteVDrako** [comment]
- [x] - Creación de diseño HTML5 para informes.

- [x] - Definición de BD de prueba MySQL.

- [x] - Publicación WEB.

- [ ] -Conexión HTML5 por PHP a MySQL.

 - [ ] - Creación de gráficas de información mediante frameworks CSS.

**Comment by DanteVDrako** [comment]
Creación de diseño HTML5 para informes.

Se ha creado plantilla para informes.

![image](https://cloud.githubusercontent.com/assets/25806785/23370231/1330fca2-fce2-11e6-8a7a-5aca24e37cb8.png)
![image](https://cloud.githubusercontent.com/assets/25806785/23370250/21f874e0-fce2-11e6-9b21-12a459f557b4.png)

**Comment by DanteVDrako** [comment]
Publicación WEB

Se ha creado el archivo para publicación WEB

[https://drive.google.com/open?id=0B3XVOrHn5OqYWVl4Ti1Nc3ZEN2c](url)

**Comment by DanteVDrako** [comment]
Conexión HTML5 por PHP a MySQL

Se ha creado el Script de conexión para la base de datos (faltando la información de la base de datos)

![image](https://cloud.githubusercontent.com/assets/25806785/23370972/7401c38e-fce4-11e6-9880-dbb970a438f3.png)

**Comment by DanteVDrako** [comment]
Creación pagina principal  plantilla de reportes en HTML5.

![captura de pantalla 2017-03-01 a las 8 05 23 p m](https://cloud.githubusercontent.com/assets/25806785/23488419/7f2a47e0-feba-11e6-9fea-10587c034d7d.png)

``

**Comment by DanteVDrako** [comment]
Definición de consultas SQL para mostrar en los reportes. 

![captura de pantalla 2017-03-01 a las 9 49 22 p m](https://cloud.githubusercontent.com/assets/25806785/23490877/051c548e-fec9-11e6-983c-26c7eab70807.png)

**Comment by DanteVDrako** [comment]
Formulario de prueba para llenar un SQL con datos básicos (probar conexión)

[href="Reportes.html" title="Reportes"<!DOCTYPE html>
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<title>Formulario</title>
	<link href="../ProyectoAPP/css/bootstrap.css" rel="stylesheet" />
	<link href="../ProyectoAPP/css/bootstrap.min.css" rel="stylesheet" />
	<link href="../ProyectoAPP/css/Site.css" rel="stylesheet" />
</head>	
<?
$conexion = mysql_connect("localhost", "(usuario)", "(password)");
mysql_select_db("(p_h01)", $conexion);
?>	

<?
    if(isset($_POST['nombre'])){
      $insertar = "INSERT INTO usuarios (nombre, nick) 
          VALUES ('".$_POST['nombre']."', '".$_POST['nick']."')";
      mysql_query($insertar,$conexion); 
     }
?>

<?
 $sql = "SELECT nombre,nick FROM usuarios";
 $retval = mysql_query( $sql, $conexion);
 while($row =  mysql_fetch_assoc($retval)){
    echo "Nombre: ".$row['nombre'].", Nick: ".$row['nick']."<br>";
} 
?>

<body>
<div class="navbar navbar-inverse navbar-fixed-top" style="background:black;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="andres.html" class="navbar-brand">Poli Fighters</a>
                
               </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li ><a href="../ProyectoAPP/Reportes.html" class="">Reportes</a></li>
                    <li ><a href="../ProyectoAPP/Formulario.html" class="">Formulario</a></li>
                </ul>
                
            </div>
        </div>
    </div>
    
<div class=container>    	
<h2 class="titles">Formulario</h2>

<label>Formulario para insertar datos en BD </label>
<form id="form1" name="form1" method="post" action="index.php">
  <table width="200" border="0">
  <tr>
    <td width="61">Nombre:</td>
    <td width="123">
      <label for="nombre"></label>
      <input type="text" name="nombre" id="nombre" />
    </td>
  </tr>
  <tr>
    <td>Usuario:</td>
    <td><label for="usuario"></label>
    <input type="text" name="usuario" id="usuario" /></td>
  </tr>
  <tr>
    <td>Pa&iacutes:</td>
    <td><label for="pais"></label>
    <input type="text" name="pais" id="pais" /></td>
  </tr>
  <tr>
    <td>Avatar:</td>
    <td><label for="avatar"></label>
    <select class="form-control">
            <option></option>
            <option>Juan La Rata</option>
            <option>Andres El Gallo</option>
            <option>Ana La Abeja</option>
    </select>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td align="right">
    <input type="submit" name="enviar" id="enviar" value="Enviar" />
    </td>
  </tr>
</table>
</form>


</div>
</div>
	<div class="col-lg-12" style="margin-top:3%;">
     	<p>Pr&aacutectica Aplicada, Polit&eacutecnico Grancolombiano</p>
	</div>
</body>
</html>](url)

**Comment by manuk160** [comment]
fue validad la base de datos y la funcionalidad del servidor web.
