### ISSUE TITLE
1.6.7 Modificación del módulo de logros

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#521]
**Descripción**

Modificación del módulo de logros según los JSON generados por los servicios

**TAREAS:**

- [x] Crear el JSON de logros **lunes 08 de mayo**
- [x] Ajustar el funcionamiento del módulo de logros a dicho archivo
- [x] Realizar pruebas locales de consumo del servicio

**Comment by juancelemin** [comment]
![imagen](https://cloud.githubusercontent.com/assets/17105514/25786118/e25889e8-3354-11e7-8e66-ce1f905ba7ab.png)

**Comment by CamilaG08** [comment]
Hola @juancelemin es necesario el envío de este archivo a mi correo ( cagutierrez2@poligran.edu.co ) para poder incluirlo en los servicios, al igual que el JSON de las cajas sorpresa junto a la descripción de cada campo de dichos archivos.
