### ISSUE TITLE
1.6.8 Modificación perfil del jugador

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#522]
**Descripción**

Modificación del módulo de perfil del jugador según los JSON generados por los servicios

**TAREAS:**

- [x] Revisar el JSON de perfil del jugador
- [x] Ajustar el funcionamiento del módulo de perfil de jugador a dicho archivo
- [x] Realizar pruebas locales de consumo del servicio

**JSON perfil:**
[perfil.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/980665/perfil.zip)

**Comment by juankrlos08** [comment]
![image](https://cloud.githubusercontent.com/assets/25808382/25959356/f9a55270-3638-11e7-98dc-f3ed9458aff2.png)
![image](https://cloud.githubusercontent.com/assets/25808382/25959364/049dbb2c-3639-11e7-8dba-0cc37b149298.png)

**Comment by juankrlos08** [comment]
Se ajusta el funcionamiento del módulo de perfil de jugador a dicho archivo

**Comment by CamilaG08** [comment]
No se asigna nuevo Issue hasta finalizar este
