### ISSUE TITLE
5.12 Diseño del tutorial

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#524]
### Descripción

Diseñar el tutorial del juego.

### Tareas:

- [x] Diseñar el tutorial del juego para el usuario
- [x] Pedir revisión del diseño antes de realizarlo
- [x] Realizar el tutorial
- [x] Mostrarlo en la reunión de cierre del Sprint 13

**Comment by KmiArthur** [comment]
### Video tutorial del juego 
`Tiempo trabajo: 7h`

[VIdeo Aquí](https://www.youtube.com/watch?v=oSBAOBYH1Is)

**Comment by CamilaG08** [comment]
Se cierra el Issue dado que se entrega el tutorial satisfactoriamente.

**Comment by KmiArthur** [comment]
```
Preferencias del video han sido cambiadas a privado por petición de @CamilaG08.
Video visible solo con el link.
```
