### ISSUE TITLE
1.15 Cargar el portal

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#525]
### Descripción

Cargar el portal en un hosting gratuito.

### Tareas:

- [x] Encontrar un hosting gratuito
- [ ] Cargar el portal dicho hosting
- [x] Documentar

**Comment by KmiArthur** [comment]
Base de datos del portal

[wpPactoHonor06052017.sql.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/981027/wpPactoHonor06052017.sql.zip)

**Comment by DiegOliveros** [comment]
@KmiArthur  debes subir este archivo al repositorio a través de commit y asociar la historia usando #525 en el comentario.

**Comment by CamilaG08** [comment]
Debido al cumplimiento de las tareas, se cierra el Issue.
