### ISSUE TITLE
5.4.9 Creación librería del código

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#526]
**Descripción**
Creación de librería del código.

**Tareas a realizar**
- [x] Crear librería del juego con html y css.
- [x] Agregar contenido a la sección de **verificacionDeCodigo.html**.
- [x] Agregar contenido a la sección de **codigoUsado.html**.
- [x] Agregar contenido a la sección de **desbloqueoPersonaje.html**.
- [x] Agregar contenido a la sección de **cajaMisteriosa.html**.
- [x] Agregar contenido a la sección de **batalla.html**.

**Comment by ghost** [comment]
# Tarea subida al repositorio REGISTRO DE TIEMPO: 7 horas y 36 minutos
