### ISSUE TITLE
1.1.42 Modificar módulo códigos alfanuméricos

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#527]
**Descripción**
Modificar módulo códigos alfanuméricos.

**Tareas a realizar**
- [x] Modificar módulo códigos alfanuméricos para consumir los servicios.
- [ ] Realizar pruebas de los servicios en el módulo.
- [x] Tabla de servicios.
- [x] Crear Json de codigos alfanumericos.
- [x] Modificar selección de código alfanumerico e incluir a Juan Rata.
- [x] Lista de codigos de pruebas.

**Comment by CristianGarzonBernal** [comment]
[JsonCodigosAlfa.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/990416/JsonCodigosAlfa.txt)

**Comment by CristianGarzonBernal** [comment]
[JsonCodigosAlfa.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/990939/JsonCodigosAlfa.txt)

**Comment by DiegOliveros** [comment]
@CristianGarzonBernal  @jnrubiano La información de los Json debe estar en la matriz de servicios (Excel).

**Comment by CristianGarzonBernal** [comment]
Por solicitud de @CamilaG08 se modifica el Json de logros, ya que estaba mal estructurado. (Los Json hechos en este issue ya fueron agregados a la matriz de servicios).
[Json Logros.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/991730/Json.Logros.txt)

**Comment by jrsosago** [comment]
Se reasigna está Issue para el Sprint 14, ya que las dos tareas faltantes son referentes a servicios.

**Comment by CristianGarzonBernal** [comment]
@JuanCheroslan 
[CodigosDePrueba.xlsx](https://github.com/ISWPOLI/Pacto-de-Honor/files/998785/CodigosDePrueba.xlsx)

**Comment by jrsosago** [comment]
Se cambia de Sprint debido a que no se ha recibido el servicio por parte de Back-end

**Comment by CristianGarzonBernal** [comment]
-Faltan las pruebas de servicios en códigos alfanuméricos, en donde se implemento el Ajax y esta en la rama de la master.

-No se hicieron las pruebas debido a que no había servidor desplegado y en la url del Ajax es necesario poner la dirección del servidor.
