### ISSUE TITLE
1.16 Cifrado del código

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#528]
- [x] Listar tareas @dayepesb 
- [x] buscar la manera de cifrar u ocultar el codigo HTML y JavaScript para evitar copias del codigo.

**Comment by dayepesb** [comment]
[Cifrado Código Fuente.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/988648/Cifrado.Codigo.Fuente.docx)

se adjunta un archivo con todos los comentarios que se hicieron respecto a  este issue

**Comment by CamilaG08** [comment]
Se cierra debido a que el cifrado debe realizarse a la versión de despliegue así que se esperará al primer despliegue.

**Comment by jrsosago** [comment]
Revisando los comentarios realizados por @dayepesb se toma la decisión de cifrar el código cuando se realice el primer despliegue, mientras tanto se bloqueara la opción de inspeccionar el código. Está tarea se volverá a crear cuando se realice el despliegue.
