### ISSUE TITLE
Validación Controles Phaser

### ISSUE THREAD

**Issue by DanteVDrako** [ISWPOLI/Pacto-de-Honor#53]
Con el objetivo de validar los controles en dispositivos móviles se realizara pruebas de funcionalidades e implementación de controles con phaser.

**Comment by DanteVDrako** [comment]
- [x] Elección de Framework de botonera para móvil.

- [x] Implementación del Framework en el entorno de pruebas.

- [x] Prueba de funcionalidad en las plataformas móviles.

**Comment by DanteVDrako** [comment]
Elección de Framework de botonera para móvil.

Se elige el Framework Generic Joystick Plugin para la implementación de la botonera en los dispositivos móviles, se descarga el Framework directamente de la WEB de Phaser.io.

[http://phaser.io/examples/v2/virtualjoystick/generic-joystick](url) 

![captura de pantalla 2017-02-22 a las 8 05 04 p m](https://cloud.githubusercontent.com/assets/25806785/23240226/40d7d3ac-f93a-11e6-86f5-d0ad94c8a245.png)

**Comment by DanteVDrako** [comment]
Implementación del Framework en el entorno de pruebas.

Se está probando el siguiente código en la implementación de prueba de juego:

`var PhaserGame = function () {
    this.pad;
    this.stick;
    this.buttonA;
    this.buttonB;
    this.buttonC;
};

PhaserGame.prototype = {
    preload: function () {
        this.load.atlas('generic', 'assets/virtualjoystick/skins/generic-joystick.png', 'assets/virtualjoystick/skins/generic-joystick.json');
        this.load.image('ship', 'assets/virtualjoystick/thrust.png');
        this.load.image('bg', 'assets/virtualjoystick/starfield2.jpg');
    },
create: function () {
        this.pad = this.game.plugins.add(Phaser.VirtualJoystick);
        this.stick = this.pad.addStick(0, 0, 200, 'generic');
        this.stick.alignBottomLeft(20);
        this.buttonA = this.pad.addButton(500, 520, 'generic', 'button1-up', 'button1-down');
        this.buttonA.onDown.add(this.pressButtonA, this);
        this.buttonB = this.pad.addButton(615, 450, 'generic', 'button2-up', 'button2-down');
        this.buttonB.onDown.add(this.pressButtonB, this);
        this.buttonC = this.pad.addButton(730, 520, 'generic', 'button3-up', 'button3-down');
        this.buttonC.onDown.add(this.pressButtonC, this);
    },
}`

**Comment by DanteVDrako** [comment]
Implementación del Framework en el entorno de pruebas.

Al probar el Framework se encuentra que se necesita el Plugin Virtual Joystick:

![pruebas_joystick](https://cloud.githubusercontent.com/assets/25806785/23242127/2e096c4e-f945-11e6-8391-918a298ad1e9.PNG)

Dicho Plugin debe ser comprado:

![compra_joystick](https://cloud.githubusercontent.com/assets/25806785/23242144/46c49574-f945-11e6-82a7-bc586aaf99aa.PNG)

**Comment by manuk160** [comment]
De acuerdo a la validación en cuanto a la librería y el costo de 20 dolares se procedió a validar la funcionalidad sin costo y mediante este proceso de validación se logro implementar una libreria que permite el manejo de controles táctiles para móviles en interfaz web.

![image](https://cloud.githubusercontent.com/assets/25807878/23730872/105e8096-0438-11e7-917a-8e7142ab4b63.png)
