### ISSUE TITLE
Integración de Módulos

### ISSUE THREAD

**Issue by EdnaEspejo** [ISWPOLI/Pacto-de-Honor#531]
Se busca lograr la captura de información de la base de datos en los siguientes módulos y consumir la información: 

- [x] Administración
- [x] Categoría
- [x] Frase

**Comment by rzambrano112** [comment]
![image](https://cloud.githubusercontent.com/assets/20976993/25773621/160c285e-3246-11e7-91b5-f0634eb3b677.png)

**Comment by rzambrano112** [comment]
Se da cumplimiento al issue #531
