### ISSUE TITLE
1.1.44 Botones de sonido

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#532]
**Descripción**
Realizar implementaciones de botones de sonido en todo el juego. Tarea para reponer horas

**Tareas a realizar**
- [x] Implementación de opción en el menú de pausa en el módulo de batalla.
- [x] Implementación de botón en el resto del juego. Pedir botón a @KmiArthur

**Comment by gabogabbs** [comment]
Se implementa el botón de sonido en el mapa de navegación y en el menú de pausa del campo de batalla.

**Comment by gabogabbs** [comment]
Se corrigen todos los sonidos y músicas del juego.
Se implementan los botones correspondientes.
Se optimizan los preloads de todos los estados debido a código duplicado.

Se da como concluido este issue.

REGISTRO DE TIEMPO: 3horas y 30 minutos.
