### ISSUE TITLE
1.1.45 Implementación pruebas Psicotécnicas

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#534]
**Descripción**
Continuar Implementación pruebas Psicotécnicas.

**Tareas a realizar**
- [x] Reunión con @jrsosago para explicación de la implementación.
Realizar implementación de las pruebas Psicotécnicas basado en las issues #492 #378, #351
- [x] Reunirse con @JuanSebastianRodriguezJ  para recibir explicación del juego. @dayepesb.
- [x] Realizar implementación de las primeras 11 preguntas-acciones. @JuanSebastianRodriguezJ 
- [ ] Realizar implementación de las últimas 11 preguntas-acciones. @dayepesb

**Comment by ghost** [comment]
Se realizo reunión con @jrsosago el dia martes 9 de mayo de 2017, de 2 horas de duración. Donde se me explica como es el funcionamiento de las pruebas psicotecnicas en el juego. 

**Duración: 2 horas.**

**Comment by jrsosago** [comment]
Debido a algunos cambios realizados en la implementación del juego, ya no se realizaran las dos últimas tareas de está Issue, sino que se crearán nuevas tareas en base a una reunión que yo tenga con @dayepesb y @JuanSebastianRodriguezJ también se aplaza está Issue para el Sprint 14.

**Comment by ghost** [comment]
Hubo una reunión con @dayepesb con el motivo de iniciar con la implementacion, en el proceso surgió que algunas acciones del juego planteadas inicialmente se descartaron durante el proceso de desarrollo y otras aun no se han terminado de realizar.  Aun falta pedir Json de las pruebas psicotecnias.
Duración de la reunión: 3 horas.

**Comment by jrsosago** [comment]
Se realiza reunión con @JuanSebastianRodriguezJ para comentarle los avances que se pueden ir realizando mientras se termina el cuadro de referencia que está en un 60%.

**Tareas a realizar**
- [x] Nueva reunión con @jrsosago.
- [x] Empezar a probar los JSON de los servicios. @JuanSebastianRodriguezJ

**Comment by jrsosago** [comment]
Está tarea se debe ir realizando está semana por @JuanSebastianRodriguezJ  mientras que @dayepesb termina su participación en el Login.

**Comment by ghost** [comment]
Debido a que hubo un cambio en el documento base de implementacion de las pruebas psicotecnias, hay que realizar nuevos cambios en dicha implementacion. 

**Tiempo gastado**: 2 horas 45 min.

**Comment by jrsosago** [comment]
Se cambia de Sprint, debido a que las dos personas involucradas en está Issue tenían otras tareas para realizar.

**Comment by CamilaG08** [comment]
Se cierra el Issue debido a que se completaron la mayoría de tareas (algunas quedan pendientes).
