### ISSUE TITLE
5.7.4 Preparar reunión con vicerrector

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#535]
**Descripción**
Preparar reunión con vicerrector.

**Tareas a realizar**
- [x] Reunirnos con @DiegOliveros  @jolarter para definir parámetros de la reunión.
- [ ] Realizar preparación de material a mostrar.
- [ ] Mostrar material a los profesores.

**Comment by CamilaG08** [comment]
Se cambia al Sprint 16 dado que después de hablar con @DiegOliveros y @jolarter se aplaza la reunión hasta el final del semestre.

**Comment by CamilaG08** [comment]
Se cierra la tarea dado que la reunión la realizarán los docentes @DiegOliveros  y @jolarter .
