### ISSUE TITLE
6.5 Revisión del juego

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#538]
**Descripción**

Revisión detallada del juego para mejorar la planeación y la entrega final.

**TAREAS:**

- [x] Revisión del juego el día martes
- [x] Revisión de reportes del martes
- [x] Seguimiento de las tareas Sprint 13
- [x] Revisión del juego día jueves

**Comment by CamilaG08** [comment]
Se toman en cuenta los comentarios dados por medio de un correo de Manuel para realizar modificaciones el día miércoles.

**Comment by CamilaG08** [comment]
Se revisan los reportes del día martes para poder realizar seguimiento a los avances y tareas.

**Comment by CamilaG08** [comment]
En la clase del día miércoles, junto a @jrsosago y luego con @jdma0440  se realiza una revisión de las tareas y avances del grupo de frontend.

**Comment by jrsosago** [comment]
Hoy 11 de Mayo se realiza revisión de avances y tareas a realizar para los siguientes Sprints con @CamilaG08, de los avances se encuentra lo siguiente:
- Se realiza vídeo tutorial del juego. 
- Se mejora la funcionalidad de los escudos.
- Adelanto librería del código.
- Se evidencia el personaje que se selecciona
