### ISSUE TITLE
5.13 Definición de servicios

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#541]
**Descripción**

Definición de los JSON de los servicios a través de un archivo excel y las estructuras JSON.

**TAREAS:**

- [x] Crear archivo excel base y compartirlo  con **Camila**
- [x] Definir/Modificar las estructuras
- [x] Documento consolidado de los datos de los servicios

**Comment by jnrubiano** [comment]
Hola @CamilaG08 : 

Por fa regalame tu correo para compartir la tabla, tambien te recomiendo los correos de todos.

Saludos.

**Comment by CamilaG08** [comment]
Hola @jnrubiano , mi correo es camila081014@gmail.com

En el menor tiempo posible te enviaré los demás correos.

**Comment by JuanCheroslan** [comment]
Hola @CamilaG08  estuve revisando el template y considero que podemos agregar o modificar estas dos columnas

- Datos de entrada: por ejemplo el token siempre ira como parametro de entrada
- Descripcion Campos: podemos hacer una segmentacion para saber cuales campos son de entrada y cuales son de salida?

@jnrubiano @jrsosago  que opinan de esto?

saludos Cordiales

**Comment by jnrubiano** [comment]
hola @JuanCheroslan 

Considero que los datos de entrada, como son parte de lo que debe considerar el desarrollador, deben estar en la documentación del servicio y no en el requerimiento.
La descripción de los atributos del JSON que espera el equipo de FE, debe estar en la columna "Descripción campos".

@CamilaG08 ya te compartí el excel, quedo pendiente de los correos para que tu equipo te empiece a dar requerimientos con base a la tabla.

Quedo atento a sus comentarios.

Saludos.

**Comment by JuanCheroslan** [comment]
@jnrubiano listo, sin embargo agreguemole la columna de si es una insercion o una consulta, solo para poder segmentar el volumen y la complejidad

**Comment by JuanCheroslan** [comment]
se realizo reunion informal con @CamilaG08  para poder  definir cuando se van a tener la definicion de los servicios, lo ideal es que mañana antes de clase esten para poder completarlos para el sabado

tiempo de la reunion 20 minutos

**Comment by CamilaG08** [comment]
Hola @jnrubiano acabé de compartir un avance de la tabla de excel, quedo pendiente de realizar modificaciones para así poder compartirla con los demás.

**Comment by nmartinezmarin** [comment]
Hola @CamilaG08 te adjunto un archivo con avances de los servicios necesarios para que lo adjuntes con la tabla en excel 
[Servicios del Juego.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/990570/Servicios.del.Juego.docx)

Quedo pendiente de cualquier comentario 

Saludos

**Comment by CamilaG08** [comment]
Queda el archivo consolidado en la siguiente dirección:  https://docs.google.com/spreadsheets/d/1gRiT-2HuagWqwhNWD6fmOzC24Cyh3JTk0gdFgl_rhQ0/edit?usp=sharing   por lo tanto se cierra el Issue
