### ISSUE TITLE
7.2.2 Contenido Red Social

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#544]
**Descripción**

Creación del contenido de la red social creada previamente.

**TAREAS:**

- [x] Recolección de la información para el contenido
- [x] Creación del contenido de la red social
- [x] Agregar a los integrantes del equipo

**Comment by ghost** [comment]
Se hace la recolección de la información de contenido para la red social Facebook, desde  las distintas fuentes como:  la pagina principal de la universidad, pagina poli pacto de honor,  portal de contenidos de juego,  http://www.poli.edu.co/,  http://pactodehonor.co.nf/equipo.html, y http://www.poli.edu.co/honorgrancolombiano que sera publicada.

tiempo empleado 30 min

**Comment by DiegOliveros** [comment]
@Basespoli favor incluir información del manual de usuario, gestión del proyecto, contexto (facultad, programa, linea, asignatura)tráiler del juego.

**Comment by ghost** [comment]
Según la recomendación del docente se realiza la publicacion de informacion expectativa para el juego **Polifighters**  se aceptan todos los aportes y recomendaciones teniendo en cuenta que esta red social Facebook se diseño con el fin de realizar la integración de la autenticación con esta red social pero es libre para todo el equipo del proyecto.

![image](https://cloud.githubusercontent.com/assets/25758763/25874797/e1d7e67c-34d9-11e7-9b55-39677e3f9b5b.png)

Tiempo empleado 1 hora.

**Comment by ghost** [comment]
Se continua trabajando se ha realizado la invitación  a algunos integrantes del grupo y se ha hecho la publicación de algunos contenidos con el asesoramiento de Trompo estos indican que es mejor orientar la red social primero a generar una expectativa del juego y para captar personas y posterior para el contenido   de los integrantes del equipo y su desarrollo.

**Comment by ghost** [comment]
Se continua con el trabajo de publicación de expectativa en la red social, muchos de los participantes se están animando a participar y me han solicitado la clave para participar activamente y no solo como espectador, esta tarea se va conformando por todos como producto final.

Tiempo empleado 40 min

Algunas de las publicaciones y datos de Analitics.

Se actualiza logos y encabezados, se pasó propuesta de que todos los diseños que participaron antes de elegir el actual se puedan ir publicando en un tiempo parcial.

![image](https://cloud.githubusercontent.com/assets/25758763/26006299/83d5bcfa-3701-11e7-8627-92a4f1e62883.png)


![image](https://cloud.githubusercontent.com/assets/25758763/26006597/a1a49106-3702-11e7-95d4-819a158e8d69.png)

![image](https://cloud.githubusercontent.com/assets/25758763/26006635/cd3bbb6e-3702-11e7-8221-21d961f78d32.png)
