### ISSUE TITLE
1.1.47 Conectar botones de los niveles de  cada mundo con el mapa de navegación

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#545]
**Descripción**
Conectar botones de los niveles de cada mundo con el mapa de navegación.

**Tareas a realizar**
- [x] Conectar botones de cada mundo con la batalla.
- [x] Completar JSON de personajes.
- [x] Modificar tamaño imágenes poderes de mini personajes.
- [x] Asignar el personaje malo a cada nivel según el documento en el repositorio.

**Comment by gabogabbs** [comment]
Se realizan las siguientes tareas:
- Conectar botones de cada mundo con la batalla.
- Completar JSON de personajes.
- Modificar tamaño imágenes poderes de mini personajes.
- Asignar el personaje malo a cada nivel según el documento en el repositorio.

Faltan imágenes de avatares de mini personajes. 
Se da como concluido este issue.

REGISTRO DE TIEMPO: 6 horas y 50 minutos.
