### ISSUE TITLE
Integración Modulo Reportes

### ISSUE THREAD

**Issue by alexsabsan** [ISWPOLI/Pacto-de-Honor#547]
Generación integración de los Submodulos de reportes    

- [x] Mundos

- [x] Usuarios

**Comment by rzambrano112** [comment]
![image](https://cloud.githubusercontent.com/assets/20976993/26134846/2ad5b7c6-3a77-11e7-8378-f0f8a74c8597.png)
Se anexan aportes frente a la sincronización #547

**Comment by rzambrano112** [comment]
![image](https://cloud.githubusercontent.com/assets/20976993/26183574/376e1f7c-3b45-11e7-8ece-21a1181f05fe.png)
Se realiza la captura de la base de datos del sumodulo Mundo del modAdministración #547

**Comment by rzambrano112** [comment]
![image](https://cloud.githubusercontent.com/assets/20976993/26183613/83dcbb8e-3b45-11e7-944c-72ab27e1fcff.png)
Evidencia de la captura de la base de datos del submódulo del  modAdministración #547

**Comment by rzambrano112** [comment]
Se realiza funcionalidad al modulo usuarios en la captura de datos #547

**Comment by rzambrano112** [comment]
Se da cierre al mismo.
