### ISSUE TITLE
Creación DB

### ISSUE THREAD

**Issue by jnrubiano** [ISWPOLI/Pacto-de-Honor#55]
Montar la base de datos en MySQL de acuerdo al modelo ER acordado en las sesiones del sábado 18 de Febrero y 22 de Febrero.
@juancelemin @EdnaEspejo @wpradere

**Comment by jnrubiano** [comment]
Montaje de la base de datos en MySQL

[PactoDeHonor.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/795304/PactoDeHonor.txt)

**Comment by jnrubiano** [comment]
Se crea el branch correspondiente a la DB y se sube el script de la primera versión.

**Comment by zergiozerna81** [comment]
Revisar nuevo issue donde se va a subir script:

https://github.com/ISWPOLI/Pacto-de-Honor/projects/1#card-1860342
