### ISSUE TITLE
Preguntas Acciones del juego base de datos

### ISSUE THREAD

**Issue by JuanCheroslan** [ISWPOLI/Pacto-de-Honor#550]
Hola @jrsosago , vi tu documento y tengo varias dudas con respecto.

- lo que pretendes guardar es el evento como tal que esta ejecutando el jugador, dentro del juego el usuario podria ejecutar la misma accion varias veces no entiendo como se debe controlar que el usuario solo haga esto una vez

- el objetivo es poder responder las pruebas psicotecnicas (que ya estan en la base), no seria mejor que dentro del manejo del codigo cuando se de un evento se inserte la respuesta y asi no tener que guardar cada evento en el log, ten en cuenta que esta orientada a 30.000 usuarios y son al rededor de 20 eventos eso nos daria un total de 600.000 registros si estos se hicieran  una unica vez.

podriamos ver esto el miercoles o que nos citemos a una llamada antes

**Comment by jrsosago** [comment]
@JuanCheroslan yo estoy disponible mañana de 5 a 6:30 o en el horario de clases. Si tú puedes antes de clase me confirmas. Gracias

**Comment by JuanCheroslan** [comment]
hola @jrsosago  trato de llegar temprano para poder revisar las duas
gracias

**Comment by jrsosago** [comment]
Se realiza reunión con @JuanCheroslan, se aclaran dudas. Por lo tanto se da por terminada está Issue.
