### ISSUE TITLE
1.1.48 Imágenes de diálogos e imágenes que están por separado.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#552]
**Descripción**
Imágenes de diálogos e imágenes que están por separado del mundo 7 al mundo 12.

**Tareas a realizar**
- [x] Imágenes de diálogos e imágenes que están por separado del mundo 7.
- [x] Imágenes de diálogos e imágenes que están por separado del mundo 8.
- [x] Imágenes de diálogos e imágenes que están por separado del mundo 9.
- [x] Imágenes de diálogos e imágenes que están por separado del mundo 10.
- [x] Imágenes de diálogos e imágenes que están por separado del mundo 11.
- [x] Imágenes de diálogos e imágenes que están por separado del mundo 12.

**Comment by ivandav** [comment]
# Archivo js e imagenes modificadas
[dialogosPersonajesMalos2.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/995007/dialogosPersonajesMalos2.txt)

![dialogobabuino](https://cloud.githubusercontent.com/assets/22629584/25981763/bc4805ee-369c-11e7-86ea-c610d299db8f.png)
![dialogobabuino2](https://cloud.githubusercontent.com/assets/22629584/25981764/bc486afc-369c-11e7-8cec-ace709ea13bb.png)
![dialogobabuino3](https://cloud.githubusercontent.com/assets/22629584/25981767/bc4c0d38-369c-11e7-8cef-e772996a18db.png)
![dialogobuitre](https://cloud.githubusercontent.com/assets/22629584/25981762/bc475f86-369c-11e7-8176-482c0d314f22.png)
![dialogobuitre2](https://cloud.githubusercontent.com/assets/22629584/25981765/bc48a6c0-369c-11e7-99a4-3c11f102af62.png)
![dialogobuitre3](https://cloud.githubusercontent.com/assets/22629584/25981766/bc4c14fe-369c-11e7-9efa-67bbb9ed0da4.png)
![dialogohiena](https://cloud.githubusercontent.com/assets/22629584/25981768/bc614158-369c-11e7-8252-1ed10c1d8053.png)
![dialogohiena2](https://cloud.githubusercontent.com/assets/22629584/25981769/bc65fde2-369c-11e7-9612-a6f4068c4542.png)
![dialogohiena3](https://cloud.githubusercontent.com/assets/22629584/25981770/bc6714e8-369c-11e7-9711-66d084883086.png)
![dialogolagarto](https://cloud.githubusercontent.com/assets/22629584/25981771/bc67be5c-369c-11e7-8400-2eee78d0dfc9.png)
![dialogolagarto2](https://cloud.githubusercontent.com/assets/22629584/25981772/bc6ab292-369c-11e7-88f2-95d7ed202437.png)
![dialogolagarto3](https://cloud.githubusercontent.com/assets/22629584/25981773/bc6d0812-369c-11e7-9374-ff7cc35cba55.png)
![dialogorata](https://cloud.githubusercontent.com/assets/22629584/25981774/bc750076-369c-11e7-9021-59db1956f5bc.png)
![dialogorata2](https://cloud.githubusercontent.com/assets/22629584/25981776/bc7b9242-369c-11e7-9883-5031e7d412c8.png)
![dialogorata3](https://cloud.githubusercontent.com/assets/22629584/25981775/bc7b7e42-369c-11e7-8839-972dacb2d4be.png)
![dialogovibora](https://cloud.githubusercontent.com/assets/22629584/25981777/bc7f70b0-369c-11e7-9773-66a8fc7dafd4.png)
![dialogovibora2](https://cloud.githubusercontent.com/assets/22629584/25981778/bc86d04e-369c-11e7-8dae-6c634550429d.png)
![dialogovibora3](https://cloud.githubusercontent.com/assets/22629584/25981779/bc88c7dc-369c-11e7-9d81-723274b05252.png)
