### ISSUE TITLE
Crear estructuras JSON servicio Asignacion personaje a jugador

### ISSUE THREAD

**Issue by JuanCheroslan** [ISWPOLI/Pacto-de-Honor#559]
Asignar un personaje a un jugador. Por debajo encuentre el id del Jugador de acuerdo al token

- [x] Codigo Fuente

- [x] SOAPUI

- [x] Documentación

**Comment by EdnaEspejo** [comment]
Se identifican fallas en la tabla Jugador_tiene_Personaje ya que no permite el llamado de la entidad para generar el servicio que permita realizar la asignación, se hace solicitud para realizar la modificación a nivel de bases de datos; se espera entrega de modificación para el día 15 mayo para poder realizar la implementación solicitada.

**Comment by EdnaEspejo** [comment]
Se genera servicio REST para la entidad Jugador_tiene_ personaje para realizar la asignación con el método create, donde se asigna al idJugador un idPersonaje. De acuerdo a lo solicitado por frontend retorna "OK" cuando se asigna correctamente y un "KO" en el caso contrario.
![image](https://cloud.githubusercontent.com/assets/25808635/26234804/e3eb9ce2-3c2c-11e7-8424-f18a36188019.png)

**Comment by EdnaEspejo** [comment]
Se realiza commit correspondiente
