### ISSUE TITLE
Población de la DB

### ISSUE THREAD

**Issue by jnrubiano** [ISWPOLI/Pacto-de-Honor#56]
Poblacion de la base de datos  condatos de prueba

**Comment by juancelemin** [comment]
- [x] poblar cada una de las tablas(1.5h)

- [x] adjuntar el script(1min)

- [x] mencionar correciones (10 min)
[scrip.txt.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/797644/scrip.txt.txt)

**Comment by zergiozerna81** [comment]
Revisar nuevo issue donde se va a subir nuevo script:

https://github.com/ISWPOLI/Pacto-de-Honor/projects/1#card-1860342
