### ISSUE TITLE
Modificacion servicio REST: personajes desbloqueados

### ISSUE THREAD

**Issue by JuanCheroslan** [ISWPOLI/Pacto-de-Honor#564]
Personajes desbloqueados: Personajes buenos que el jugador ha desbloqueado

- [x] Codigo Fuente

- [ ] SoapUI

- [ ] Documentación

**Comment by EdnaEspejo** [comment]
Se identificaron fallas a nivel de bases de datos con la tabla Categoria que es la que permite identificar el tipo de personaje, se solicitaron las modificaciones correspondientes que ya se encuentran cargadas y se generan las nuevas conexiones para el desarrollo en el entorno local.

**Comment by EdnaEspejo** [comment]
`/**
     * Busca los personajes que un jugador ha desbloqueado
     * Se prueba con el TestCase "unlockedCharacter" del proyecto JugadorTienePersonaje-soapui-project
     * @param token String con el token que se otorgo en el login
     * @param idJugador
     * @return list nombre, avatar, estado y descripcion del personaje
     */
    @GET
    @Path("unlockedCharacter")
    @Produces({"application/json"})
    public String unlockedCharacter(@QueryParam("idJugador") Integer idJugador, @QueryParam("token") String token){
        String result = "";
        try{
            Query queryToken = em.createNamedQuery("Usuario.findToken");
            queryToken.setParameter("token", token);
            Usuario user = (Usuario) queryToken.getSingleResult();
            if(user != null){
                Query queryJugadorTienePersonaje = em.createNamedQuery("JugadorTienePersonaje.findJugador");
                queryJugadorTienePersonaje.setParameter("idJugador", idJugador);
                List<JugadorTienePersonaje> jugadortienepersonaje = queryJugadorTienePersonaje.getResultList();
                if(!jugadortienepersonaje.isEmpty()){
                    if(jugadortienepersonaje.size() == 1){
                        Personaje personaje = em.find(Personaje.class, jugadortienepersonaje.get(0).getIdJugador());
                        int estado;
                        //categoria 1 para personajes buenos
                        if(personaje.getIdCategoria() == 1){
                            estado = 1; //desbloqueado
                            result = "{\"idP\":\""+personaje.getIdPersonaje()+"\",\"nombrePersonaje\":\""+personaje.getNombrePersonaje()+"\",\"estado\":\""+estado+"\",\"avatar\":\""+personaje.getIdImagen()+"\",\"descripcion\":\""+personaje.getDescripcionPersonaje()+"\"}";
                        }else{
                            estado = 0; //bloqueado
                            result = "{\"idP\":\""+personaje.getIdPersonaje()+"\",\"nombrePersonaje\":\""+personaje.getNombrePersonaje()+"\",\"estado\":\""+estado+"\",\"avatar\":\""+personaje.getIdImagen()+"\",\"descripcion\":\""+personaje.getDescripcionPersonaje()+"\"}";
                        }
                    }else{
                        result = "{\"response\":\"No unlocked character\"}";
                    }
                }else{
                    result = "{\"response\":\"No unlocked character\"}";
                }
            }else{
                result = "{'response':'KO', 'cause':'Invalid token'}";
            }
        }catch(Exception e){
            result = "{'response':'KO', 'cause':'Invalid token'}";
            e.printStackTrace();
        }
        return result;
    }`
