### ISSUE TITLE
Creacion Estructura JSON: Resultado batalla

### ISSUE THREAD

**Issue by JuanCheroslan** [ISWPOLI/Pacto-de-Honor#566]
Resultado batalla: Toma los cambios resultantes en la batalla y los modifica en la base de datos

- [x] Codigo Fuente

- [x] SoapUI

- [x] Documentación

**Comment by jnrubiano** [comment]
Este método se entregó en el commit 060f179252c85023089bbf5fa5e4c6275145f5ef
