### ISSUE TITLE
Creacion de Servicio REST: Logros

### ISSUE THREAD

**Issue by JuanCheroslan** [ISWPOLI/Pacto-de-Honor#567]
Logros: Logros que el jugador ha desbloqueado e información pertinente para saber si es necesario desbloquear algún otro

- [ ] Codigo Fuente

- [ ] SoapUI

- [ ] Documentación

**Comment by nmartinezmarin** [comment]
Esta isuue se cierra ya que el trabajo es realizado por @JuanCheroslan  en la issue . 
https://github.com/ISWPOLI/Pacto-de-Honor/issues/352
