### ISSUE TITLE
Crear estructura JSON Prueba Piscotecnica: Factor

### ISSUE THREAD

**Issue by JuanCheroslan** [ISWPOLI/Pacto-de-Honor#569]
Validar si la respuesta esta asociada a un factor especifico en la base de datos.

- [x] Codigo Fuente

- [x] SoapUI

- [x] Documentación

**Comment by ghost** [comment]
Se realiza el código Fuente para verificar si la respuesta esta asociada a un factor en especifico en la base de datos.

**Comment by ghost** [comment]
Se crea servicio:
`package rest;

import entities.PreguntaPruebaPsicotecnica;
import entities.PruebaPsicotecnicaFactores;
import entities.Usuario;
import entities.RespuestaPreguntasPsicotecnicas;
import java.util.List;
import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.MediaType;

/**
 * Servicio para la entidad Factor
 * @author JERR
 */

@Stateless
@Path("pruebapsicotecnicafactores")
public class PruebaPsicotecnicaFactoresFacadeREST extends AbstractFacade<PruebaPsicotecnicaFactores> {

    @PersistenceContext(unitName = "PolifightPU")
    private EntityManager em;

    public PruebaPsicotecnicaFactoresFacadeREST() {
        super(PruebaPsicotecnicaFactores.class);
    }

          
    @GET
    @Path("getEstado")
    @Consumes({"application/json"})
    @Produces({"application/json"})
    public String returnEstado(@QueryParam("token") String token, @QueryParam("numeroPreguntaPrueba") Integer np, @QueryParam("idFactor") Integer idf) {
        String resultado="";
        try{
            Query query = em.createNamedQuery("Usuario.findToken");
            query.setParameter("token", token);
            Usuario user = (Usuario) query.getSingleResult();
                                 
            if (user == null) {
                resultado = "{'response':'KO', 'cause':'No found token'}";
            } if (np == null) {
                    resultado = "{'response':'KO','cause':'id # pregunta not found'}";
            } if (idf == null) {
                    resultado = "{'response':'KO','cause':'id Factor not found'}";
            }
            
            if(user!=null){
            
            Query query2 = em.createNamedQuery("PreguntaPruebaPsicotecnica.findByIdPreguntaPsicotecnica");   
            query2.setParameter("idPruebaPsicotecnica", np);
            PreguntaPruebaPsicotecnica idpp=(PreguntaPruebaPsicotecnica)query2.getSingleResult();
            
            Query query3 = em.createNamedQuery("RespuestaPreguntasPsicotecnicas.findByIdFactor"); 
            query3.setParameter("idFactor", idpp);
            RespuestaPreguntasPsicotecnicas descripcion = (RespuestaPreguntasPsicotecnicas) query3.getSingleResult();
            resultado = "{'Response':'" + descripcion.getDescripcion() + "'}";
            }     
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println(e);
                 }
        return resultado;
    }
    
    @POST
    @Override
    @Consumes({"application/xml", "application/json"})
    public void create(PruebaPsicotecnicaFactores entity) {
        super.create(entity);
    }

    @PUT
    @Path("{id}")
    @Consumes({"application/xml", "application/json"})
    public void edit(@PathParam("id") Integer id, PruebaPsicotecnicaFactores entity) {
        super.edit(entity);
    }

    @DELETE
    @Path("{id}")
    public void remove(@PathParam("id") Integer id) {
        super.remove(super.find(id));
    }

    @GET
    @Path("{id}")
    @Produces({"application/xml", "application/json"})
    public PruebaPsicotecnicaFactores find(@PathParam("id") Integer id) {
        return super.find(id);
    }

    @GET
    @Override
    @Produces({"application/xml", "application/json"})
    public List<PruebaPsicotecnicaFactores> findAll() {
        return super.findAll();
    }

    @GET
    @Path("{from}/{to}")
    @Produces({"application/xml", "application/json"})
    public List<PruebaPsicotecnicaFactores> findRange(@PathParam("from") Integer from, @PathParam("to") Integer to) {
        return super.findRange(new int[]{from, to});
    }

    @GET
    @Path("count")
    @Produces(MediaType.TEXT_PLAIN)
    public String countREST() {
        return String.valueOf(super.count());
    }

    @Override
    protected EntityManager getEntityManager() {
        return em;
    }
    
}`

**Comment by ghost** [comment]
Prueba con SoapUI:

![image](https://cloud.githubusercontent.com/assets/25758763/26518638/c56f4a4a-4279-11e7-905b-bd39893b572b.png)

[PruebasSoapPolifightFactores-soapui-project.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/1033357/PruebasSoapPolifightFactores-soapui-project.zip)

**Comment by ghost** [comment]
Se entrega documentación:
[Serviciofactores.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/1033358/Serviciofactores.pdf)

**Comment by ghost** [comment]
Se cierra por actividades completadas, se deja a consideración si se requiere modificación ya que los servicios pueden variar dependiendo de la estructura.
