### ISSUE TITLE
Diseño ER

### ISSUE THREAD

**Issue by jnrubiano** [ISWPOLI/Pacto-de-Honor#57]

**Comment by wpradere** [comment]
Se realiza modelo grafico de la BD Entidad relación  y se sube .png
![grafica](https://cloud.githubusercontent.com/assets/22016129/23240959/533057e6-f93e-11e6-9de8-797885fe3814.png)

Se toma 1 hora en este proceso

**Comment by zergiozerna81** [comment]
Se realiza nuevo modelo entidad relación de la base de datos, a continuación link del issue.

https://github.com/ISWPOLI/Pacto-de-Honor/projects/1#card-1860342

**Comment by juancelemin** [comment]
[poli_fighter.txt](https://github.com/ISWPOLI/Pacto-de-Honor/files/835483/poli_fighter.txt)
![diagrama](https://cloud.githubusercontent.com/assets/17105514/23820242/986db29e-05e2-11e7-9ee5-15335330d94f.png)

**Comment by manuk160** [comment]
nuevo modelo de acuerdo a cambios.

![modelo_entidad_relacion_version01](https://cloud.githubusercontent.com/assets/25807878/23836346/b5ca2936-0744-11e7-9a4b-3c3272236def.PNG)
