### ISSUE TITLE
Crear Estructura JSON: obtener las respuestas para una pregunta y un factor especifico

### ISSUE THREAD

**Issue by JuanCheroslan** [ISWPOLI/Pacto-de-Honor#570]
Respuesta para una la pregunta y factor especifico.

- [x] Codigo Fuente

- [x] SoapUI

- [x] Documentación

**Comment by ghost** [comment]
Código Fuente:

`import entities.PreguntaPruebaPsicotecnica;
import entities.PruebaPsicotecnicaFactores;
import entities.Usuario;
import entities.RespuestaPreguntasPsicotecnicas;
import java.util.List;
import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.MediaType;

/**

Servicio para la entidad Factor
@author JERR
*/
@stateless
@path("pruebapsicotecnicaRespuestafactores")
public class PruebaPsicotecnicaFactoresFacadeREST extends AbstractFacade {

@PersistenceContext(unitName = "PolifightPU")
private EntityManager em;

public PruebaPsicotecnicaRespuestaFactoresFacadeREST() {
    super(PruebaPsicotecnicaFactores.class);
}

      
@GET
@Path("getEstado")
@Consumes({"application/json"})
@Produces({"application/json"})
public String returnEstado(@QueryParam("token") String token, @QueryParam("numeroPreguntaPrueba") Integer np, @QueryParam("idFactor") Integer idf) {
    String resultado="";
    try{
        Query query = em.createNamedQuery("Usuario.findToken");
        query.setParameter("token", token);
        Usuario user = (Usuario) query.getSingleResult();
                             
        if (user == null) {
            resultado = "{'response':'KO', 'cause':'No found token'}";
        } if (np == null) {
                resultado = "{'response':'KO','cause':'id # pregunta not found'}";
        } if (idf == null) {
                resultado = "{'response':'KO','cause':'id Factor not found'}";
        }
        
        if(user!=null){
        
        Query query2 = em.createNamedQuery("PreguntaPruebaPsicotecnica.findByIdPreguntaPsicotecnica");   
        query2.setParameter("idPruebaPsicotecnica", np);
        PreguntaPruebaPsicotecnica idpp=(PreguntaPruebaPsicotecnica)query2.getSingleResult();
        
        Query queryFactor = em.createNamedQuery("RespuestaPreguntasPsicotecnicas.findByIdFactor"); 
        queryFactor .setParameter("idFactor", idpp);
        RespuestaPreguntasPsicotecnicas descripcion = (RespuestaPreguntasPsicotecnicas) query3.getSingleResult();
        resultado = "{'Response':'" + respuesta.getRespuesta() + "'}";
        }     
    } catch (Exception e) {
        e.printStackTrace();
        System.out.println(e);
             }
    return resultado;
}

@POST
@Override
@Consumes({"application/xml", "application/json"})
public void create(PruebaPsicotecnicaFactores entity) {
    super.create(entity);
}

@PUT
@Path("{id}")
@Consumes({"application/xml", "application/json"})
public void edit(@PathParam("id") Integer id, PruebaPsicotecnicaFactores entity) {
    super.edit(entity);
}

@DELETE
@Path("{id}")
public void remove(@PathParam("id") Integer id) {
    super.remove(super.find(id));
}

@GET
@Path("{id}")
@Produces({"application/xml", "application/json"})
public PruebaPsicotecnicaFactores find(@PathParam("id") Integer id) {
    return super.find(id);
}

@GET
@Override
@Produces({"application/xml", "application/json"})
public List<PruebaPsicotecnicaFactores> findAll() {
    return super.findAll();
}

@GET
@Path("{from}/{to}")
@Produces({"application/xml", "application/json"})
public List<PruebaPsicotecnicaFactores> findRange(@PathParam("from") Integer from, @PathParam("to") Integer to) {
    return super.findRange(new int[]{from, to});
}

@GET
@Path("count")
@Produces(MediaType.TEXT_PLAIN)
public String countREST() {
    return String.valueOf(super.count());
}

@Override
protected EntityManager getEntityManager() {
    return em;
}`

**Comment by ghost** [comment]
Pruebas SoapUI

![image](https://cloud.githubusercontent.com/assets/25758763/26735913/93eafb80-4789-11e7-844e-56d31a937857.png)

**Comment by ghost** [comment]
Documentación servicio.

[ServicioRespuesta-factores.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/1048370/ServicioRespuesta-factores.pdf)

**Comment by ghost** [comment]
Se cierra Issues por tareas completadas, el servicio se puede modificar si la estructura del modelo cambia.
