### ISSUE TITLE
Crear Estrucuta JSON: Respuesta

### ISSUE THREAD

**Issue by JuanCheroslan** [ISWPOLI/Pacto-de-Honor#571]
este servicio debe insertar la respuesta del jugador y luego devolver si se pudo insertar o no

- [x] Código Fuente @Basespoli

- [x] SoapUI  @Basespoli

- [x] Documentación  @Basespoli

**Comment by ghost** [comment]
Se configura todo el entorno de trabajo para poder desarrollar el servicio. 

Tiempo empleado 40 min

![image](https://cloud.githubusercontent.com/assets/25758763/26090537/44171f4c-39cb-11e7-81f3-bc99086b1e0d.png)

**Comment by ghost** [comment]
Se descarga, instala y se aprende a manejar SoapUI para probar  los servicios.


![image](https://cloud.githubusercontent.com/assets/25758763/26091367/58c0a9e0-39d0-11e7-8668-ae8695f38e8e.png)

Tiempo empleado 1 hora

**Comment by ghost** [comment]
Capacitación y resolución de dudas para problemas de entorno de desarrollo y pruebas de estructuras @JuanCheroslan 

Tiempo empleado 50 min

**Comment by ghost** [comment]
Se crean servicios en código fuente  y están en procesos de pruebas funcionales con el aplicativo SoapUI.

![image](https://cloud.githubusercontent.com/assets/25758763/26133442/ab360b74-3a6c-11e7-9b8c-a7c3169cdeda.png)

Tiempo empleado 40 min

**Comment by ghost** [comment]
Código Fuente:
`package rest;

import entities.RespuestaPreguntasPsicotecnicas;
import entities.Usuario;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.List;
import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.MediaType;

/**
 *
 * @author JERR
 */
@Stateless
@Path("respuestapreguntaspsicotecnicas")
public class RespuestaPreguntasPsicotecnicasFacadeREST extends AbstractFacade<RespuestaPreguntasPsicotecnicas> {

    @PersistenceContext(unitName = "PolifightPU")
    private EntityManager em;

    public RespuestaPreguntasPsicotecnicasFacadeREST() {
        super(RespuestaPreguntasPsicotecnicas.class);
    }

    @POST
    @Path("create")
    @Consumes({"application/json"})
    @Produces({"application/json"})
    public String crearPersonaje(@QueryParam("token") String token, RespuestaPreguntasPsicotecnicas entity) {
        String resultado;
        try{
            Query query = em.createNamedQuery("Usuario.findToken");
            query.setParameter("token", token);
            
            Usuario user = (Usuario) query.getSingleResult();
            if(user != null){
                em.persist(entity);
                
                resultado = "{'response':'OK'}";
            }else{
                resultado = "{'response':'KO', 'cause':'Token invalid'}";
            }            
        }catch (Exception e){
            e.printStackTrace();
            StringWriter errors = new StringWriter();
            e.printStackTrace(new PrintWriter(errors));            
            resultado = "{'response':'KO', 'cause':'"+errors.toString()+"'}";
        }
        return resultado;
    }
    
    
    @PUT
    @Path("{id}")
    @Consumes({"application/xml", "application/json"})
    public void edit(@PathParam("id") Integer id, RespuestaPreguntasPsicotecnicas entity) {
        super.edit(entity);
    }

    @DELETE
    @Path("{id}")
    public void remove(@PathParam("id") Integer id) {
        super.remove(super.find(id));
    }

    @GET
    @Path("{id}")
    @Produces({"application/xml", "application/json"})
    public RespuestaPreguntasPsicotecnicas find(@PathParam("id") Integer id) {
        return super.find(id);
    }

    @GET
    @Override
    @Produces({"application/xml", "application/json"})
    public List<RespuestaPreguntasPsicotecnicas> findAll() {
        return super.findAll();
    }

    @GET
    @Path("{from}/{to}")
    @Produces({"application/xml", "application/json"})
    public List<RespuestaPreguntasPsicotecnicas> findRange(@PathParam("from") Integer from, @PathParam("to") Integer to) {
        return super.findRange(new int[]{from, to});
    }

    @GET
    @Path("count")
    @Produces(MediaType.TEXT_PLAIN)
    public String countREST() {
        return String.valueOf(super.count());
    }

    @Override
    protected EntityManager getEntityManager() {
        return em;
    }
    
}
`

**Comment by ghost** [comment]
Prueba con soapUI:

![image](https://cloud.githubusercontent.com/assets/25758763/26291405/a46e53f4-3e73-11e7-87a6-4637b9b241b1.png)


[PruebasServicioswebPolifight-workspace.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/1017739/PruebasServicioswebPolifight-workspace.zip)

**Comment by ghost** [comment]
Se entrega Documentación:
[ServicioRespuestaPruebaPsicotecnica_v0.3.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/1017728/ServicioRespuestaPruebaPsicotecnica_v0.3.pdf)

**Comment by JuanCheroslan** [comment]
se cierra por actividades completadas
