### ISSUE TITLE
Crear Estructura JSON: conteo de factores prueba psicotenica

### ISSUE THREAD

**Issue by JuanCheroslan** [ISWPOLI/Pacto-de-Honor#572]
Este servicio es el encargado de sumar puntos para asi poder validar si un usuario representa a un personaje malo o bueno.

- [x] Codigo Fuente

- [x] SoapUI

- [x] Documentación

**Comment by JuanCheroslan** [comment]
cambio de sprint debido a reasignacion de actividades

**Comment by nmartinezmarin** [comment]
*Se realiza la intalacion de la base de datos y se hace deploy de los servicios de forma local para poder empezar con el desarrollo de la tarea

**Comment by nmartinezmarin** [comment]
Les pido explicacion a @jnrubiano y a @JuanCheroslan  para entender la estructura del proyecto y poder empezar con el desarrollo del servicio

**Comment by nmartinezmarin** [comment]
Se corre de sprint para terminar la documentación y el archivo de pruebas
