### ISSUE TITLE
1.2.13 Mostrar el personaje seleccionado

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#574]
**Descripición**

Debido a recomendaciones dadas por @DiegOliveros , se muestra el personaje seleccionado antes de la batalla.

**TAREAS**
- [x] Mostrar el personaje que es seleccionado

**Comment by gabogabbs** [comment]
Se implementa la selección de personaje funcional mostrando el personaje seleccionado antes de la batalla. Se hace merge en la rama Master. 
Se da como concluido este issue.

REGISTRO DE TIEMPO: 1 hora y 30 minutos.
