### ISSUE TITLE
1.1.49 Prueba módulo de compra

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#577]
**Descripción**

Modificar el módulo de compra para el funcionamiento total con consumo de JSON.

**TAREAS:**

- [x] Revisar el módulo de compras actual
- [ ] Modificarlo para que funcione con el JSON designado
- [ ] Consumir servicio del compra
- [ ] Inserción de información después de uso del módulo

**Comment by CamilaG08** [comment]
Archivo de compra .js y .txt con el JSON:

[Compra.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/995003/Compra.zip)

**Comment by jnrubiano** [comment]
Hola @CamilaG08 

Se terminó el desarrollo del método de compra y quedó la documentación en el servicio "Jugador", por fa revísala y me notificas si quedó de acuerdo a lo acordado (issue #479 ). Cambio el estado en el excel a "Entregado".

Atento a tus comentarios,

Saludos.

**Comment by CamilaG08** [comment]
@dayepesb  Es necesario finalizar esta tarea para el día miércoles 24 de mayo.

**Comment by CamilaG08** [comment]
No se realizan las tareas debido a que @dayepesb quedó a cargo del login, queda pendiente por realizar. Se cierra el Issue.
