### ISSUE TITLE
6.2.23 Reporte SCRUM Master(Sábado 13 de mayo)

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#586]
**Descripción**
Realizar reporte SCRUM Master sábado 13 de mayo.

**Tareas a realizar**
- [x] Reporte SCRUM Master.

**Comment by ghost** [comment]
# Reporte 13 de Mayo

## Issue #586 - Reporte SCRUM MASTER (Sábado 13 de Mayo) [Dario Muñoz]:
- Se revisaron y reportaron avances en las tareas de 8 integrantes del grupo de Frontend.
- Se subieron reportes a la Issue.

## Issue #526 - Creación de la libreria del juego [Darío Muñoz]:
- Se solicita a Camilo D'achiardi el diseño de una portada para la librería.
- Se subieron los archivos **inicio.html**, **verificacionDeCodigo.html**, **codigoUsado.html**, **desbloqueoPersonaje.html**, **cajaMisteriosa.html** y **batalla.html** de la librería.
- El resto de la librería se subirá en el sprint 14.

## Issue #524 - Diseño del tutorial [Camillo D'achiardi]:
- Se realizó un video-tutorial mostrando como se usa el juego.
- Se sube a youtube el video https://youtu.be/oSBAOBYH1Is.

## Issue #421 - Estandarización de botones [Camilo D'achiardi]:
- Camila le dice a Camilo que hace falta diseñar 5 botones que estaran dentro del perfil del jugador.
- Se diseñaron 5 botones y fueron al repositorio.

## Issue #471 - Cookies [Gabriel Álvarez]:
- Se implementó un archivo de prueba de la respuesta que da el servicio de login.
- Se guardó el token en una cookie.

## Issue #469 - Integración Login y juego [Gabriel Álvarez, David Yepes y Julio Ernesto]:
- No hay avances en esta tarea ya que el profesor Diego Oliveros dice que se cree una nueva tarea para Gabriel Álvarez y David Yepes.

## Issue #532 - Botones de sonido [Gabriel Álvarez]:
- Se corrigieron todas las variables y los preloads.
- Los botones de sonido quedaron funcionales.

## Issue #574 - Mostrar el personaje seleccionado [Gabriel Álvarez]:
- Se modifico **seleccionPersonaje.js**, para que quedara funcional.
- Esta sección ahora muestra que personaje esta seleccionado.

## Issue #534 - Implementación pruebas psicotécnicas [Sebastián Rodríguez y David Yepes]:
- Hubó una reunión con Jeimy Sosa con el motivo de explicación de como implementar las pruebas psicotécnicas en el juego.
- Hubó una reunión con David Yepes con el motivo de iniciar con la implementación.
- En el proceso de implementación surgió que algunas acciones del juego planteadas inicialmente se descartaron durante el proceso de desarrollo.
- Aún falta pedir JSON's de las pruebas psicotécnicas (Subtarea para David Yepes).
- Aún terminar de implementar las pruebas psicotécnicas en el juego (Subtarea para Sebastián Rodriguez).

## Issue #521 - Modificación módulo de logros [Juan Guillermo Celemín]:
- Se creo un JSON de ejemplo para hacer pruebas.
- Se integró el JSON con el módulo de logros.

## Issue #522 - Modificación perfil del jugador [Juan Carlos Quintana]:
- Hay un problema con la rama de Juan Carlos.
- Se creó el JSON que se consumirá, pero aún no se ha logrado implementar.
- Se crea un JSON para hacer pruebas.

## Issue #541 - Definición de servicios [Camila Gutierrez]:
- Se terminó con la definición de servicios el día miércoles 10 de mayo.

## Issue #538 - Revisión del juego [Camila Gutiérrez y Jeimy Sosa]:
- Se reviso entregas ya avances de tareas de todos los integrantes de Frontend.

## Issue #535 - Preparación de reunión con el vice rector [Camila Gutiérrez y Jeimy Sosa]:
- Se habló con Diego Oliveros y con Julián Olarte con el motivo de solicitar las pautas para la reunión.
- Ellos dicen que la reunión debe aplazarse hasta el sprint 16.

## Issue #550 - Preguntas Acciones del juego base de datos [Jeimy Sosa]:
- Se habló con Juan Camilo con el motive de aclarar dudas sobre servicios de las pruebas psicotécnicas.

## Issue #537 - Realizar video explicativo del juego [Jeimy Sosa]:
- Se realizó un video de todos los integrantes del proyecto.
