### ISSUE TITLE
6.2.24 Reporte SCRUM Master(Sábado 13 de mayo)

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#587]
**Descripción**
Reporte SCRUM Master Sábado 13 de mayo.

**Tareas a realizar**
- [x] Reporte SCRUM Master

**Comment by ivandav** [comment]
# Reportes 13 de mayo del 2017
 Se revisan los avances de las tareas que fueron asignadas el día sábado para el nuevo Sprint. 
 
## Issue #539 Documentación del código [Jaime Bernal]:
   - Se revisa el documento realizado por Dario Muñoz.
   - Se empiezan hacer las modificaciones segun los nuevos cambios en el código.    

## Issue #519 Revisar entregas Sprint 12 [Jaime Bernal]:
   - Se cerro la issue pues la tarea se completo.

## Virtual Story Mapping [Jaime Bernal]:
   - Se actualizaron los entregables.

## Pagina pacto de honor en wordpress [Jaime Bernal]:
   - Se esta realizando la importación de todas las imágenes de los Sprint.

## Issue #449 Reportes Scrum Master sabado 13 de mayo [Ivan Barrantes]:
   - Se realiza la revisión de los trabajos que tenían que realizar los integrantes del grupo y esto se consolida y se sube a github.


## Issue #552 Imágenes de diálogos e imágenes que están por separado mundo 7-12 [Ivan Barrantes]:
   - Se realizan modificaciones a la imágenes que se recibieron, se cambia el tamaño, se hace photoshop ara retirar los textos y finalmente se crea el archivo en javaScript para cargar la nuevas imágenes y unirlas con los textos que pueden ser modificados. 


## Issue #534 Implementacion pruebas psicotecnicas [David Yepes]:
   - Se tuvo a reunión con juan sebastian.
   - Se identificaron algunas cosas que se tienen que modificar en los servicios. 

## Issue #469 Integración login y juego [David Yepes]:
   - Se va realizar un nuevo login por problemas con el anterior. 
 
 
## Issue #527 Modificar modulo códigos alfanuméricos [Cristian Garzon]:
   - Se tienen problemas a la hora de unir códigos alfanuméricos y JSON. 

## Issue #541 Definición de servicios [Nicolas Martinez]:
   - No asiste a clase. 

## Issue #523 Mejorar todo el juego [Nicolas Martinez]:
   - No asiste a clase

## Issue #483 Servicios REST campo de batalla [Nicolas Martinez]:
   - No asiste a clase. 
 
## Issue #544 Contenido red social [Ernesto Rodriguez]:
   - Se completo la tarea y por ende se cierra en github. 

## Issue #475 Integración login con otros esquemas de login [Ernesto Rodriguez]:
   - Se hace el canal el canal de socket de comunicación.
   - Se hace la prueba del consumo del servicio.

## Issue #474 Login redes sociales [Ernesto Rodriguez]:
   - Se investiga como se hace la integración con microsoft.
   - Se hace un diagrama para explicar la autentificacion con facebook. 

## Issue #469 Integracion login y juego [Ernesto Rodriguez]:
   - Se va crear un nuevo login.

**Comment by jrsosago** [comment]
Se cierra está Issue por actividad realizada.
