### ISSUE TITLE
6.2.25 Reporte SCRUM Master (Miércoles  17 de mayo)

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#588]
**Descripción**
Realizar reporte SCRUM Master Miércoles 17 de mayo.

**Tareas a realizar**
- [x] Realizar reporte SCRUM Master.

**Comment by ghost** [comment]
# Reporte 17 de Mayo

## Issues #588 y #589 - Reporte SCRUM MASTER (Miércoles 17 de Mayo) [Dario Muñoz]:
- Se revisaron y reportaron avances en las tareas de 14 integrantes del grupo de Frontend.
- Se subieron reportes a la Issue.

## Issue #595 - Creación de la libreria del juego [Darío Muñoz]:
- Se modificó contenido de **inicio.html**.
- Se modificó contenido de **verificacionDeCodigo.html**.
- Se modificó contenido de **codigoUsado.html**.
- Se modificó contenido de **desbloqueoPersonaje.html**.
- Se modificó contenido de **batalla.html**.
- Se agregó contenido al archivo llamado **boot.html**.
- Se agregó contenido al archivo llamado **cajaMisteriosa.html**.
- Se agregó contenido al archivo llamado **compraPersonajes.html**.
- Se agregó contenido al archivo llamado **cookies.html**.
- Se agregó contenido al archivo llamado **creditos.html**.
- Se agregó contenido al archivo llamado **fin.html**.
- Se agregó contenido al archivo llamado **game.html**.
- Se agregó contenido al archivo llamado **historieta.html**.
- Se agregó contenido al archivo llamado **inivitarAmigos.html**.
- Se agregó contenido al archivo llamado **boot.html**.
- Se agregó contenido al archivo llamado **logros.html**.

## Issue #591 - Documentación del código [Camilo D'achiardi]:
- Se modifica la estructura del documento que se venia manejando.
- Aún no se ha agregado ni modificado ninguna explicación de código.

## Issue #593 - Investigación de saltos de personajes en batalla [Camilo D'achiardi]:
- Se investigó sobre los saltos en phaser.
- Se subió explicación a la Issue.

## Issue #598 - PITCH/Diapositivas [Camila Gutiérrez y Jeimy Sosa]:
- Se realizó el Pitch y diapositivas.
- El día 17 de mayo se realizará reunión con Diego Oliveros y Julián Olarte con el motivo de revisar el pitch.

## Issue #605 - Hacer cambios en relación de acciones y preguntas a implementar en el juego [Jeimy Sosa]:
- Se realizó un avance en la tabla de acciones y preguntas del juego.

## Issue #594 - Manual del desarrollador [Gabriel Álvarez]:
- Se realizó la estructura del manual de desarrollador con html y css.
- Se realizó la introducción.
- Se agregó la portada del manual.
- Se incluyó el menú de navegación con sus items.
- Se agregó contenido a la sección **programacion.html**.

## Issue #600 - Navegabilidad del juego [Gabriel Álvarez]:
- Se realizó la sección **seleccionAvatar.js** funcional.
- Se pusó indicador de posición de scroll en **seleccionAvatar.js**.
- Se pusó indicador de posición de scroll en **compraPersonajes.js**.
- Se pusó indicador de posición de scroll en **cajaMisteriosa.js**.
- Se pusó indicador de posición de scroll en **logros.js**.

## Issue #590 - Pantalla de personajes desbloqueados y jefes derrotados [Juan Carlos Quintana y Juan Guillermo Celemín]:
- Se diseño módulo de jefes derrotados
- Se implementó la sección de jefes derrotados.
- Aún hace falta implementar los personajes desbloqueados.
- No se encontraron los json de los personajes desbloqueado y jefes derrotados.

## Issue #522 - Modificación perfil del jugador [Juan Carlos Quintana]:
- Ya esta el JSON creado.
- No se ha podido integrar este JSON para que consuma los servicios.
