### ISSUE TITLE
6.2.26 Reporte SCRUM Master(Miércoles 17 de mayo)

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#589]
**Descripción**
Reporte SCRUM Master Miércoles 17 de mayo.

**Tareas a realizar:**
- [x] Reporte SCRUM Master.

**Comment by jrsosago** [comment]
Se reasigna a @jdma0440, por la poca cantidad de personas de ahora solo se asignara a @jdma0440 en está tarea.

**Comment by ghost** [comment]
# Reporte 17 de Mayo

## Issue #527 - Modificar módulo códigos alfanuméricos [Cristian Garzón]:
- Aún no hay avances en esta tarea.

## Issue #603 - Revisar entregas Sprint 13 [Cristian Garzón]:
- Se revisarón 12 entregas.
- Se realizó el documento de conclusiones de estas 12 entregas.
- Aún faltan 6 entregas.

## Issue #609 - Caricaturizar escenarios [Cristian Garzón]:
- Se caricaturizaron 7 escenarios.
- Se subieron al repositorio.
- Aún hacen falta 6 escenarios.

## Issue #596 - Revisión entregas Sprint 13 [Iván Barrantes]:
- Aún no hya avances en esta tarea.

## Issue #597 - Instrucciones nivel 1 [Iván Barrantes]:
- Se realizaron los mockups para versión web y móvil.
- Aún no se ha implementado esto en el juego.

## Issue #601 - Re-estructuración del Login [Iván Barrantes y David Yepes]:
- Se organizaron algunos archivos que se tenian del login anterior para lograr su funcionamiento (Subtarea realizada por Iván Barrantes).
- Se enviaron estos archivos a David Yepes (Subtarea realizada por Iván Barrantes).
- Se revisó como consumir el servicio (Subtarea realizada por David Yepes).

## Issue #534 - Implementación pruebas psicotécnicas [David Yepes y Sebastián Rodríguez]:
- No hay avances en esta tarea por parte de David Yepes.
- Debido a que se creo un nuevo documento de acciones a evaluar en el juego, la implementación también cambia.
- Se implementá en la seccion de **logros.js** algunas pruebas psicotécnicas dentro de las funciones.
- Aún falta volver a iniciar con las implementaciones.

## Issue #577 - Prueba módulo de compra [David Yepes]:
- Se revisó el código y se probó que funcionara localmente.

## Sin Issue - Realización de reporte consolidado de análisis de reportes entregados por todos [Jaime Bernal]:
- Se realizó reporte consolidado de análisi de reportes del día 9 de mayo.
- Se realizó reporte consolidado de análisi de reportes del día 12 de mayo.

## Issue #539 - Documentación del código [Jaime Bernal]:
- Se agrego líneas de explicación al documento formal de código del archivo **indexGame.html**.

## Sin Issue - Virtual Story Map [Jaime Bernal]:
- Se actualizó con las tareas de la semana.

**Comment by ghost** [comment]
## Issue #523 - Mejorar todo el juego [Nicolás Martínez]:
- Se encapsularon las variables del módulo **cajaMisteriosa.js**.
- Se encapsularon las variables del módulo **compra.js**.
- Se encapsularon las variables del módulo **creditos.js**.
- Se encapsularon las variables del módulo **logros.js**.
- Se encapsularon las variables del módulo **boot.js**.
- Se encapsularon las variables del módulo **seleccionPersonajes.js**.
- Se encapsularon las variables del módulo **perfilJugador.js**.
- Se arreglaron los conflictos que habian con los escudos.
- Se implementó la función de salto.
- Se modificaron las funciones del campo de batalla para que funcionara cuando los personajes intercambiaran posiciones.
- Se modificaron los eventos de las teclas para que funcionaran cuando se presionara solo una vez.
- Falta modificar los eventos de los eventos de la versión móvil, pero no se realizará debido a que Nicolás fue cambiado al grupo de Backend.
- Falta cambiar las funciones en la versión móvil para que funcione el salto.
