### ISSUE TITLE
1.6.9 Pantalla de personajes desbloqueados y jefes derrotados

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#590]
**Descripción**

Realizar las pantallas faltantes pertenecientes al perfil del jugador

**TAREAS:**

- [x] Realizar la pantalla de personajes desbloqueados por el jugador @juankrlos08 
- [x] Realizar la pantalla de jefes derrotados por el jugador @juancelemin 
- [x] Darle funcionalidad al módulo de personajes desbloqueados @juankrlos08 
- [x] Darle funcionalidad al módulo de jefes derrotados @juancelemin 
- [x] Probar la pantalla de personajes desbloqueados por el jugador con el archivo JSON existente @juankrlos08 
- [x] Probar la pantalla de jefes derrotados por el jugador con el archivo JSON existente @juancelemin 
- [ ] Consumir el servicio de personajes desbloqueados por el jugador @juankrlos08 
- [ ] Consumir el servicio de jefes derrotados por el jugador @juancelemin 
- [x] Realizar commit y referenciar el Issue @juancelemin @juankrlos08

**Comment by juancelemin** [comment]
![imagen](https://cloud.githubusercontent.com/assets/17105514/26091050/55c87fa8-39ce-11e7-866f-58d063c3b8a7.png)

**Comment by CamilaG08** [comment]
@juancelemin Por favor dejar los títulos en español ya que el juego se está manejando de esa manera en su mayoría.

**Comment by juankrlos08** [comment]
![osoloock](https://cloud.githubusercontent.com/assets/25808382/26164165/7b055e8e-3af1-11e7-8ce0-f9cc56775e67.png)
![panteraloock](https://cloud.githubusercontent.com/assets/25808382/26164167/7b1b5d1a-3af1-11e7-94bf-4a678e9362b2.png)
![peresozoloock](https://cloud.githubusercontent.com/assets/25808382/26164166/7b1b2b88-3af1-11e7-9354-352fd4193058.png)
![rataloock](https://cloud.githubusercontent.com/assets/25808382/26164169/7b1d4670-3af1-11e7-97da-8611c603ddd3.png)
![ratonloock](https://cloud.githubusercontent.com/assets/25808382/26164170/7b1dc3ca-3af1-11e7-92e4-7f29f3d0a6ad.png)
![ruisenorloock](https://cloud.githubusercontent.com/assets/25808382/26164171/7b2558a6-3af1-11e7-9b49-6c9874ab37b0.png)
![serpeinteloock](https://cloud.githubusercontent.com/assets/25808382/26164168/7b1c448c-3af1-11e7-8c3a-0c0480ed1277.png)
![viboraloock](https://cloud.githubusercontent.com/assets/25808382/26164172/7b3a88b6-3af1-11e7-9efa-b69377ec1891.png)
![zorroloock](https://cloud.githubusercontent.com/assets/25808382/26164174/7b3dfd20-3af1-11e7-870e-4a3a7d7e7403.png)
![babuinoloock](https://cloud.githubusercontent.com/assets/25808382/26164175/7b412c52-3af1-11e7-8516-6dad7278b25c.png)
![buitreloock](https://cloud.githubusercontent.com/assets/25808382/26164176/7b416488-3af1-11e7-8e7f-0aa1adb77647.png)
![burroloock](https://cloud.githubusercontent.com/assets/25808382/26164173/7b3d141e-3af1-11e7-8fa5-0b9bdc60866d.png)
![camaleonloock](https://cloud.githubusercontent.com/assets/25808382/26164177/7b45c776-3af1-11e7-8c76-a021fd9073d4.png)
![canarioloock](https://cloud.githubusercontent.com/assets/25808382/26164182/7b5eca78-3af1-11e7-8a3d-083a25d9ad42.png)
![ciervaloock](https://cloud.githubusercontent.com/assets/25808382/26164183/7b5f13ca-3af1-11e7-9f99-55c011db8bb5.png)
![galloloock](https://cloud.githubusercontent.com/assets/25808382/26164180/7b5be7a4-3af1-11e7-8ad0-edf940420de8.png)
![hienaloock](https://cloud.githubusercontent.com/assets/25808382/26164179/7b595818-3af1-11e7-8be5-f10cd65574d8.png)
![hormigaloock](https://cloud.githubusercontent.com/assets/25808382/26164178/7b5a1406-3af1-11e7-8adc-431b1dd30199.png)
![jirafaloock](https://cloud.githubusercontent.com/assets/25808382/26164181/7b5c0612-3af1-11e7-884c-e94ce9434d26.png)
![leonloock](https://cloud.githubusercontent.com/assets/25808382/26164184/7b77df18-3af1-11e7-8e86-ebf7bda0fe77.png)
Imagenes de personajes y  villanos bloqueados

**Comment by CamilaG08** [comment]
**JSON personajes desbloqueados:**

{ 
 "idP1": {"nombre": "hormiga","estado": "0", "avatar": "ruta avatar", "descripcion": "texto"}, 
 "idP2": {"nombre": "gallo","estado": "1", "avatar": "ruta avatar", "descripcion": "texto"}, 
 "idP3": {"nombre": "pantera","estado": "0", "avatar": "ruta avatar", "descripcion": "texto"}, 
 "idP4": {"nombre": "jirafa","estado": "0", "avatar": "ruta avatar", "descripcion": "texto"}, 
 "idP5": {"nombre": "cierva","estado": "1", "avatar": "ruta avatar", "descripcion": "texto"}, 
 "idP6": {"nombre": "leon","estado": "0", "avatar": "ruta avatar", "descripcion": "texto"}, 
 "idP7": {"nombre": "raton","estado": "0", "avatar": "ruta avatar", "descripcion": "texto"}, 
 "idP8": {"nombre": "canario","estado": "0", "avatar": "ruta avatar", "descripcion": "texto"}, 
 "idP9": {"nombre": "ruisenor","estado": "1", "avatar": "ruta avatar", "descripcion": "texto"} 
 }

**Comment by CamilaG08** [comment]
**JSON jefes derrotados:**

{ 
 "idP1": {"nombre": "zorro","estado": "0", "avatar": "ruta avatar", "descripcion": "texto"}, 
 "idP2": {"nombre": "oso","estado": "1", "avatar": "ruta avatar", "descripcion": "texto"}, 
 "idP3": {"nombre": "burro","estado": "0", "avatar": "ruta avatar", "descripcion": "texto"}, 
 "idP4": {"nombre": "rata","estado": "0", "avatar": "ruta avatar", "descripcion": "texto"}, 
 "idP5": {"nombre": "camaleon","estado": "1", "avatar": "ruta avatar", "descripcion": "texto"}, 
 "idP6": {"nombre": "buitre","estado": "0", "avatar": "ruta avatar", "descripcion": "texto"}, 
 "idP7": {"nombre": "abejaA","estado": "0", "avatar": "ruta avatar", "descripcion": "texto"}, 
 "idP8": {"nombre": "abejaS","estado": "0", "avatar": "ruta avatar", "descripcion": "texto"}, 
 "idP9": {"nombre": "hiena","estado": "1", "avatar": "ruta avatar", "descripcion": "texto"},
 "idP10": {"nombre": "lagarto","estado": "1", "avatar": "ruta avatar", "descripcion": "texto"},
 "idP11": {"nombre": "vibora","estado": "1", "avatar": "ruta avatar", "descripcion": "texto"},
 "idP12": {"nombre": "babuino","estado": "1", "avatar": "ruta avatar", "descripcion": "texto"} 
 }

**Comment by CamilaG08** [comment]
Dado que aún no se ha entregado ninguno de los servicios, las tareas faltantes se mueven al Sprint 15.

**Comment by juankrlos08** [comment]
falta consumo del servicio, pero el metodo queda implementado

**Comment by CamilaG08** [comment]
Queda pendiente el consumo de servicios por parte de estos módulos, se cierra el Issue debido a que las demás tareas están completadas.
