### ISSUE TITLE
5.4.11 Documentación del código

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#591]
### Descripción

Contribuir a la documentación del código actualizado al cierre del Sprint 14

### Tareas:

- [x] Hablar con @jdma0440 para revisar el formato
- [x] Revisar los cambios realizados en el código
- [ ] Consolidar la documentación hasta el 19 de mayo
- [ ] Subir el documento al repositorio
-------------
**Distribución de trabajo con Jaime:**

- [x] Revisión y documentación del archivo: Fin.js
- [x] Revisión y documentación del archivo: InvitarAmigos.js
- [x] Revisión y documentación del archivo: PerfilJugador.js
- [x] Revisión y documentación del archivo: Logros.js
- [x] Revisión y documentación del archivo: Personajes.js
- [x] Revisión y documentación del archivo: CompraPersonajes.js
- [x] Revisión y documentación del archivo: Rankings.js
- [x] Revisión y documentación del archivo: funcionesBatalla.js
- [x] Revisión y documentación del archivo: PruebasPsicotecnicas.js
- [x] Revisión y documentación del archivo: Box.js
- [x] Revisión y documentación del archivo: Código JSP
- [x] Revisión y documentación del archivo: Login.jsp
- [x] Revisión y documentación del archivo: Forgot.jsp
- [x] Revisión y documentación del archivo: Registro.jsp
- [x] Revisión y documentación del archivo: bloqueMoviles.css
- [x] Revisión y documentación del archivo: main.css
- [x] Revisión y documentación del archivo: RegistroLogin.java
- [x] Revisión y documentación del archivo: AbstractFacade.java
- [x] Revisión y documentación del archivo: RegistrologinFacade.java
- [x] JRevisión y documentación del archivo: avaBeansLogin.java

**Comment by KmiArthur** [comment]
Distribución de trabajo con Jaime:

- [ ] Revisión y documentación del archivo: Fin.js
- [ ] Revisión y documentación del archivo: InvitarAmigos.js
- [ ] Revisión y documentación del archivo: PerfilJugador.js
- [ ] Revisión y documentación del archivo: Logros.js
- [ ] Revisión y documentación del archivo: Personajes.js
- [ ] Revisión y documentación del archivo: CompraPersonajes.js
- [ ] Revisión y documentación del archivo: Rankings.js
- [ ] Revisión y documentación del archivo: funcionesBatalla.js
- [ ] Revisión y documentación del archivo: Boot.js
- [ ] Revisión y documentación del archivo: PruebasPsicotecnicas.js
- [ ] Revisión y documentación del archivo: Box.js
- [ ] Revisión y documentación del archivo: Código JSP
- [ ] Revisión y documentación del archivo: Login.jsp
- [ ] Revisión y documentación del archivo: Forgot.jsp
- [ ] Revisión y documentación del archivo: Registro.jsp
- [ ] Revisión y documentación del archivo: Código CSS
- [ ] Revisión y documentación del archivo: bloqueMoviles.css
- [ ] Revisión y documentación del archivo: RegistroLogin.java
- [ ] Revisión y documentación del archivo: AbstractFacade.java
- [ ] Revisión y documentación del archivo: RegistrologinFacade.java
- [ ] JRevisión y documentación del archivo: avaBeansLogin.java

**Comment by CamilaG08** [comment]
Dado que aún falta mucho, se da plazo hasta el lunes 22 de mayo para completar la tarea, no se realiza nueva asignación hasta finalizar esta.

**Comment by CamilaG08** [comment]
Se cierra el Issue a pesar de no ser completado ya que se cumple el plazo. Sin embargo la tarea se puede continuar en el Issue #641
