### ISSUE TITLE
5.14 Investigación de saltos de personajes en batalla

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#593]
**Descripción**

Realizar un documento detallado de cómo se manejan los saltos en Phaser.

**TAREAS:**

- [x] Revisar la documentación de Phaser para conocer la función de gravedad
- [x] Realizar un documento detallado de cómo manipular dicha función o si es necesario la creación de sprites
- [x] Subir el documento al repositorio

**Comment by KmiArthur** [comment]
**Función Saltar:**

Capacidad de saltar. El cursor ascendente es nuestra clave de salto y probamos si está abajo. Sin embargo, también probamos si el jugador está tocando el piso, de lo contrario podrían saltar mientras están en el aire. Comprobamos la variable `hitPlatform` sólo para asegurarnos de que el jugador realmente chocó con el piso, y no otra cosa.

Si se cumplen estas dos condiciones, aplicamos una velocidad vertical de 350 px / seg sq. El jugador caerá al suelo automáticamente debido al **valor de gravedad** que le aplicamos.  [Fuente](https://phaser.io/tutorials/making-your-first-phaser-game/part6)

-----
**Fue implementado por @nicolas96**

**Comment by CamilaG08** [comment]
Se cierra el Issue debido a que se realiza la investigación @KmiArthur  y avances en la implementación por @nicolas96
