### ISSUE TITLE
5.15 Manual del desarrollador

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#594]
**Descripción**
Realizar Manual del desarrollador.

**Tareas a realizar**
- [x] Portada del manual.
- [x] Tabla de contenido.
- [x] Introducción.
- [x] Glosario.
- [x] Cuerpo del manual (el cuerpo del manual debe contener imágenes y descripción).

**Comment by gabogabbs** [comment]
Se crea la primera versión del Manual de Desarrollador con las siguientes secciones:
- Portada del Manual. (Realizada por @KmiArthur).
- Barra de navegación con los contenidos del Manual.
- Introducción al Manual.
- Sección programación.

REGISTRO DE TIEMPO: 3 horas.

**Comment by gabogabbs** [comment]
El día miércoles 17 de mayo se realiza el cuerpo del Glosario con los términos en clase.

REGISTRO DE TIEMPO: 1 hora y 30 minutos.

**Comment by gabogabbs** [comment]
Se realiza una reunión con @CamilaG08 para revisar el avance realizado en el Manual de desarrollador además de que se verifica que ajustes hacen falta en la navegabilidad del juego (#594). 

REGISTRO DE TIEMPO: 30 minutos.

**Comment by gabogabbs** [comment]
Se añaden las definiciones de los términos del Glosario.

REGISTRO DE TIEMPO: 40 minutos.

**Comment by gabogabbs** [comment]
Se añaden 5 términos al Glosario y se crea el cuerpo del manual.
Se da como concluido el issue.

REGISTRO DE TIEMPO: 2 horas y 30 minutos.

**Comment by CamilaG08** [comment]
Se cierra la tarea dado que se entrega lo pedido anteriormente.
