### ISSUE TITLE
8.2.3 Revisión entregas Sprint 13.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#596]
**Descripción**
Revisar cada una de las entregas del Sprint 13, el contenido, es decir la parte funcional de la entrega.

**Tareas a realizar**
- [x] Revisar cada una de las entregas del Sprint 13, el contenido, es decir la parte funcional de la entrega.
- [x] Realizar un documento resumen de está entrega. Preguntar especificaciones documento @DiegOliveros

**Comment by ivandav** [comment]
# Revisión contenido funcional Sprint 13
[Reporte_contenido_funcional_Sprint13.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/1013355/Reporte_contenido_funcional_Sprint13.docx)
