### ISSUE TITLE
1.1.50 Instrucciones nivel 1.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#597]
**Descripción**
Instrucciones nivel 1. ¿Cómo jugar la batalla? Web y móvil.

**Tareas a realizar**
- [x] Realizar Mockups de ¿cómo jugar en web?
- [x] Realizar Mockups de ¿cómo jugar en móvil?
- [x] Implementar Instrucciones en el juego web.
- [x] Implementar Instrucciones en el juego móvil.

**Comment by ivandav** [comment]
# Mockups como jugar en web
![mockuptuto1](https://cloud.githubusercontent.com/assets/22629584/26174688/d160c466-3b15-11e7-9239-7448041941f7.png)
![mockuptuto2](https://cloud.githubusercontent.com/assets/22629584/26174687/d160662e-3b15-11e7-9a30-764cef04c7e3.png)
![mockuptuto3](https://cloud.githubusercontent.com/assets/22629584/26174690/d164e96a-3b15-11e7-9507-726e1aeff15f.png)
![mockuptuto4](https://cloud.githubusercontent.com/assets/22629584/26174691/d1677d88-3b15-11e7-9b9c-85ab59329e1e.png)
![mockuptuto5](https://cloud.githubusercontent.com/assets/22629584/26174689/d1630c76-3b15-11e7-99d4-894c9818bc30.png)
![mockuptuto6](https://cloud.githubusercontent.com/assets/22629584/26174692/d16d3ea8-3b15-11e7-962c-28a1c783bc96.png)

**Comment by ivandav** [comment]
# Mockups como jugar en moviles
![moviles1](https://cloud.githubusercontent.com/assets/22629584/26174769/10742d5a-3b16-11e7-9518-fa8ce5fa4b91.png)
![moviles2](https://cloud.githubusercontent.com/assets/22629584/26174768/1073d544-3b16-11e7-836f-f383b6345433.png)
![moviles3](https://cloud.githubusercontent.com/assets/22629584/26174771/107abab2-3b16-11e7-9e20-11ec100dfb6f.png)
![moviles4](https://cloud.githubusercontent.com/assets/22629584/26174770/1074cdbe-3b16-11e7-8865-36d2a530fbee.png)

**Comment by ivandav** [comment]
# Pruebas del tutorial funcional
![prueba](https://cloud.githubusercontent.com/assets/22629584/26232838/a78d22b0-3c1e-11e7-9639-b8ea3d738f02.png)
![tuto1](https://cloud.githubusercontent.com/assets/22629584/26232840/a78ff670-3c1e-11e7-887a-f6ad0fa9c350.png)
![tuto2](https://cloud.githubusercontent.com/assets/22629584/26232837/a78cac2c-3c1e-11e7-9256-e536f51af526.png)
![tuto3](https://cloud.githubusercontent.com/assets/22629584/26232835/a78b7b40-3c1e-11e7-99f1-ab8c6a5f6849.png)
![tuto4](https://cloud.githubusercontent.com/assets/22629584/26232836/a78c5a10-3c1e-11e7-8319-7cee5a02cedc.png)
![tuto5](https://cloud.githubusercontent.com/assets/22629584/26232839/a78e0784-3c1e-11e7-8f78-737c817b8261.png)
![tuto6](https://cloud.githubusercontent.com/assets/22629584/26232841/a79ce790-3c1e-11e7-85d8-832817905094.png)

**Comment by ivandav** [comment]
# Tutorial en móviles
El tutorial para móviles no se realiza debido a que se observa que falta implementar algunas acciones que el juego en web si tiene, por ejemplo en móviles el personaje no salta, tampoco activa los  dos escudos; por ende se espera que se realicen estas acciones para hacer su correspondiente tutorial.
