### ISSUE TITLE
5.7.5 PITCH/Diapositivas

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#598]
**Descripción**
PITCH para la presentación del viernes 19 de Mayo.

**Tareas a realizar**
- [x] Listar tareas a realizar. @CamilaG08 @jrsosago
- [x] Definir temas a tratar
- [x] Crear el PITCH
- [x] Crear diapositivas
- [x] Revisión del PITCH y diapositivas con @DiegOliveros y @jolarter 
- [x] Realizar correcciones necesarias

**Comment by CamilaG08** [comment]
Se definen los siguientes temas por mi parte con espera de aprobación de @jrsosago : 

- Interacción con el público para llamar su atención (Contexto)
- Presentación del equipo
- Descripción de la metodología
- Funcionalidad del juego (Mostrar tutorial mejorado)
- Mostrar el juego en el servidor

**Comment by jrsosago** [comment]
Estoy de acuerdo con los temas propuestos por @CamilaG08.

**Comment by jrsosago** [comment]
Se realiza adelanto de PITCH y diapositivas con @CamilaG08. **Tiempo empleado: 1 hora y 30 minutos**

**Comment by jrsosago** [comment]
Se comparte PITCH y diapositivas a los correos de los profesores.

**Comment by jrsosago** [comment]
Se realiza reunión en compañía de @CamilaG08, con los profesores Diego Oliveros y Julián Olarte para presentar PITCH y diapositivas en la clase del miércoles. En está reunión también se hace una revisión de la funcionalidad del juego por parte de los profesores.

**Comment by CamilaG08** [comment]
Se realizan cambios con @jrsosago sobre el PITCH y las diapositivas según las sugerencias previas.
