### ISSUE TITLE
10 TIPOS DE PLAGIO

### ISSUE THREAD

**Issue by ingenieriadelsoftware** [ISWPOLI/Pacto-de-Honor#6]

**Comment by CamilaG08** [comment]
El estudiante Wilmer Ricardo también hace parte de nuestro grupo. Su usuario es Richard Cas7ro.

**Comment by ingenieriadelsoftware** [comment]
Hola Camilla puedes por favor agregarlo, tienes permiso de edición.


Saludos,


Diego Iván Oliveros Acosta <mailto:dolivero@poligran.edu.co>

**Comment by CamilaG08** [comment]
https://docs.google.com/document/d/1AC5tztp0d4KDGZ37oyFyKgTktMqPDulrWFsLUTPCgFI/edit?usp=sharing
