### ISSUE TITLE
1.1.51 Navegabilidad del Juego

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#600]
**Descripción**
Revisar y mejorar navegabilidad del Juego.

**Tareas a realizar**
- [x] Poner indicador de Scroll en la selección de avatar.
- [x] Poner indicador de Scroll en la compra de personajes.
- [x] Poner indicador de Scroll en las cajas sorpresa.
- [x] Poner indicador de Scroll en los logros.
- [x] Hacer la selección de avatar funcional.
- [x] Corregir caracteres con tildes y ñ de variables y archivos.
- [ ] Consumir servicios del módulo de batalla basado en el Issue #483 y en lo realizado por @nicolas96

**Comment by gabogabbs** [comment]
Se modifica la selección de avatar para que sea funcional. El avatar seleccionado se puede ver en el Perfil de Jugador.

REGISTRO DE TIEMPO: 1 hora.

**Comment by gabogabbs** [comment]
Se implementa un indicador de Scroll para los siguientes estados:
- Selección de avatar.
- Cajas sorpresa.
- Logros.
- Compra de personajes.

REGISTRO DE TIEMPO: 1 hora.

**Comment by CamilaG08** [comment]
Revisar este documento dejado por @nicolas96 : 

[Mejoras del juego.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/1006098/Mejoras.del.juego.docx)

**Comment by gabogabbs** [comment]
El día miércoles 17 de mayo se realiza corrección de caracteres 'ñ' y tildes de todos los módulos  y carpetas de assets para evitar conflictos con los datos de backend.

REGISTRO DE TIEMPO: 1 hora.

**Comment by gabogabbs** [comment]
Ya que la tarea de consumir el servicio de batalla no se puede realizar, se sugiere cerrar este issue para abrir uno en el siguiente sprint específico para los servicios.

**Comment by CamilaG08** [comment]
Se cierra la tarea siguiendo la recomendación, y teniendo en cuenta que queda pendiente.
