### ISSUE TITLE
7.4 Re - estructuración del Login

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#601]
**Descripción**

Re - estructurar el login para finalizar su funcionalidad.

**TAREAS:**

- [x] Reunión con @ivandav y @dayepesb 
- [x] Implementar el login consumiendo el servicio necesario
- [x] Integrar el login con el juego y el perfil de cada jugador

**Comment by jrsosago** [comment]
Por acuerdo de @gsalvarez y @ivandav se cambia la asignación de @gsalvarez por @ivandav

**Comment by jrsosago** [comment]
Desde el Sprint 14 está Issue se realiza por parte de @dayepesb

**Comment by dayepesb** [comment]
Se hizo la integración y el correcto funcionamiento del login con el juego

**Comment by CamilaG08** [comment]
Se cierra el Issue dado que se realizan las tareas satisfactoriamente.
