### ISSUE TITLE
1.1.52 Caricaturizar escenarios

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#609]
**Descripción**

Caricaturizar los escenarios.

**TAREAS:**

- [x] Pedir escenarios a @gsalvarez 
- [x] Caricaturizar los escenarios
- [x] Presentarlos para revisión

**Comment by gabogabbs** [comment]
Los escenarios se encuentran en la rama master, en la carpeta "img/escenarios" https://github.com/ISWPOLI/Pacto-de-Honor/tree/master/FRONTEND/juego/img/escenarios

**Comment by jrsosago** [comment]
No se asignan más Issues hasta que se terminen todas las tareas de está.

**Comment by jrsosago** [comment]
Se cierra está Issue por actividades terminadas.
