### ISSUE TITLE
5.16 Tutorial actualizado

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#624]
**Descripción:**

Realizar una versión actualizada del tutorial ya existente.

**TAREAS:**

- [x] Hablar con @gsalvarez y @nicolas96 sobre cambios realizados.
- [x] Realizar la segunda versión del tutorial.

**Comment by KmiArthur** [comment]
**[Video tutorial](https://youtu.be/qRSEK9a8J3g)** con nuevas correcciones sugeridas.

`https://youtu.be/qRSEK9a8J3g`

**Comment by CamilaG08** [comment]
Se cierra la tarea debido a que se entrega el producto satisfactoriamente.
