### ISSUE TITLE
1.1.53 Cambiar nivel del jugador después de ganar una batalla o nivel

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#639]
**Descripción**
Cambiar nivel del jugador después de ganar una batalla o nivel.

**Tareas a realizar**
- [x] Cambiar nivel por jugador.
- [x] Cambiar nivel por cada personaje.

**Comment by gabogabbs** [comment]
Se añade la función para verificar el nivel del Jugador dependiendo de los puntos de experiencia que tenga.
Esta verificación al iniciar el juego y al terminar una batalla.

REGISTRO DE TIEMPO: 1 hora y 30 minutos.

**Comment by gabogabbs** [comment]
Se implementa una función al inicio del juego para verificar el nivel de los personajes que tiene el jugador.
También se implementa el código necesario para subir la experiencia del personaje al finalizar una batalla.
Se da como concluido este issue.

REGISTRO DE TIEMPO: 1 hora y 30 minutos.
