### ISSUE TITLE
8.2.3 Revisión entregas Sprint 14.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#642]
**Descripción**
Revisar cada una de las entregas del Sprint 14, el contenido, es decir la parte funcional de la entrega.

**Tareas a realizar:**
- [x] Revisar cada una de las entregas del Sprint 14, el contenido, es decir la parte funcional de la entrega.
- [x] Realizar un documento resumen de está entrega. Preguntar especificaciones documento @DiegOliveros

**Comment by ivandav** [comment]
# Documento
[Reporte_contenido_funcional_Sprint14.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/1029832/Reporte_contenido_funcional_Sprint14.docx)
