### ISSUE TITLE
7.5.1 Login GMAIL

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#644]
**Descripción:**

Realizar el login funcional con GMAIL.

**TAREAS:**
- [x] Revisar Issue #474 
- [ ] Realizar el login funcional con GMAIL
- [ ] Realizar pruebas

**Comment by juankrlos08** [comment]
![image](https://cloud.githubusercontent.com/assets/25808382/26481801/1a791088-41a9-11e7-9af3-c17306c4fda9.png)

![image](https://cloud.githubusercontent.com/assets/25808382/26481807/1e706cfe-41a9-11e7-9861-39c491efc829.png)

![image](https://cloud.githubusercontent.com/assets/25808382/26481815/2451d658-41a9-11e7-9fa3-4921eda90c9d.png)

![image](https://cloud.githubusercontent.com/assets/25808382/26481818/285b5b70-41a9-11e7-9659-dc93cc6c9e45.png)
![image](https://cloud.githubusercontent.com/assets/25808382/26481825/30ff5754-41a9-11e7-9e07-75898762e695.png)

![image](https://cloud.githubusercontent.com/assets/25808382/26481831/3810426a-41a9-11e7-9c31-15cec3791146.png)

![image](https://cloud.githubusercontent.com/assets/25808382/26481838/422f9714-41a9-11e7-83ee-8044c522f233.png)

**Comment by juankrlos08** [comment]
[IMPLEMENTACION DE BOTON GOOGLE.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/1033611/IMPLEMENTACION.DE.BOTON.GOOGLE.pdf)

**Comment by juankrlos08** [comment]
Queda pendiente el funcionamiento del boton de google. y en las credenciales del id del cliente pide el nombre del manifiesto que fue suministrado por Gabriel y con el codigo $ keytool -list -v -keystore mystore.keystore generaria una huella digital que se requiere dentro el id cliente del apk que fue creado pero no genera ningun codigo.

**Comment by jrsosago** [comment]
Se cierra está Issue debido a que se terminan los Sprint, queda pendiente algunas tareas de está Issue que se relacionan en la parte anterior a este comentario.
