### ISSUE TITLE
1.1.54 Sonidos campos de batalla.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#645]
**Descripción**
Sonidos campos de batalla. Está tarea es para ser entregada el día 19 de Mayo.

**Tareas a realizar**
- [x] Poner diferentes sonidos al campo de batalla. (Botón movimiento, ataque especial y puños).

**Comment by ghost** [comment]
Se crearon los nuevos sonidos en batalla y Botón movimiento, ataque especial y puños y se cambiaron algunos sonidos adicionales para el juego
Tiempo gastado: 1 hora 20 min.
