### ISSUE TITLE
8.1.4 Revisar entregas Sprint 14

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#646]
**Descripción:**

Revisar cada una de las entregas del Sprint 14, el contenido, es decir la parte funcional de la entrega.

**TAREAS:**

- [x] Revisar cada una de las entregas del Sprint 14, el contenido, es decir la parte funcional de la entrega.
- [x] Realizar un documento resumen de está entrega. Preguntar especificaciones documento @DiegOliveros

**Comment by jdbernalv** [comment]
Buenas Noches, Se realiza la revisión, documentación y entrega del reporte consolidado al correo del docente Diego Oliveros como fue solicitado. La entrega fue enviada el 25/05/2017 - 20:08. @jrsosago
