### ISSUE TITLE
8.3.1 Registro estadístico de la actividad diaria en informes.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#655]
**Descripción**
Registro estadístico de la actividad diaria de informes Sprint 15.

**Tareas a realizar**
- [x] Documento estadístico de la actividad diaria Sprint 15

**Comment by jdbernalv** [comment]
Buenas Madrugadas, De acuerdo a la solicitud de control de horas Extra-Clase se genera una tabla con las horas registradas por cada estudiante del grupo Practica Aplicada, se genera el siguiente esquema:

- Un reporte en Excel que tiene el reporte de horas detallado con las fechas 02, 09, 12 y 19 de Mayo.
- El reporte cuenta con los campos Fecha, Nombres y Apellidos, Codigo, Inicio, Fin, Interrupción, Observaciones, Trabajo Total y Total Interrupciones que permiten filtrar de acuerdo a la necesidad.
- El reporte totaliza automáticamente sin importar el filtro que se le asigne en los campos Total de Horas (Horas Extra-Clase), Total de Horas (Interrupciones) y Total de Horas (Horas Extra-Clase +                         Interrupciones).  

Por lo anterior, se entrega completamente la tabla al correo del Docente Diego Oliveros. @DiegOliveros @jrsosago
