### ISSUE TITLE
1.1.55 Mejorar la secuencia de cada personaje en cada mundo.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#656]
**Descripción:**
Mejorar la secuencia de cada personaje en cada mundo.

**Tareas a realizar:**
- [x] Mejorar la dificultad del personaje malo y mini-personajes mundo 1.
- [x] Mejorar la dificultad del personaje malo y mini-personajes mundo 2.
- [x] Mejorar la dificultad del personaje malo y mini-personajes mundo 3.
- [x] Mejorar la dificultad del personaje malo y mini-personajes mundo 4.
- [x] Mejorar la dificultad del personaje malo y mini-personajes mundo 5.
- [x] Mejorar la dificultad del personaje malo y mini-personajes mundo 6.
- [x] Mejorar la dificultad del personaje malo y mini-personajes mundo 7.
- [x] Mejorar la dificultad del personaje malo y mini-personajes mundo 8.
- [x] Mejorar la dificultad del personaje malo y mini-personajes mundo 9.
- [x] Mejorar la dificultad del personaje malo y mini-personajes mundo 10.
- [x] Mejorar la dificultad del personaje malo y mini-personajes mundo 11.
- [x] Mejorar la dificultad del personaje malo y mini-personajes mundo 12.

**Comment by gabogabbs** [comment]
Se ajustan las dificultades de todos los enemigos de los mundos. Se da como concluido este issue.

REGISTRO DE TIEMPO: 3 horas.

**Comment by jrsosago** [comment]
Se cierra está Issue por actividades realizadas.
