### ISSUE TITLE
7.5.2 Login Facebook

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#660]
**Descripción:**
Login Facebook.

**Tarea a realizar:**
- [x] Revisar Login Facebook. Usar de base Issue #474.
- [x] Investigar como se puede invitar amigos de Facebook.
- [ ] Implementar función de invitar amigos de Facebook en el juego.

**Comment by CamilaG08** [comment]
Dado que el login se encuentra realizado , se reasignan tareas como realizar la invitación de amigos.

**Comment by CristianGarzonBernal** [comment]
-Se realizo la investigación de invitación de amigos, en donde ya se encuentra el código para implementar en el reporte semanal. 4hrs

**Comment by CristianGarzonBernal** [comment]
Se realiza documento formal donde ese explica lo realizado en la investigación y el código que se debe implementar. 5hrs con el código, investigación y realización del documento.
[Implementación Invitar amigos en Facebook.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/1033612/Implementacion.Invitar.amigos.en.Facebook.pdf)

**Comment by jrsosago** [comment]
Se cierra está Issue, debido a que se acabaron los Sprint, falta implementación para invitar los amigos de Facebook.

**Comment by CristianGarzonBernal** [comment]
- La tarea no se termino por que  recibí el código del login de Facebook mucho después y no estaba en GitHub, era necesario para unirlo con esta tarea, ya que es fundamental que haya iniciada una sesión en Facebook para poder invitar amigos.
