### ISSUE TITLE
1.18 Creación de la aplicación móvil

### ISSUE THREAD

**Issue by CamilaG08** [ISWPOLI/Pacto-de-Honor#661]
**Descripción**

Crear el archivo con extensión .apk que traerá el juego móvil para Android.

**TAREAS:**
- [x] Revisar el documento realizado en el Issue #195 
- [x] Crear un documento con los parámetros necesarios para la aplicación móvil
- [x] Tomar los archivos para versión móvil del juego
- [x] Crear el aplicativo para móvil (Android)

**Comment by juancelemin** [comment]
[apache cordova.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/1030728/apache.cordova.pdf)

**Comment by jrsosago** [comment]
Se cierra está Issue por actividades realizadas.
