### ISSUE TITLE
5.3.7 Reporte reposición de horas

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#662]
**Descripción**
Reporte reposición de horas.

**Tareas a realizar:**
- [x] Reporte reposición de horas individual David Yepes. @CamilaG08 
- [x] Reporte reposición de horas individual Nicolás Martinez. @CamilaG08
- [x] Reporte reposición de horas individual Camilo D'Achardi. @CamilaG08
- [x] Reporte reposición de horas individual Juan Carlos. @CamilaG08
- [x] Reporte reposición de horas individual Juan Guillermo. @CamilaG08
- [x] Reporte reposición de horas individual Jeimy. @CamilaG08 
- [x] Reporte reposición de horas individual Dario. @jrsosago
- [x] Reporte reposición de horas individual Iván. @jrsosago
- [x] Reporte reposición de horas individual Juan Sebastián. @jrsosago
- [x] Reporte reposición de horas individual Cristian. @jrsosago
- [x] Reporte reposición de horas individual Gabriel. @jrsosago
- [x] Reporte reposición de horas individual Jaime. @jrsosago
- [x] Reporte reposición de horas individual Camila. @jrsosago

**Comment by CamilaG08** [comment]
Camilo, Juan Carlos y Juan Guillermo no han pedido tareas para reponer horas.

**Comment by CamilaG08** [comment]
![image](https://cloud.githubusercontent.com/assets/22283896/26385839/f9df6612-4007-11e7-9a29-abe1690c303e.png)


Se adjunta la imgen del reporte enviado a @DiegOliveros

**Comment by jrsosago** [comment]
Jaime, no nos a pedido a Camila ni a mi horas a reponer.

**Comment by jrsosago** [comment]
![image](https://cloud.githubusercontent.com/assets/22827594/26386993/f1f5ceb6-400f-11e7-83e2-c879f9cf3d59.png)

Se adjunta la imagen del reporte enviado a el profesor @DiegOliveros **Tiempo empleado: 1 hora y 26 minutos**

**Comment by CamilaG08** [comment]
Se consolida un sólo formato y se adjunta el pantallazo del correo enviado a @DiegOliveros y @jrsosago .

<img width="1064" alt="captura de pantalla 2017-05-24 a las 8 33 22 p m" src="https://cloud.githubusercontent.com/assets/22283896/26432313/7c4f32f4-40c0-11e7-9788-fd51ab913ebd.png">

**Comment by CamilaG08** [comment]
Se cierra el Issue dado que se realizan las tareas correspondientes.
