### ISSUE TITLE
1.1.56 Tutorial del juego para móvil

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#682]
**Descripción**
Tutorial del juego para móvil 

**Tareas a realizar:**
- [x] Realizar tutorial para la batalla nivel 1

**Comment by ivandav** [comment]
# Tutorial para móviles
![moviles](https://cloud.githubusercontent.com/assets/22629584/26480069/57493fa8-419d-11e7-9759-e89687faa1fa.png)
