### ISSUE TITLE
1.1.57 Creación de la aplicación móvil

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#689]
**Descripción**
Está tarea es de apoyo para la issue #661.

**Tareas a realizar**
- [x] Generar proyecto Cordova.
- [ ] Corregir conflictos en Android Studio.
- [x] Añadir nuevo código del repositorio.
- [x] Generar apk.

**Comment by gabogabbs** [comment]
Se utiliza Cordova para generar el apk del juego. Se corrigen errores dentro del proyecto de Android Studio. 
REGISTRO DE TIEMPO: 2 horas.

**Comment by gabogabbs** [comment]
Se corrigen rutas de imágenes y archivos, se añaden las funciones que fueron subidas al repositorio durante el día jueves. 

REGISTRO DE TIEMPO: 1 hora.

**Comment by gabogabbs** [comment]
Se comentaron las líneas de los códigos alfanuméricos ya que no se pudo corregir un conflicto. Se sube el apk al repositorio.

**Comment by jrsosago** [comment]
Se cierra está Issue por actividades completas.
