### ISSUE TITLE
COMBATE

### ISSUE THREAD

**Issue by ingenieriadelsoftware** [ISWPOLI/Pacto-de-Honor#8]

**Comment by jrsosago** [comment]
Poderes personajes y Combate:
Personaje Tati la Hormiga: Tati, tiene el poder de arrojar partes de un trabajo

**Comment by DiegOliveros** [comment]
Cuál es la justificación para cerrar esta Epica?
la única condición debe ser que todas las características estén realizadas

**Comment by jrsosago** [comment]
Se cierra, está Issue, ya que es antigua y ya existen Issues nuevas y una característica para la Batalla.
