### ISSUE TITLE
4.1.2 Sprites Personajes buenos y Poderes

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#80]

**Comment by gabogabbs** [comment]
Se realizaron modificaciones en los sprites (frames de especial) de Daniel León y Daniela Jirafa. 
[ModificacionSpritesLeonJirafaPorGabriel.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/795421/ModificacionSpritesLeonJirafaPorGabriel.zip)

REGISTRO DE TIEMPO: 3 HORAS.

**Comment by gabogabbs** [comment]
Se realizaron las modificaciones en los frames del Especial de cada sprite para cada uno de los personajes correspondientes. 
[ModificacionEspeciales.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/800380/ModificacionEspeciales.zip)

REGISTRO DE TIEMPO: 3 HORAS.
