### ISSUE TITLE
4.2.1 Sprites personajes malos y poderes

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#81]
## SPRITES PERSONAJES:

- [x] Sprite para Andrés Zorro
- [x] Sprite para Felipe Oso
- [x] Sprite para Carlos Buitre
- [x] Sprite para Luis Víbora
- [x] Sprite para Camilo Perezoso
- [x] Sprite para Nicolás Lagarto
- [x] Sprite para Víctor Hiena

**Comment by KmiArthur** [comment]
# Adelanto de **Sprites** realizado en clase del miércoles 22 feb:

![victor hiena](https://cloud.githubusercontent.com/assets/17441569/23242483/05f41fae-f947-11e6-9094-ba2676774d35.png)
![stock-vector-cartoon-monkey-sprites-vector-clip-art-illustration-with-simple-gradients-each-element-on-a-330024107](https://cloud.githubusercontent.com/assets/17441569/23242488/060b0b42-f947-11e6-915e-bdb85390cb44.png)
![nicolas lagarto](https://cloud.githubusercontent.com/assets/17441569/23242485/05f8435e-f947-11e6-81d5-718643fe8227.png)
![main_character_preview1](https://cloud.githubusercontent.com/assets/17441569/23242487/060607d2-f947-11e6-8464-99c87122b69e.png)
![mage_skill](https://cloud.githubusercontent.com/assets/17441569/23242486/0605428e-f947-11e6-8002-4ca072fcfbc7.png)
![luis vibora](https://cloud.githubusercontent.com/assets/17441569/23242484/05f7f250-f947-11e6-93a9-4623386f3955.png)
![depositphotos_111536162-stock-illustration-cartoon-squirrel-sprites](https://cloud.githubusercontent.com/assets/17441569/23242490/06118ed6-f947-11e6-96d3-9331fec14b4a.png)
![depositphotos_97242904-stock-illustration-thief-boy-game-sprites](https://cloud.githubusercontent.com/assets/17441569/23242489/060fee96-f947-11e6-9b47-a3c13a1d0928.png)
![depositphotos_42403599-stock-illustration-running-cat-animation-sprite](https://cloud.githubusercontent.com/assets/17441569/23242491/0612b950-f947-11e6-9fac-469e9da0da5b.png)
![carlos buitre](https://cloud.githubusercontent.com/assets/17441569/23242492/061e972a-f947-11e6-8edc-57b36dfea5b6.png)
![55aaae787ff8c2031ccf0b95d138a91f](https://cloud.githubusercontent.com/assets/17441569/23242493/061fb8da-f947-11e6-81c1-f1924581ef87.png)
![46976191-sprites-game-boy-geeky-de-desplazamiento-lateral-de-acci-n-y-aventura-corredor-sin-fin-de-juegos-m-v-foto-de-archivo](https://cloud.githubusercontent.com/assets/17441569/23242494/06240d72-f947-11e6-82bd-0a1aa963b7f6.png)
![camilo perezoso](https://cloud.githubusercontent.com/assets/17441569/23242495/0629de3c-f947-11e6-8a03-cb949497c94b.png)
![captura de pantalla 2017-02-22 a las 9 30 52 p m](https://cloud.githubusercontent.com/assets/17441569/23242496/062aabaa-f947-11e6-8352-721f5653fc88.png)
![captura de pantalla 2017-02-22 a las 9 30 58 p m](https://cloud.githubusercontent.com/assets/17441569/23242497/062bc5c6-f947-11e6-8896-489652cfa47c.png)
![buitre](https://cloud.githubusercontent.com/assets/17441569/23242670/1f5f2c3a-f948-11e6-8b08-ff1bbaf88d0d.png)

**Comment by KmiArthur** [comment]
### SPRITES PERSONAJES **(7H-CASA)**:

Adjunto archivo ZIP con todas las variables e imágenes: [Sprites.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/800918/Sprites.zip)
