### ISSUE TITLE
4.2.1 Sprites personajes malos y poderes

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#82]

**Comment by ghost** [comment]
Se realiza los sprites de Victor Hiena, Fabian Babuino, Julian Burro, Juan Camaleon, Juan Rata, Ana Abeja, Sara Abeja e Ivan Ruiseñor. 

- [x] Sprite para Víctor Hiena
- [x] Sprite para Fabián Babuino
- [x] Sprite para Julián Burro
- [x] Sprite para Juan Camaleón
- [x] Sprite para Juan Rata
- [x] Sprite para Ana Abeja
- [x] Sprite para Sara Abeja
- [x] Sprite para Iván Ruiseñor


Duración: 5 horas 20 minutos.
[Sprites.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/800987/Sprites.zip)
