### ISSUE TITLE
1.2.1 Mockups selección personaje e implementación

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#85]
**Tareas a Realizar:**
- [x] Mockup selección personaje.
- [x] Implementación selección personaje.

**Comment by nmartinezmarin** [comment]
Historia de la tarea
[MOCK.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/795427/MOCK.docx)

Primer diseño 
[Modelo de Mock ups Seleccion de Avatars.pptx](https://github.com/ISWPOLI/Pacto-de-Honor/files/795434/Modelo.de.Mock.ups.Seleccion.de.Avatars.pptx)

**Comment by jrsosago** [comment]
No se evidencia realización de trabajo desde el miércoles hasta hoy 25 febrero

**Comment by nmartinezmarin** [comment]
Mock up de la seleccion de avatar

[Web.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/807274/Web.zip)

Tiempo Registrado:5 horas

**Comment by nmartinezmarin** [comment]
[Web.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/809968/Web.zip)
Corrección de vista de las imágenes y menú desplegable

Tiempo registrado:1 hora 30 minutos
