### ISSUE TITLE
1.1.7 Nombre, logo y tipo de letra juego.

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#86]
**Tareas a Realizar**
- [x] Asignar nombre al juego.
- [x] Escudo del juego.
- [x] Tipo de letra que se utilizarán en el juego.
- [x] Subir el tipo de letra.

**Comment by ghost** [comment]
## Registro Total de tiempo: 1 hora

## 1. Tipo de Letra a Usar: (Registro de tiempo: 15 minutos)

- Para todo el juego se usará "Roboto" como tipo de letra.
- Se usará color blanco para el encabezado de cada pantalla (Login, Registro, Creditos, Selección de personaje, Ranking) y para el texto de los botones.
- Se usará color negro para el texto que no sea encabezado (Dialogos, Indicador de nivel, Contenido de lo creditos, Usuarios del ranking).
- Se usará color rojo para el texto que este seleccionado (Un escenario en especifico, un usuario en especifico del ranking).

## 2. Nombre del Juego: (Registro de tiempo: 15 minutos)

- Poli Fighters.

## 3. Logo del Juego: (Registro de tiempo: 30 minutos)

![l3](https://cloud.githubusercontent.com/assets/22629833/23315985/a7c62cfa-fa96-11e6-814c-f1b774a11405.png)

**Comment by ghost** [comment]
### En el siguiente enlace se encuentra el tipo de letra:
https://fonts.google.com/selection?selection.family=Roboto
