### ISSUE TITLE
1.1.2 Mockups mapa y segundo mundo

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#88]
**Descripción:**
Mockups de mapa entrando al segundo mundo, sus niveles y la batalla final.
**Tareas a realizar:**
- [x] Mockup mapa entrando al segundo mundo.
- [x] Mockup mapa del segundo mundo (niveles y batalla final).
- [x] Mockup de cada nivel (4 en total).
- [x] Mockup batalla final (escenario y personaje correspondiente a el mundo 2)

**Comment by jrsosago** [comment]
Tarea que había sido asignada para el día 25 de febrero y no se entrego.

**Comment by ivandav** [comment]
MOCKUPS PROGRAMADOS DE MAPA, SELECCION MUNDO 2, 4 BATALLAS Y BATALLA FINAL.
Estimacion de tiempo: 5 horas
![batalla1](https://cloud.githubusercontent.com/assets/22629584/23594689/d2a0eca8-01e9-11e7-873f-b7ea21654dad.png)
![batalla2](https://cloud.githubusercontent.com/assets/22629584/23594688/d2a0836c-01e9-11e7-9de5-0a079bbc2e8d.png)
![batalla3](https://cloud.githubusercontent.com/assets/22629584/23594690/d2a122d6-01e9-11e7-8929-f24e2f06da1a.png)
![batalla4](https://cloud.githubusercontent.com/assets/22629584/23594691/d2bf7d26-01e9-11e7-9908-cd00faaca846.png)
![batallafinal](https://cloud.githubusercontent.com/assets/22629584/23594693/d2cb0d3a-01e9-11e7-8c3d-db5b912314ff.png)
![mapa niveles](https://cloud.githubusercontent.com/assets/22629584/23594692/d2c99b26-01e9-11e7-9800-0535d6fe4218.png)
![mapa programado](https://cloud.githubusercontent.com/assets/22629584/23594694/d2d47bea-01e9-11e7-95c1-0822342bce42.png)
