### ISSUE TITLE
5.1.3 Propuestas para incluir los 10 tipos de plagio

### ISSUE THREAD

**Issue by ingenieriadelsoftware** [ISWPOLI/Pacto-de-Honor#9]
**Elaborar documento**
Crear un documento compartido que contenga ideas de cómo integrar los 10 tipos de plagio al juego

**TAREAS**
- [x] Camila Crear el documento compartido
- [x] Camila Asignar responsabilidades dentro del documento
- [x] Nicolás Ideas de asignación para los primeros 3 tipos de plagio
- [x] Camilo Ideas de asignación para los segundos 3 tipos de plagio
- [x] Camila Ideas de asignación para los últimos 4 tipos de plagio
- [x] Ricardo Revisar el documento existente y complementar con ideas sobre la integración de los 10 tipos de plagio

**Comment by CamilaG08** [comment]
https://docs.google.com/document/d/1AC5tztp0d4KDGZ37oyFyKgTktMqPDulrWFsLUTPCgFI/edit

**Comment by CamilaG08** [comment]
Repartir los 10 tipos de plagio en 3 grupos de la siguiente forma:

Nicolás: Primer grupo de 3 
Camilo: Segundo grupo de 3
Camila: Tercer grupo de 4
Ricardo: Complementar el documento con ideas de integración

**Comment by CamilaG08** [comment]
**Mosaico**

Ana y Sara Abeja/Camilo Perezoso: Logran clonar los poderes de sus enemigos, una vez en su poder, logran mezclarlos y crear combos poderosos.

**Error 404**

Felipe Oso/Andrés Zorro: Al quedarse sin vida, puede tomarla de una fuente inexistente y misteriosa que lo restaura por completo.

**Fuente RSS**

Julián Burro/Carlos Buitre: Lee los poderes de sus enemigos y se encarga de copiarlos CASI a la perfección, gritando el nombre de a quién le copió el poder al lanzarlo.

**Reutilización**

Nicolás Lagarto/Juan Rata: Lee los poderes de sus enemigos y se encarga de copiarlos CASI a la perfección, gritando el nombre de a quién le copió el poder al lanzarlo, pero a diferencia de Julián Burro, también toma el equipamiento y el rostro de sus enemigos.


- Después de ciertos niveles, permitir a los jugadores copiar personajes de sus amigos, teniendo en cuenta los diferentes tipos de plagio (Copiar completamente, copiar pero dejar claro quién fue la fuente, copiar pero tomar o cambiar algunas habilidades, sólo tomar algunas habilidades...)

**Comment by KmiArthur** [comment]
**Remix**
Ana y Sara Abeja: Éstas dos fieles compañeras, andan revoloteando sobre sus amigos y enemigos, aprovechando lo pequeñas que se pueden convertir, sin importar lo que necesiten, usan sus ojos especiales para obtener información de todo lo que puedan y así unir todo para cumplir sus objetivos finales.

**Reciclado**
Juan Rata: Aprovechando los negocios que hace Juan Rata vendiendo los exámenes que él ya ha presentado, usa grandes pedazos información que él ya tiene para crear nuevos trabajos y exámenes sin que nadie lo note. 

**Híbrido**
Juan Camaleón / Ana y Sara Abeja: Usando los ojos de Juan Camaleón que tienen la capacidad de ver a todos lados, se monta en los hombros de sus enemigos para obtener la información que necesite, a diferencia que el ojo derecho siempre se acuerda de quién toma la información para tenerlo en cuenta, y el ojo izquierdo nunca sabe de dónde saca la información. Ana Abeja es parecido al ojo derecho de Juan, ya que ella siempre le toma foto a la persona de quien está tomando la información, pero Sara solo toma foto a la información y nunca sabe de dónde la sacó, y juntas hacen una mezcla terrible en el momento de hacer un trabajo, puesto que no todo en el trabajo está citado.

**Comment by Richardcas7ro** [comment]
. Involucrar a los profesores en el juego, para ello a final de cada semana el profesor tendrá la potestad de evaluar a los estudiantes de acuerdo a su comportamiento (actos teniendo en cuenta los 10 tipos de plagio) y los estudiantes que el considere que se lo merece le dará ya sea un bonus, puntos, subida de nivel en el juego, esto de una forma incentivaría a los estudiantes a no cometer ningún tipo de plagio para así llegar a obtener esta recompensa.
.Ofrecerle a cada jugador sin que él se dé cuenta una opción de hacer “trampa “en el juego al final de cada nivel (que sería la batalla contra el jefe) que podría ser una manera de derrotarlo fácilmente pero haciendo trampa y que este tenga una consecuencia más adelante en el juego que sería pérdida de puntos, perdida de nivel, retención de monedas.
.Agregador:  Víctor Hiena logra agregar a sus poderes habilidades  de sus contrincantes de manera legal, pero gasta su opción de tener un poder original así al momento de enfrentar a un jefe el cual esquive todas sus habilidades copiadas , la única opción es derrotarlo con un poder original pero él no lo tiene así que pierde.

.Para usar los poderes cada jugador podría tener un pequeño tutorial de cómo usarlos como Felipe el Oso copia la tarea y no supo que responder podríamos incluirlo, de que copien los poderes de los demás pero no sepan cómo usarlos (en este caso no se los permitiríamos usar)
Así no sabrían que hacer y esto sería inútil.


.En la mayoría de juegos se busca que los jugadores gasten sus monedas ya sea para pasar un nivelo algo así en el nuestro no podríamos darles la opción de que las monedas solo sean para comprar armadura o trajes de batalla pero al mismo tiempo les podríamos dar la opción de que utilicen las monedas para saltarse un nivel ya que Julián Burro compra los parciales podríamos decir que puede comprar niveles, pero como en cada nivel sería un aprendizaje se estaría saltando la oportunidad de ganar una habilidad, monedas, o subida de nivel así que perdería y podríamos penalizarlo.

**Comment by nmartinezmarin** [comment]
### Clonación
Felipe Oso/  : como felipe el oso tiene pereza de pelear crea copias malvadas de los personajes contra los que lucha.

### Copia y pegado
Julian burro/Nicolás Lagarto: Como solo cambian pequeños detalles envían  secuaces con cuerpos desconocidos pero con los mismos rostros de los personajes a los que enfrentan.

### Búsqueda y reemplazo
Juan Rata/ Victor Hiena: Como les gusta buscar en múltiples fuentes cosas para que encajen en una sola, ellos envían secuaces conformados por partes de los distintos personajes 



La idea es asociar a cada personaje malo un tipo de plagio y como hay más personajes que tipo de plagio,  hay dos villanos (la víbora y el babuino) que tendrán asignados más tipos de plagio y serian los últimos jefes del juego.

Como para llegar a cada villano hay que atravesar diferentes escenarios podemos incorporar pequeñas líneas de texto que describen al villano de ese nivel y el tipo de plagio asociado, con esto también podemos incorporar la historia ya sea con el virus CH que contamina a los estudiantes del poli o con la Villa Chidestoria y sus comandantes que invaden a la villa del poli. 

Para identificar el tipo de plagio de cada personaje podemos incorporarlos en las peleas, por ejemplo:
En el caso de la clonación que el villano sea capaz de replicar los poderes de los personajes 
O en el caso de Reutilización que el villano use citas conocidas que mucha gente conozca  como “yo soy tu padre” y con esto la gente puede saber que se trata de plagio y sería una forma de distinguirlo.
