### ISSUE TITLE
1.3.5 Integración historia juego y perfil del usuario

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#92]
**Tareas a Realizar**
- [x] Realizar integración y animación de la historia de juego.
- [x] Prototipo funcional de perfil de usuario, en donde se pueda ver, personajes desbloqueados, personajes faltantes, puntos, nivel, recompensas, etc.

**Comment by CamilaG08** [comment]
Se cierra debido a que se reasigna en el Issue #192
