### ISSUE TITLE
1.1.6 Sonidos juego - Personajes y niveles

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#93]
**Descripción**

Proponer los sonidos correspondientes a los poderes d elos personajes y la música de fondo para las batallas de los niveles.

**TAREAS**

- [x] Sonido para el poder de lanzar
- [x] Sonido para el poder de arrojar
- [x] Sonido para poder de caer del cielo
- [x] Sonido para escudos
- [x] Música para las batallas de los niveles

**Comment by CamilaG08** [comment]
Sonido para el poder de lanzar:

[Lanzamientos.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/800900/Lanzamientos.zip)

**Comment by CamilaG08** [comment]
Sonido para el poder de arrojar:

[Lanzamientos2.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/800902/Lanzamientos2.zip)

**Comment by CamilaG08** [comment]
Sonido para el poder de caer del cielo(Lluvia y/o rayo):

[Trueno_Lluvia.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/800903/Trueno_Lluvia.zip)

**Comment by CamilaG08** [comment]
Sonido para los escudos:

[Escudos.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/800906/Escudos.zip)

**Comment by CamilaG08** [comment]
Música de fondo para las batallas (Varias sugerencias):

[Fondo_Batalla.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/800907/Fondo_Batalla.zip)
